### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lbmn** [anacrolix/torrent#1]
Hope you'll use MIT, BSD, or one of these other permissive licenses - http://copyfree.org/standard/licenses

**Comment by anacrolix** [comment]
Is the Apache license compatible with your purposes?

**Comment by jzelinskie** [comment]
+1 for MIT or BSD, but Apache is better than something like GPL

**Comment by lbmn** [comment]
Apache License is definitely better than GPL, but it's a bit flawed from the perspective of the Copyfree Initiative - http://copyfree.org/standard/rejected

ISC, MIT, or 2-clause BSD are best.

Note that people who don't like restrictive licenses usually aren't motivated by desire to create a closed-source fork.  We just find restrictive licenses hypocritical and contrary to the philosophy and spirit of "free software".  Fortunately the copyleft fad has largely passed, they seem to be on their way out.

**Comment by 3marcusw** [comment]
I'd recommend the Mozilla Public License[0] because it has, like MIT style licenses, the ability to link with code under any other license (Proprietary and GPL both), but still has file based copyleft that ensures modifications to the code will be open source. 
[0] https://www.mozilla.org/MPL/2.0/FAQ.html

**Comment by lbmn** [comment]
Copyleft does nothing but harm the free software movement and alienate people.  It's socialist / anti-business ideology.

**Comment by anacrolix** [comment]
I'm really liking the suggested MPL 2.0.

**Comment by lbmn** [comment]
I now regret bringing up the license issue - it made the situation worse as far as I'm concerned...  :(

**Comment by anacrolix** [comment]
You want to make closed-source changes? As I understand, MPL lets you do business as usual (such as bundling proprietary binaries etc.), just as long as the changes you make to source files that come with this repository are made public. It doesn't taint any of your other code.
