### ISSUE TITLE
Make memory managment of send and receive buffer more efficient

### ISSUE THREAD

**Issue by hustcat** [anacrolix/torrent#109]
Torrent consume a lot of CPU when high-speed transmit, and I found `gc` in golang consumed a of CPU:

```
Samples: 325K of event 'cycles', Event count (approx.): 135790396170
 10.77%  docker                  [.] runtime.scanobject
  9.22%  docker                  [.] runtime.gcDrainUntilPreempt
  8.24%  docker                  [.] runtime.cas64
  7.81%  docker                  [.] crypto/sha1.block
  4.95%  docker                  [.] runtime.atomicor8
  4.80%  docker                  [.] runtime.greyobject
  4.36%  docker                  [.] runtime.atomicload64
  4.12%  docker                  [.] runtime.mSpan_Sweep
  2.94%  docker                  [.] runtime.heapBitsForObject
  1.60%  [kernel]                [k] copy_user_generic_string
  1.46%  docker                  [.] runtime.memclr
  1.31%  docker                  [.] runtime.xchg
  1.03%  docker                  [.] runtime.atomicload
```

I think the reason is memory allocation in [sendChunk](https://github.com/anacrolix/torrent/blob/master/client.go#L1101) and [receive](https://github.com/anacrolix/torrent/blob/master/peer_protocol/protocol.go#L147).

I think we need make memory allocation more efficient. Maybe self-managed memory pool is better? #107

**Comment by anacrolix** [comment]
I think we need benchmark functions for sendChunk and Decode, then we can work on making some improvements there.

**Comment by hustcat** [comment]
It seem some problems in Go. Go1.5.x consume much CPU more than Go1.3.x:

Go1.3.x:
![image](https://cloud.githubusercontent.com/assets/1716915/18269975/40974146-745d-11e6-8792-4902c6e9b87e.png)

Go1.5.x:

![torrent_cpu](https://cloud.githubusercontent.com/assets/1716915/18270080/a6105cc4-745d-11e6-9b83-e6d8621d437a.jpg)

**Comment by hustcat** [comment]
@anacrolix There are some examples of manual memory managment in Go. It will relieving pressure on the garbage collector. Such as [couchbase](https://github.com/couchbase/go-slab), [sync.Pool](https://golang.org/pkg/sync/#Pool) and [cloudflare](https://blog.cloudflare.com/recycling-memory-buffers-in-go/). I will test it later.

**Comment by anacrolix** [comment]
Absolutely there are things that can be done. Benchmarking is the right way to ensure those changes are worth it, and in the right direction.

**Comment by hustcat** [comment]
@anacrolix I test with [sync.Pool](https://github.com/hustcat/torrent/commit/a929a8515b2780fd727ac831b23737fd19f79e3d), performance of torrent increase 80+%, and CPU usage of `scanblock`  droped from 14% to 6%:

go 1.3.x:

old:
![image](https://cloud.githubusercontent.com/assets/1716915/18385987/63e3974c-76c6-11e6-9de1-52045decb073.png)

with sync.Pool:
![image](https://cloud.githubusercontent.com/assets/1716915/18385976/4e19bda6-76c6-11e6-8de8-59e6eae474e3.png)

**Comment by anacrolix** [comment]
Can you submit this with a benchmark?

**Comment by hustcat** [comment]
The implementation is not perfect，I'd like to submit it after some optimization:)

**Comment by anacrolix** [comment]
Can you submit this with a benchmark?

**Comment by anacrolix** [comment]
Can you submit this with a benchmark?

**Comment by anacrolix** [comment]
I've written a test for the connection loop, this is the alloc_objects mem profile for it.
![prof](https://cloud.githubusercontent.com/assets/988750/18415445/1e263f72-7836-11e6-9731-a652523b0233.png)
I'm getting 400MB/s throughput currently. A rough guess based on CPU usage and the memory profile would suggest this is 1/3 to 1/2 of what can be achieved, which is excellent considering.

BenchmarkConnectionMainReadLoop-4          30000             40851 ns/op         401.06 MB/s
PASS
ok      github.com/anacrolix/torrent    1.677s

**Comment by anacrolix** [comment]
@hustcat can you ensure you're running torrent with the fixes to #106? If you are, the sha1.block overhead is interesting. That should only occur after that fix when pieces are checked. If that's the biggest bottleneck, it might be difficult to squeeze peformance from elsewhere without first improving that. (With a C or asm implementation).

**Comment by hustcat** [comment]
@anacrolix Here is test result by using your benchmark test:

```
# go test -v -bench BenchmarkConnectionMainReadLoop -cpu 1,4,8 -benchtime=10s -run=^$
PASS
BenchmarkConnectionMainReadLoop           500000             26198 ns/op         625.37 MB/s
BenchmarkConnectionMainReadLoop-4         500000             35308 ns/op         464.03 MB/s
BenchmarkConnectionMainReadLoop-8         500000             38863 ns/op         421.58 MB/s
ok      github.com/anacrolix/torrent    51.202s
```

After user `sync.Pool`:

```
# go test -v -bench BenchmarkConnectionMainReadLoop -cpu 1,4,8 -benchtime=10s -run=^$
PASS
BenchmarkConnectionMainReadLoop          1000000             10425 ns/op        1571.57 MB/s
BenchmarkConnectionMainReadLoop-4        1000000             14008 ns/op        1169.61 MB/s
BenchmarkConnectionMainReadLoop-8        1000000             14894 ns/op        1099.98 MB/s
ok      github.com/anacrolix/torrent    39.731s
```

My code is [here](https://github.com/hustcat/torrent/commits/bench-1)

**Comment by hustcat** [comment]
I will do more detailed test on `sha1.block`, and optimize it later.

**Comment by anacrolix** [comment]
I've cherry picked that commit into master. You can probably pool more aggressively, at the Torrent level, when the chunk size is set, as all requests will result in chunk pieces of that size coming back. Furthermore, you check that the cap of slices is the chunk size before pushing them back into the pool. You don't need to worry about chunks that have lens less than the chunk size (which occurs on piece boundaries sometimes), they will have been made by slicing an underlying slice with the full capacity. For an example of this, see all referrers to https://github.com/anacrolix/utp/blob/master/utp.go#L53 in package utp.

**Comment by hustcat** [comment]
With a small [optimization](https://github.com/hustcat/torrent/tree/bench-2), and got many performance improvements:

```
# go test -v -bench BenchmarkConnectionMainReadLoop -cpu 1,4,8 -benchtime=10s -run=^$
PASS
BenchmarkConnectionMainReadLoop          2000000              8129 ns/op        2015.46 MB/s
BenchmarkConnectionMainReadLoop-4        2000000              8663 ns/op        1891.24 MB/s
BenchmarkConnectionMainReadLoop-8        2000000              8767 ns/op        1868.76 MB/s
ok      github.com/anacrolix/torrent    77.004s
```

**Comment by anacrolix** [comment]
I think maybe this can be closed @hustcat ?
