### ISSUE TITLE
disabling linkage of sqlite

### ISSUE THREAD

**Issue by mischief** [anacrolix/torrent#115]
is there a way to do this?

if not, i would like either sqlite to be disabled by default, or have a documented go build tag to do it.

**Comment by anacrolix** [comment]
Is this for building on some difficult platform, say where you don't have a C compiler or something?

**Comment by mischief** [comment]
@anacrolix yeah, for example on plan 9, where there is *no* cgo. i've done this in the past (by stripping out mmap from cmd/torrent).

it seems for now that `CGO_ENABLED=0 go install -x -v -tags netgo` will actually compile go-sqlite3, but without any actual code compiled, just doc.go. this results in:

```
2016/09/15 16:30:51 couldn't open piece completion db in "tmp": sql: unknown driver "sqlite3" (forgotten import?)
```

**Comment by anacrolix** [comment]
Yes I've had a few comments from people about sqlite3 lately, due to its use in the default completion DB. Would a tag like 'nosqlite3' or 'nocc' be appropriate to disable this do you think?

**Comment by mischief** [comment]
the build tag could simply be `cgo` - which is respected for CGO_ENABLED=0 IIUC - https://godoc.org/go/build

**Comment by anacrolix** [comment]
That sounds good. I'm surprised it compiles, maybe there's something different going on on plan9. I get:

# github.com/mattn/go-sqlite3
/root/gopath/src/github.com/mattn/go-sqlite3/tracecallback_noimpl.go:7: undefined: SQLiteConn

I'll use build tags to bypass piece completion DB if cgo isn't enabled.

**Comment by anacrolix** [comment]
Hm if you get the error `couldn't open piece completion db in "tmp": sql: unknown driver "sqlite3" (forgotten import?)`, `anacrolix/torrent` will continue to work anyway, that error occurs at the point where it selects the completion DB backend, so you will get an in-memory version at that point. Do you still want to go ahead with the cgo build tag?

**Comment by anacrolix** [comment]
@mischief Could you respond to https://github.com/anacrolix/torrent/issues/115#issuecomment-247493766?

**Comment by mischief** [comment]
seems fine without it, but being able to manually control cgo use would be (imo) desirable.

**Comment by anacrolix** [comment]
A bolt DB backend is now the default for tracking piece completion, per #124.

**Comment by mischief** [comment]
fantastic news! however, see my other comment on that issue :-)

**Comment by andrejvanderzee** [comment]
Still not able to build on Linux without cgo:

```
$ CGO_ENABLED=0 go build --ldflags '-extldflags "-static"' -ldflags '-s' -a -installsuffix cgo
# github.com/mattn/go-sqlite3
../../../../github.com/mattn/go-sqlite3/tracecallback_noimpl.go:7: undefined: SQLiteConn
```

**Comment by anacrolix** [comment]
@andrejvanderzee Check you're running 27893acf3445be53896f8d24e0eb427f4a288ccc or later.
