### ISSUE TITLE
BEP19 WebSeed support

### ISSUE THREAD

**Issue by mischief** [anacrolix/torrent#116]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2450%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/anacrolix/torrent/issues/116)

afaict, torrent doesn't utilize URLList to implement [BEP19](http://bittorrent.org/beps/bep_0019.html)

it would be great to have support for this, because there are places like [archive.org](https://archive.org) which pretty much only have webseeds.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $50.00)

- [<img src='https://avatars1.githubusercontent.com/u/4278113?v=4' alt='steelbrain' width=24 height=24> steelbrain](https://issuehunt.io/u/steelbrain) ($50.00)

### Submitted pull Requests
- [#410 Add support for BEP 19 WebSeeds](https://issuehunt.io/r/anacrolix/torrent/pull/410)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/anacrolix/torrent/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by anacrolix** [comment]
This will be good. A starting place will be to map pieces to a sequence of HTTP/FTP range requests, similar to how the file-based backends for osFile and mmap work. URLs may be able to be scored like connections are, to compete for a slot in the established connections.

**Comment by cathalgarvey** [comment]
Would also love to see this.

**Comment by lutostag** [comment]
Started to take a stab at it with https://github.com/lutostag/torrent/tree/bep19, @anacrolix, can you give more explanation of where the `file-based backends for osFile and mmap` is in the repo so I can see what you mean?

Also, according to https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.35, http supports multiple ranges via the range header, supposing I don't want to reimplement what you have @ https://github.com/anacrolix/missinggo/blob/master/httptoo/bytes_content_range.go would you be amenable to a PR against that first? (as using multiple-ranges, if the server supports it  -- seems like at least nginx does so -- would refute the argument in `A Not Recommended Client Implementation` from the BEP).

My intention is to support http/s only for now, and I think at least the `Not Recommended Client Implementation` is within my reach, not sure on changing up the piece selection bits are at the moment, but hopefully we can cross that bridge when we get to it...

Thanks!

**Comment by anacrolix** [comment]
The backends are in ./storage, at https://godoc.org/github.com/anacrolix/torrent/storage. Specifically pieces are mapped on to the variable length files in the mmap and file implementations. Files backed by HTTP, will have similar mappings if you use HTTP Range requests. I think these days you can rely on Range being supported in most places it matters. A website serving archive files over HTTP will very likely support them, and the alternative is potentially wasteful and probably not worth considering on a first pass. Feel free to submit PRs against any of my code as required.

**Comment by anacrolix** [comment]
@shithappens2016 @axet

**Comment by axet** [comment]
it is working under LGPL3

https://gitlab.com/axet/libtorrent

**Comment by shithappens2016** [comment]
@axet
Is your webseed unit simply work alone or it can work with torrent p2p at same time ?

I mean your need dispatch which part of the file use p2p to download and which part use http to download, right?

**Comment by axet** [comment]
In my library it does work simultaneously, and use simple sequentially algorithm... In theory it can work even better. But I'm lazy to implement anything above simple.

**Comment by anacrolix** [comment]
Is there any interest in financially backing this feature? It's a day or two of work for a feature I don't personally need, but can integrate effectively with my knowledge of the codebase.

**Comment by vintikzzz** [comment]
@anacrolix Yes, I am interested in backing. I also have special ideas. Can we discuss it somewhere?

**Comment by anacrolix** [comment]
@vintikzzz https://gitter.im/anacrolix/torrent or email me for other plans?

**Comment by anacrolix** [comment]
> [@anacrolix](https://issuehunt.io/u/anacrolix) has rewarded $45.00 to [@anacrolix](https://issuehunt.io/u/anacrolix). [See it on IssueHunt](https://issuehunt.io/repos/28986292/issues/116)
> 
> * 💰 Total deposit: $50.00
> * 🎉 Repository reward(0%): $0.00
> * 🔧 Service fee(10%): $5.00

![image](https://user-images.githubusercontent.com/988750/83702828-18fcbd80-a651-11ea-8b55-3b3aaec87b95.png)
