### ISSUE TITLE
Requesting an example on how to obtain information about seeders/leechers of a torrent.

### ISSUE THREAD

**Issue by 22morph** [anacrolix/torrent#127]
I wanted to ask if it would be possible to give an example on how one can get the number of seeders and leechers of a torrent. I have tried looking through the documentation but I can't figure it out by myself. I know this is not exactly an issue but I didn't know where else to ask and I would appreciate the example very much.
Thank you.

**Comment by anacrolix** [comment]
Do you mean those that are currently connected to the client, or the numbers present in the swarm?

**Comment by 22morph** [comment]
In the swarm if it's possible.

**Comment by anacrolix** [comment]
It's not straightforward. The swarm consists of what is published by DHT, trackers, and PEX. DHT and trackers can be scraped with the dht and tracker packages in this repo respectively. You'd have to run a Client and scrape whatever comes out of PEX for that part, and even then it will never be complete. That's not currently exposed, though the client does make use of it. Most BitTorrent related sites just scrape popular trackers for numbers.

Just in case that's not what you meant, Torrents in the client do maintain a list of pending peer addresses, that haven't yet been connected to. That's limited to 200 peers for memory reasons. That number of unused peers is a very good indication of the health of a Torrent.

**Comment by 22morph** [comment]
Thank you very much for the quick reply and for the information! Now I know which way to approach this.

**Comment by anacrolix** [comment]
Do let me know if anything isn't clear in the tracker and dht packages.

**Comment by MrGlp** [comment]
Hello, dear author, I understand that your previous response told me how to get the health of a seed, right? This method is to scrape the number of unused peers. So how can I use code to get this number for a specific torrent? Could you please help me? Thank you very much.

**Comment by anacrolix** [comment]
@MrGlp I think you want to use PendingPeers from the return value of https://pkg.go.dev/github.com/anacrolix/torrent#Torrent.Stats.
