### ISSUE TITLE
What should I do after torrent-create?

### ISSUE THREAD

**Issue by Wang-Kangjin** [anacrolix/torrent#129]
i used the  `go run torrent-create/main.go foo-file.iso > foo-file.torrent` command to create a torrent named foo-file.torrent.  So.. what should I do after that? If i should tell the tracker server about resource's location?  And which api I should use?

**Comment by Wang-Kangjin** [comment]
oh...sorry.i found a similar issue at https://github.com/anacrolix/torrent/issues/23
maybe it is a general problem, you can write this to README.md
Thx!

**Comment by anacrolix** [comment]
I'd like to improve the README. Is there some sequence of commands you can use to explain the solution you found? I'm not entirely sure what you were having trouble with. Thanks.
