### ISSUE TITLE
unsupported peers value type: []interface {}

### ISSUE THREAD

**Issue by axet** [anacrolix/torrent#130]
I'm not yet familiar with trackers, so here is a error. I add panic() call to see call stack.

it is not very popular / private tracker, If you willing to get .torrent file I can email you.

```
E/Go: panic(0x7bcff6fbb340, 0xc4204ab840)
E/Go: 	/opt/local/lib/go/src/runtime/panic.go:500 +0x1a1
E/Go: github.com/anacrolix/torrent/tracker.(*httpResponse).UnmarshalPeers(0xc42021c300, 0x31b, 0x600, 0x7bcff6fbbee0, 0xc42021c300, 0x0)
E/Go: 	/Users/axet/source/android-torrent-client/libtorrent/src/github.com/anacrolix/torrent/tracker/http.go:32 +0x3a0
E/Go: github.com/anacrolix/torrent/tracker.announceHTTP(0xc420298600, 0xc4203abc00, 0xc420299627, 0x15, 0x25e4, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
E/Go: 	/Users/axet/source/android-torrent-client/libtorrent/src/github.com/anacrolix/torrent/tracker/http.go:95 +0x71e
E/Go: github.com/anacrolix/torrent/tracker.AnnounceHost(0xc420338aa0, 0x4a, 0xc420298600, 0xc420299627, 0x15, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
E/Go: 	/Users/axet/source/android-torrent-client/libtorrent/src/github.com/anacrolix/torrent/tracker/tracker.go:66 +0x160
E/Go: github.com/anacrolix/torrent.(*trackerScraper).announce(0xc4203ab880, 0x0, 0x0, 0x0, 0x45d964b800, 0xecfba974e, 0x5a1dd30, 0x7bcff7279d60, 0x0)
E/Go: 	/Users/axet/source/android-torrent-client/libtorrent/src/github.com/anacrolix/torrent/tracker_scraper.go:95 +0x1e0
E/Go: github.com/anacrolix/torrent.(*trackerScraper).Run(0xc4203ab880)
E/Go: 	/Users/axet/source/android-torrent-client/libtorrent/src/github.com/anacrolix/torrent/tracker_scraper.go:123 +0x243
E/Go: created by github.com/anacrolix/torrent.(*Torrent).startMissingTrackerScrapers
E/Go: 	/Users/axet/source/android-torrent-client/libtorrent/src/github.com/anacrolix/torrent/torrent.go:1250 +0x265
```

**Comment by anacrolix** [comment]
Thanks. The tracker is probably not returning the compact peer representation. I've never actually encountered one that does this in the wild, but the original specification actually defaults to it.

Email me the torrent, that'll probably be easiest. It'll be a relatively simple fix for me. Thanks.

**Comment by anacrolix** [comment]
I made a fix, though I wasn't able to test it with a live tracker. Let me know if there's any issues.

**Comment by axet** [comment]
Not sure what you mean, I did send you a .torrent... I did test it and t works! Thanks!!!

**Comment by anacrolix** [comment]
The private tracker wouldn't let me make requests, even with the codes you provided, they're usually not that simple and have IP-based checks.

Great that it works, I just followed the spec. Perhaps you could verify that you're successfully getting useful peers from the tracker, and not just not crashing.

Thanks.
