### ISSUE TITLE
Getting lots of error sending get_peers request

### ISSUE THREAD

**Issue by mavjs** [anacrolix/torrent#131]
I am getting a lot of:

`error sending get_peers request to IPv4:port: &errors.errorString{s:"error writing 95 bytes to IPv4:port: write udp [::]:port->IPv4:port: sendto: operation not permitted"}`

**Comment by axet** [comment]
which platform?

**Comment by mavjs** [comment]
Fedora 24 x86_64

**Comment by anacrolix** [comment]
I believe this happens if you send to quickly to the interface on some platforms. There's likely a kernel configuration that's limiting how many packets you can send. Currently the DHT implementation doesn't throttle itself. Perhaps you can try adjusting the kernel configuration or tweaking some of the limits in the DHT code and let us know what works for you?

**Comment by Kent-H** [comment]
I'm also seeing this issue.  This line is always shown first, when the system is initialized:
```2017/04/27 00:35:57 error bootstrapping DHT: error sending find_node: error writing 91 bytes to 67.215.246.10:6881: write udp 127.0.0.1:36491->67.215.246.10:6881: sendto: invalid argument
```

**Comment by anacrolix** [comment]
Thanks @Kent-H . What OS are you on?

**Comment by Kent-H** [comment]
Ubuntu xenial, 16.04 LTS, 64-bit.  (Running as an AWS EC2 t2.micro instance)

The same program runs without errors when running on Windows 10.

Even when there are errors, the downloads seem to continue without issues.

**Comment by anacrolix** [comment]
DHT messages aren't critically important. If enough are getting through that you are getting some peers, it doesn't matter a whole lot. This error is undesirable at best.

**Comment by anacrolix** [comment]
Are you still getting this issue?

**Comment by mavjs** [comment]
@anacrolix I forgot to report back after a while. Apologies. During the time I reported, I was using a Macbook Pro with Fedora 24 x86_64 with the broadcom wifi driver on it (I should have been more verbose then). To be honest, I have not seen that kind of error since I have been using this on my other computer running Fedora 25 and 26 x86_64

**Comment by anacrolix** [comment]
I will close this for now, thanks.
