### ISSUE TITLE
Is sequential download possible?

### ISSUE THREAD

**Issue by tapir** [anacrolix/torrent#139]
I couldn't find it in the documentation.
Is this possible?

Thanks

**Comment by anacrolix** [comment]
Yes, if you open a Reader on a Torrent, and discard it, the Client will prioritize reading pieces in order. Approximately:

cl := NewClient()
t := cl.AddTorrent()
r := t.NewReader()
io.Copy(ioutil.Disard, r)

**Comment by tapir** [comment]
That's very nice thanks

**Comment by gitpubber** [comment]
> Yes, if you open a Reader on a Torrent, and discard it, the Client will prioritize downloading pieces in order. Approximately:
> 
> cl := NewClient()
> t := cl.AddTorrent()
> r := t.NewReader()
> io.Copy(ioutil.Disard, r)

Hello @anacrolix , i am trying to create option for torrent to toggle sequential download.

Is doing this once enough for torrent to have sequential download? also,won't there be any performance penalty?

and,how can i stop sequential download? please help

**Comment by gitpubber** [comment]
> Yes, if you open a Reader on a Torrent, and discard it, the Client will prioritize downloading pieces in order. Approximately:
> 
> cl := NewClient()
> t := cl.AddTorrent()
> r := t.NewReader()
> io.Copy(ioutil.Disard, r)

i plan to do this in another goroutine. but,won't this be resource intensive? allocating and buffer,etc. ?

**Comment by gitpubber** [comment]
> Yes, if you open a Reader on a Torrent, and discard it, the Client will prioritize downloading pieces in order. Approximately:
> 
> cl := NewClient()
> t := cl.AddTorrent()
> r := t.NewReader()
> io.Copy(ioutil.Disard, r)

is there a way to stop this(i mean sequential download).should i wrap context with reader or what?

**Comment by anacrolix** [comment]
I believe Reader implements a method for reading that takes a Context, so you can cancel this. Unfortunately the default `io` utilities don't use this, so you'd have to do the discard yourself.

The newest request strategy however, will default to rarest piece and then sequential download anyway, so this may not be such an issue. Furthermore, it would be trivial to tweak to default to sequential in all cases. I guess it depends how strong your conviction on sequentiality is.
