### ISSUE TITLE
outgoing connection fast close

### ISSUE THREAD

**Issue by axet** [anacrolix/torrent#142]
If we start torrent and then close torrent client very fast we can cause catch racing condition.

initiateConn/go outgoingConnection

outgoingConnection is not locked by global lock to keep DialTimeout free of blocking main application. But at the same time we may close client and no outgoing connection should occurs after we called Client.close() but if it does client will crash (socket closed) nil pointer exception.

Seems like we need to have additional client lock mutex to keep socket operations synchronized. So fast client close should be locked and waited until all outgoing connections get timeout. As well if we close client non outgoing connection will occurs.

Then every DialTimeout will lock client socket mutex and every utp socket operation should do the same. Can it be a problem adding two mutex and facing potential deadlocks?

EDIT: Now i think. The only solution is to have waitgroups for every go routines with utp access.

```
E/Go: goroutine 11954 [running]:
E/Go: panic(0x716657c3fb00, 0xc42000c040)
E/Go: 	/opt/local/lib/go/src/runtime/panic.go:500 +0x1a1
E/Go: github.com/anacrolix/utp.(*Socket).network(0x0, 0x71665760de10, 0xc42044ac80)
E/Go: 	/Users/axet/source/android-torrent-client/libtorrent/src/github.com/anacrolix/utp/socket.go:353 +0x22
E/Go: github.com/anacrolix/utp.(*Socket).resolveAddr(0x0, 0xc4221ad6e0, 0x12, 0x716657ef2aa0, 0xc420a3be60, 0xc420b65700, 0xc4214d1780)
E/Go: 	/Users/axet/source/android-torrent-client/libtorrent/src/github.com/anacrolix/utp/socket.go:345 +0x2f
E/Go: github.com/anacrolix/utp.(*Socket).DialTimeout(0x0, 0xc4221ad6e0, 0x12, 0x6fc23ac00, 0x71666503a300, 0xc4206301e0, 0x0, 0x0)
E/Go: 	/Users/axet/source/android-torrent-client/libtorrent/src/github.com/anacrolix/utp/socket.go:359 +0x8b
E/Go: github.com/anacrolix/torrent.(*Client).dialUTP(0xc42018e000, 0xc4221ad6e0, 0x12, 0xc4202cf400, 0x716657ef0101, 0x0, 0x0, 0x0)
E/Go: 	/Users/axet/source/android-torrent-client/libtorrent/src/github.com/anacrolix/torrent/client.go:549 +0x6c
E/Go: github.com/anacrolix/torrent.(*Client).establishOutgoingConn(0xc42018e000, 0xc4202cf400, 0xc4221ad6e0, 0x12, 0x0, 0x0, 0x0)
E/Go: 	/Users/axet/source/android-torrent-client/libtorrent/src/github.com/anacrolix/torrent/client.go:645 +0x1ab
E/Go: github.com/anacrolix/torrent.(*Client).outgoingConnection(0xc42018e000, 0xc4202cf400, 0xc4221ad6e0, 0x12, 0x716657b02f4c, 0x1)
E/Go: 	/Users/axet/source/android-torrent-client/libtorrent/src/github.com/anacrolix/torrent/client.go:663 +0x5b
E/Go: created by github.com/anacrolix/torrent.(*Client).initiateConn
E/Go: 	/Users/axet/source/android-torrent-client/libtorrent/src/github.com/anacrolix/torrent/client.go:529 +0x292
```

**Comment by anacrolix** [comment]
Can you create a unit test that reproduces this? I'm not able to from your description. It should trigger a race condition when run under `go test -race`.

**Comment by axet** [comment]
Ok. I see. Your code does not crash, only my code have this issue.

After Client.Close() here a few go routines which can call utpSock.Dial(). May be this is not good time to call any utpSock actions after main client closed. Not a big deal, but someday may matter.

My code cleans up utpSock = nil after Client.Close() and it does crash - so I see the problem.
