### ISSUE TITLE
Storage - Create/Delete

### ISSUE THREAD

**Issue by Emyrk** [anacrolix/torrent#148]
In my application I need to create thousands of torrents, and have the ability to delete a torrent.

Using your Bolt data storage is very effective for my clients, as the file descriptor overhead is drastically reduced, and the files are all small (<400KB) so bolt is a great way to store them all. My issue is the following:

- Is it possible to delete a torrent from Bolt storage? 
- I cannot figure out how to create a torrent and add it to the Bolt storage to seed.

**Comment by anacrolix** [comment]
There's no provided way to delete torrents from Bolt, other than to search for the info hash bucket and delete its contents yourself. The storage backends provided are geared toward bootstrapping from existing peers.

In my personal downstream projects, I use storage.NewResourcePieces to wrap https://godoc.org/github.com/anacrolix/missinggo/filecache#Cache.AsResourceProvider, and discard data that hasn't be used in a while.
