### ISSUE TITLE
panic: listeners exist on different addresses

### ISSUE THREAD

**Issue by insionng** [anacrolix/torrent#15]
My code:

```
package main

import (
	"fmt"
	"github.com/anacrolix/torrent"
)

func main() {

	c, e := torrent.NewClient(&torrent.Config{})
	defer c.Close()
	if e != nil {
		fmt.Printf("torrent.NewClient errors:%s", e)
	}

	t, e := c.AddMagnet("magnet:?xt=urn:btih:KRWPCX3SJUM4IMM4YF5RPHL6ANPYTQPU")
	if e != nil {
		fmt.Printf("AddMagnet errors:%s", e)
	}
	fmt.Println(t)
	fmt.Println(t.GotInfo)
	fmt.Println(t.DisplayName)
	t.DownloadAll()
	c.WaitAll()
	fmt.Println("ermahgerd, torrent downloaded")
}

```
i got this errors:
------
panic: listeners exist on different addresses

goroutine 1 [running]:
github.com/anacrolix/torrent.(*Client).ListenAddr(0xc08202e000, 0x1421f0, 0xc082
066ba0)
        E:/gopath/src/github.com/anacrolix/torrent/client.go:164 +0x220
github.com/anacrolix/torrent.func路003(0x0, 0x0)
        E:/gopath/src/github.com/anacrolix/torrent/client.go:486 +0x4c
github.com/anacrolix/torrent.NewClient(0xc08202a100, 0xc08202e000, 0x0, 0x0)
        E:/gopath/src/github.com/anacrolix/torrent/client.go:519 +0xc68
main.main()
        E:/magnetor/tor.go:10 +0x5b

goroutine 5 [runnable]:
github.com/anacrolix/torrent.(*Client).acceptConnections(0xc08202e000, 0x142220,
 0xc082042038, 0x0)
        E:/gopath/src/github.com/anacrolix/torrent/client.go:589
created by github.com/anacrolix/torrent.NewClient
        E:/gopath/src/github.com/anacrolix/torrent/client.go:503 +0x984

goroutine 6 [runnable]:
github.com/anacrolix/utp.(*Socket).reader(0xc082074300)
        E:/gopath/src/github.com/anacrolix/utp/utp.go:416
created by github.com/anacrolix/utp.NewSocket
        E:/gopath/src/github.com/anacrolix/utp/utp.go:407 +0x2e6

goroutine 7 [runnable]:
github.com/anacrolix/utp.(*Socket).dispatcher(0xc082074300)
        E:/gopath/src/github.com/anacrolix/utp/utp.go:470
created by github.com/anacrolix/utp.NewSocket
        E:/gopath/src/github.com/anacrolix/utp/utp.go:408 +0x303

goroutine 8 [runnable]:
github.com/anacrolix/torrent.(*Client).acceptConnections(0xc08202e000, 0x143398,
 0xc082074300, 0x1)
        E:/gopath/src/github.com/anacrolix/torrent/client.go:589
created by github.com/anacrolix/torrent.NewClient
        E:/gopath/src/github.com/anacrolix/torrent/client.go:511 +0xbf2

**Comment by anacrolix** [comment]
Hi, thanks for trying this. What OS are you using? Could you change the line that is panicking to read something like `panic(fmt.Sprintf("listeners are on different addresses: %q != %q", l.Addr().String(), addr.String()))`. This will tell us why it's disagreeing. If I had to guess it may be that your OS is assigning or mixing IPv6 address string representations. Thanks.

**Comment by insionng** [comment]
my os is  windows7 64bit

**Comment by insionng** [comment]
panic: listeners are on different addresses: "0.0.0.0:50007" != "[::]:50007"

**Comment by insionng** [comment]
How can we fix this problem?

**Comment by anacrolix** [comment]
Try changing dht/dht.go:108 "udp" to "udp4", and client.go:498 "tcp" to "tcp4". Let me know how it goes. There's a chat channel on https://gophers.slack.com/#torrent if you want to discuss interactively, cheers.

**Comment by insionng** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0x47a429]

goroutine 1 [running]:
github.com/anacrolix/torrent.(*torrent).numPieces(0xc20803c000, 0x0)
	/mnt/xvdb/gopath/src/github.com/anacrolix/torrent/torrent.go:513 +0x9
github.com/anacrolix/torrent.Torrent.DownloadAll(0xc20806e000, 0xc20803c000)
	/mnt/xvdb/gopath/src/github.com/anacrolix/torrent/client.go:2000 +0x7f
main.main()
	/root/tor.go:22 +0x2a9

goroutine 5 [runnable]:
github.com/anacrolix/torrent.(*Client).acceptConnections(0xc20806e000, 0x7fc67d874070, 0xc20802a028, 0x0)
	/mnt/xvdb/gopath/src/github.com/anacrolix/torrent/client.go:585
created by github.com/anacrolix/torrent.NewClient
	/mnt/xvdb/gopath/src/github.com/anacrolix/torrent/client.go:499 +0x97d

goroutine 6 [runnable]:
github.com/anacrolix/utp.(*Socket).reader(0xc208040200)
	/mnt/xvdb/gopath/src/github.com/anacrolix/utp/utp.go:416
created by github.com/anacrolix/utp.NewSocket
	/mnt/xvdb/gopath/src/github.com/anacrolix/utp/utp.go:407 +0x2df

goroutine 7 [runnable]:
github.com/anacrolix/utp.(*Socket).dispatcher(0xc208040200)
	/mnt/xvdb/gopath/src/github.com/anacrolix/utp/utp.go:470
created by github.com/anacrolix/utp.NewSocket
	/mnt/xvdb/gopath/src/github.com/anacrolix/utp/utp.go:408 +0x2fc

goroutine 8 [runnable]:
github.com/anacrolix/torrent.(*Client).acceptConnections(0xc20806e000, 0x7fc67d8751e8, 0xc208040200, 0x1)
	/mnt/xvdb/gopath/src/github.com/anacrolix/torrent/client.go:585
created by github.com/anacrolix/torrent.NewClient
	/mnt/xvdb/gopath/src/github.com/anacrolix/torrent/client.go:507 +0xbeb

goroutine 9 [runnable]:
github.com/anacrolix/torrent/dht.func·004()
	/mnt/xvdb/gopath/src/github.com/anacrolix/torrent/dht/dht.go:153
created by github.com/anacrolix/torrent/dht.NewServer
	/mnt/xvdb/gopath/src/github.com/anacrolix/torrent/dht/dht.go:163 +0x23f

goroutine 10 [runnable]:
github.com/anacrolix/torrent/dht.func·005()
	/mnt/xvdb/gopath/src/github.com/anacrolix/torrent/dht/dht.go:164
created by github.com/anacrolix/torrent/dht.NewServer
	/mnt/xvdb/gopath/src/github.com/anacrolix/torrent/dht/dht.go:169 +0x291

goroutine 11 [runnable]:
runtime.timerproc()
	/usr/local/go/src/runtime/time.go:151
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 12 [runnable]:
github.com/anacrolix/torrent.(*Client).announceTorrentTrackers(0xc20806e000, 0xc20803c000)
	/mnt/xvdb/gopath/src/github.com/anacrolix/torrent/client.go:2338
created by github.com/anacrolix/torrent.(*Client).AddTorrentSpec
	/mnt/xvdb/gopath/src/github.com/anacrolix/torrent/client.go:2125 +0x8e4

goroutine 13 [runnable]:
github.com/anacrolix/torrent.(*Client).announceTorrentDHT(0xc20806e000, 0xc20803c000, 0xc208038401)
	/mnt/xvdb/gopath/src/github.com/anacrolix/torrent/client.go:2209
created by github.com/anacrolix/torrent.(*Client).AddTorrentSpec
	/mnt/xvdb/gopath/src/github.com/anacrolix/torrent/client.go:2128 +0x928

**Comment by insionng** [comment]
546cf15f724d19c4319cc17b179d7e035f89c1f4
0x401710

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x47d239]

goroutine 1 [running]:
github.com/anacrolix/torrent.(*torrent).numPieces(0xc08206a000, 0x241dc8)
        E:/gopath/src/github.com/anacrolix/torrent/torrent.go:513 +0x9
github.com/anacrolix/torrent.Torrent.DownloadAll(0xc08202e000, 0xc08206a000)
        E:/gopath/src/github.com/anacrolix/torrent/client.go:2000 +0x86
main.main()
        e:/magnetor/tor.go:23 +0x5a9

goroutine 5 [runnable]:
github.com/anacrolix/torrent.(*Client).acceptConnections(0xc08202e000, 0x242220,
 0xc082042038, 0x0)
        E:/gopath/src/github.com/anacrolix/torrent/client.go:585
created by github.com/anacrolix/torrent.NewClient
        E:/gopath/src/github.com/anacrolix/torrent/client.go:499 +0x984

goroutine 6 [runnable]:
github.com/anacrolix/utp.(*Socket).reader(0xc082074300)
        E:/gopath/src/github.com/anacrolix/utp/utp.go:416
created by github.com/anacrolix/utp.NewSocket
        E:/gopath/src/github.com/anacrolix/utp/utp.go:407 +0x2e6

goroutine 7 [runnable]:
github.com/anacrolix/utp.(*Socket).dispatcher(0xc082074300)
        E:/gopath/src/github.com/anacrolix/utp/utp.go:470
created by github.com/anacrolix/utp.NewSocket
        E:/gopath/src/github.com/anacrolix/utp/utp.go:408 +0x303

goroutine 8 [runnable]:
github.com/anacrolix/torrent.(*Client).acceptConnections(0xc08202e000, 0x243398,
 0xc082074300, 0x1)
        E:/gopath/src/github.com/anacrolix/torrent/client.go:585
created by github.com/anacrolix/torrent.NewClient
        E:/gopath/src/github.com/anacrolix/torrent/client.go:507 +0xbf2

goroutine 9 [runnable]:
github.com/anacrolix/torrent/dht.func路004()
        E:/gopath/src/github.com/anacrolix/torrent/dht/dht.go:153
created by github.com/anacrolix/torrent/dht.NewServer
        E:/gopath/src/github.com/anacrolix/torrent/dht/dht.go:163 +0x246

goroutine 10 [runnable]:
github.com/anacrolix/torrent/dht.func路005()
        E:/gopath/src/github.com/anacrolix/torrent/dht/dht.go:164
created by github.com/anacrolix/torrent/dht.NewServer
        E:/gopath/src/github.com/anacrolix/torrent/dht/dht.go:169 +0x298

goroutine 11 [runnable]:
runtime.timerproc()
        C:/Go/src/runtime/time.go:151
runtime.goexit()
        C:/Go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 12 [runnable]:
github.com/anacrolix/torrent.(*Client).announceTorrentTrackers(0xc08202e000, 0xc
08206a000)
        E:/gopath/src/github.com/anacrolix/torrent/client.go:2338
created by github.com/anacrolix/torrent.(*Client).AddTorrentSpec
        E:/gopath/src/github.com/anacrolix/torrent/client.go:2125 +0x8eb

goroutine 13 [runnable]:
github.com/anacrolix/torrent.(*Client).announceTorrentDHT(0xc08202e000, 0xc08206
a000, 0xc082008501)
        E:/gopath/src/github.com/anacrolix/torrent/client.go:2209
created by github.com/anacrolix/torrent.(*Client).AddTorrentSpec
        E:/gopath/src/github.com/anacrolix/torrent/client.go:2128 +0x92f

insion@SATELLITE /E/magnetor
$

**Comment by anacrolix** [comment]
It's an error to call DownloadAll before GotInfo returns. Chat on Slack if you're curious. This is unrelated to your original bug report.

```
<-t.GotInfo()
t.DownloadAll()
c.WaitAll()
```

**Comment by insionng** [comment]
I'm sorry, I can not because the relationship between GFW good access slack service.
Thank you to answer my question.

**Comment by anacrolix** [comment]
@insionng are you able to access https://gitter.im/anacrolix/torrent?
