### ISSUE TITLE
Sequential Downloads

### ISSUE THREAD

**Issue by swrap** [anacrolix/torrent#150]
Can you add support for sequential downloading.

**Comment by anacrolix** [comment]
Do you mean for cmd/torrent? In the library, just open a reader on the file/torrent you want, and read in the order you want.

**Comment by swrap** [comment]
I can use the reader to read in order, but that doesn't ensure the torrent downloads in order. I understand BitTorrent is not optimal to download the data in order, but I wish to use it for video streaming.

**Comment by anacrolix** [comment]
I use the torrent Client myself for video streaming, its piece prioritization is designed to ensure that data is optimized toward satisfying sequential reads from the `torrent.Reader` type. For example any time the `Reader` is blocked on a `Read`, the piece is selected for *all* current peers. The next piece is also chosen next, only after the next 2 pieces are available does it start to split the peers across the `Readahead` window set on the `Reader`. (It's currently 5MB by default.) If you `io.Copy(ioutil.Discard, someReader)`, it will consume the data so quickly it will probably download every single piece in order as it will always be blocked on the next unavailable piece.

Just to check, be sure to stream the data to your player from the `torrent.Reader`. Don't access the filesystem directly as I've seen people do. When accessing the filesystem, the player won't know that `EOF` isn't corruption, as it isn't synced with the torrent client as it will be if you feed it from the `torrent.Reader` yourself. See `cmd/torrentfs` if you want to go that route.

**Comment by swrap** [comment]
Thanks so much! I will check this out and write back about my findings :) Really appreciate the quick response and love the library!

**Comment by anacrolix** [comment]
@antonsoroko not currently
