### ISSUE TITLE
boltdb can't open after Client.Close()

### ISSUE THREAD

**Issue by elgatito** [anacrolix/torrent#158]
After closing the whole client with `Client.Close()` and then opening with `torrent.NewClient(Config)` I get the error:

```
couldn't open piece completion db in "/home/.../Download": timeout
```

I see there is `Close()` in `boltPieceCompletion.go`, but somehow it's not called on close?

**Comment by elgatito** [comment]
I have passed this with using manually defiend DefaultStorage in &Config{}, but still it's probably a bug?

**Comment by anacrolix** [comment]
Good catch, I'll try to track it down.

**Comment by anacrolix** [comment]
I'm able to reproduce. I take it you only get a log about it, and not an error from NewClient.

**Comment by elgatito** [comment]
There is a fallback to `NewMapPieceCompletion`, but I was not investigating which one is used after this message.

**Comment by anacrolix** [comment]
I have a fix for this, I will push it soon.
