### ISSUE TITLE
torrentfs doesn't build for windows

### ISSUE THREAD

**Issue by a7a2** [anacrolix/torrent#162]
C:\Go\gopath\src>go get github.com/anacrolix/torrent/cmd/torrentfs
# bazil.org/fuse
bazil.org\fuse\error_std.go:27: undefined: errNoXattr
bazil.org\fuse\fuse.go:1345: undefined: attr
bazil.org\fuse\fuse_kernel.go:166: undefined: syscall.O_DIRECTORY
bazil.org\fuse\fuse_kernel.go:175: undefined: syscall.O_ACCMODE
bazil.org\fuse\fuse_kernel.go:404: undefined: attr

**Comment by anacrolix** [comment]
I don't think bazil.org/fuse supports windows. See http://godoc.org/bazil.org/fuse:
>Package fuse enables writing FUSE file systems on Linux, OS X, and FreeBSD.
