### ISSUE TITLE
Download not starting when using t.AddPeers()

### ISSUE THREAD

**Issue by kklas** [anacrolix/torrent#169]
Hi,

I'm adding peers manually with `func (t *Torrent) AddPeers(pp []Peer)` and have disabled trackers in the client configuration.

The problem I have is when I add a seed peer that is not yet up, the client will keep the peer in a half-open state, and the download won't start even after one minute of starting the seed peer.

One fix I have found is to re-add the peer, but this only works when I set `DisableUTP: true` in the config, but not when `DisableTCP: true`. This is very hacky and not ideal.

Any ideas how to solve this? Will the half-open connections resolve eventually? When?

**Comment by anacrolix** [comment]
The outbound connection should expire after no more than 30 seconds. It looks the timeout isn't used for the libutp version of Socket.DialTimeout: https://github.com/anacrolix/go-libutp/blob/master/socket.go#L159, and the wrapped libutp library might be getting into a bad state (it does that) and not using its own internal timeout correctly.

**Comment by anacrolix** [comment]
I've added anacrolix/go-libutp#1. Are you able to confirm that go-libutp is the utp implementation your configuration is using? It should be selected with recent anacrolix/torrent if you have cgo enabled.

**Comment by kklas** [comment]
Using newest version of anacrolix/torrent and cgo is enabled.

Still, when using TCP the conections are in half-open state even after 3 minutes (output from client.WriteStatus()). I start the seed peer immediately after starting the other peer. Is the only way to make the connection to re-add the peers on an interval? Isn't TCP supposed to connect after retries?

**Comment by anacrolix** [comment]
I've fixed the bug I observed in anacrolix/go-libutp#1, this may help.

How are you determining that the connections to your other peer are the ones in the half-open state? Do you mean TCP half-open or torrent client half-open? They're not the same. TCP will do resends while attempting to connect, but not usually for very long.

I think I need more information.

**Comment by kklas** [comment]
Unfortunately, I don't have access to the code I was working on (complicated situation) so I can't look into it deeper. One thing I forgot to mention is that I'm always using IPv6. Last time I was working on it the situation was:

two machines on LAN:
  UTP - works as expected (leech peer is able to connect to seed peer even with leech peer starting before seed peer)
  TCP - didn't test

two clients running on same machine on different ports:
  UTP - when starting the leech peer before the seed peer, the only way they are able to connect is to re-add the the seed peer to the torrent on the leech peer client. Also I'm getting ECONNRESET log messages
  TCP - same as UTP but without getting the ECONNRESET log message

Sorry it's not very detailed or precise - I'm writing this from the top of my head since I don't have access to my code anymore. I'll try to do some more testing if/when I get my code back.

**Comment by anacrolix** [comment]
I believe this is fixed by https://github.com/anacrolix/go-libutp/commit/e269ab9501c073d3e14e463f7d90c6d636553871.
