### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ericnyamu** [anacrolix/torrent#17]
Since we are dealing with torrents here is there away (using scripts) to download top 20 torrents(movies)with the highest seed count found on kickasstorrent movie section page found here https://kat.cr/movies/ .
The script should also be able to check  for duplicate movies and also be able to ignore torrents with certain words like cam or spanish (for english speaking people).
    The script could be ran once after three days (using cron job) to scrape the section(movie) and download the top 20 movie torrents by invoking a torrent client of choice.Also if the script could be ran on linux it would be nice.I know its a simple matter of parsing the html file @ kat.cr/movies then scraping for top torrents with user defined setting then invoking a torrent client to download the torrent but i just donot know how to do it programmatically.
Kickasstorrent also have an api @ https://kat.cr/api/ . also this github user has some kickasstorrent api : https://github.com/stephan-mclean/KickassTorrentsAPI and also this one https://github.com/asfaltboy/meowify

**Comment by anacrolix** [comment]
Writing such a script is outside the scope of the project. You can definitely invoke cmd/torrent with your magnets and torrents when you're done scraping, and it will complete when everything has been downloaded to the working directory.

I will close this issue. If there are specific features you need that are in the scope of the project, please report them.
