### ISSUE TITLE
How to get info dictionary of a torrent as it is?

### ISSUE THREAD

**Issue by boramalper** [anacrolix/torrent#170]
I want to get the bencoded `info` dictionary of the torrent **as it is** (*i.e.* where the SHA-1 sum of the blob would be same as the torrent's info hash).

I couldn't find any way to do it, so I'm asking here.

**Comment by anacrolix** [comment]
Special treatment is made of the info bytes, for the reasons you are clearly aware of. Try https://godoc.org/github.com/anacrolix/torrent#Torrent.Metainfo. The returned type contains the info bytes. https://godoc.org/github.com/anacrolix/torrent/metainfo#MetaInfo

**Comment by boramalper** [comment]
Okay that worked! Thanks a ton. =)

**For Reference:**

```
package main

import (
	"github.com/anacrolix/torrent"
	"crypto/sha1"
	"fmt"
)

func main() {
	info_hash := "742B6526705073686D68D8CDAE853D523D0DA21C"

	c, _ := torrent.NewClient(nil)
	defer c.Close()

	fmt.Printf("<- %s\n", info_hash)
	t, _ := c.AddMagnet(fmt.Sprintf("magnet:?xt=urn:btih:%s", info_hash))
	<- t.GotInfo()

	fmt.Printf("-> %X\n", sha1.Sum(t.Metainfo().InfoBytes))
}
```
