### ISSUE TITLE
go-libutp build issues on Windows

### ISSUE THREAD

**Issue by shellus** [anacrolix/torrent#171]
```cmd

C:\Users\shellus\go\src\github.com\shellus\untitled>go get github.com/anacrolix/torrent
# github.com/anacrolix/go-libutp
..\..\anacrolix\go-libutp\utp.go:12:1: error: unknown type name 'uint64_t'
 uint64_t errorCallback(utp_callback_arguments *);
 ^~~~~~~~
..\..\anacrolix\go-libutp\utp.go:13:1: error: unknown type name 'uint64_t'
 uint64_t logCallback(utp_callback_arguments *);
 ^~~~~~~~
..\..\anacrolix\go-libutp\utp.go:14:1: error: unknown type name 'uint64_t'
 uint64_t acceptCallback(utp_callback_arguments *);
 ^~~~~~~~
..\..\anacrolix\go-libutp\utp.go:15:1: error: unknown type name 'uint64_t'
 uint64_t sendtoCallback(utp_callback_arguments *);
 ^~~~~~~~
..\..\anacrolix\go-libutp\utp.go:16:1: error: unknown type name 'uint64_t'
 uint64_t stateChangeCallback(utp_callback_arguments *);
 ^~~~~~~~
..\..\anacrolix\go-libutp\utp.go:17:1: error: unknown type name 'uint64_t'
 uint64_t readCallback(utp_callback_arguments *);
 ^~~~~~~~

C:\Users\shellus\go\src\github.com\shellus\untitled>


```

**Comment by anacrolix** [comment]
It looks like you are on Windows. I don't have access to a Windows machine, but if you're familiar with C you may need to add something like `#include <stdint.h>`.

**Comment by shellus** [comment]
shellus@WIN-0F1IMB3OK7F MINGW64 ~
$ go install github.com/anacrolix/torrent
# github.com/anacrolix/go-libutp
C:\Users\shellus\AppData\Local\Temp\go-build429960314\github.com\anacrolix\go-libutp\_obj\utp_internal.cpp.o: In function `aux::host_to_network(unsigned int)':
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_templates.h:70: undefined reference to `__imp_htonl'
C:\Users\shellus\AppData\Local\Temp\go-build429960314\github.com\anacrolix\go-libutp\_obj\utp_internal.cpp.o: In function `aux::host_to_network(unsigned short)':
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_templates.h:69: undefined reference to `__imp_htons'
C:\Users\shellus\AppData\Local\Temp\go-build429960314\github.com\anacrolix\go-libutp\_obj\utp_internal.cpp.o: In function `aux::host_to_network(unsigned int)':
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_templates.h:70: undefined reference to `__imp_htonl'
C:\Users\shellus\AppData\Local\Temp\go-build429960314\github.com\anacrolix\go-libutp\_obj\utp_internal.cpp.o: In function `aux::host_to_network(unsigned short)':
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_templates.h:69: undefined reference to `__imp_htons'
C:\Users\shellus\AppData\Local\Temp\go-build429960314\github.com\anacrolix\go-libutp\_obj\utp_internal.cpp.o: In function `aux::host_to_network(unsigned int)':
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_templates.h:70: undefined reference to `__imp_htonl'
C:\Users\shellus\AppData\Local\Temp\go-build429960314\github.com\anacrolix\go-libutp\_obj\utp_internal.cpp.o: In function `aux::network_to_host(unsigned short)':
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_templates.h:72: undefined reference to `__imp_ntohs'
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_templates.h:72: undefined reference to `__imp_ntohs'
C:\Users\shellus\AppData\Local\Temp\go-build429960314\github.com\anacrolix\go-libutp\_obj\utp_internal.cpp.o: In function `aux::host_to_network(unsigned short)':
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_templates.h:69: undefined reference to `__imp_htons'
C:\Users\shellus\AppData\Local\Temp\go-build429960314\github.com\anacrolix\go-libutp\_obj\utp_internal.cpp.o: In function `aux::network_to_host(unsigned short)':
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_templates.h:72: undefined reference to `__imp_ntohs'
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_templates.h:72: undefined reference to `__imp_ntohs'
C:\Users\shellus\AppData\Local\Temp\go-build429960314\github.com\anacrolix\go-libutp\_obj\utp_internal.cpp.o: In function `aux::host_to_network(unsigned short)':
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_templates.h:69: undefined reference to `__imp_htons'
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_templates.h:69: undefined reference to `__imp_htons'
C:\Users\shellus\AppData\Local\Temp\go-build429960314\github.com\anacrolix\go-libutp\_obj\utp_internal.cpp.o: In function `aux::host_to_network(unsigned int)':
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_templates.h:70: undefined reference to `__imp_htonl'
C:\Users\shellus\AppData\Local\Temp\go-build429960314\github.com\anacrolix\go-libutp\_obj\utp_internal.cpp.o: In function `aux::host_to_network(unsigned short)':
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_templates.h:69: undefined reference to `__imp_htons'
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_templates.h:69: undefined reference to `__imp_htons'
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_templates.h:69: undefined reference to `__imp_htons'
C:\Users\shellus\AppData\Local\Temp\go-build429960314\github.com\anacrolix\go-libutp\_obj\utp_internal.cpp.o: In function `aux::host_to_network(unsigned int)':
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_templates.h:70: undefined reference to `__imp_htonl'
C:\Users\shellus\AppData\Local\Temp\go-build429960314\github.com\anacrolix\go-libutp\_obj\utp_internal.cpp.o: In function `aux::host_to_network(unsigned short)':
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_templates.h:69: undefined reference to `__imp_htons'
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_templates.h:69: undefined reference to `__imp_htons'
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_templates.h:69: undefined reference to `__imp_htons'
C:\Users\shellus\AppData\Local\Temp\go-build429960314\github.com\anacrolix\go-libutp\_obj\utp_internal.cpp.o: In function `aux::network_to_host(unsigned short)':
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_templates.h:72: undefined reference to `__imp_ntohs'
C:\Users\shellus\AppData\Local\Temp\go-build429960314\github.com\anacrolix\go-libutp\_obj\utp_internal.cpp.o: In function `aux::network_to_host(unsigned int)':
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_templates.h:73: undefined reference to `__imp_ntohl'
C:\Users\shellus\AppData\Local\Temp\go-build429960314\github.com\anacrolix\go-libutp\_obj\utp_internal.cpp.o: In function `aux::network_to_host(unsigned short)':
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_templates.h:72: undefined reference to `__imp_ntohs'
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_templates.h:72: undefined reference to `__imp_ntohs'
C:\Users\shellus\AppData\Local\Temp\go-build429960314\github.com\anacrolix\go-libutp\_obj\utp_internal.cpp.o: In function `aux::host_to_network(unsigned short)':
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_templates.h:69: undefined reference to `__imp_htons'
C:\Users\shellus\AppData\Local\Temp\go-build429960314\github.com\anacrolix\go-libutp\_obj\utp_internal.cpp.o: In function `aux::host_to_network(unsigned int)':
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_templates.h:70: undefined reference to `__imp_htonl'
C:\Users\shellus\AppData\Local\Temp\go-build429960314\github.com\anacrolix\go-libutp\_obj\utp_internal.cpp.o: In function `aux::host_to_network(unsigned short)':
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_templates.h:69: undefined reference to `__imp_htons'
C:\Users\shellus\AppData\Local\Temp\go-build429960314\github.com\anacrolix\go-libutp\_obj\utp_internal.cpp.o: In function `aux::host_to_network(unsigned int)':
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_templates.h:70: undefined reference to `__imp_htonl'
C:\Users\shellus\AppData\Local\Temp\go-build429960314\github.com\anacrolix\go-libutp\_obj\utp_packedsockaddr.cpp.o: In function `PackedSockAddr::set(sockaddr_storage const*, int)':
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_packedsockaddr.cpp:80: undefined reference to `__imp_ntohs'
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_packedsockaddr.cpp:75: undefined reference to `__imp_ntohs'
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_packedsockaddr.cpp:80: undefined reference to `__imp_ntohs'
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_packedsockaddr.cpp:75: undefined reference to `__imp_ntohs'
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_packedsockaddr.cpp:75: undefined reference to `__imp_ntohs'
C:\Users\shellus\AppData\Local\Temp\go-build429960314\github.com\anacrolix\go-libutp\_obj\utp_packedsockaddr.cpp.o: In function `PackedSockAddr::get_sockaddr_storage(int*) const':
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_packedsockaddr.cpp:115: undefined reference to `__imp_htons'
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_packedsockaddr.cpp:107: undefined reference to `__imp_htons'
C:\Users\shellus\AppData\Local\Temp\go-build429960314\github.com\anacrolix\go-libutp\_obj\utp_packedsockaddr.cpp.o: In function `PackedSockAddr::fmt(char*, unsigned long long) const':
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_packedsockaddr.cpp:133: undefined reference to `libutp::inet_ntop(int, void const*, char*, unsigned long long)'
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_packedsockaddr.cpp:127: undefined reference to `libutp::inet_ntop(int, void const*, char*, unsigned long long)'
collect2.exe: error: ld returned 1 exit status

shellus@WIN-0F1IMB3OK7F MINGW64 ~
$

**Comment by anacrolix** [comment]
https://stackoverflow.com/questions/2033608/mingw-linker-error-winsock

Where this is added on Windows with cgo I am not sure.

**Comment by axet** [comment]
I guess something like this:

```go
// +build darwin
package desktop
/*
#cgo LDFLAGS: -lobjc -framework AppKit
#include <stdlib.h>
#include <objc/objc-runtime.h>
BOOL NSApplicationLoad (void);
*/
import "C"
```

For OSX example...

**Comment by anacrolix** [comment]
Thanks @axet

**Comment by shellus** [comment]
Thanks @axet

I fix it, but I am having new problems

```
shellus@WIN-0F1IMB3OK7F MINGW64 ~
$ go install github.com/anacrolix/torrent
# github.com/anacrolix/go-libutp
C:\Users\shellus\AppData\Local\Temp\go-build196746206\github.com\anacrolix\go-libutp\_obj\utp_packedsockaddr.cpp.o: In function `PackedSockAddr::fmt(char*, unsigned long long) const':
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_packedsockaddr.cpp:133: undefined reference to `libutp::inet_ntop(int, void const*, char*, unsigned long long)'
C:/Users/shellus/go/src/github.com/anacrolix/go-libutp/utp_packedsockaddr.cpp:127: undefined reference to `libutp::inet_ntop(int, void const*, char*, unsigned long long)'
collect2.exe: error: ld returned 1 exit status

shellus@WIN-0F1IMB3OK7F MINGW64 ~
$

```

**Comment by anacrolix** [comment]
Windows is a problem :)

**Comment by shellus** [comment]
now only

 `undefined reference to `libutp :: inet_ntop (int, void const *, char *, unsigned long long) `

problem

see: https://stackoverflow.com/questions/15370033/how-to-use-inet-pton-with-the-mingw-compiler

I do not C language, so I can not do anything

**Comment by anacrolix** [comment]
How did you go with this?

**Comment by shellus** [comment]
I do not know what you are asking

**Comment by anacrolix** [comment]
Are you still having build issues on Windows?

**Comment by christian-roggia** [comment]
**NOTE: The following instructions will help you COMPILE the library in a Windows environment but the library itself WON'T work correctly on a Windows machine and you will get errors in runtime.**

I am sharing this information because some people, like me, might find useful to compile to code on a Windows machine even if the library is broken, this useful especially when you use `Atom` and `go plus` addon or for unittesting. I have a UNIX environment where I compile the code correctly for production and deployment but I still find it useful to be able to code on my desktop at home without the annoying "gcc: not found" notification.

**I will eventually fully convert the code to be completely Windows-compatible and I will PR to the original library repository and to this repository.**

In order to correctly compile the go-libutp on a Windows machine you'll have to edit the following files:

# **utp.h**
Add the following statement before the import `#include <stdarg.h>`

> #ifdef _WIN32
> #include <stdint.h>
> #endif

# **utp.go**

Add the following statement before the import #include "utp.h"`
> // Windows additional flags
> #cgo windows LDFLAGS: -lws2_32
> #cgo windows CXXFLAGS: -D_WIN32_WINNT=0x600

# **sockaddr.go**
Line 25:
> return (*C.struct_sockaddr)(unsafe.Pointer(&rsa)), C.socklen_t(unsafe.Sizeof(&rsa))

Line 36:
> return (*C.struct_sockaddr)(unsafe.Pointer(&rsa)), C.socklen_t(unsafe.Sizeof(&rsa))

# **conn.go**
Line 196:
> var addrlen C.socklen_t = C.socklen_t(unsafe.Sizeof(&rsa))

**Comment by anacrolix** [comment]
@christian-roggia any PRs that assist use of the package on Windows will be appreciated.

**Comment by mh-cbon** [comment]
hi,

i forked, patched the lib with the changes provided by christian-roggia, it built!

It works a little bit, I receive new errors such `[::]:8083->:8080: wsasendto: The requested address is not valid in its context.` which does not pop on linux.

built on appveyor 
- https://github.com/mh-cbon/rendez-vous/blob/master/appveyor.yml
- https://ci.appveyor.com/project/mh-cbon/rendez-vous/build/1.0.43

changes: https://github.com/mh-cbon/go-libutp/commit/6669cba2a727f28aee1393e8610452a2052188de

**Comment by mh-cbon** [comment]
hi,

i forked, patched the lib with the changes provided by christian-roggia, it built!

It works a little bit, I receive new errors such `[::]:8083->:8080: wsasendto: The requested address is not valid in its context.` which does not pop on linux.
I was not able to solve that error.

built on appveyor 
- https://github.com/mh-cbon/rendez-vous/blob/master/appveyor.yml
- https://ci.appveyor.com/project/mh-cbon/rendez-vous/build/1.0.43

changes: https://github.com/mh-cbon/go-libutp/commit/6669cba2a727f28aee1393e8610452a2052188de

**Comment by anacrolix** [comment]
I expect that Windows is not resolving :8080 to localhost:8080, which might be a Linux nicety. You'll need to track down where in the tests or your code this assumption is being made.

**Comment by mh-cbon** [comment]
> I expect that Windows is not resolving :8080 to localhost:8080, which might be a Linux nicety. You'll need to track down where in the tests or your code this assumption is being made.

yes, it was about the ip indeed.
To be more specific, the error will trigger if you try to write to a remote address like "0.0.0.0...".

**Comment by christian-roggia** [comment]
My suggestion for this PR is the following:
**DO NOT** apply changes directly to the code because this might break things on UNIX machines and we don't want that. Unfortunately this library is **NOT** unittested and we **CANNOT** assume that the library is working correctly just because the code compiles correctly under Windows and UNIX environments. 

In order to achieve this (an experimental code ONLY for Windows environment) we need to differentiate the code in UNIX and Windows machines:

- Add a file called conn_windows.go and copy the content of conn.go
- Add the build tag "+build windows" to the file conn_windows.go
- Apply the experimental code to the file conn_windows.go
- Add the build tag "+build !windows" to the file conn.go

NOTE: The file conn.go should be the original conn.go with the addition of the build tag.

> Same steps for sockaddr.go

More info about conditional compilation with go: https://dave.cheney.net/2013/10/12/how-to-use-conditional-compilation-with-the-go-build-tool

This way we can be sure that changes are applied only on Windows machines and we won't brake the code on other platforms.

NOTE: utp.h and utp.go in my previous comment **already have** conditional flags/tags which means they won't break the code on other environments.

**Comment by anacrolix** [comment]
The PR won't be accepted if it breaks unix functionality. anacrolix/go-libutp does have unit tests.

**Comment by mh-cbon** [comment]
@christian-roggia thanks for the very detailed inputs.

> DO NOT apply changes directly to the code because this might break things on UNIX machines and we don't want that. Unfortunately this library is NOT unittested and we CANNOT assume that the library is working correctly just because the code compiles correctly under Windows and UNIX environments.

I would not have know about that. 

By any chance can you elaborate about how it might fail ?

**Comment by mh-cbon** [comment]
> anacrolix/go-libutp does have unit tests.

I support this, 
https://travis-ci.org/mh-cbon/go-libutp/builds/274119973
https://ci.appveyor.com/project/mh-cbon/go-libutp/build/1.0.36

**Comment by christian-roggia** [comment]
@anacrolix @mh-cbon 

You are right about the unittesting, I saw **only 1 file with 3 unittests** and assumed that the library's unittests were not extensive enough, didn't realize that it makes use of the package **nettest**.

**Comment by mh-cbon** [comment]
@christian-roggia happy you double checked anyways.

**Comment by anacrolix** [comment]
This issue was moved to anacrolix/go-libutp#4

**Comment by anacrolix** [comment]
This has been fixed.
