### ISSUE TITLE
Can't install By using go get github.com/anacrolix/torrent ?

### ISSUE THREAD

**Issue by LuYuChengProject** [anacrolix/torrent#176]
When I run cmd , then get this error:

package golang.org/x/net/context: unrecognized import path "golang.org/x/net/context" (https fetch: Get https://golang.org/x/net/context?go-get=1: dial tcp: lookup golang.org: no such host)
package golang.org/x/time/rate: unrecognized import path "golang.org/x/time/rate" (https fetch: Get https://golang.org/x/time/rate?go-get=1: dial tcp: lookup golang.org: no such host)

How to fix it ?

**Comment by a7a2** [comment]
Hello, Chinese.Open your vpn please.

2017年8月13日 14:23，"Joe-Taki" <notifications@github.com>写道：

**Comment by anacrolix** [comment]
Thanks for the assistance @a7a2 .
