### ISSUE TITLE
Feature: webseeding

### ISSUE THREAD

**Issue by axet** [anacrolix/torrent#177]
Hello!

I update my app to download music from great78.archive.org, all .torrent files uses webseeding and seems 'torrent' does not support such a nice seeding boost. Would be nice to this option in an torrent app. 

  * https://archive.org/details/78rpm?&sort=-publicdate

**Comment by anacrolix** [comment]
I think we might start on this soon. See #116 .

**Comment by anacrolix** [comment]
Duplicate of #116.
