### ISSUE TITLE
Some dht-related examples don't run properly

### ISSUE THREAD

**Issue by Powersource** [anacrolix/torrent#178]
I haven't tried others but here are the two that don't work for me:

```
me@lap[anacrolix/torrent]% go run cmd/magnet-metainfo/main.go magnet:?xt=urn:btih:6a9759bffd5c0af65319979fb7832189f4f3c35d&dn=sintel.mp4           
[1] 30878
me@lap[anacrolix/torrent]% 2017/08/17 19:28:48 error announcing "6a9759bffd5c0af65319979fb7832189f4f3c35d" to DHT: no initial nodes
2017/08/17 19:28:48 error bootstrapping dht: no initial nodes
```
(also, this command starts two processes that I have to kill manually)

`go test -run example_test.go` says there are no tests to run (I am not familiar enough with go to know why) but copy pasting the code into a new file and running that gives this:

```
% go run main.go
making client
2017/08/17 19:36:53 error announcing "cb84ccc10f296df72d6c40ba7a07c178a4323a14" to DHT: no initial nodes
2017/08/17 19:36:53 error bootstrapping dht: no initial nodes
```

**Comment by anacrolix** [comment]
Thanks for the report. I've fixed the initial nodes warning. You must quote the magnet you pass as it contains a `&` which your shell will interpret to mean backgrounding and running multiple processes.
```
go run cmd/magnet-metainfo/main.go 'magnet:?xt=urn:btih:6a9759bffd5c0af65319979fb7832189f4f3c35d&dn=sintel.mp4'
```
The output will be `sintel.mp4.torrent` when it completes.
You may find [`godo`](https://github.com/anacrolix/godo) more intuitive.
```
go get github.com/anacrolix/godo
godo -v github.com/anacrolix/torrent/cmd/magnet-metainfo 'magnet:?xt=urn:btih:6a9759bffd5c0af65319979fb7832189f4f3c35d&dn=sintel.mp4'
$ ls sintel.mp4.torrent 
sintel.mp4.torrent
```

**Comment by Powersource** [comment]
Thanks for the quick fix!

Shouldn't CI have caught this? If we don't add this to the automatic tests this is likely to silently break again.

Also, I might be dumb here but what is the recommended way to handle this?: `example_test.go` works but when I want to change the target directory and therefore the config, it breaks. I think it's because I overwrite the entire default config and not just `DataDir`. The code I put at the start of the file, replacing the old NewClient call:

```
	var clientConfig torrent.Config
	clientConfig.DataDir = "bt-videos"
	c, _ := torrent.NewClient(&clientConfig)
```

**Comment by anacrolix** [comment]
I don't have any CI that checks the sample cmds work, but I do for the unit tests, so it checks they build https://circleci.com/gh/anacrolix/torrent . You'll probably want to specify the torrent.Config.DHTConfig.StartingNodes per the way it's done for the default config now. https://github.com/anacrolix/torrent/blob/master/client.go#L227

Also I forgot to mention earlier, but the `-run` flag to `go test` lets you specify which unit tests to run, as the next argument, which you've passed `example_test.go`, which is not valid.
