### ISSUE TITLE
Finding out Peers for a given torrent

### ISSUE THREAD

**Issue by rikonor** [anacrolix/torrent#179]
Hi,

First of all, thank you very much for this library.

I used to be able to find the Peers for a given torrent by using `t.Peers()` where `t` is a `torrent.Torrent`.

Apparently I was using a pretty outdated commit, but upon updating to the latest commit it seems like `Peers` is no longer there.

Was wondering if there was a reason it was removed and if there's another way to access that information?

Thanks!

**Comment by anacrolix** [comment]
It looks like it was lost in 153c13db4374722e7665311e0355fdb4c3820363, quite some time ago. I see no reason I can't reexpose it. It's an unusual thing to want to access, it only represents peers we will try next time we need more connections. You may find Torrent.Stats useful. May I ask what it is you're trying to achieve?

**Comment by rikonor** [comment]
Hi,

My use case is to crawl for Peers (the underlying use case is research) in order to find all (or as many) peers for a given torrent.

Ah, I thought that `Torrent.peers` was the peers we are currently connected to.

Interestingly, the `Peers()` implementation I had before I updated the repo to `master` (unfortunately, I don't remember the commit I was on) returned `[]Peers`, rather then `map[...]Peer` (it just iterated over the map).

I'm actually considering to just use `dht.Announce` and `tracker.Announce` now as there would be much less overhead involved. Do you think that would be more appropriate for this use case?

**Comment by anacrolix** [comment]
Yes you would be better off directly using the tracker and dht packages.

**Comment by rikonor** [comment]
Thanks @anacrolix, I leave it at your discretion to close this issue.

Also, can you elaborate a bit on the `Torrent.peers` not being the peers we are currently connected to? Are you basically opening connections to peers as they come along, but not store those peers anymore once they become connections, then keep track of additional peers that can be used to open new connections if previous connections close?

Finally, a couple of unsolicited suggestions:
1. You might want to publish releases (github lets you do that fairly easily) to make it easier to vendor this library, e.g `1.0.0`, `1.1.0`, etc.
2. You might want to run the library through `golint`, `govet`, etc. There are a few issues that those tools will complain about.

Thanks again,
Or

**Comment by anacrolix** [comment]
Your description of how Torrent.peers is used is spot on.

I haven't decided on a preferred way to version my Go stuff, as I don't use any vendoring. I'd be happy to take release/tagging suggestions from others if they have value in it.

Cheers

**Comment by rikonor** [comment]
Thanks @anacrolix, I've been using `dht` and `tracker` directly with good success so far.
