### ISSUE TITLE
New Feature: Custom torrent output

### ISSUE THREAD

**Issue by jpillora** [anacrolix/torrent#18]
How much of a change would it be to provide an `io.Writer` as the destination for in-progress torrent files:

``` go
client.SetOutput(func(file File) io.Writer {
  //file encrypter
  //network write (HTTP req starts torrent -> response streams it back?)
})
```

This way I wouldn't have to buffer files on disk before modifying them / sending them out again. Not sure if this is practical though.

**Comment by anacrolix** [comment]
Yes, this is a core feature for anacrolix/torrent. Open a torrent.Reader, set the areas of the torrent you desire, and you can just Read/ReadAt/whatever from it as the data arrives.

http://godoc.org/github.com/anacrolix/torrent#ex-package--FileReader

You can configure the torrent data backend to store data however you wish. http://godoc.org/github.com/anacrolix/torrent#Config, see TorrentDataOpener. This part of the API isn't set in stone, as I currently have only my use-cases to consider. Piece-based, mmap'd-files, raw files, and REST backends have been implemented.

Let me know how this addresses your requirements.

**Comment by jpillora** [comment]
Ah awesome! Sorry didn't notice that. I'd just set `DataDir` to `os.TempDir()`, local temporary data storage is fine, my goal is to be able to stream the torrent as it arrives, which it looks like it does. Closed :+1:

**Comment by anacrolix** [comment]
Sorry I'm not very good at communicating features and API. I would love any doc enhancements you can muster. You might like to take a look at how ./torrentfs works, and ./cmd/torrentfs. It streams and stores using the file-based scheme too.

**Comment by jpillora** [comment]
No worries, I find that too and I think examples are the easiest way to convey features. In hindsight I've already been using the `cmd/*` tools as reference and should have looked there first.
