### ISSUE TITLE
Implement `Peers()` for type Torrent

### ISSUE THREAD

**Issue by boramalper** [anacrolix/torrent#183]
I need to move a torrent between different `Client`s in my program and to do this, being able to copy the list of the active peers is sufficient. But unfortunately, there is no `Peers()` function for type Torrent that returns the list of all `Peer`s for a given torrent.

I can implement it myself and send a PR if you are fine.

Best!

**Comment by anacrolix** [comment]
Sounds good. I'm not sure of the naming to use, as you have "pending", "active", and "half-open" connections to peers, but sounds like you only intend to return `Peer` values for them. That type can be produced for each of those peer categories from the data structures in `Torrent`, and the combined state for them represents a subset of the swarm for the torrent, the known swarm if you will. With that information I'd suggest adding `func (*Torrent) KnownSwarm() []Peer`, returning `Peer` values derived from all the aforementioned states.

**Comment by christian-roggia** [comment]
+1 I was looking for a function similar to this one in the past

**Comment by anacrolix** [comment]
@boramalper Have you started on this? Do you want me to do it?

**Comment by boramalper** [comment]
@anacrolix I'm starting right now =)

**Comment by anacrolix** [comment]
I believe this is fixed!
