### ISSUE TITLE
Hashing is very slow at 16-32 MB/s

### ISSUE THREAD

**Issue by ambientsound** [anacrolix/torrent#184]
Hello,

I want to use the torrent library in a project that will distribute files across a number of heterogenous storage nodes. I wrote a very simple client, the source code is here: https://gist.github.com/ambientsound/bbc30b258bdd253d5fbaa6ce339e2ff1

Now, after adding a torrent, the client starts hashing. The hash speed is very slow, however, stuck between 16-32 MB/s. The filesystem can handle around 250 MB/s when doing `sha1sum` from the command line.

I expect 10x the performance I can see from the torrent library, and thus assume that I'm doing something wrong. Can you provide some help?

**Comment by ambientsound** [comment]
Here's the torrent file, attached as zip: [ecatmo.zip](https://github.com/anacrolix/torrent/files/1270480/ecatmo.zip)

**Comment by ambientsound** [comment]
On another system I can see speeds of 160M/s when running the hash operation. Any suggestions on debugging steps?

**Comment by anacrolix** [comment]
Without knowing more, I'd guess that your systems may be different architectures, one of which doesn't have an optimized SHA1 in Go. Can you benchmark SHA1 for those systems using Go?

**Comment by ambientsound** [comment]
Hi again. I wrote the following benchmark. Not sure if this is representative or realistic, though.

```
package main_test

import (
        "crypto/sha1"
        "testing"
)

func BenchmarkSha1(b *testing.B) {
        payload := []byte("this is some text that must be hashed.")
        h := sha1.New()
        for n := 0; n < b.N; n++ {
                h.Sum(payload)
        }
}
```

The benchmark did 3M iterations, and on the fast hashing and slow hashing system, resulted in 474 ns/op and 552 ns/op respectively. I'm running Go 1.9.

**Comment by ambientsound** [comment]
Furthermore, both systems are running Ubuntu Xenial, they are x86_64 architecture.

The slow hashing system is running on a `Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz`.

**Comment by ambientsound** [comment]
Hi again. Sorry for spamming the thread.

I ran the same code again on the slow machine with CPU profiling enabled. The profiling report reveals some interesting numbers. Of CPU time:

* 23.88% is spent actually computing the SHA1 sum.
* 66.05% is spent in the `fileTorrentImplIO.readFileAt` function, of which:
  * 23.06% is spent on file `Open()` call.
  * 15.13% is spent on file `Close()` call.

Nearly 40% is spent opening and closing the file. The slow machine is running the Lustre high performance file system. I suspect there is a lot more overhead opening and closing files on Lustre than on ext4.

For reference, here is a zip with the compiled binary, the profiling results, and the profiling graph:
 [pprof.zip](https://github.com/anacrolix/torrent/files/1274793/pprof.zip).

**Comment by anacrolix** [comment]
Thanks, this is very helpful!

**Comment by anacrolix** [comment]
There should be an optimisation for storing the successful state in a .torrent.bolt.db file, in the data directory. Is that present? Are you getting warnings about any issues with it? I note that lustre is a distributed network filesystem, does it support sync and memory mapping as expected by something like bolt?

A file handle could be associated with `storage.Piece`, or the API modified to provide opening and closing a handle to the piece, to allow reuse of resources between successive ReadAt/WriteAts. It seems unfortunate that this would be necessary, are there any options you can manipulate with your fs? Testing on a ext4 16.04 Ubuntu I get overheads of <3% for opening and closing files.

**Comment by ambientsound** [comment]
The `.torrent.bolt.db` file is present and working. There are no warnings, to the best of my knowledge. For this test I placed this file on the shared memory file system `/dev/shm`, so it should really be lightning fast and have no problems with mmap.

Unfortunately I'm unable to experiment with the filesystem flags, as this is a production system and I don't have access to hardware resources that would replicate the current setup. I talked with the team in charge of our setup, they are concerned with the large number of small writes and file re-opens.

Our setup is optimised for HPC workloads and parallell I/O, so big chunk sizes in combination with file descriptors that are kept open should probably do the trick.

**Comment by anacrolix** [comment]
I'll take another look at your pprof, I think the best way forward will be to modify the storage Piece API slightly to allow persistent file descriptor use. That should be enough, but if it isn't, some custom user-space caching of chunks will be necessary, that's a larger change.

**Comment by anacrolix** [comment]
Does lustre support memory mapping files? I can't determine that

**Comment by elgatito** [comment]
We were chatting about this on gitter before. Maybe we can add functionality like libtorrent's Fastresume, to save file state and then reusing it without doing hashing next time. Something like `Torrent->SaveState()->Close()`, then `Torrent->OpenWithState()`

**Comment by anacrolix** [comment]
> Maybe we can add functionality like libtorrent's Fastresume, to save file state and then reusing it without doing hashing next time.

This is actually already present. I believe there may be an inefficiency however for pieces that haven't been completed, but the file has been truncated in preparation for the data. This is very likely what @ambientsound is encountering. If there are lots of large files in his test torrent, and he's resuming the download after completing much previously. See here: https://github.com/anacrolix/torrent/blob/master/torrent.go#L1479. This isn't as much of a problem if piece-based storage backend is used, and probably not a problem at all if there are no incompleted files lying around on startup.

This section here triggers the hashing when a torrent is added, it has been in and out of occurring automatically throughout the client's history, I am considering making the user issue it instead.

**Comment by elgatito** [comment]
> See here. This isn't as much of a problem if piece-based storage backend is used, and probably not a problem at all if there are no incompleted files lying around on startup.

If you remember, we have spoke about that before. We had issues because of `sum := t.hashPiece(piece)` for each piece when already-downloaded torrent was loaded and it tried to make hash of each piece to verify its consistent. I will make a test with latest master to see if current code changes anything with that situation. have not used it for 4 months probably.

**Comment by ambientsound** [comment]
Maybe relevant to the discussion, the download speed is also capped when seeding and leeching on the system when serving and downloading data from Lustre. The speeds measured range from 1-10 MB/s. I suspect this is due to the same problem.

The torrent contains one file of 8 GB.

**Comment by anacrolix** [comment]
Yeah you should get some crazy syscall usage writing chunks constantly. Could you try with your `torrent.Config.DefaultStorage = storage.NewMMap(config.DataDir)`? I don't know why I didn't think of this earlier.

**Comment by ambientsound** [comment]
Trying with memory mapped default storage does not yield any visible difference in speeds, except perhaps the minimum speed went from 1 MB/s to 2 MB/s.

**Comment by anacrolix** [comment]
The issue is about hashing speed, how does it compare with mmap storage? I've pushed 2aa20b3e222e218541b30d9e063cd2e3c855e9ca which removes automatic verification when torrents are added (but of course previously determined piece completion is still used). It's not technically a fix for the speed issue you saw with the file backend, but will help nonetheless.

**Comment by ambientsound** [comment]
Sorry for the delayed response. The reported speed is the hashing speed, not the transfer speed.

This ticket is about hashing speed, although it might really be that the design choices made are influencing file operation speed on this particular file system. Do you suggest that a new ticket is created?

**Comment by anacrolix** [comment]
I thought you mean transfer speed. You said your hashing speed was initially 16-32MB/s, what is it now? If it's still roughly the same, I suspect as you would expect, that distributed filesystems are slower except for long sequential operations. Torrent prefers to write chunks all over the place. It's difficult to justify redesigning the management of incomplete pieces just for this case. I have used an S3 storage backend in the past, but I maintained incomplete pieces on the local filesystem. I'm not sure what your use case is, but if your end goal is the completed files from the torrent on your distributed filesystem, you may find it faster to run the client with storage on the local filesystem, and stream the completed files to your distributed filesystem. `io.Copy(fileOnDistributedFS, torrent.Reader)`. The implementation will take care of prioritisation and ensure the data is streamed in order. You can use a piece cache, similar to what is used in https://github.com/anacrolix/confluence.

**Comment by anacrolix** [comment]
What's the status of this issue? Are you still having the performance issues?

**Comment by ambientsound** [comment]
Hi @anacrolix, due to the fact that the file system was tuned for large sequential workloads, and that the torrent protocol inherently is based on random reads and writes, we decided to try another approach. Thanks for your support in this issue.

**Comment by anacrolix** [comment]
No problem, cheers.
