### ISSUE TITLE
Extract file attributes

### ISSUE THREAD

**Issue by themihai** [anacrolix/torrent#186]
Is it possible to extract the File attributes such [Filemode](https://godoc.org/os#FileMode)  so that I can check the permissions/if it's a directory([FileMode.IsDir](https://godoc.org/os#FileMode.IsDir)) or  modification time?

**Comment by anacrolix** [comment]
Do you mean for this type? https://godoc.org/github.com/anacrolix/torrent#File

**Comment by anacrolix** [comment]
File modes do not exist at the torrent info level. Directories are not exposed through the Torrent type. The storage defines how torrent data is stored, and it doesn't even need to be file-based, so I guess the answer is maybe, but it's dependent on the [storage](http://godoc.org/github.com/anacrolix/torrent/storage). You must modify or explicitly manage your storage to be file-based if you want any of these things.
