### ISSUE TITLE
cmd/torrent always fails on macOS at bind: address already in use

### ISSUE THREAD

**Issue by artyom** [anacrolix/torrent#187]
`cmd/torrent` (checked 0388ec1, Go 1.9) on macOS High Sierra beta always fails at:

    ¶ torrent 'magnet:?xt=urn:btih:KRWPCX3SJUM4IMM4YF5RPHL6ANPYTQPU'
    2017/09/10 14:25:43 main.go:170: error creating client: listen udp :50007: bind: address already in use

Strangely the listed line `main.go:170` doesn't seem to obviously call anythig related to listen:

https://github.com/anacrolix/torrent/blob/0388ec1/cmd/torrent/main.go#L170

I guess this error originates from somewhere else.

**Comment by anacrolix** [comment]
Can you try with `-addr=:0` ? You likely have another instance of `cmd/torrent` running, or forgotten in the background.

**Comment by anacrolix** [comment]
Also your torrent package is probably out of date, hence the line number discrepancy. Try `go get -u github.com/anacrolix/torrent/cmd/torrent`.

**Comment by artyom** [comment]
Sorry for not making it clear earlier — this was done on a clean GOPATH, so it's with all dependencies fetched by `go get`. I wiped GOPATH and run `go get` again to get a clean state (previous was done a few days earlier), now it fails in a different way:

```
tmp ¶ /tmp/go/bin/torrent 'magnet:?xt=urn:btih:KRWPCX3SJUM4IMM4YF5RPHL6ANPYTQPU'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x441f164]

goroutine 1 [running]:
github.com/anacrolix/go-libutp.(*Socket).Close(0x0, 0x0, 0x0)
	/tmp/go/src/github.com/anacrolix/go-libutp/socket.go:131 +0x74
github.com/anacrolix/torrent.(*Client).Close(0xc420189c00)
	/tmp/go/src/github.com/anacrolix/torrent/client.go:359 +0x1d8
github.com/anacrolix/torrent.NewClient.func2(0xc420155e00, 0xc42000e740)
	/tmp/go/src/github.com/anacrolix/torrent/client.go:250 +0x3b
github.com/anacrolix/torrent.NewClient(0xc4201d8000, 0xc4201d8000, 0x48f30a0, 0xc42015ca50)
	/tmp/go/src/github.com/anacrolix/torrent/client.go:300 +0xaac
main.main()
	/tmp/go/src/github.com/anacrolix/torrent/cmd/torrent/main.go:173 +0x157
```

Here's the list of all git repos in GOPATH that were fetched by `go get` with their checked out versions:

```
golang.org/x/net	66aacef
golang.org/x/time	8be79e1
github.com/ryszard/goskiplist	2dfbae5
github.com/boltdb/bolt	fa5367d
github.com/huandu/xstrings	d6590c0
github.com/glycerine/go-unsnap-stream	87275ce
github.com/philhofer/fwd	bb6d471
github.com/golang/snappy	553a641
github.com/gosuri/uilive	ac356e6
github.com/gosuri/uiprogress	d0567a9
github.com/google/btree	316fb6d
github.com/anacrolix/tagflag	4643b59
github.com/anacrolix/dht	bfcf39d
github.com/anacrolix/go-libutp	0b46da3
github.com/anacrolix/torrent	0388ec1
github.com/anacrolix/missinggo	5738054
github.com/anacrolix/envpprof	0383bfe
github.com/anacrolix/sync	d29d955
github.com/anacrolix/utp	87ba793
github.com/spaolacci/murmur3	9f5d223
github.com/willf/bitset	v1.0.0-119-g1a37ad9
github.com/willf/bloom	v2.0.0-43-g54e3b96
github.com/dustin/go-humanize	79e699c
github.com/RoaringBitmap/roaring	v0.2.8-131-gad459fb
github.com/bradfitz/iter	454541e
github.com/tinylib/msgp	4a23c71
github.com/mattn/go-sqlite3	05548ff
github.com/edsrzf/mmap-go	0bce6a6
```

**Comment by anacrolix** [comment]
Have you rebooted this machine since your last attempt? The error you're getting seems plausible if a non-nil utp Socket is returned but I don't see how that could occur in the code. The true origin of the failure though still appears to be failure to bind to the same address. Try with `-addr=:0` or reboot your machine to rule out forgotten processes.

**Comment by artyom** [comment]
Ok, looks like I've found a way to reproduce this:

1. On the first run of the program after reboot macOS pops up an UI dialog asking whether you want to allow the program to accept incoming connections, the program seems to be working just fine on this run (see attached screenshot).

![screen shot 2017-09-11 at 14 15 31](https://user-images.githubusercontent.com/68182/30272168-d7c178ae-96fb-11e7-97e7-35f51be1fd65.jpg)

2. If you choose the allow option, the system user/password dialog pops up to save preferences.
3. If you cancel this popup without providing user/password, then on the next run the program crashes with the panic listed above — during this time the firewall prompt pops up again briefly, but disappears once the the program crashes, which takes sub-second, so this dialog is hard to notice (and impossible to interact with).

**Comment by anacrolix** [comment]
Thanks for the detailed instructions. Step 2 doesn't occur for me. I hit allow in step 1, and that's it.

**Comment by anacrolix** [comment]
Clicking deny, gives me this error, which helps with the earlier problems:
```
$ torrent 'magnet:?xt=urn:btih:KRWPCX3SJUM4IMM4YF5RPHL6ANPYTQPU'
2017/09/12 09:49:19 main.go:167: error creating client: listen udp :50007: bind: address already in use
```

**Comment by anacrolix** [comment]
I just realised the error. This is one of those idiotic nil pointer inside an interface issues. I shouldn't have picked Go.
