### ISSUE TITLE
How to disable DefaultStorage/automatic download?

### ISSUE THREAD

**Issue by themihai** [anacrolix/torrent#190]
I just found out that while I'm reading from [torrent.Reader ](https://godoc.org/github.com/anacrolix/torrent#Reader)the library somehow downloads and creates files in background in the working directory. How can I disable this behaviour?  I want to download/read files only through the [Reader](https://godoc.org/github.com/anacrolix/torrent#Reader.Read) interface  and copy/write it manually(e.g. write it in a Amazon S3 object)without to save anything on the disk.

**Comment by anacrolix** [comment]
The client requires somewhere to store incomplete data. Use one of the other provided storage backends, or implement your own. The file storage is the default as that's the most familiar to incoming users.

I use a piece-based cache in some of my downstream projects. I did have an S3 storage backend at one point, I can confirm that works. If however you want to stream completed files to S3, you may want to implement a purely memory based storage backend, or use small cache.

**Comment by themihai** [comment]
> The client requires somewhere to store incomplete data. 

Could you please elaborate a bit more on this?  Even if I use a in-memory backend how can I set the client to download only a specific file at a time from the torrent and download its content sequentially so that I can also stream it while is being downloaded? Having an in memory storage I need to make sure that the content downloaded is also streamed (i.e. to S3) as soon as it becomes available to avoid memory starvation. Basically the point is to download only what I need and when I need it.

Here is the solution I'm thinking about: 
  - Get the file pieces offsets using [(*File).State()](https://godoc.org/github.com/anacrolix/torrent#File.State)
  - Prioritize the pieces sequencelly using (*File).[PrioritizeRegion](https://godoc.org/github.com/anacrolix/torrent#File.PrioritizeRegion) 

The code is below. The issue is that I have no guarantee that the Client will download only the pieces I prioritise. Is it possible to force it download only what I set with PrioritizeRegion without anything else in background? 

```
// ReadFile receives a torrent and the path of the file to download from
// the torrent. It writes its content into dest
func ReadFile(to *torrent.Torrent, filePath string, dest io.Writer) error {
	var file *torrent.File
	for _, f := range to.Files() {
		if f.Path() == filePath {
			file = f
			break
		}
	}
	torrentReader := to.NewReader()
	// get the file reader
	fileReader = missinggo.NewSectionReadSeeker(r, f.Offset(), f.Length())
	pieces := file.State()
	var totalRead int64
	// Loop through the file pieces and read them sequentially. We assume that
	// file.State() returns them sequentially.
	for k, piece := range file.State() {
		// Download only the piece we need
		file.PrioritizeRegion(file.Offset()+totalRead, piece.Bytes)
		// wait until the piece is downloaded
		for {
			pieces := file.State()
			if pieces[k].Complete {
				break
			}
			time.Sleep(1 * time.Second) // cool it down a bit
		}
		// Write the downloaded piece in our destination
		i, err := io.Copy(dest, fileReader)
		if err != nil {
			log.Error(err)
			return err
		}
		totalRead += i
	}
	return nil
}
```

**Comment by anacrolix** [comment]
> Even if I use a in-memory backend how can I set the client to download only a specific file at a time from the torrent and download its content sequentially so that I can also stream it while is being downloaded?

That's the default behaviour. If you open a Reader and just start reading, the priorities are handled for you. If the storage backend is in memory, then nothing will hit disk, and the data will stream out in the order you read it from the Reader.

I'm curious why this isn't apparent, it's sort of the main feature of this implementation, can you suggest somewhere in the documentation I could make this clear to assist as it's a common point of confusion.

**Comment by anacrolix** [comment]
The rest of your comment builds on the earlier point. You don't need to manage any of the priorities manually. If you want to minimize the amount of caching required, limit the [readahead](https://godoc.org/github.com/anacrolix/torrent#Reader.SetReadahead) on the Reader.

**Comment by elgatito** [comment]
> Even if I use a in-memory backend how can I set the client to download only a specific file at a time from the torrent and download its content sequentially so that I can also stream it while is being downloaded?

Actually, I have implemented, what I wanted, using memory for downloading and reading by a media player.

The problem arise when you need a 8gb file (for example) on a 1gb device and you don't want to bother IO devices. How I do it: initialize a memory buffer for N pieces, watching reader position to see when piece is no longer needed and is already read, remove piece from memory, download next piece, and so on. 

Works just fine with a 150-250mb buffer for 1080p movies.

Probably it can be a PR into this library to include in basic functionality...

**Comment by themihai** [comment]
@anacrolix  what made me think that Reader doesn't work that way is that certain files that I never [Read](https://godoc.org/github.com/anacrolix/torrent#Reader.Read) are automatically downloaded in the default storage. For example I [Read](https://godoc.org/github.com/anacrolix/torrent#Reader.Read) a big file `x.ISO` but while I'm reading this I can observe that other files (e.g. readme.txt etc) are being downloaded/completed concurrently in working directory. Is there any way that I can stop the download of these files? What triggers the download of these files?

**Comment by themihai** [comment]
I also set SetReadAhead to 0 with no difference(i.e. files are still being downloaded even if I don't Read them).

**Comment by anacrolix** [comment]
> How I do it: initialize a memory buffer for N pieces, watching reader position to see when piece is no longer needed and is already read, remove piece from memory, download next piece, and so on.

I do it very similar. I have an LRU cache for the pieces. https://github.com/anacrolix/torrent/blob/master/storage/piece_resource.go#L15, and https://godoc.org/github.com/anacrolix/missinggo/filecache#Cache.AsResourceProvider. I see it's not clear that is an option.

**Comment by anacrolix** [comment]
> What triggers the download of these unwanted files?

The pieces in a torrent don't align to piece boundaries. So if you download the beginning of one file, you may be getting the end of another.

**Comment by elgatito** [comment]
>  I have an LRU cache for the pieces. https://github.com/anacrolix/torrent/blob/master/storage/piece_resource.go#L15, and https://godoc.org/github.com/anacrolix/missinggo/filecache#Cache.AsResourceProvider. I see it's not clear that is an option.

Do you have any example of usage LRU as a storage? Maybe it's better than what I've got. 
Spent some time to make count when reader already read that piece.

**Comment by anacrolix** [comment]
Yes, it's used by default by [confluence](https://github.com/anacrolix/confluence). See here: https://github.com/anacrolix/confluence/blob/master/main.go#L43 for how it's configured for that project.

**Comment by themihai** [comment]
@anacrolix  That makes sense. I'm closing this.
