### ISSUE TITLE
Resuming of torrents on restart

### ISSUE THREAD

**Issue by deranjer** [anacrolix/torrent#194]
I'm not sure if this is implemented (not sure if it should be in this package, but saw that bolt had a "completed" bucket) but I was wondering about storage and resume of torrents on restart of the client.

Sorry very new to golang and only a basic programmer so hopefully this isn't a bad question.  Basically I was curious if there was a function in this package already to store all the torrents already added (via whatever method they are added) and resume them (either complete downloading or continue seeding) on restart of the client.  I didn't think there would be since this isn't supposed to be a full featured client (which is what I am trying to make). 

However, I did see the storage component and saw that it has a bucked for "completed" so thought I would ask.  If not, I assume the best way for me to implement that would be to modify my local copy of Storage to add a feature that dumps the metainfo into a new bucket and when I open my client just re-add all of the torrents?  As long as the files are there in the correct directory it shouldn't redownload (via my testing with the CMD example).  

Thank you!

**Comment by anacrolix** [comment]
There isn't currently a mechanism that records how torrents were added. I wouldn't modify your storage implementation, instead I would devise a schema that performs your resume actions on top of the Client/Torrent interfaces. I also wouldn't store your schema inside the storage bolt DB unless you had good reason to associate them together.

You may find these links helpful:

* https://github.com/anacrolix/torrent#other-public-projects-using-torrent
* https://github.com/anacrolix/confluence
* https://godoc.org/github.com/anacrolix/torrent#Torrent.VerifyData

Good luck, I look forward to your progress.

**Comment by deranjer** [comment]
Thank you so much for your help!  I did a quick code review and test and neither peerflix nor cloud torrent appeared to have any method in place for resume on restart (cloud torrent says it is planned) so I thought I would ask before I implemented it in my own way.  

I scanned through the storage code and it was a struggle since I'm not familiar with boltdb, but are you just storing the "completed" hash in boltdb?  What else is the storage backend doing?  If nothing else, then it seems like it would make sense for me to store "downloading" hashes in the same database and read those in at start, or is that a bad idea for some reason I'm missing?

I must have missed "confluence" but that does look like it would do some of the features I would need, but I'm planning on the end result to be passing a lot more data back and forth so am trying my own implementation although the javascript integration is proving difficult with it refusing to recognize my generated JSON from the go backend.. still working on that, thanks for your help!

**Comment by anacrolix** [comment]
There's no reason to couple your client wrappers data with the storage backend's. The implementation may change for example. Confluence is nice for integrating with other systems and working with torrent as a service, if there are features it might need to satisfy your requirements that make sense, feel free to submit issues for them.
