### ISSUE TITLE
url-list

### ISSUE THREAD

**Issue by axet** [anacrolix/torrent#197]
Seems like bencode not parsing all torrent correctly, url-list is empty. Here two torrents from archive.org and libreoffice.org seems like bencode does not parse 'url-list' and 'sources'

  * https://archive.org/details/kzz003
  * https://www.libreoffice.org/download/download/

Checking torrent files I can see booth: 'url-list' and 'sources' at the end of torrent. But 'torrent' does not read those values. Booth torrent files works in transmissionbt.com client.

This issue kinda correspond to #116 but also to correct torrent reading.

**Comment by anacrolix** [comment]
I see the LibreOffice torrent has a sources key, I've not seen that before. Are you aware of any spec on this?

The url-list field is marshalled and unmarshalled, but it's not currently used by the torrent client. Are you finding that the value isn't even unmarshalled?

**Comment by axet** [comment]
1) I never heard of 'sources' before, and I can not find any info on web. like it is not enougth,  transmission does not have references in source code to the 'sources'. and complete magic is - transmissionbt does read those values!

  * https://github.com/transmission/transmission/blob/master/libtransmission/quark.h
  * https://github.com/transmission/transmission/blob/master/libtransmission/quark.c

2) in my tests, url-list was empty

**Comment by anacrolix** [comment]
The sources and url-list fields are identical in the LibreOffice torrent, this is probably why it appears to work. Transmission is likely using the url-list. I've added url-list to the output of cmd/torrent-metainfo-pprint, which verifies that both the torrents you provide are being parsed correctly.

**Comment by anacrolix** [comment]
It looks like `TorrentSpec` is missing a field corresponding to `url-list`, which likely explains why you're not seeing the value returned by `Torrent.Metainfo`. I'd like to do away with `TorrentSpec`, and just use raw `MetaInfo` in the future, which will solve this problem.

**Comment by axet** [comment]
no magic :(
