### ISSUE TITLE
ParseMagnetURI: can it retain non standard parameters ?

### ISSUE THREAD

**Issue by mh-cbon** [anacrolix/torrent#199]
Hi anacrolix,

https://github.com/anacrolix/torrent/blob/master/metainfo/magnet.go#L35

is it possible the magnet retains eventual non standard arguments in the query ?

The point is to avoid to have to parse the uri twice to collect those, if any.

**Comment by anacrolix** [comment]
Hm, what's the use case? What unsupported parameters are you having to deal with?
