### ISSUE TITLE
Use semantic versioning and something like gopkg.in to get stable versions of the library ? 

### ISSUE THREAD

**Issue by karuppiah7890** [anacrolix/torrent#206]
I see that locking versions of lib is quite an issue in golang. Usually lib is copied locally - vendoring. But having semantic versions and something like gopkg.in in torrent lib can help people to get it's stable versions while building things using torrent lib and also keep the lib up to date too.

**Comment by anacrolix** [comment]
If you have some specific commits in mind, or need something from me to enable this, let me know.

**Comment by karuppiah7890** [comment]
I don't know golang so much to commit stuff. But to start with, it's looks like it's easy to use gopkg.in . We just need to create tags/branches for the specific versions and then provide a gopkg.in URL and it will redirect to the corresponding branch/tag in GitHub. The gopkg site mentions that the supported URLs are : 

```
gopkg.in/pkg.v3      → github.com/go-pkg/pkg (branch/tag v3, v3.N, or v3.N.M)
gopkg.in/user/pkg.v3 → github.com/user/pkg   (branch/tag v3, v3.N, or v3.N.M)
```

I think we can use the second one, because for the first one, you would have to get a GitHub user account like `go-torrent` and create a repo called `torrent`.

**Comment by karuppiah7890** [comment]
An example repo is [https://github.com/go-yaml/yaml](https://github.com/go-yaml/yaml)

**Comment by karuppiah7890** [comment]
And if a repo has no tag/branches with version numbers, the `master` branch is taken up and considered as v0 , so torrent lib is v0 now : http://gopkg.in/anacrolix/torrent.v0

**Comment by anacrolix** [comment]
Is there any update on this? Have you made or chosen a versioning scheme for this repo that works for you?

**Comment by anacrolix** [comment]
go mod is now supported, corresponding version tags are in use.
