### ISSUE TITLE
help

### ISSUE THREAD

**Issue by imjingoudan** [anacrolix/torrent#21]
how can i add more magnet url for download meta-info,
im try new a global client and add many magnet url
but out of memory pprof tip me utp use many memory

**Comment by anacrolix** [comment]
Try disabling UTP, pass the DisableUTP flag in the Client Config. If you add a lot of torrents without the Info, torrent can consume 80 connections per torrent. Currently this isn't exposed in the config, and it isn't really necessary if you only want the metainfo, usually after 5-10 peers you'll find a kind soul that will send you the metainfo. So try setting socketsPerTorrent down to 5-10 in client.go. Additionally you could try limiting the number of torrents pending metainfo to some number, say 10 or 100, depending on the value of socketsPerConnection and the number of available file descriptors. Let me know how you go, maybe I can expose something to make your use case easier.

**Comment by imjingoudan** [comment]
think you. help me !
I want to create a service It from redis receive infohash and then download the meta info, discard the infohash if more than 30 s

**Comment by anacrolix** [comment]
You can drop the infohash if you haven't received it soon enough by calling Drop on the Torrent handle.

**Comment by imjingoudan** [comment]
can youhelp me 
i need an example

**Comment by anacrolix** [comment]
Do you mean to receive the info hash from a Redis PUBSUB?

Some pseudo-code:
```
while True:
   ih = infohash_from_redis()
   t, new, _ = torrent_client.add_torrent_spec(torrent_spec_from_infohash(ih))
   if new:
      go func:
          select {
              case <-t.GotInfo():
                  do_something_with_info(t.Info())
              case time.After(30*time.Second):
                   t.Drop()
           }
```

Maybe you could extend the timeout if the same infohash arrives before the last attempt gave up.
