### ISSUE TITLE
"undefined reference to `clock_gettime'" build error 

### ISSUE THREAD

**Issue by tzngit** [anacrolix/torrent#210]
when i run `go build main.go`
/tmp/go-build142286407/github.com/anacrolix/go-libutp/_obj/utp_utils.cpp.o: In function `utp_default_get_milliseconds(utp_callback_arguments*)':
utp_utils.cpp:(.text+0xd9): undefined reference to `clock_gettime'
utp_utils.cpp:(.text+0x119): undefined reference to `clock_gettime'
/tmp/go-build142286407/github.com/anacrolix/go-libutp/_obj/utp_utils.cpp.o: In function `utp_default_get_microseconds(utp_callback_arguments*)':
utp_utils.cpp:(.text+0x1a9): undefined reference to `clock_gettime'
utp_utils.cpp:(.text+0x1e9): undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status

main.go(just official example):

    package main

    import (
        "github.com/anacrolix/torrent"
        "log"
    )

    func main() {
        c, _ := torrent.NewClient(nil)
        defer c.close()
        t, _ := c.AddMagnet("magnet:?xt=urn:btih:ZOCMZQIPFFW7OLLMIC5HUB6BPCSDEOQU")
        <-t.GotInfo()
        t.DownloadAll()
        c.WaitAll()
        log.Printf("torrent downloaded")
    }

**Comment by anacrolix** [comment]
What is your OS?
