### ISSUE TITLE
mmap storage doesn't notice missing files

### ISSUE THREAD

**Issue by buaazp** [anacrolix/torrent#212]
I use `cmd/torrent` to re-product the issue:

```
./torrent -seed -mmap -addr=xxxx ubuntu-17.10-desktop-amd64.iso.torrent
[wait download succ]

[rm the file]
rm ubuntu-17.10-desktop-amd64.iso

[start torrent again]
./torrent -seed -mmap -addr=xxxx ubuntu-17.10-desktop-amd64.iso.torrent
```

The download process become 100% immediately. And the file is not correct.

But if I use file storage, this issue dose not occur.

#### Cause

Maybe the `PieceCompletion` `.torrent.bolt.db` is not changed after restart. So completion check is pass and client doesn't download files.

#### Advice

`AddTorrent()` should verify file data and re-download the missing or corrupted pieces.

**Comment by anacrolix** [comment]
I actually changed it to not check and cache the state in the bolt file, because there'd be considerable overhead at startup for some users. I guess the mmap backend could be made more defensive, if files are missing when it does the mapping, it could clear the state at the same time.

**Comment by buaazp** [comment]
Sorry for my poor English. I don't understand your reply clearly.
I know you cached all the completion state in boltdb. But why the `file storage` is ok after restart which also uses boltdb. Only `mmap storage` become 100% immediately.

Is there any way to fix my problem? I need to re-download the file after files missing or corrupted.

Or can you delete the `*Torrent`'s cached completion states in boltdb when `t.Drop`. If I found the file missing or corrupted, I can call `t.Drop` to clean the cached states and re-add the torrent.

**Comment by anacrolix** [comment]
The reason is at https://github.com/anacrolix/torrent/blob/master/storage/file_piece.go#L30. The file piece implementation checks the file lengths, mmap storage does not.

**Comment by buaazp** [comment]
Thank you very much. I got it.

**Comment by anacrolix** [comment]
@buaazp I'm closing this as I don't intend to fix it. Let me know if there's something needed to make it possible to improve on the situation here.
