### ISSUE TITLE
No examples of bootstrapping a torrent from a file on disk.

### ISSUE THREAD

**Issue by james-lawrence** [anacrolix/torrent#218]
I've spent all day trying to figure out how to take a binary file on disk and seed it to other nodes without the use of a tracker.

```
var (
  b []byte
)

info := metainfo.Info{PieceLength: 256 * 1024}

if err = info.BuildFromFilePath(path); err != nil {
  log.Fatalln(err)
}

if b, err = bencode.Marshal(info); err != nil {
  log.Fatalln(err)
}

mi = metainfo.MetaInfo{
  InfoBytes: b,
}
mi.SetDefaults()

tor, err := client.AddTorrent(mi)
if err != nil {
  log.Fatalln(err)
}
client.DHT().Announce(mi.HashInfoBytes(), 0, true)

// try to download at this point from another client
```

it seems like the other nodes block because the source node doesn't think it has the parts....
calling tor.BytesCompleted() returns 0 on the source node.

a working example that demonstrates how to load a file from disk and have it be seeded to other nodes would be a huge help.

based on some of your comments in other issues it seems like the assumption here is that a torrent always bootstraps from a remote endpoint.

**Comment by anacrolix** [comment]
Have you seed `Seed = true` in the Client [`Config`](https://godoc.org/github.com/anacrolix/torrent#Config)?

**Comment by james-lawrence** [comment]
Yup, turns out it was a mismatch between where I was placing the file and where the library expected it.

TBH there isn't a way to easily make a valid torrent instances from an IO source, which would vastly simply alot of code.

**Comment by anacrolix** [comment]
Do you mean the BuildFromFilePath? Creating torrents hasn't really been a focus for me with the repo, I've been using torrents already made. The documentation isn't clear on it, but if you set up PieceLength and Files or Name correctly, you can call Info.GeneratePieces with a callback that provides a ReadCloser to fill the hashes in Pieces. https://godoc.org/github.com/anacrolix/torrent/metainfo#Info.GeneratePieces, which is used by BuildFromFilePath internally. I'm open to better interface suggestions to match your requirements.

There's also github.com/anacrolix/torrent/cmd/torrent-create to create a metainfo externally.

**Comment by anacrolix** [comment]
I'd appreciate PRs for docs/comments to help others who might run into the original issue here you described.

**Comment by anacrolix** [comment]
I've improved some of the documentation around the metainfo.Info methods.

**Comment by james-lawrence** [comment]
Yes, I was referring to BuildFromFilePath.

here are my initial thoughts when dealing with the library the other day.

first I'd remove most of the torrent related methods off the client.
there are just want too many of them. poorly documented, and its unclear which ones should be used and when.

```golang
func (cl *Client) AddMagnet(uri string) (T *Torrent, err error) {}
func (cl *Client) AddTorrentFromFile(filename string) (T *Torrent, err error) {}
func (cl *Client) AddTorrent(mi *metainfo.MetaInfo) (T *Torrent, err error) {}
func (cl *Client) AddTorrentInfoHash(infoHash metainfo.Hash) (t *Torrent, new bool) {}
func (cl *Client) AddTorrentInfoHashWithStorage(infoHash metainfo.Hash, specStorage storage.ClientImpl) (t *Torrent, new bool) {}
func (cl *Client) AddTorrentSpec(spec *TorrentSpec) (t *Torrent, new bool, err error) {}
```

I would likely remove all of them except for two, and I'd add two:
```golang
func (cl *Client) AddTorrent(T *TorrentSpec) (new bool, err error) {}
func (cl *Client) DropTorrent(T *TorrentSpec) error {}
func (cl *Client) MergeTorrent(T *TorrentSpec) (new bool, err error) {}
func (cl *Client) ReadTorrent(T *TorrentSpec) (ret *Reader, err error) {}
```

I'd either no longer expose the Torrent or TorrentSpec
- remove Drop() from Torrent, I believe tis the only method that actually interacts with the client on the Torrent structure. then each torrent can have its own mux instead of sharing one with the client.


I would add the following helper methods that generate torrent specs.
```golang
type TorrentSpecOption func(*TorrentSpec)
// TorrentSpecData provide the source data to the torrent, nil can represent no local data.
type TorrentSpecData(d TorrentImpl) TorrentSpecOption {
  return func(t *TorrentSpec) {
    t.TorrentImpl = d
  }
}

// New create a torrent from the metainfo.Info and any additional options.
func New(mi metainfo.Info, options ...TorrentSpecOption) (*TorrentSpec, error) {}

// NewFromData creates a torrent from the raw data the torrent will represent.
func NewFromData(r io.Reader, options ...TorrentSpecOption) (*TorrentSpec, error) {}

// NewFromFile convience method to create a torrent from a file. see NewFromData for
// more information.
func NewFromFile(path string, options ...TorrentSpecOption) (*TorrentSpec, err error) {
  var (
    d *os.File
  )

  if d, err = os.Open(path); err != nil {
    return nil, err
  }
  defer d.Close()
  return NewFromData(d, options...)
}

// NewFromMetadata creates a torrent from metadata stored in a file based format.
func NewFromMetadata(r io.Reader, options ...TorrentSpecOption) (*TorrentSpec, error) {}

// NewFromMagnet create a torrent from a magnet URL.
func NewFromMagnet(s string, options ...TorrentSpecOption) (*TorrentSpec, error) {}
```

**Comment by anacrolix** [comment]
Let's open another issue for redesign of the API. What's the status of this issue? Do you still think the documentation needs improving?

**Comment by TongxiJi** [comment]
But where is the  example of bootstrapping a torrent from a file on disk  now？

**Comment by elgatito** [comment]
@TongxiJi 
https://godoc.org/github.com/anacrolix/torrent#Client.AddTorrentFromFile ?

**Comment by elgatito** [comment]
@TongxiJi full path to torrent file as an argument.
