### ISSUE TITLE
Ctrl+C wont terminate in ubuntu

### ISSUE THREAD

**Issue by famgez** [anacrolix/torrent#22]
Hello,
I've tried terminating a torrent process by using ctrl+c and it wont kill the process. closing the terminal also results in the torrent process continuing.

**Comment by anacrolix** [comment]
Per the example in the [README](https://github.com/anacrolix/torrent#torrent-1), it's important that you quote your magnet links because of errant ? characters. If you don't, cmd/torrent may be started as a background job, with only partial magnet links to work with.
