### ISSUE TITLE
Specify priority for individual files in a torrent

### ISSUE THREAD

**Issue by deranjer** [anacrolix/torrent#220]
I would like to be able to specify download priorities for individual files in a torrent. Something like this is an option:
High -> Normal -> Do Not Download (cancel)

Everyone, please add your opinions and suggestions for this issue!

**Comment by elgatito** [comment]
In terms of library Priorities I would add another Priority level to make it:
Readahead -> *High* -> Normal -> None

Should be easy enough. bitmap with prioritized pieces?

**Comment by anacrolix** [comment]
Yeah that's how I was going to do it. It'll just slot in alongside the other priority handling code quite easily.

**Comment by elgatito** [comment]
@anacrolix , that can come alongside with enabling/disabling files downloads :)

**Comment by anacrolix** [comment]
See #221 for that.
