### ISSUE TITLE
How to limit uploads/downloads

### ISSUE THREAD

**Issue by akillmer** [anacrolix/torrent#225]
Are there any examples on how to limit uploads and download rates for the torrent client? Ideally setting the limit to a value expressed as bytes per second. I scanned the code and see that uploadLimit is used within connection to reserve time for reads, but I’m not exactly sure how this limits the upload rate. Also for downloadLimit the only reference I could find was it being assigned within client, but not being used anywhere else.

Thanks!

**Comment by elgatito** [comment]
Look at  https://godoc.org/github.com/anacrolix/torrent#Config
It should be downloadLimiter / uploadLimiter.

**Comment by anacrolix** [comment]
Download limiter currently applies to all reads from peers, https://github.com/anacrolix/torrent/blob/master/client.go#L1252. Upload limit applies to uploading chunks to peers only (to maintain responsiveness communicating local state to peers).

**Comment by akillmer** [comment]
@anacrolix thanks for the link, sorry I missed that.

Obviously, I'm not to familiar with using Golang's `rate` package. With `NewLimiter(r Limit, b int)`, I would want `b` to at least be 16 to fit a whole chunk. Would `r` translate to how many bytes are read/written per second?

**Comment by anacrolix** [comment]
Yes that's right. But b should be at least 16<<10, but I'd give it a lot of headroom I think someone else had issues with setting this too tightly. For instance if you wanted 100KB/s, you might set `rate.NewLimiter(100<<10, 256<<10)`, to let it burst up to 256KB after a slow period.

**Comment by elgatito** [comment]
>  I think someone else had issues with setting this too tightly.
It was me, probably. I have a common use-case:
- On new playback started - download without limits N megabytes, then limit (so weak devices don't overuse storage and CPU) download/upload while watch started, when finished - again unlimit download upload.

The problem is that rate.Limiter can't be changed to `rate.Inf` on the fly, need to re-create the limiter, but then `Client` does not support re-assigning the limiter.

**Comment by anacrolix** [comment]
If you need that, open an issue for it.

**Comment by anacrolix** [comment]
Let's discuss on [gitter](https://gitter.im/anacrolix/torrent).
