### ISSUE TITLE
Download speed very slow

### ISSUE THREAD

**Issue by NeoCro44** [anacrolix/torrent#227]
I have been pointed from creator of elementum addon that speed has nothing to do with his addon and that i have to post here.
It seems i cant get speed more then 3000 kbps and that's very rare
i got optic fiber 500 Mbit and torrents i try in utorrent are downloading faster then my hard drive can handle :P 
but when i try same torrent in kodi i get max 2500-3000

am i doing something wrong ?
i haven't limited speed in addon

ty for your time

**Comment by elgatito** [comment]
I believe you are talking about default file storage engine, right? And you have no download limits?

**Comment by NeoCro44** [comment]
I'm sorry but I'm not sure what do u mean by default storage engine
i have elementum and elementum burst
I've chosen on my tv box download folder where to download and that's it

**Comment by elgatito** [comment]
@NeoCro44 , first option in addon settings, asks how to download, to file, to memory. 
Better if you start Kodi and paste your kodi.log somewhere like paste.ubuntu.com

**Comment by NeoCro44** [comment]
huh I'm not sure i know how to post log
i know how to upload log just don't know where to search for it ?

**Comment by elgatito** [comment]
Easy way: http://kodi.wiki/view/Log_file/Easy

**Comment by NeoCro44** [comment]
i found option 
its download to file

**Comment by elgatito** [comment]
@anacrolix , then it's a default storage from the library.

@NeoCro44 would be great if you can upload the log, it will show how library is configured and would be much helpful.

**Comment by NeoCro44** [comment]
give me 3 min

**Comment by NeoCro44** [comment]
https://paste.ubuntu.com/26341967/

**Comment by NeoCro44** [comment]
i have switched storage to memory just for testing purpose 
its back to "download to file"

**Comment by NeoCro44** [comment]
tonight i installed to friend laptop elementum burst and he got 20 Mbit connection
he can get max 300 kbps
it seems like burst is using % of internet speed

**Comment by anacrolix** [comment]
Is this still the case? Is it more related to Kodi than directly to this repo? There are several big performance changes in the last few days that address performance issues found on non-MacOS systems, and with the Bolt piece completion back end.

**Comment by NeoCro44** [comment]
Still same
I switched back to quasar
Geting alot bigget download speed

**Comment by elgatito** [comment]
The main issue, found, while investigating this issue (the bolt backend being slow), is fixed, so other optimizations are not related to this issue.

**Comment by anacrolix** [comment]
Cheers

**Comment by NeoCro44** [comment]
Wll i just tried elementum but still same
I even asked in one fb group (croatian group)
People still having slow download speed
