### ISSUE TITLE
Allow re-configuring of ListenAddr

### ISSUE THREAD

**Issue by elgatito** [anacrolix/torrent#229]
Currently we set ListenAddr once and use it all the time. 
That works until IP has changed. 
And, knowing, people use private networks or DHCP connections - this leads to expected problems.

Adding `Client.SetListenAddr()` would be great and much helpful. (was somehow implemented by @axet in his library)

**Comment by anacrolix** [comment]
I can imagine how changing the port requires support, but I'm not sure how IP can change in a way that the Client needs to know about. You might switch interfaces that you're listening on, but in general wouldn't you be listening on [::] or the equivalent of INADDR_ANY? Do you have some examples?

**Comment by elgatito** [comment]
> Do you have some examples?

The only way we can use proxying is VPN (currently), so people set up it and type in the interface, and i'm resolving the IP and passing it as `ListenAddr: IP:0`. It there any better way to listen on specific interface?

**Comment by anacrolix** [comment]
Not that I can find.

**Comment by anacrolix** [comment]
@elgatito are you still interested in this?

**Comment by elgatito** [comment]
@anacrolix not, at the moment. But I believe it can be helpful for users of the library.

**Comment by anacrolix** [comment]
This should be easier now that you can add arbitrary Listeners to the Client. It would be good to get feedback from users making use of this feature.

**Comment by anacrolix** [comment]
The solution here now would be to remove an old Listener, and add a new one. I believe all the features are in place to allow this.

**Comment by gitpubber** [comment]
> The solution here now would be to remove an old Listener, and add a new one. I believe all the features are in place to allow this.

Can you please tell how to do this?

**Comment by anacrolix** [comment]
Actually there's no way to remove a Listener, so this isn't completely true. If a listener is closed, the accepter on it could remove it, or alternatively, adding could return a handle to remove the same Listener.

Is there still interest in this feature?

**Comment by gitpubber** [comment]
> Actually there's no way to remove a Listener, so this isn't completely true. If a listener is closed, the accepter on it could remove it, or alternatively, adding could return a handle to remove the same Listener.
> 
> Is there still interest in this feature?

it's not necessity for me.
