### ISSUE TITLE
How to bootstrap seeding after creating the torrent file?

### ISSUE THREAD

**Issue by schemacs** [anacrolix/torrent#23]
I have run two track servers(using opentrack, the same as the piratebay), and also know how to download files from the DHT network, but I want to distribute my own files(created locally) for private sharing, how to add (downloaded) files list to `client` or `torrent` to indicate downloading is finished and should only seeding(do the upload part)?
I can see the client will not re-download the files in current directory after the files has been download from the DHT before using torrent files or magnet link.

**Comment by anacrolix** [comment]
If you set the Seed option in the Client Config, the client will check which pieces are already available when the first peer is connected. This is deferred to the data store. The 2 default stores, mmap and file based, will perform the necessary hashing of pieces as required.

So all you need to do is add the torrents to a Client with Seed=true, and ensure the data store will find the existing data.

**Comment by anacrolix** [comment]
The DataDir config option can help here if the files are not in the working directory.

**Comment by schemacs** [comment]
Thanks for your detailed reply, and I have done seeding and download successfully in two files shown here https://gist.github.com/schemacs/d8a47a83fc8fc0d358f3 , but I don't know how to do seeding after download first. Now leecher.go only downloads the file, but not does the seeding even setting Seed to true in config.

**Comment by anacrolix** [comment]
I did some checks, a leecher will definitely seed after it completes a download, I'm adding a test case for this soon. So the next cause for failure to seed, would be not having peers that need the file. If you're running more than one leecher, they'll be sharing the same directory, `filepath.Join(os.TempDir(), "leecher")`. Leechers started after the first one finishes, will hash the existing data and have nothing left to do. Is this the case? Run the new test case when I add it too, and ensure you're using the latest revision of torrent.

**Comment by anacrolix** [comment]
0f606a2d24d68dadd25d9d1f3fed40d9ff73fa9f contains the new test.

**Comment by anacrolix** [comment]
6b27e1473dde1712b829256886129d16e06a9426 prevents the new test from randomly failing. Maybe this was the issue you ran into. Let me know.

**Comment by anacrolix** [comment]
Any news on this?
