### ISSUE TITLE
Add Upnp/NAT support

### ISSUE THREAD

**Issue by elgatito** [anacrolix/torrent#230]
To have a better speed (mostly for seeding speeds) on end-user devices, which are usually behind the routers and firewalls, it would be great to have in-house usage of Upnp/NAT.

Example of implementation:
https://github.com/jackpal/Taipei-Torrent

https://gitlab.com/axet/libtorrent/blob/master/port.go , with use of 
https://github.com/syncthing/syncthing (which is usually advised to use to this stuff).

**Comment by anacrolix** [comment]
I will try the syncthing packages.

**Comment by elgatito** [comment]
> not sure it currently belongs in the torrent package 

I'm fine with any way, since it's just a few dozens of lines and uses external package :)

**Comment by anacrolix** [comment]
I'll assume this is working for anyone that uses it. It's been in a while and there's been no issues.
