### ISSUE TITLE
[Request] Show and using Seeds/Peers info

### ISSUE THREAD

**Issue by burekas7** [anacrolix/torrent#231]
In continues to the discussion here regarding the Elementum addon in this issue: https://github.com/elgatito/plugin.video.elementum/issues/55

My request is to make a separation between Seeds and Peers.
Currently it presents only the Seeds info.

And of course, first it should be supported for Uploading, otherwise there is no meaning for the Peers.

This is very important for the principle of the Torrents using and sharing.

Thanks for your great work.

**Comment by anacrolix** [comment]
I'm not sure I follow. Can you refer to a part of the [torrent API](https://godoc.org/github.com/anacrolix/torrent) where you want to see seeds?

**Comment by elgatito** [comment]
@anacrolix this is about torrent stats and having separate seeds and peers.
