### ISSUE TITLE
Allow changing rate limiter while client is running

### ISSUE THREAD

**Issue by deranjer** [anacrolix/torrent#233]
Allow the user to change the config.UploadRateLimiter and config.DownloadRateLimiter without having to restart the client.

**Comment by anacrolix** [comment]
I'll have to take a PR for this one.

**Comment by thrisp** [comment]
I came here for this. I'm working with on tearing down /axetet/libtorrent for my own use and that package has client.SetUploadRate/SetDownLoadRate functions that trace back to here, but there is nothing here that does that (I assume its using an old version of this package, because there is so much wrong with what it does in many places)

**Comment by anacrolix** [comment]
I don't believe there's anything stopping you from calling https://godoc.org/golang.org/x/time/rate#Limiter.SetLimit on `DownloadRateLimiter` and `UploadRateLimiter` in https://godoc.org/github.com/anacrolix/torrent#ClientConfig.

**Comment by thrisp** [comment]
> I don't believe there's anything stopping you from calling https://godoc.org/golang.org/x/time/rate#Limiter.SetLimit on `DownloadRateLimiter` and `UploadRateLimiter` in https://godoc.org/github.com/anacrolix/torrent#ClientConfig.

I will have to look into that thanks

**Comment by anacrolix** [comment]
@deranjer Can you confirm calling methods on the `rate.Limiter` is sufficient?

**Comment by deranjer** [comment]
Yes, per my tests it did work fairly well, you can see my rather sloppy implementation in my config code: https://github.com/deranjer/goTorrent/blob/5b262e66516f249a8bea937a1b36b3a65332a20b/settings/settings.go#L75

Essentially it boils down to these two lines: 
```
uploadRateLimiter = rate.NewLimiter(rate.Limit(uploadRateLimiterSize), uploadRateLimiterSize)
downloadRateLimiter = rate.NewLimiter(rate.Limit(downloadRateLimiterSize), downloadRateLimiterSize)
```

rate.Limit accepts and INT I believe, or you can do rate.Inf which is the built in unlimited.  This can be passed to the config easily on startup... just can't modify it while running which is what I was hoping to do.

**Comment by deranjer** [comment]
Hmm, just reread your comment.. you are talking about resetting the limit while running using the Setlimit on an existing limiter?  I don't remember if I tried doing that or not...

**Comment by anacrolix** [comment]
Yes I believe you can change the rate while it's running.

**Comment by axet** [comment]
Seems like race condition to me. Rate limited not thread safe.

**Comment by anacrolix** [comment]
It's thread safe: https://github.com/golang/time/blob/master/rate/rate.go#L266.

**Comment by anacrolix** [comment]
Please reopen if this solution doesn't work for you.

**Comment by anacrolix** [comment]
It now also supports changing the burst on the fly, see https://github.com/anacrolix/torrent/commit/a298d295b26bcfd25160d38178ae10abd8e6ed1c.
