### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by greyireland** [anacrolix/torrent#236]
```
# go build main.go
# github.com/anacrolix/mmsg
../../../mmsg/mmsg.go:29: cannot use pr (type PacketReader) as type net.Conn in argument to socket.NewConn:
        PacketReader does not implement net.Conn (missing Close method)
# github.com/anacrolix/sync
../../../sync/sync.go:143: syntax error: unexpected = in type declaration
../../../sync/sync.go:144: syntax error: unexpected = in type declaration
```

**Comment by anacrolix** [comment]
What go version?

**Comment by greyireland** [comment]
go env
GOARCH="amd64"
GOBIN="/Users/xiaodong/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/xiaodong/go"
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/l7/p6b66srj33b29q40qt0drbd00000gn/T/go-build867115954=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

go version go1.8.3 darwin/amd64

**Comment by anacrolix** [comment]
I believe those packages require go1.9's support for type aliases. Can you try with go1.9 or greater?

**Comment by anacrolix** [comment]
I guess it works now. Thanks.
