### ISSUE TITLE
The file storage implementation is vulnerable to filename collisions

### ISSUE THREAD

**Issue by themihai** [anacrolix/torrent#237]
The default storage implementation uses the paths provided by the torrent at the root of the `DataDir` path. So if you download two torrents with the same directory/filenames structure (but different content) you end-up with a mess/. 

I believe it should use the torrent hash as prefix  (e.g. DataDir + torrent hash + torrent/file path ) to prevent such issues as each torrent would have its own `namespace`.

**Comment by elgatito** [comment]
Makes sense, it will also help with situations when one torrent was downloaded, then you open another one with the same file name and get many piece validation fails.

**Comment by anacrolix** [comment]
It's true that collisions can occur, but how often does it happen in practice? The downside with prefixing with the infohash is that users will be confused or annoyed about where their files are going. Can you share a few examples of collisions you've encountered?

**Comment by themihai** [comment]
>> The downside with prefixing with the infohash is that users will be confused or annoyed about where their files are going. 

@anacrolix If that's an issue I believe we could add a flag/option (i.e. `namespaceStorage bool`). This library is supposed to be used programatically after all so it must work correctly in the first place(i.e. bug free, corruption free data) yet offer you enough flexibility to build your product friendly to end users(i.e. make the data available under friendly names).

>> Can you share a few examples of collisions you've encountered?

It doesn't happen very often to download a file with the same name but when it does you surely don't want a destructive behaviour(i.e overwrite old files). 

That being said a flag `namespaceStorage` could provide a non breaking feature to guard against name collision yet allow the clients to keep using the current behaviour(if they wish so).

**Comment by themihai** [comment]
Another option to keep both friendly and collision free namespaces is to add a suffix when a collision occurs (i.e. file.mov,  file-(1).mov, file(2).mov etc) and  maintain an internal index with torrentHash -> real-filename -> suffixed-filename.

**Comment by anacrolix** [comment]
It looks like someone [already implemented this](https://godoc.org/github.com/anacrolix/torrent/storage#NewFileByInfoHash). If it's not already exposed, a flag to use this as the default storage in the sample cmds will solve the other part of this issue.

**Comment by anacrolix** [comment]
Does someone want to do a PR for that?

**Comment by themihai** [comment]
I will send a PR in a few minutes.

**Comment by themihai** [comment]
@anacrolix  I  actually take my word back because i'm not very familiar with the cmd package. As far as I understand someone could simply use NewFileByInfoHash as storage implementation when it creates a new client so there is no need to pollute the Config with another option(as I initially proposed).  This also fixes (partially) #238 (i.e. remove torrent data by hash) though we still need a way to remove the meta data.

**Comment by anacrolix** [comment]
Yeah I meant a PR for adding the flags to the cmd packages. I'm in the process of rewriting `cmd/torrent`, so I'll create an issue just for the flags.

**Comment by anacrolix** [comment]
Actually I won't, I'm buried in stuff. But if you want them added, leave this issue open, otherwise let's close it.

**Comment by anacrolix** [comment]
The original problem is solved. If someone needs this exposed in the sample cmds, they can add it there easily enough.
