### ISSUE TITLE
The iplist is missing a function that adds a new range on the fly.

### ISSUE THREAD

**Issue by elico** [anacrolix/torrent#239]
The iplist is missing a function that adds a new range on the fly.
Usually you would reload from disk but I want to add a range via a webui api.
Any suggestions?

**Comment by anacrolix** [comment]
You can extend one of the implementations to include a method to add them. There's likely some overhead to ensure it remains performant, or you may need to use a tree implementation.

**Comment by elico** [comment]
@anacrolix I was thinking about a radix tree, what do you think?

**Comment by anacrolix** [comment]
Sounds good.

**Comment by anacrolix** [comment]
Any progress @elico ?

**Comment by anacrolix** [comment]
See https://github.com/anacrolix/torrent/blob/4e257ffdcfe2759b6386e41174710b52f901b0d5/iplist/iplist_test.go#L18 and https://www.iblocklist.com/list?list=ydxerpxkpcfqjaybcssw in p2p format.

**Comment by anacrolix** [comment]
@elico any update?

**Comment by elico** [comment]
@anacrolix let me see my read my notes.. | / - \ | / -  .. Found
I wrote this simple parser for testing: https://github.com/elico/ipfilter
I had to re-learn a bit IP math to understand the different options.
I reviewed couple use cases singe this code is for usage in the application level.

I found couple implementations based on trees but non of them made my life easy in any form.
The best solution for a **loaded** system is to use the OS Firewall when possible.

For other systems even the warning:
https://github.com/anacrolix/torrent/blob/4e257ffdcfe2759b6386e41174710b52f901b0d5/iplist/iplist.go#L36
> // Create a new IP list. The given ranges must already sorted by the lower
> // bound IP in each range. Behaviour is undefined for lists of overlapping
> // ranges.

Is not a real issue..
So the simple solution would be to just append another range into the list.
It will help to add some sync\mutex lock to the process.
So the *IPList object needs to have a function: AddRange or AppendRange and support more then one range.
Support for different range formats as a source can be pretty nice.

A full/new list update is another issue and this case should be handled separately.

Talking about Linux.. so iptables+ipset implements almost the same concept ie:
read file, create a temporary IPSET, swap the old IPSET with the temporary.

With RHEL 8 and Debian 10 nftables is your friend!!!
This example tool creates an nft set update file from a text file url:
https://gist.github.com/elico/4bbe404c67f0a91c0cf22763fac88a15

Or another nice one is:
https://github.com/rpthms/nft-blacklist

**Comment by anacrolix** [comment]
I think my point above was that you just need to implement [`iplist.Ranger`](https://pkg.go.dev/github.com/anacrolix/torrent/iplist?tab=doc#Ranger) for the `IPBlocklist` field in the [`ClientConfig`](https://github.com/anacrolix/torrent/blob/v1.11.0/config.go#L25). If you want to introduce locking and do synchronization outside the `Client` that's fine, it will work no problems. If you want to introduce a tree data structure to reduce overhead in inserting ranges, that's a great idea.

Do you want to implement a synchronized, mutatable implementation of the existing Ranger, or create your own, or should I unassign it the issue from you?

**Comment by elico** [comment]
@anacrolix I will need to think about it.
The iplist.Ranger should have one or more functions in it to support this feature.
For now the tree implementation is off the table, notice that we first need a tree to work with.
There are couple of them but anyone of them have a specific insert/remove overhead by itself.

I can try to implement an iplist.Ranger based on the code in the git in the future.

**Comment by anacrolix** [comment]
@elico do you still have any interest to add this feature?

**Comment by elico** [comment]
@anacrolix Not sure.

**Comment by anacrolix** [comment]
I'll close this: there's not much interest, and it's doable with some simple wrappers per above.
