### ISSUE TITLE
Panic while downloading

### ISSUE THREAD

**Issue by hmvs** [anacrolix/torrent#240]
Got panic while downloading. Not sure if it addressed or.no. 
https://paste.ubuntu.com/p/PSxSDdQbdY/
https://paste.ubuntu.com/p/nQQhYpqSkY/

Thank you

**Comment by anacrolix** [comment]
It should be addressed by https://github.com/anacrolix/go-libutp/commit/89a35c2661e99e6d1c14b1096bed2ed0d59a84a0.

**Comment by anacrolix** [comment]
Downstream will integrate the fix.
