### ISSUE TITLE
Ability to remove peers over time.

### ISSUE THREAD

**Issue by james-lawrence** [anacrolix/torrent#242]
occassionally peers disappear and do not return, is there a mechanism to remove them?

**Comment by anacrolix** [comment]
Do you mean from the pending peers?

**Comment by james-lawrence** [comment]
I'm referring to the DHT nodes.

table seems to build up over time with no mechanism to clear out nodes that are dead and not returning.

`func (s *Server) WriteStatus(w io.Writer)` prints the information I'm referring to.

**Comment by anacrolix** [comment]
I think this is specific to https://github.com/anacrolix/dht, should we move it there?

**Comment by james-lawrence** [comment]
ah, possibly yeah lets start there.
