### ISSUE TITLE
no public ip causing bep40PriorityBytes to panic

### ISSUE THREAD

**Issue by AlhasanIQ** [anacrolix/torrent#245]
The panic fail-safe `bep40.go:71` is being called due to a.IP being nil.

Reason: on `client.go:1273`'s `firstNotNil()` returning nil due to both sides being nil.

i.e. `cl.config.PublicIp4` ,  `missinggo.AddrIP(cl.ListenAddr()).To4()` are nil.

Client info:
```
ListenAddr: "[::]:50007"
```

**Comment by anacrolix** [comment]
Thanks, do you want to submit a test case and/or propose best behaviour?

**Comment by muesli** [comment]
This seems to be a dupe of #244?

**Comment by anacrolix** [comment]
It is a duplicate of #244.
