### ISSUE TITLE
Avoid listening TCP6 if not enabled

### ISSUE THREAD

**Issue by elgatito** [anacrolix/torrent#250]
Currently we try to listen TCP6 even if we don't need it, and some systems are not configured to use ipv6, so when we create a torrent client we get this error:

```
&errors.errorString{s:"subsequent listen: listen tcp6 :36141: socket: address family not supported by protocol"}
```

I have tried with `DisableIPv6: true`, but still we listen TCP6:

```
netstat -nlp | grep elementum
tcp        0      0 0.0.0.0:6891            0.0.0.0:*               LISTEN      15971/elementum 
tcp6       0      0 :::65220                :::*                    LISTEN      15971/elementum 
tcp6       0      0 :::6891                 :::*                    LISTEN      15971/elementum 
udp        0      0 0.0.0.0:6891            0.0.0.0:*                           15971/elementum 
udp6       0      0 :::6891                 :::*                                15971/elementum 
```

Probably, we should not listen if DisableIPv6 is enabled?

**Comment by anacrolix** [comment]
Thanks for the report. Is the error returned from `NewClient`?

**Comment by elgatito** [comment]
Yes, result from Listen bind there.

**Comment by anacrolix** [comment]
I want to move away from doing the listening in NewClient, and have the user attach network instances as they desire. I'm not able to reproduce the exact error as I can't work out how to disable IPv6 on any of my systems. I'll make a quick fix in the meanwhile.

**Comment by elgatito** [comment]
@anacrolix confirming IPv6 not binded with `DisableIPv6: true`. Will wait for user feedback with new release being out.

Regarding custom network instances, I like the way there is default implementation and a setting for overriding with own one, but don't much like when own implementation become mandatory :)
