### ISSUE TITLE
file permissions + umask

### ISSUE THREAD

**Issue by porjo** [anacrolix/torrent#257]
Using the default file storage, dirs + files are being created with perm `750 (rwxr-x---)` & `660 (rw-rw----)` respectively. This prevents the umask from modifying the 'other users' permission bit.

It would be better if those perms were `777` & `666`. A umask can then be applied as required. The typical Linux system has a umask of `0022` which would result in dirs with `755 (rwxr-xr-x)` and files with `644 (rw-r--r--)`

**Comment by anacrolix** [comment]
Sounds fine to me, do you want to make a PR?
