### ISSUE TITLE
download/upload chunk number constrait goes to config

### ISSUE THREAD

**Issue by schemacs** [anacrolix/torrent#26]
I know this line is here to prevent some bad peers, but any plan to move this (the magic number `6`) to client's config : https://github.com/anacrolix/torrent/blob/master/client.go#L1431 

	for seeding || c.chunksSent < c.UsefulChunksReceived+6 {

I also want to do some network feedback to the client(or client's torrents), so I get more control of the usage of network bandwidth(not use to much of it), any suggestion on this or download/upload rate-limit?

**Comment by anacrolix** [comment]
I welcome any pull requests, go to town.

I've discussed rate limiting, see https://github.com/anacrolix/torrent/issues/11.

Please consider using https://gitter.im/anacrolix/torrent for more interactive discussion. Cheers

**Comment by anacrolix** [comment]
The upload logic is now much more intelligent. See https://github.com/anacrolix/torrent/blob/f98ff7507e44288a1c37124ccdd2811899646eca/connection.go#L1380-L1454, and https://github.com/anacrolix/torrent/issues/11#issuecomment-550502432
