### ISSUE TITLE
Undetermined panic on loading

### ISSUE THREAD

**Issue by YouROK** [anacrolix/torrent#264]
There is a panic when the torrent is loaded, only on windows systems
On linux systems all ok

> panic: undetermined
> 
> goroutine 568 [running]:
> github.com/anacrolix/torrent.(*multiLess).Final(0xc0448fd53e, 0xb9249c6d)
>         /home/yourok/Space/Projects/Android/TorrServe/TorrServer/src/github.com/anacrolix/torrent/multiless.go:17 +0x5e
> github.com/anacrolix/torrent.worseConn(0xc04520d340, 0xc0432dc580, 0x0)
>         /home/yourok/Space/Projects/Android/TorrServe/TorrServer/src/github.com/anacrolix/torrent/worst_conns.go:14 +0x246
> reflect.Value.call(0x9051c0, 0x9e65d8, 0x13, 0x9b54b7, 0x4, 0xc0448fd920, 0x2, 0x2, 0xc042094cb0, 0x9bac2d, ...)
>         /usr/local/go/src/reflect/value.go:447 +0x970
> reflect.Value.Call(0x9051c0, 0x9e65d8, 0x13, 0xc0448fd920, 0x2, 0x2, 0x196, 0x196, 0x9b2e80)
>         /usr/local/go/src/reflect/value.go:308 +0xab
> github.com/anacrolix/missinggo/slices.(*sorter).Less(0xc0429e9aa0, 0x19, 0x18, 0xc044908001)
>         /home/yourok/Space/Projects/Android/TorrServe/TorrServer/src/github.com/anacrolix/missinggo/slices/sorter.go:15 +0x154
> sort.insertionSort(0xa2ce80, 0xc0429e9aa0, 0x18, 0x20)
>         /usr/local/go/src/sort/sort.go:27 +0xa3
> sort.quickSort(0xa2ce80, 0xc0429e9aa0, 0x18, 0x20, 0x8)
>         /usr/local/go/src/sort/sort.go:209 +0x20e
> sort.quickSort(0xa2ce80, 0xc0429e9aa0, 0xe, 0x20, 0x8)
>         /usr/local/go/src/sort/sort.go:197 +0x12a
> sort.Sort(0xa2ce80, 0xc0429e9aa0)
>         /usr/local/go/src/sort/sort.go:218 +0x80
> github.com/anacrolix/missinggo/slices.Sort(0x8dcbc0, 0xc04544f840, 0x9051c0, 0x9e65d8, 0x1, 0x3d0000)
>         /home/yourok/Space/Projects/Android/TorrServe/TorrServer/src/github.com/anacrolix/missinggo/slices/sort.go:15 +0x132
> github.com/anacrolix/torrent.(*Torrent).writeStatus(0xc042154700, 0xa289e0, 0xc042325b40)
>         /home/yourok/Space/Projects/Android/TorrServe/TorrServer/src/github.com/anacrolix/torrent/torrent.go:617 +0x5b8
> github.com/anacrolix/torrent.(*Client).WriteStatus(0xc0420c4dc0, 0xa29840, 0xc042094008)
>         /home/yourok/Space/Projects/Android/TorrServe/TorrServer/src/github.com/anacrolix/torrent/client.go:150 +0x6b9
> main.test.func2(0xc042154700, 0xc0420c4dc0)
>         /home/yourok/Space/Projects/Android/TorrServe/TorrServer/src/main/test.go:55 +0x68
> created by main.test
>         /home/yourok/Space/Projects/Android/TorrServe/TorrServer/src/main/test.go:48 +0x21c

Test example:
```
package main

import (
	"log"
	"os"
	"sync"
	"time"

	"github.com/anacrolix/torrent"
)

func main() {
	config := torrent.NewDefaultClientConfig()

	config.EstablishedConnsPerTorrent = 100
	config.HalfOpenConnsPerTorrent = 65
	config.DisableIPv6 = true
	config.NoDHT = true

	client, err := torrent.NewClient(config)
	if err != nil {
		log.Fatal(err)
	}

	//Ubuntu
	t, err := client.AddMagnet("magnet:?xt=urn:btih:e4be9e4db876e3e3179778b03e906297be5c8dbe&dn=ubuntu-18.04-desktop-amd64.iso&tr=http%3a%2f%2ftorrent.ubuntu.com%3a6969%2fannounce&tr=http%3a%2f%2fipv6.torrent.ubuntu.com%3a6969%2fannounce")
	if err != nil {
		log.Fatal(err)
	}
	<-t.GotInfo()
	file := t.Files()[0]

	reader := file.NewReader()
	var wa sync.WaitGroup
	wa.Add(1)

	go func() {
		buf := make([]byte, t.Info().PieceLength)
		for {
			_, err := reader.Read(buf)
			if err != nil {
				break
			}
		}
		wa.Done()
	}()

	go func() {
		cl := t.Closed()
		for {
			select {
			case <-cl:
				return
			default:
				client.WriteStatus(os.Stdout)
			}
			time.Sleep(time.Second)
		}
	}()
	wa.Wait()
}
```
It was observed that panic occurs after a heavy download after a while
compile:
GOOS=windows GOARCH=amd64 go build -o test.exe main

**Comment by anacrolix** [comment]
What version of Go are you using?

**Comment by anacrolix** [comment]
Also what version of Windows?

**Comment by YouROK** [comment]
go version go1.10.3
Windows 10 Pro X64

**Comment by anacrolix** [comment]
Just checking my assumption is correct, do you want to run this code from [here](https://github.com/golang/go/issues/11313#issue-89847838)?:
```
// Play with finding minimal time difference via subsequent calls to time.Now().
package main

import (
    "fmt"
    "time"
)

func timediff() time.Duration {
    t0 := time.Now()
    for {
        t := time.Now()
        if t != t0 {
            return t.Sub(t0)
        }
    }
}

func main() {
    var ds []time.Duration
    for i := 0; i < 10; i++ {
        ds = append(ds, timediff())
    }
    fmt.Printf("%v\n", ds)
}
```

**Comment by anacrolix** [comment]
Courtesy of @Nemiroff for future reference:
Code from Issue on Windows 7 Pro x64 [1.0001ms 0s 1.0001ms 1ms 1.0001ms 1ms 1.0001ms 1.0001ms 1ms 1.0001ms]
From Windows 10 Pro x64 [997.3µs 995.5µs 997.8µs 996.7µs 996.7µs 997.9µs 996.7µs 998.4µs 997.8µs 996.7µs]
