### ISSUE TITLE
Support custom DHT servers

### ISSUE THREAD

**Issue by toby** [anacrolix/torrent#266]
Currently the torrent library instantiates an `anacrolix/dht` DHT server and assigns it to a Client during new client construction. It would be nice if there was a DHT server interface that specified client needed functionality and the ability to specify implementers of that interface as DHT servers for the client.

**Comment by BruceWang666** [comment]
How to  hook OnQuery in dht.ServerConfig when I init an torrent client ?

**Comment by anacrolix** [comment]
This seems particularly relevant now. @toby are you or is anyone you know running `torrent` with an alternative DHT implementation? What do you think such an interface might look like?

For posterity, @BruceWang666's query resulted in #319.

**Comment by toby** [comment]
@anacrolix I'm not but I did look into it. One of the difficulties I had was that the krpc implementation is also part of the `anacrolix/dht` and its pretty interwoven into `anacrolix/torrent`.

I think the ideal implementation would split all three areas of responsibility (torrent, dht, krpc) into separate libs that communicate through interfaces. I _did_ start working on this and have a very broken, rough work in progress plus some notes that you can look at here: https://github.com/anacrolix/torrent/compare/master...toby:custom-dht

You can see there's a lot of surgery that will have to take place but I think it would be very powerful to decouple the libraries. There were also some changes I made to the dht library to support this but I appear to have lost them :/

**Comment by anacrolix** [comment]
Thanks @toby that helps a lot.

**Comment by anacrolix** [comment]
@toby did you have any more progress on this?

**Comment by toby** [comment]
@anacrolix sadly I haven't worked on it since then.

**Comment by anacrolix** [comment]
@toby could you take another look? I've broken out this abstraction on `master`. Cheers

**Comment by toby** [comment]
Oh this is great! I'm super heads down on some projects right now but will try to get to this soon.

**Comment by anacrolix** [comment]
Ok I'll close this as I believe it's now fixed. Feel free to continue discussion or open new issues if something's missing.
