### ISSUE TITLE
Panic in golang 1.5

### ISSUE THREAD

**Issue by ccampbell** [anacrolix/torrent#27]
I am still debugging, but after updating to go 1.5 I am getting this panic

```
2015/08/22 13:08:11 http: panic serving 127.0.0.1:51786: sync.Cond is copied
goroutine 50 [running]:
net/http.(*conn).serve.func1(0xc8201a6000, 0x4fa5e80, 0xc820026090)
	/usr/local/Cellar/go/1.5/libexec/src/net/http/server.go:1287 +0xb5
sync.(*copyChecker).check(0x4805440)
	/usr/local/Cellar/go/1.5/libexec/src/sync/cond.go:116 +0xa8
sync.(*Cond).signalImpl(0x4805410, 0x1)
	/usr/local/Cellar/go/1.5/libexec/src/sync/cond.go:83 +0x35
sync.(*Cond).Broadcast(0x4805410)
	/usr/local/Cellar/go/1.5/libexec/src/sync/cond.go:79 +0x26
github.com/anacrolix/torrent.(*Client).setMetaData(0x4805300, 0xc8200a68c0, 0xc820174a20, 0xc820216000, 0xeafb, 0xeafb, 0x0, 0x0)
	/Users/craig/go/src/github.com/anacrolix/torrent/client.go:1927 +0x28c
github.com/anacrolix/torrent.(*Client).AddTorrentSpec(0x4805300, 0xc820085270, 0x4805300, 0x0, 0x1, 0x0, 0x0)
	/Users/craig/go/src/github.com/anacrolix/torrent/client.go:2183 +0xa23
```

I did notice this in the 1.5 release notes

> The WaitGroup implementation in package sync now diagnoses code that races a call to Add against a return from Wait. If it detects this condition, the implementation panics.

**Comment by ccampbell** [comment]
```go
cl.mu.Lock()
cl.event.Broadcast()
cl.mu.Unlock()
```

Seems to fix the panic, but the sync.Cond.Broadcast() call just hangs after that

**Comment by anacrolix** [comment]
I believe for this to occur, *Client would have to be dereferenced. I've had a good look and don't see this occurring anywhere in the torrent code. Are you doing this in your calling code somewhere? You should be certain that you're only using *Client, and not Client. I've added a test that should trigger the panic if it occurs within the torrent code but it doesn't fail. I'll add that shortly, perhaps you could run it on your own system.

Thanks for the report.

**Comment by anacrolix** [comment]
The test is added, let me know how it goes

**Comment by ccampbell** [comment]
Thank you!  That's exactly what the issue was :relieved:

I was using

```diff
-var client torrent.Client
+var client *torrent.Client
```

**Comment by anacrolix** [comment]
No problem, you wouldn't believe how many times that's tripped me up.
