### ISSUE TITLE
torrent client can't assign dht.ServerConfig

### ISSUE THREAD

**Issue by BruceWang666** [anacrolix/torrent#274]
https://github.com/anacrolix/torrent/blob/master/client.go
in line 274
can i change the dht.ServerConfig to hook OnQuery ?

**Comment by anacrolix** [comment]
I don't believe the ability to add custom DHT servers is yet implemented. It is shortlisted as a new feature. See also #266 .

**Comment by BruceWang666** [comment]
tks
