### ISSUE TITLE
Can I get torrent's metadata via infohash

### ISSUE THREAD

**Issue by BruceWang666** [anacrolix/torrent#275]
Can there be a function to further obtain and return the metadata of the torrent through the infohash after passing in the infohash.Such as file name, file size, etc.

**Comment by anacrolix** [comment]
That would be https://godoc.org/github.com/anacrolix/torrent#Torrent.Info.

**Comment by anacrolix** [comment]
You can also use https://godoc.org/github.com/anacrolix/torrent#Torrent.Files for the example properties you gave.

**Comment by BruceWang666** [comment]
How can I get the torrent's metadata only through infohash without the seed file?

**Comment by anacrolix** [comment]
Adding a torrent by infohash will automatically attempt to acquire the metadata. You will have to wait for that process to complete before you can use stuff like Torrent.{Info,Files} etc. See Torrent.GotInfo.

**Comment by toby** [comment]
@BruceWang666 here's a full example: https://github.com/anacrolix/torrent/blob/master/cmd/magnet-metainfo/main.go
