### ISSUE TITLE
pt torrent  tracker ：Banned Client, Please goto pt.btschool.net/faq.php#id29

### ISSUE THREAD

**Issue by f4nff** [anacrolix/torrent#277]
go toreent trakcer：
```
/announce.php?GET /announce.php?compact=1&downloaded=0&info_hash=%FCTq%19%A8l%FB%9D%EE83%A6w%87R%25%A3L%DA4&left=2384765666&passkey=85e53655ec85b095f51a02332ecade16&peer_id=-GT0001-q%90%2F%EB%E6%26%A4%97%1B%FF%F4%1F&port=41882&supportcrypto=1&uploaded=0 HTTP/1.1
 Host: pt.btschool.net
 User-Agent: Azureus 5.7.6.0;Windows 10;Java 1.8.0_161
 Accept-Encoding: gzip
```
Vuze tracker：

```
GET /announce.php?passkey=85e53655ec85b095f51a02332ecade16&info_hash=%FCTq%19%A8l%FB%9D%EE83%A6w%87R%25%A3L%DA4&peer_id=-AZ5760-gbOrWBQyea50&supportcrypto=1&port=49121&azudp=49121&uploaded=0&downloaded=0&left=2384765666&corrupt=0&event=started&numwant=100&no_peer_id=1&compact=1&key=2RFv2BEY&azver=3 HTTP/1.1
User-Agent: Azureus 5.7.6.0;Windows 10;Java 1.8.0_161
Connection: close
Accept-Encoding: gzip
Host: pt.btschool.net
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
```

I have modified the tracker http agent field。
But the pt tracker is still a client that is forbidden to use.
I caught the packet and found that the get field is different.

**Comment by f4nff** [comment]
The same parameters are: 
```
passkey
Info_hash
Peer_id
Supportcrypto
Port
Uploaded
Downloaded
Left
Compact
```


Azureus Extra fields：

```
azudp
corrupt
event
numwant
no_peer_id
key
azver
```

**Comment by f4nff** [comment]
I have already solved it.

config.go

```
		ExtendedHandshakeClientVersion: "Vuze 5.7.6.0",
		Bep20:                          "-AZ5760-",

```


`var DefaultHTTPUserAgent = "Azureus 5.7.6.0;Windows 10;Java 1.8.0_161"`

**Comment by elgatito** [comment]
@f4nff  there are trackers which have "whitelist" of torrent clients (not the blacklist of banned clients). But I'm not sure if that is good to pretend something else by default.

**Comment by anacrolix** [comment]
It's very poor practice to have whitelists. Those trackers should do their best to respond appropriately, and send error messages if they cannot, otherwise it just becomes a guessing game of which client name to masquerade as. Here's a simple example: https://webaim.org/blog/user-agent-string-history/

**Comment by anacrolix** [comment]
If this issue was just a case of a tracker having a whitelist, I think it's appropriate to close this.
