### ISSUE TITLE
Suggest，Multiple requests can be initiated with a single peer...

### ISSUE THREAD

**Issue by f4nff** [anacrolix/torrent#278]
Normally, when the peer to peer has only one tcp connection, it will be limited by the isp quotient. If multiple tcp connections are available, you can get more speed. You want to support multiple peer tcp connection requests.

**Comment by f4nff** [comment]
[idm ](http://www.internetdownloadmanager.com/)
It is very efficient to use multiple tcp concurrently to get more bandwidth.
In a single environment, in some environments, the speed is very slow, you must use multiple tcp concurrent to get more speed.

**Comment by anacrolix** [comment]
This works in some situations, however for this implementation I don't think it's worth the extra complexity. Other clients likely don't support or want this kind of thing either. Thanks for the suggestion.
