### ISSUE TITLE
support dns over https?

### ISSUE THREAD

**Issue by f4nff** [anacrolix/torrent#279]
[cloudflared ](https://github.com/cloudflare/cloudflared)

`cloudflared proxy-dns --port 53 --address 0.0.0.0 --upstream https://cloudflare-dns.com/dns-query`

I hope to integrate into the torrent and become the default setting.
Because some areas can pollute dns, dns over https can be used to effectively encrypt dns request information.

**Comment by anacrolix** [comment]
Can you provide a link to instructions on how to integrate this as an alternate DNS resolver in Go?

**Comment by f4nff** [comment]
I don't know this, I only know that cloudflared can use dns over https, you are a god, I believe this is hard to beat you.

**Comment by elgatito** [comment]
@anacrolix  I believe this is more about DNS over HTTPS, which is available not only with cloudflare's DNS services.

Probably something like this: https://github.com/m13253/dns-over-https and https://github.com/m13253/dns-over-https/blob/master/doh-client/client.go

More info, related to miekg/dns - https://github.com/coredns/coredns/issues/1650
Another one https://github.com/albertito/dnss

**Comment by anacrolix** [comment]
Thanks @elgatito . @f4nff are you or is anyone else still interested in this?

**Comment by elgatito** [comment]
@anacrolix me not. I have added dns client internally - https://github.com/elgatito/elementum/blob/master/proxy/dns.go#L78
