### ISSUE TITLE
Ipv4+ ipv6 dual stack access tracker improvements

### ISSUE THREAD

**Issue by f4nff** [anacrolix/torrent#280]
If the resolved domain name exists in ipv4+ipv6,
such as:
`Https://t.quic.ws:443/announce`

```
root@c:~# nslookup  t.quic.ws
Server:         154.85.36.144
Address:        154.85.36.144#53

Non-authoritative answer:
Name:   t.quic.ws
Address: 104.24.103.248
Name:   t.quic.ws
Address: 104.24.102.248
Name:   t.quic.ws
Address: 2606:4700:30::6818:67f8
Name:   t.quic.ws
Address: 2606:4700:30::6818:66f8
```

If ipv6 is available, the default is only to ipv6 request, then the tracker can't get ipv4 peer.

The optimized process I think should be available when ipv6 is available, and the ipv4+ipv6 dual stack is requested at the same time.

The optimized process I think should be available when ipv6 is available, and the ipv4+ipv6 dual stack is requested at the same time.

After the file download is complete, request again so that the pt tracker can be used for data upload.

**Comment by f4nff** [comment]
![image](https://user-images.githubusercontent.com/19538878/47133575-df403d00-d2db-11e8-98d2-1c69c88d9b80.png)

The connection requested a tracker only when it was just started.

After I grabbed the package analysis, after the file download was completed, the process ended directly. I didn't connect the tracker report upload again, download the information, so the pt tracker could not count the download....

**Comment by anacrolix** [comment]
Can you reference where it's not possible to get peers on the other IP stack? According to BEP 7, it's allowed to announce to one or both stacks, and possible to receive addresses for both stacks in a single response. It's not specified whether announcing to both is preferred, or when peers for both stacks will not be returned.

**Comment by anacrolix** [comment]
@f4nff do you have any more information?

**Comment by anacrolix** [comment]
I don't believe this is correct. My understanding is the HTTP announce will request both ipv4 and ipv6 at present.
