### ISSUE TITLE
add ed2k

### ISSUE THREAD

**Issue by f4nff** [anacrolix/torrent#283]
please add ed2k link

**Comment by anacrolix** [comment]
Can you elaborate?

**Comment by f4nff** [comment]
Download resources like [eMule](https://www.emule-project.net/home/perl/general.cgi?l=42).
such as：
`ed2k://|file|en_win_xp_pro_x64_vl.iso|614166528|69C268B5F717E29EB81BA5E506FF15EA|/`

**Comment by anacrolix** [comment]
I'm not aware of any form of ed2k link that can be directly supported by a BitTorrent client. There does appear to be clients out there that include ed2k support, but I don't have any intention of bolting that onto this implementation, unless perhaps there's a Go implementation and some way to easily tap into the network. It doesn't appear that you can generate ed2k links from BitTorrent infos or vice versa without having all the data available to you (someone would have to publish it for you to benefit from it).

**Comment by anacrolix** [comment]
Please reopen if more information on how this is possible comes to light.
