### ISSUE TITLE
peer to peer  add tls1.3

### ISSUE THREAD

**Issue by f4nff** [anacrolix/torrent#284]
peer to peer  add tls1.3

**Comment by anacrolix** [comment]
Could you elaborate? Is there a spec for TLS use in BitTorrent?

**Comment by f4nff** [comment]
For now, this is just one of my ideas, and there are no clear standards.
Client-to-tracker can be transmitted using https encryption.
Peer-to-peer should also support tls, which can be used as an extension protocol.

**Comment by anacrolix** [comment]
If there's a spec for TLS support for the wire protocol, that can be implemented. The existing BitTorrent protocol obfuscation is fully supported already, and has its own peculiarities that are appropriate for the BitTorrent protocol. See https://godoc.org/github.com/anacrolix/torrent#EncryptionPolicy and https://godoc.org/github.com/anacrolix/torrent/mse.
