### ISSUE TITLE
Request to add segments and concurrently download http resources

### ISSUE THREAD

**Issue by f4nff** [anacrolix/torrent#285]
Just like [idm](http://www.internetdownloadmanager.com/), it's great to download http resources in multiple concurrent chunks....

**Comment by f4nff** [comment]
Custom http header, segmentation and more concurrent http downloads, is very good.

**Comment by anacrolix** [comment]
This is dependent on the implementation of #116, I think suggestions about the kind of features included belong there, cheers.
