### ISSUE TITLE
Remove C dependencies

### ISSUE THREAD

**Issue by jpillora** [anacrolix/torrent#29]
Hey matt,

Cross compiling fails due to C dependencies. Currently attempting to compile `github.com/anacrolix/torrent/cmd/torrent` on http://gox.jpillora.com/ yields:

```
../../../../spacemonkeygo/monotime/mono_fallback.go:21:2: no buildable Go source files in /app/.heroku/go/src/github.com/spacemonkeygo/monotime/_cgo
```

If it's not practical to remove the C dependencies, feel free to close this.

This is for https://github.com/jpillora/cloud-torrent where I'd like to have auto-releases working for all platforms (currently only native - linux amd64 - works)

**Comment by anacrolix** [comment]
I ran into this too when I tried to use torrent on ARM. I'll see what I can
do, suggestions welcome. I don't recall why I used monotime in the first
place but it was likely something misled.

**Comment by jpillora** [comment]
It seems go has monotonic time, though it's private

http://golang.org/pkg/runtime/?m=all#nanotime

**Comment by anacrolix** [comment]
Do you want to try passing CGO_ENABLED=1, per
https://golang.org/doc/go1.1#crosscompile in gox?

**Comment by anacrolix** [comment]
You might like godepgraph, which I used to track down what was depending on
this:

godepgraph -s -horizontal github.com/anacrolix/torrent/cmd/torrent | dot
-Tpng -o dep.png

I've tested a change in github.com/anacrolix/utp that uses time.Now instead
of monotime.Monotonic, and it looks good, I'll push it now.

**Comment by anacrolix** [comment]
Fixes are pushed to github.com/anacrolix/utp

**Comment by jpillora** [comment]
with CGO, i get a different error:

**Comment by jpillora** [comment]
```
clang: error: argument unused during compilation: '-mno-thumb'
# runtime/cgo
```

**Comment by anacrolix** [comment]
http://1d4chan.org/images/5/5c/Fail2.jpg

I guess ditching monotime is the path of least resistance

**Comment by jpillora** [comment]
Indeed :) looks like its working now http://gox.jpillora.com/ thanks Matt
