### ISSUE TITLE
DisableIPv6 is not properly handled

### ISSUE THREAD

**Issue by elgatito** [anacrolix/torrent#290]
Hello,

With the change commit at https://github.com/anacrolix/torrent/commit/1a4950ad4a9fdad8b9cc3253d9dd8a52b410eda6#diff-d0b7f86cea13f90d3cc0cc2338da8d5f we now try to `allPeerNetworks`, which is `var allPeerNetworks = []string{"tcp4", "tcp6", "udp4", "udp6"}`.

And the problem is that on systems, without IPv6 support we get errors, even when we set `DisableIPv6: true`.

In my understanding DisableIPv6 should disable listening of v6 (tcp/udp) and should not send any v6 requests. 

Also, DHT should not use IPv6 if it's not possible. Not sure if it does respect that now.

**Comment by anacrolix** [comment]
The behaviour is intentional. The goal is to reserve ports on all relevant protocols and networks. Disabling protocols/networks will disable accepting and dialing out on those disabled protocol/networks.

I think the easiest solution will be to ignore errors when listening due to unsupported networks or protocols, as the original intention will be preserved. I'll commit a change that improves the error type for this error. I'm not sure if it's easier to match this error by string or by unpacking the type yet.

**Comment by elgatito** [comment]
Latest version of Elementum is crashing without any panic in the log, on systems without IPv6. 
I wonder if that could be a C error, that kill entire application. Not sure how to test it. On same systems previous version (release almost 3 monthes ago) is starting fine.

**Comment by elgatito** [comment]
With the most newest version the problem persists - https://pastebin.com/sM9bCMYw 
Without DHT and with Disabled IPv6 peogram crashes when system physically not supporting IPv6.

**Comment by elgatito** [comment]
So we are not getting error from the `NewClient()`, it's killed on the half way.

**Comment by anacrolix** [comment]
This error looks like it should cause NewClient to fail: `19:39:05.013 T:139689921431296  NOTICE: [plugin.video.elementum] [31mERRO  bittorrent   ▶ configure        [0mError creating bit client: subsequent listen: listen tcp6 :42609: socket: address family not supported by protocol`. I would switch back to `listenAll(cl.enabledPeerNetworks(), ...)` per your suggestion but it's not quite that simple (need to listen on UDP if either of UTP or DHT are enabled for example). I will have to create a network type as the handling is getting complex, and may get more complex with the addition of WebRTC.

**Comment by elgatito** [comment]
I'm not sure how system handles when IPv6 is disabled in the kernel and we try to listen. One thing is that adapter is not enabled with ipv6, another thing when system totally disabled ipv6.

Hard to reproduce it. Maybe need any virtual machine build without ipv6. Not sure.

Why do we have to listen ipv6 if we not going to receive or send any ipv6 requests?

**Comment by anacrolix** [comment]
Per your recommendation, I've decided not to listen to IPv6 networks if it's disabled. Peer clients may misinterpret the listener being present (even though it's not used when disabled), and deciding when to ignore the listen error for disabled networks is complex.

**Comment by elgatito** [comment]
Thanks, I will try the new version.

**Comment by elgatito** [comment]
Got a feedback from user, that your fixes helped, now application is not crashing.
Thanks!
