### ISSUE TITLE
Torrents stuck in getting info

### ISSUE THREAD

**Issue by svera** [anacrolix/torrent#291]
I'm trying to develop a little torrent client, but I cannot pass from `<-gotInfo()`, as I no receive no information from any server. Using the library CLI I cannot download it either. On the other hand, I've tried to download the same torrent file with qBittorrent with no problem, so the file has seeds and peers.
I'm trying to troubleshoot what is the problem, but with no luck. Could anyone provide me hints about where to start, maybe open ports, etc? I'm using Mac OS X 10.14 Mojave.

**Comment by svera** [comment]
Answering myself, this is definitely a problem with Mac OS, as I've tried the same code in Ubuntu and it's working perfectly.

**Comment by anacrolix** [comment]
I've just tried with Mojave on a mobile internet connection. If you have blocked ports it will be much harder to get peers for less popular torrents. I tested with `magnet:?xt=urn:btih:KRWPCX3SJUM4IMM4YF5RPHL6ANPYTQPU`.
