### ISSUE TITLE
ConnTrack issues

### ISSUE THREAD

**Issue by elgatito** [anacrolix/torrent#295]
Creating this issue to report of a different issues, related to ConnTrack addition.

I have a report of waiting for 1 minute till `GotInfo` returns

```
10:17:40.681 T:18364  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ NewTorrent       Waiting for information fetched for torrent: "7231f5b659254ed03681ee3ae235424a74633e62"
10:17:40.687 T:18364  NOTICE: [plugin.video.elementum] 2018/11/27 10:17:40 error looking up "router.silotis.us:6881": lookup router.silotis.us: no such host
10:18:10.645 T:18364  NOTICE: [plugin.video.elementum] 2018-11-27 10:18:10 client.go:305: dht server on 0.0.0.0:3600: dht bootstrap: {855 142}
10:18:54.048 T:18364  NOTICE: [plugin.video.elementum] DEBU  memory       ▶ Start            StorageStart

```

As I have written on the gitter channel, it would be great if we prioritize different sources of connection requests, like: Resolve (maybe other places, that need immediate requests)  -> anacrolix/torrent -> anacrolix/dht -> other

**Comment by elgatito** [comment]
Can we print conntrack status in the client status? 
It's not public, so not printable from the outside.

`Max: 200 ` behaves better than 1000?

**Comment by anacrolix** [comment]
1000 is the default for public testing, definitely something smaller should be required for bad routers. Somewhere between 100 and 500 in my experience. 200 is a good starting place. It's probably worth exposing that value to your users, as it's completely dependent on their internet service capabilities.

**Comment by elgatito** [comment]
@anacrolix trying latest fixes.

After few minutes of playback I get:
```
num entries: 500

waiters:
num   reason
4267  "send dht query"
```

After another minute:
```
num entries: 500

waiters:
num   reason
4669  "send dht query"
```


And so on, so it raises and raises.

**Comment by elgatito** [comment]
Trying with custom timeout (10s), looks better. 

Do we really need so big timeout?

**Comment by anacrolix** [comment]
It's really hard to say, routers vary so much, and when the limits are hit, the results are usually pretty severe. You're probably best to expose very reasonable defaults (say 1000 max), and let users fiddle it to suit their conditions (and report what works for them so you can adjust your defaults perhaps). nf_conntrack defaults to 30s for UDP, and I think TCP has a default of around 180s. If you can find any more information I'm happy to adjust those defaults in the conntrack module itself too. Also I can find areas to relieve some of the pressure, for instance some errors when writing/dialing indicate that the router would not have even registered the entry. You can see those in recent commits. Cheers

**Comment by elgatito** [comment]
I have released new version with the latest changes. 
Have set `Max` to be `ConnectionsPerTorrent * 15` and a manual setting ability (if anyone wants to change it). And `Timeout: 10 * time.Second`. 

Will test with these values. Looks fine, speed gained pretty quickly and it looks more adequate.

**Comment by anacrolix** [comment]
I think you're better off with a fixed MaxEntries, say 600, than increasing the timeout, but let's see. Include https://github.com/anacrolix/dht/commit/b09db78595aaba14cd992537fbe992a4c5e0a141 when you can too.

**Comment by elgatito** [comment]
I see there is a support for handling keep-alive requests.

Are we sending keepalives for active connections? 
I see this code:
```
keepAliveTimer = time.AfterFunc(keepAliveTimeout, func() {
		cn.mu().Lock()
		defer cn.mu().Unlock()
		if time.Since(lastWrite) >= keepAliveTimeout {
			cn.tickleWriter()
		}
		keepAliveTimer.Reset(keepAliveTimeout)
	})
```

**Comment by elgatito** [comment]
> I think you're better off with a fixed MaxEntries, say 600, than increasing the timeout, but let's see. Include anacrolix/dht@b09db78 when you can too.

We default we have 50 per torrent, so it would be `MaxEntries: 750` in ConnTracker.
