### ISSUE TITLE
[metainfo] resulting filenames are invalid utf8 if containing chinese/japanese characters 

### ISSUE THREAD

**Issue by btkador** [anacrolix/torrent#298]
while runing a few hundred test torrents thru my torrent parser using your metadata decorder I ran into a problem with the following torrent. All the filenames and path names I get are broken utf8. If I open the same torrent with ie uTorrent it all looks right.

http://itorrents.org/torrent/6AD28246A348EEBBBB6B070ED08EE75F350E9B62.torrent

If I run 
```
	for _, file := range info.UpvertedFiles() {
		filename := filepath.Join(append([]string{info.Name}, file.Path...)...)

		if len(file.Path) > 0 {
			fmt.Printf("%t %s %q", utf8.Valid([]byte(file.Path[0])),file.Path[0],file.Path[0],)
		}
        }
```

I get only bad utf8 crap like

```
false 1024������^ t66y.com.jpg "1024\xb2\xdd\xc1\xf1\xc9\xe7\x85^ t66y.com.jpg"
false AV Day-�C��վ.url "AV Day-\xbeC\xba\xcfվ.url"
false AVDVD ���˹��.url "AVDVD \xb3\xc9\xc8˹\xe2\xb5\xfa.url"
false AV��Ӱֱ��,�Ը�ģ��,��Ůͼ��.url "AV\xb5\xe7Ӱֱ\xb2\xa5,\xd0Ը\xd0ģ\xcc\xd8,\xc3\xc0Ůͼ\xbf\xe2.url"
false UU����AY456.COM.gif "UU\xc2\xe3\xc1\xc4AY456.COM.gif"
false mmbo.me - �����������������AV����ɫ���Ӱ���غ�������߹ۿ���վ.url "mmbo.me - \xb9\xe3\xb4\xf3\xd2\xf9\xc3\xf1\xd7\uec2e\xb5\xc4\xd7\xee\xbf\xec\xd7\xee\xd0\xc2AV\xb3\xc9\xc8\xcbɫ\xc7\xe9\xb5\xe7Ӱ\xcf\xc2\xd4غ\xcd\xc3\xe2\xb7\xd1\xd4\xda\xcf߹ۿ\xb4\xcd\xf8վ.url"
false mmbo.me_���³��˸�����L���]��Ƭ�������.gif "mmbo.me_\xd7\xee\xd0³\xc9\xc8˸\xdf\xc7\xe5\xb5\xea\xe9L\xcd\xc6\xcb]\x8f\x8aƬ\xcc\xec\xcc\xec\xb8\xfc\xd0\xc2.gif"
true mo888.net~Free Adult Movie, Fastest & Newest Porn Movie Site.jpg "mo888.net~Free Adult Movie, Fastest & Newest Porn Movie Site.jpg"
```

Is that a bug or a mistake from my side?

thanks

**Comment by anacrolix** [comment]
I believe the torrent contains invalid unicode. At least it does not appear to be utf8, which is expected.

**Comment by anacrolix** [comment]
Perhaps if you identify the correct encoding (if any, it's probably utf16 or something silly), you might be able to convert it. I'm not aware of non-utf8 being a requirement in any torrent spec, so I'll close this for now until more information comes to light.
