### ISSUE TITLE
disable pex and dht

### ISSUE THREAD

**Issue by jzelinskie** [anacrolix/torrent#3]
there's a cli flag for disabling trackers; it would be super useful to get some to disable pex and dht

**Comment by jzelinskie** [comment]
It looks like there's already an option for disabling DHT in `torrent.Config`, so it's just the work of adding the flag.

**Comment by anacrolix** [comment]
Will do. It would be nice to use something that exposes config structs as flag.FlagSets. All of the torrent-related binaries want to expose the same set of flags.
