### ISSUE TITLE
need a example about seeding files directly from the filesystem

### ISSUE THREAD

**Issue by TongxiJi** [anacrolix/torrent#300]

**Comment by TongxiJi** [comment]
I find a problom or a bug  that  seeding will failed if seed dir has any read-only file .

**Comment by TongxiJi** [comment]
@anacrolix  I generate an info  from a file or directory first，then i  do as torrent downloading and replace  function  “AddTorrent” to “AddTorrentWithStorage”.
I've test pass dir without read-only file.

**Comment by TongxiJi** [comment]
@anacrolix   And test env os is windows10 64bit.

**Comment by akghka** [comment]
I don't understand how to seedingd directly from the filesystem.What should i do?Should I impl my own storage

**Comment by anacrolix** [comment]
@akghka do you want to ask this on Discussions?

**Comment by anacrolix** [comment]
See https://github.com/anacrolix/torrent/discussions/556.

**Comment by anacrolix** [comment]
The linked-to discussion addresses this issue.
