### ISSUE TITLE
dht announce sent only once per torrent

### ISSUE THREAD

**Issue by btkador** [anacrolix/torrent#301]
I've added some debug print in the torrent.go code

```
func (t *Torrent) dhtAnnouncer(s *dht.Server) {
	cl := t.cl
	log.Printf("[debug] DHT start announcer %s",t.infoHash.HexString())
	for {
		select {
		case <-t.wantPeersEvent.LockedChan(cl.locker()):
			log.Printf("[debug] DHT wantPeersEvent.LockedChan %s",t.infoHash.HexString())
		case <-t.closed.LockedChan(cl.locker()):
			return
		}
		log.Printf("[debug] DHT start announceDHT %s",t.infoHash.HexString())
		err := t.announceDHT(true, s)
		log.Printf("[debug] DHT done announceDHT %s",t.infoHash.HexString())
		func() {
			cl.lock()
			defer cl.unlock()
			if err == nil {
				t.numDHTAnnounces++
			} else {
				log.Printf("error announcing %q to DHT: %s", t, err)
			}
		}()
		select {
		case <-t.closed.LockedChan(cl.locker()):
			return
		case <-time.After(5 * time.Minute):
			log.Printf("[debug] DHT 5 minutes %s",t.infoHash.HexString())
		}
	}
}
```

and I get only the `DHT start announceDHT` per torrent but never the `DHT done announceDHT` .. therefor `numDHTAnnounces` is always 0 - which was the reason I got suspicious in the first place.

so I looked deeper into that and figured out that after sending the announce dht packet `s.Announce()`, `t.consumeDHTAnnounce(ps.Peers)` is triggered, which goes to an infinity loop, waiting for new incoming peers in response to the sent announce.

```
func (t *Torrent) announceDHT(impliedPort bool, s *dht.Server) (err error) {
	cl := t.cl
	ps, err := s.Announce(t.infoHash, cl.incomingPeerPort(), impliedPort)
	if err != nil {
		return
	}
	t.consumeDHTAnnounce(ps.Peers)
	ps.Close()
	return
}
```

It says that the loop is done, once the announce is done and the channel is closed. But that seems never to happen. Only if I test with a torrent that has more peers than `cl.config.TorrentPeersHighWater` the function returns, and `t.numDHTAnnounces` is incremented. And only in that case further announces are sent.. otherwise it will stay in stat state forever - especial if trackers are disabled.

**Comment by btkador** [comment]
my quickfix for now 

```
func (t *Torrent) announceDHT(impliedPort bool, s *dht.Server) (err error) {
	cl := t.cl
	ps, err := s.Announce(t.infoHash, cl.incomingPeerPort(), impliedPort)
	if err != nil {
		return
	}
	go t.consumeDHTAnnounce(ps.Peers)
	time.Sleep(time.Minute)
	ps.Close()
	return
}
```

since all get_peers responses should have been received within one minute easily

**Comment by btkador** [comment]
may be the reason for #291 too, since when you add a magnetlink without trackers, and the first dht query doesn't deliver any peers (ie because still bootstrapping) it will stay in this state forever.

My quickfix worked for me so far, but fixing it in the dht library may be the better solution ;-)

**Comment by anacrolix** [comment]
I'm not able to find a bug. I think the announces are just taking a very long time, on account of the rate limiting recently introduced. An announce on a very quiet torrent took 26m in my testing.

**Comment by btkador** [comment]
Sending an announce (dht get_peers) and waiting 26m for responses doesn't realy make sense. While instead sending one every 5 minutes while below `TorrentPeersLowWater` - like it seems originally designed - makes way more sense. 

Due to the design of DHT a get_peers run can always return low or zero peers, while the next one (walking another tree) returns a lot more. Waiting (and blocking further announces) 26 minutes after the first query slows things down a lot - and it's quite unneccessaery. There wont be a get_peers response to a request  sent 20 minutes ago .. or even 5 minutes.

The only reason I can see why the announce currenty returns fast (or even imedially, with plenty of peers) for torrents with a high ammount of peers seems to be that it run's into `TorrentPeersHighWater`, and closes the channel and therfor the announce.

```
// Adds peers revealed in an announce until the announce ends, or we have
// enough peers.
func (t *Torrent) consumeDHTAnnounce(pvs <-chan dht.PeersValues) {
	cl := t.cl
	// Count all the unique addresses we got during this announce.
	allAddrs := make(map[string]struct{})
	for {
		select {
		case v, ok := <-pvs:
			if !ok {
				return
			}
			addPeers := make([]Peer, 0, len(v.Peers))
			for _, cp := range v.Peers {
				if cp.Port == 0 {
					// Can't do anything with this.
					continue
				}
				addPeers = append(addPeers, Peer{
					IP:     cp.IP[:],
					Port:   cp.Port,
					Source: peerSourceDHTGetPeers,
				})
				key := (&net.UDPAddr{
					IP:   cp.IP[:],
					Port: cp.Port,
				}).String()
				allAddrs[key] = struct{}{}
			}
			cl.lock()
			t.addPeers(addPeers)
			numPeers := t.peers.Len()
			cl.unlock()
			if numPeers >= cl.config.TorrentPeersHighWater {
				return
			}
		case <-t.closed.LockedChan(cl.locker()):
			return
		}
	}
}
```

My quickfix posted before fixes that, by sending the announce and closing it after 1 minute. There shouldn't be any responses later than that? That way nothing is blocked, and there can be an announce every 5 minutes, like original intended.

**Comment by anacrolix** [comment]
The announce crawls the keyspace, always favouring addresses closest to the target. There are many `get_peers` queries sent. Overtime, as the nodes closest the target have been queried, the traversal will drift away from the target. I haven't worked out when to terminate that part of the search. 26m currently traverses about 10-15k nodes.

**Comment by btkador** [comment]
dht follows the nearest path. so even you use 10-15k nodes in your table it does always jump to the next nearest using a tree of 8.. doesn't it? and that should be done within 1 minute. 
Did you check if you ever get new peers 5 minutes after you've send the initial announce query? 

I'm still confident that aborting the search here after 1 minute is totally fine (works for me perfectly atm) and do a new one 5 minutes later, if more peers required - instead of waiting half an hour.

**Comment by anacrolix** [comment]
I've been thinking about this problem a lot and I think you're correct. However I wish to set the DHT announce interval to 5 mins, with some smarter logic about when to abort the announce. Do you want to try a PR with the minimal changes?

**Comment by btkador** [comment]
since I haven't forked anything yet and it's just two likes of code lets go for a patch for now

```
--- torrent.go	(date 1547821994664)
+++ torrent.go	(date 1547821994664)
@@ -1392,7 +1392,9 @@
 	if err != nil {
 		return
 	}
-	t.consumeDHTAnnounce(ps.Peers)
+	// TODO: come up with a smarter logic to abort the announce
+	go t.consumeDHTAnnounce(ps.Peers)
+	time.Sleep(time.Minute)
 	ps.Close()
 	return
 }
```

That would fix the existing issue right now and you can still come up with a smarter logic later :-)
