### ISSUE TITLE
panic: sync: negative WaitGroup counter

### ISSUE THREAD

**Issue by antonsoroko** [anacrolix/torrent#302]
Hi. I get panic after search in elementum on armv6 device (raspberry pi 1b):
```
2018-12-21 05:44:03 client.go:324: dht server on 0.0.0.0:33485: dht bootstrap: dht.TraversalStats{NumAddrsTried:9236, NumResponses:5975}
panic: sync: negative WaitGroup counter

goroutine 66531 [running]:
sync.(*WaitGroup).Add(0x2d2b9a0, 0xffffffff)
	/usr/local/go/src/sync/waitgroup.go:74 +0x158
sync.(*WaitGroup).Done(0x2d2b9a0)
	/usr/local/go/src/sync/waitgroup.go:99 +0x24
github.com/anacrolix/dht.(*Server).Bootstrap.func1.1(0x0, 0x0, 0x0, 0x2f62b12, 0x2, 0x2f62b1d, 0x1, 0x39b2740, 0x0, 0x2f62a20, ...)
	/ext-go/2/src/github.com/anacrolix/dht/server.go:723 +0xb4
github.com/anacrolix/dht.(*Server).findNode.func1(0x0, 0x0, 0x0, 0x2f62b12, 0x2, 0x2f62b1d, 0x1, 0x39b2740, 0x0, 0x2f62a20, ...)
	/ext-go/2/src/github.com/anacrolix/dht/server.go:685 +0x80
created by github.com/anacrolix/dht.(*Server).query.func3
	/ext-go/2/src/github.com/anacrolix/dht/server.go:594 +0x50
```
please let me know if you need some extra info.

**Comment by anacrolix** [comment]
This was reported [once before](https://github.com/anacrolix/dht/issues/15) and never resolved. I can only guess it's a hardware-specific bug or a race condition of some kind. Are you able to run with `-race` by any chance? Are you able to reproduce it consistently? Thanks

**Comment by antonsoroko** [comment]
Hi.
> Are you able to reproduce it consistently? 

I got it 2 times so I guess yes.
<details>
  <summary>First time I got something more weird</summary>
2018-12-21 05:46:30 client.go:324: dht server on 0.0.0.0:43791: dht bootstrap: dht.TraversalStats{NumAddrsTried:5950, NumResponses:2392}
panic: sync: negative WaitGroup counter

goroutine 40132 [running]:
sync.(*WaitGroup).Add(0x222d330, 0xffffffff)
	/usr/local/go/src/sync/waitgroup.go:74 +0x158
sync.(*WaitGroup).Done(0x222d330)
	/usr/local/go/src/sync/waitgroup.go:99 +0x24
github.com/anacrolix/dht.(*Server).Bootstrap.func1.1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/ext-go/2/src/github.com/anacrolix/dht/server.go:715 +0xf8
github.com/anacrolix/dht.(*Server).findNode.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/ext-go/2/src/github.com/anacrolix/dht/server.go:685 +0x80
created by github.com/anacrolix/dht.(*Server).query.func5
	/ext-go/2/src/github.com/anacrolix/dht/server.go:607 +0xc8
</details>
<br>


> Are you able to run with -race by any chance?

Could you please put more details? (If you mean like `run go build -race` then I guess only with @elgatito help)

**Comment by elgatito** [comment]
@anacrolix build with `-race` and then reproduce the error with that binary? Or just build and expect any warnings?

**Comment by antonsoroko** [comment]
I guess build and run, but there is a slight problem with that as I can see:
https://golang.org/doc/articles/race_detector.html#Supported_Systems

>The race detector runs on darwin/amd64, freebsd/amd64, linux/amd64, and windows/amd64.

So I guess it should be investigated in other way...

**Comment by anacrolix** [comment]
@elgatito I think the error will have to be reproduced in running the binary.

**Comment by anacrolix** [comment]
I'm really not sure. I wasn't able to solve this last time either.

**Comment by antonsoroko** [comment]
https://github.com/derekparker/delve/blob/master/Documentation/usage/dlv_exec.md
https://golang.org/doc/gdb

The only thing is that we probably need to re-compile the binary:
>Please note that if the binary was not compiled with optimizations disabled, it may be difficult to properly debug it.

**Comment by anacrolix** [comment]
Is this issue definitely constrained to armv6?

**Comment by antonsoroko** [comment]
can't say for sure. I had this issue only on linux arm. I also used elementum on android arm32 and linux x64 but have not seen this issue.

**Comment by anacrolix** [comment]
I believe I've tracked down the issue. Please see anacrolix/dht#15.

**Comment by antonsoroko** [comment]
@anacrolix @elgatito 
I guess we can try to run it on Linux x86, but as I mentioned before it could be impossible on armv6 (if documentation is correct).
Thanks.

**Comment by anacrolix** [comment]
@antonsoroko do you refer to running with `-race`? You can still run this unit test without `-race`, it will just take many more runs to reproduce the issue. Please try without `-race` if that's the case.

**Comment by anacrolix** [comment]
Fixed upstream.
