### ISSUE TITLE
Download with limiter does not work 

### ISSUE THREAD

**Issue by elgatito** [anacrolix/torrent#304]
I've got an issue about not working download when downlowd limit is set.
Nothing was changed from my side. 
I could reproduce the problem myself.

Setting to 1000 kb rate limiter. Starting magnet - it cannot even download metadata. If starting torrent file - there are no active connections, while available connections are there.

You can take a look: https://paste.ubuntu.com/p/dFkFHfhz4j/

**Comment by anacrolix** [comment]
I can't reproduce this. It's possible setting the PublicIP4 and PublicIP6 fields in the ClientConfig are a big contributor. I did find that it took some time to start connecting to peers for those torrents over the DHT.

**Comment by anacrolix** [comment]
Any update on this @elgatito?

**Comment by elgatito** [comment]
@anacrolix we can close it.
