### ISSUE TITLE
Add release version

### ISSUE THREAD

**Issue by onestraw** [anacrolix/torrent#307]
There is one repo `chihaya` used the package, chihaya use `dep` to manage its dependecies, as far as I know `dep` can not specify `commit` of package, so `chihaya` must update torrent-related code if run `dep enusre -update` even if we want to add some new packages.

https://github.com/chihaya/chihaya/issues/444

**Comment by anacrolix** [comment]
Is a tag sufficient? I am considering to add tags for go mod support.

**Comment by onestraw** [comment]
Yes, it works.
By the way, `dep` supports specifying commit with [`revision` command](https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md). `dep` recommends using `version` as it is more formal and provides more release infomations.

**Comment by anacrolix** [comment]
I've released and tagged v1.0.0. I intend to support go modules, which should work for go dep so far as I can tell.
