### ISSUE TITLE
Add option and support of forced sequential download mode

### ISSUE THREAD

**Issue by antonsoroko** [anacrolix/torrent#309]
Hi.
It would be nice to have support of forced sequential download mode - would be really useful for streaming. In current implementation there is buffering problems in elementum if download speed is not so great (e.g. I experience issues with geographically remote peers). But with real sequential download and big buffer we can mitigate this kind of problem.

Thank you.

**Comment by anacrolix** [comment]
I think this has been suggested before. If you are using a Reader, and struggling to acquire data, the downloads are effectively sequential. You can also make the buffer as small as possible to truly force sequential download, but I don't believe sequential downloads with a larger buffer will give as much benefit as you think. I will leave this issue open in case others identify specifics about this behaviour.

**Comment by anacrolix** [comment]
See https://github.com/anacrolix/torrent/issues/150#issuecomment-289264973 and https://github.com/anacrolix/torrent/issues/139#issuecomment-269085138.

**Comment by antonsoroko** [comment]
It works just fine in quasar (libtorrent) :-)

**Comment by anacrolix** [comment]
@antonsoroko I don't believe performance differences between libtorrent and anacrolix/torrent are for this reason.

**Comment by antonsoroko** [comment]
I mean that I believe that this could mitigate this difference.

**Comment by mihaiav** [comment]
You can download sequentially if you are using a reader. You can actually even Seek/get random access. I actually implemented a http server on top of anacrolix with support for range requests.

**Comment by anacrolix** [comment]
@antonsoroko I think to progress we need to know that the proposed solution doesn't work. Do you have any more information that would suggest that using a `Reader` is not sufficient?

**Comment by antonsoroko** [comment]
Hi.
Unfortunately I don't have any technical info.
This issue was created to improve user experience in elementum, but nowadays elementum does not use this library.
So if you don't see any value in this option for other users i guess we can close this issue.
Thank you.

**Comment by anacrolix** [comment]
@antonsoroko Thanks, I'll close this.
