### ISSUE TITLE
Support 'x.pe' parameter on magnet URIs

### ISSUE THREAD

**Issue by pataquets** [anacrolix/torrent#310]
When opening/decoding magnet links, parsing x.pe parameter would allow faster download and bootstrapping of torrents.
More info: http://bittorrent.org/beps/bep_0009.html#magnet-uri-format

**Comment by anacrolix** [comment]
Thanks! Great idea.

**Comment by anacrolix** [comment]
There's now support for extra magnet parameters, you could examine `x.pe` yourself and directly add the peers.

**Comment by anacrolix** [comment]
@pataquets do you want to try with master with the new field?

**Comment by anacrolix** [comment]
@pataquets the new field is available since `v1.8.0`.

**Comment by pataquets** [comment]
Thank you very much, @anacrolix.
However, I can no longer test it under my current usage scenario. I was using it indirectly from Elementum Kodi addon, which switched to libtorrent (see elgatito/plugin.video.elementum#351).

**Comment by anacrolix** [comment]
The only remaining feature is to automatically add `x.pe` peers to the Torrent. I've not seen any magnet URIs in the wild that included an `x.pe`, and I wonder about the security implication (probably no worse than having an arbitrary `tr` element).

**Comment by pataquets** [comment]
Thanks for the heads-up, @anacrolix.
Indeed, I made some attempts at testing it under torrentfs/torrent-magnet, in case I could report back, but I failed. Since I could not rule out some error on my part, I left it alone.
When you speak about the remaining feature, you mean that adding peers has to be implemented in this library (continued on this issue) or that it is the library clients who are supposed to implement adding the peers in their app's code?
In case it has to be implemeted here, could you please give a pointer where it should be? My guess is that [here](https://github.com/anacrolix/torrent/blob/378ccd0932c5791e503fd32a82846d45263aad03/client.go#L1114) a call to `t.AddPeers()` with the values from `spec.Params["x.pe"]` would be enough.
I've stumbled on another project using it (albeit using a too old version, but that's another story) and I might give it a stab, although my go-fu is weak.

**Comment by anacrolix** [comment]
> When you speak about the remaining feature, you mean that adding peers has to be implemented in this library (continued on this issue) or that it is the library clients who are supposed to implement adding the peers in their app's code?

I have no preference currently.

> In case it has to be implemeted here, could you please give a pointer where it should be? My guess is that [here](https://github.com/anacrolix/torrent/blob/378ccd0932c5791e503fd32a82846d45263aad03/client.go#L1114) a call to `t.AddPeers()` with the values from `spec.Params["x.pe"]` would be enough.

That would be right, but if the relevant field isn't available in TorrentSpec, it might be more appropriate after https://github.com/anacrolix/torrent/blob/378ccd0932c5791e503fd32a82846d45263aad03/client.go#L1178.

**Comment by anacrolix** [comment]
As @yarikk helpfully mentioned, this is now fixed.
