### ISSUE TITLE
How to pipe as I read?

### ISSUE THREAD

**Issue by 0xbkt** [anacrolix/torrent#313]
I'm working on a piper application which originally requests a big file from a remote HTTP server in chunks using HTTP ranges and uploads them concurrently (e.g. 10-by-10 simultaneously) to another HTTP server. I wanted to implement the same for torrents. But when I use `NewReader`, it creates a BoltDB file and the file I'm downloading on disk on its own, which is unexpected in my case as I'm limited in system resources.

1) Can I disable this behaviour?
2) If not, can I create my own storage solution by imitating `filecache` package so as to create Linux FIFO pipe files and writing onto them and simultaneously reading them on the other end?
3) Is there a better alternative for a do-pipe-as-read-concurrently?

**Comment by anacrolix** [comment]
1. Yes, you can provide a custom storage backend. For example you might make use of a filecache (there's some examples floating around, probably in anacrolix/confluence), or use an entirely memory based solution, or whatever you prefer.
2. It wouldn't be necessary, per 1. You also really shouldn't access the data without going through a torrent.Reader, particularly when it comes to streaming, unless you can make specific synchronization guarantees about the state of the torrent client, and the storage.
3. torrent.Reader was made for this.
