### ISSUE TITLE
Unable to build on Linux

### ISSUE THREAD

**Issue by Sioro-Neoku** [anacrolix/torrent#32]
Hey,

I [received this error](https://github.com/Sioro-Neoku/go-peerflix/issues/4) regarding your package:
```
go get github.com/Sioro-Neoku/go-peerflix
# github.com/anacrolix/torrent/dht
/root/go/src/github.com/anacrolix/torrent/dht/addr.go:6: import /root/go/pkg/linux_arm/github.com/anacrolix/missinggo.a: object is [linux arm go1.2.1 X:none] expected [linux arm go1.4.2 X:precisestack]
# github.com/anacrolix/utp
/root/go/src/github.com/anacrolix/utp/utp.go:29: import /root/go/pkg/linux_arm/github.com/anacrolix/jitter.a: object is [linux arm go1.2.1 X:none] expected [linux arm go1.4.2 X:precisestack]
```

**Comment by anacrolix** [comment]
I think you have some package files left over from a Go update. Go is absymal at managing this: Try `$ rm -r "$GOPATH/pkg"`, then run your command again.

**Comment by Sioro-Neoku** [comment]
Summon @milankragujevic .

**Comment by anacrolix** [comment]
![](http://i1.kym-cdn.com/entries/icons/facebook/000/004/808/inglip.jpg)

**Comment by milankragujevic** [comment]
WHO DARES TO SUMMON ME... (in school, ttyl8r)

**Comment by milankragujevic** [comment]
Ermahgerd it werks. Thanks you!
> root@scw-4e3ec1:~# rm -r "$GOPATH/pkg"
> root@scw-4e3ec1:~# go get github.com/Sioro-Neoku/go-peerflix
> [...]
> root@scw-4e3ec1:~/go/bin# go-peerflix
> Usage of go-peerflix:
>   -seed=true: Seed after finished downloading
>   -vlc=false: Open vlc to play the file

**Comment by anacrolix** [comment]
A++ would tech support again.

**Comment by Sioro-Neoku** [comment]
10/10 Would proxy issues to other developers again.
