### ISSUE TITLE
go-libutp dependency prints build warnings

### ISSUE THREAD

**Issue by anacrolix** [anacrolix/torrent#332]
See https://github.com/anacrolix/torrent/issues/327#issuecomment-524277454, and https://github.com/anacrolix/go-libutp/pull/12. The fix should be pulled here when available.

**Comment by FIGBERT** [comment]
I believe this is briefly mentioned in the [comment on #327](https://github.com/anacrolix/torrent/issues/327#issuecomment-524277454) but:

`github.com/anacrolix/go-libutp` logs to `stderr` even when `ClientConfig.Logger` is set to `log.Discard`. This has become an issue with a TUI client I'm working on, as I'd like to handle most errors myself.

`github.com/anacrolix/go-libutp` initializes a `Logger` variable in [logger.go](https://github.com/anacrolix/go-libutp/blob/b194960121750737aaa23258a784cd894651af67/logging.go). Logging to `stderr` may be a good default behavior, but I think that it should match `ClientConfig.Logger` when that's customized.

**Comment by anacrolix** [comment]
@FIGBERT do you have sample log messages you're seeing? It's possible they're coming out of underlying C++ implementation, but if you provide some samples I can check.

**Comment by FIGBERT** [comment]
A sample:
```

**Comment by FIGBERT** [comment]
A sample:
```
go-libutp: 2021/09/26 21:15:03 callbacks.go:73: error sending packet: write udp4 0.0.0.0:42069->0.0.179.30:42069: sendto: no route to host
go-libutp: 2021/09/26 21:15:05 callbacks.go:73: error sending packet: write udp4 0.0.0.0:42069->0.0.179.30:42069: sendto: no route to host
go-libutp: 2021/09/26 21:15:08 callbacks.go:73: error sending packet: write udp4 0.0.0.0:42069->0.0.179.30:42069: sendto: no route to host
```

Regardless of the reasons for the error – potentially related to my VPN, I'm unsure – I'd like to find a way to configure the logger because in its current form it draws over my UI.
