### ISSUE TITLE
panic: changes to torrent length from int to *int causing segfault.

### ISSUE THREAD

**Issue by james-lawrence** [anacrolix/torrent#337]
https://github.com/anacrolix/torrent/blob/master/t.go#L40 is segfaulting due to the change to a pointer. this might be exposing a latent race condition where the length was returning 0 improperly.

**Comment by anacrolix** [comment]
Thanks. I think this is an undocumented case where the info must be available first. If you can confirm that `Torrent.Info` is `nil` prior to calling `NewReader`, I'll document this requirement.

**Comment by james-lawrence** [comment]
the code triggering this is waiting for the info.

**Comment by anacrolix** [comment]
With the context you've provided, it's still not a requirement that the info is present before calling `NewReader`. If you're streaming the `Torrent`, it also isn't necessary be calling `DownloadAll`, let alone be guarding that (presumably necessary) call with a possible timeout.

	if tt, dlrequired = t.client.AddTorrentInfoHash(m.InfoHash); dlrequired {
		go func() {
			<-tt.GotInfo()
			tt.DownloadAll()
		}()
	}

	select {
	case <-tt.GotInfo():
	case <-ctx.Done():
		return newErrReader(errors.New("timed out waiting for torrent info"))
	}

    tt.NewReader()

You should also take a look at:
https://github.com/anacrolix/confluence/blob/6ddde336a3771b5862469746d2dd660f8cd76124/confluence/mux.go#L12
https://github.com/anacrolix/confluence/blob/55071d746a2be82aa97774cdfab4d73364ffbe2b/confluence/middlewares.go#L70-L82
https://github.com/anacrolix/confluence/blob/55071d746a2be82aa97774cdfab4d73364ffbe2b/confluence/misc.go#L67-L81

**Comment by anacrolix** [comment]
@james-lawrence Does https://github.com/anacrolix/torrent/issues/338#issuecomment-548970244 apply here? Can we close this?
