### ISSUE TITLE
Peer lists are not exchanged over PEX

### ISSUE THREAD

**Issue by yarikk** [anacrolix/torrent#341]
PEX support in the library is limited to handling incoming PEX messages and updating own peer lists. The list of currently connected peers is not being communicated.

[BEP 11](http://bittorrent.org/beps/bep_0011.html) regulates the frequency of batch updates to  happen no more than once a minute and have no more than 50 entires, but it's better be kept flexible.

We are looking into creating a tracker-less setup in an isolated managed environment, with initial seed addresses bootstrapped via metadata or magnet links.

@anacrolix Any pointers before I jump into implementing this?

**Comment by anacrolix** [comment]
@yarikk that's right. I'm sure I had an issue and TODO regarding this, but I cannot find them. I welcome your contributing this. You'll probably want to add code to generate the outgoing pex message here: https://github.com/anacrolix/torrent/blob/289293f3cc0cfd03bbe3bf168dcc1ba6a90d13aa/connection.go#L590. You'll probably also want a timer like the keep alive one, to trigger updates like this one: https://github.com/anacrolix/torrent/blob/289293f3cc0cfd03bbe3bf168dcc1ba6a90d13aa/connection.go#L602. Let me know what you think, it looks like there's some interesting requirements on the implementation from reading the BEP.

**Comment by yarikk** [comment]
Addressed in #341.

**Comment by anacrolix** [comment]
@yarikk I wasn't sure where else to message you, I've made some recent changes to PEX to use net/netip, and some fixes to the interval use (I think it was applied for the whole torrent, rather than per peer). Do you want to take a look?
