### ISSUE TITLE
torrent-create always sets comment 'yoloham'

### ISSUE THREAD

**Issue by rwenz3l** [anacrolix/torrent#342]
Based on the defaults defined here: 
https://github.com/anacrolix/torrent/blob/dfcb8524874306491949934638d05161329014a3/metainfo/metainfo.go#L60-L65

all torrents created with `torrent-create` include a comment.

Tested with:
```
go get github.com/anacrolix/torrent/cmd/...
dd if=/dev/random of=~/test.mp4 bs=1m count=100
torrent-create ~/test.mp4 > ~/test.mp4.torrent
```

I consider this a bug, as I do not expect a comment when there is none specified, especially not something like 'yoloham'.

**Comment by anacrolix** [comment]
@rwenz3l a PR would be welcomed. It's probably enough just to remove the "yoloham" comment assignment.

**Comment by anacrolix** [comment]
@rwenz3l are you still interested in this?

**Comment by rwenz3l** [comment]
hey @anacrolix, I had this in my backlog for quite some time. I could def. take care of this, but not sure when I will actually get around doing it. 

Am I interested: Yes. Am I going to work on it anytime soon? Maybe.
