### ISSUE TITLE
Download part of the video to stream from certain time

### ISSUE THREAD

**Issue by bcashier** [anacrolix/torrent#345]
Hi,

Is there a wa to stream a video starting from for a example 30min while this part not yet downloaded?

When we select a certain duration, this part will start automatically to be downloaded.

Thank you

**Comment by anacrolix** [comment]
Yes, this is supported by serving your HTTP byte-range requests with a Torrent.Reader. See documented examples and other issues on how to do this.

**Comment by wegel** [comment]
@anacrolix where are the documented examples pertaining to this topic specifically? Thanks.

**Comment by anacrolix** [comment]
@wegel https://github.com/anacrolix/torrent/issues/309#issuecomment-454779880 is the best place to look. I'm not sure on the status of the documentation in this area.
