### ISSUE TITLE
validateInfo in misc.go is offbyone

### ISSUE THREAD

**Issue by soul9** [anacrolix/torrent#35]
ValidateInfo should work perfectly fine except for a -1 that slipped in the length sanity verification somehow here https://github.com/anacrolix/torrent/blob/master/misc.go#L119

**Comment by anacrolix** [comment]
That's for rounding up integer division. Do you have an example or test case for broken behaviour you're experiencing?

**Comment by soul9** [comment]
sure, here is the testcase
https://gist.github.com/soul9/b2e8cdd3f069222d0e65

**Comment by anacrolix** [comment]
Thanks for that. The error is actually in the builder code, which I incorporated from another project. metainfo/builder.go:307. I'll issue a fix soon.
