### ISSUE TITLE
panic: error writing chunk: open: too many open files

### ISSUE THREAD

**Issue by nektro** [anacrolix/torrent#351]
```
panic: error writing chunk: open /media/meghan/EL-1/data/LibGen/133000/6acf242768fed996bff7fbb46baacffc: too many open files

goroutine 1237594 [running]:
github.com/anacrolix/torrent.(*connection).receiveChunk(0xc04d9c8000, 0xc07ff32af0, 0x5, 0x1)
	/home/meghan/go/src/github.com/anacrolix/torrent/connection.go:1347 +0x95e
github.com/anacrolix/torrent.(*connection).mainReadLoop(0xc04d9c8000, 0x0, 0x0)
	/home/meghan/go/src/github.com/anacrolix/torrent/connection.go:1140 +0x490
github.com/anacrolix/torrent.(*Client).runHandshookConn(0xc000112b00, 0xc04d9c8000, 0xc00065ce00)
	/home/meghan/go/src/github.com/anacrolix/torrent/client.go:879 +0x59b
github.com/anacrolix/torrent.(*Client).outgoingConnection(0xc000112b00, 0xc00065ce00, 0xc021bb75a0, 0x4, 0x4, 0xc00091e1af, 0xab0d00, 0x2)
	/home/meghan/go/src/github.com/anacrolix/torrent/client.go:709 +0x33a
created by github.com/anacrolix/torrent.(*Torrent).initiateConn
	/home/meghan/go/src/github.com/anacrolix/torrent/torrent.go:1740 +0x263
```

**Comment by anacrolix** [comment]
Thanks for the report. What platform are you on? What kind of storage are you using? Could you track the value of the `expvar` `torrentConcurrentChunkWrites` up until the panic occurs?

**Comment by nektro** [comment]
I believe this was a race condition with my drive and the torrents I was using. I'm on `linux amd64` but I was using the LibGen torrents which are each 1,000 files each.

**Comment by anacrolix** [comment]
Do you have a lot of torrents loaded too? I think you should need a combined uploading and downloading connections of over 1000 to trigger this. A workaround would be to use the mmap storage backend.

**Comment by nektro** [comment]
I happened to have 100 of the torrents loaded at the time of this particular crash.

**Comment by anacrolix** [comment]
@nektro Could you try with the mmap storage? Do you want to increase your file handle limit?

**Comment by nektro** [comment]
<https://stackoverflow.com/a/32325509/5203655>
```
➜  EL-1 ulimit -n
1024
```
