### ISSUE TITLE
add a public version of Torrent.numPiecesCompleted()

### ISSUE THREAD

**Issue by nektro** [anacrolix/torrent#352]

**Comment by anacrolix** [comment]
Was there a PR with this? Have you tried using `Torrent.Piece`? Maybe a `Torrent.Pieces` should be added?

**Comment by nektro** [comment]
There's `Torrent.NumPieces` but that's the total number of pieces, not the number of completed ones.

**Comment by anacrolix** [comment]
What I mean is that you could collect this data yourself by checking each Piece. Something like
```
for i := 0; i < t.NumPieces(); i++ {
    do something with t.Piece(i).Storage().Completion()
}
```

**Comment by james-lawrence** [comment]
imo could be added to torrent stats.

**Comment by anacrolix** [comment]
@nektro any update on this? Is the suggested workaround okay got you?

**Comment by nektro** [comment]
If it returns the same number then I can copy/paste the internal implementation sure, but the issue was asking if this method would be exposed publicly without having to make my own function (since it already exists privately (lowercase name)).

**Comment by anacrolix** [comment]
@nektro I wouldn't want to expose a method just for this, if it can be bundled into some other method that requires a lock (like torrent stats per @james-lawrence suggestion).

**Comment by anacrolix** [comment]
Added this to stats.
