### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by yarikk** [anacrolix/torrent#356]
The RC4 cipher currently part of BitTorrent protocol encryption is considered insecure these days. In search for replacement, TLS appears the best candidate, comprising a modern, widely deployed suite of cryptographic protocols. Although there is no active or draft BEP specification on TLS, it would be a major step forward in the protocol development. The proposal  here is to  develop a not-yet-standard extension adding TLS support to BitTorrent protocol, with a perspective to have it thoroughly documented and put up as a BEP.

Any constructive input is welcome.

**Comment by anacrolix** [comment]
RC4 is only used as obfuscation in BitTorrent, it's probably much easier in most cases to figure out which infohash is being used as the secret key. I'm not sure how you would change this. Can you link to any upstream proposals?

**Comment by yarikk** [comment]
This is an original proposal, to be referenced in further discussions. The idea is to wrap the whole peer protocol into a TLS session, either right from the beginning or after negotiating during the basic handshake, to be decided. Therefore every peer connection is going to have own set of negotiated keys.

**Comment by chantra** [comment]
I think essentially what would be useful is to be able to provide a custom dialer in https://github.com/anacrolix/torrent/blob/d34dfa6575c49eaad2dd2a6b35101f1bce26da5e/socket.go#L69, if the custom dialer is nil, it would default to net.Dialer{}. Similarly for the Listeners. 

This could be propagated through ClientConfig by using 
 something like DialerFunc, ListenerFunc which would have some default implemetation if not overriden.
https://github.com/anacrolix/torrent/blob/d34dfa6575c49eaad2dd2a6b35101f1bce26da5e/client.go#L230 would need to pass those specifically, or the whole ClientConfig.

This way, someone that want to implement customer dialer (for instance TLS), could put the logic in their own dialer, where they would need to handle validation and all on their own. For lack of existing BEP, this may give flexibility without adding complexity to the library.

This would work for the use-case we are interested in, e.g using TLS between peers, but dealing with certificates and their validation is very in-house. Solutions within the boundaries of an organizations may be pretty simple (supposedly, all leechers could use the same certs and clients would validate that cert), but TLS over public swarm would seem much more difficult to achieve.

@anacrolix any thoughts?

**Comment by anacrolix** [comment]
@chantra I think you're on a great path here. I think instead of injecting a custom dialer, we should just open adding custom sockets directly. The intention of the socket abstraction that exists is to allow dialing and listening to be done by the client on whatever it wants, it just never became public. It might be worth separating them into Listener and Dialer, which will help elsewhere for example with proxies (see https://github.com/anacrolix/torrent/issues/359 and https://github.com/anacrolix/torrent/pull/360).

**Comment by chantra** [comment]
cc @ericsage 

> we should just open adding custom sockets directly.

Are you saying to make `socket` and `dialer` public? So one could then provide a custom `listenAll` that would return their custom sockets ? 

SGTM

**Comment by anacrolix** [comment]
@chantra One would create whatever kinds of dialers and listeners you want, then attach them to the `Client`. There are a lot of areas of the package that could take on this kind of extra flexibility, but I'm not sure about how best to migrate to a thinner client. At least in the short-term, it might be possible to have the `Client` not listen for you, and expose methods to add your own stuff instead (or in addition).

**Comment by anacrolix** [comment]
@yarikk @chantra Could you please try with the latest version.

**Comment by chantra** [comment]
@anacrolix  I gave it a try off  ddc61845acb725707781d1acd756a3a60c60c8d0 and it seems to work. The main issue I encountered was needing to set ListenPort to 0 given that it is initialized in https://github.com/anacrolix/torrent/blob/c855c7a3665fcd1c5b73cfc22778796e9cf8267e/config.go#L166 , not sure if this is a change in behaviour or not as we did not need to set it before (but we were running off a very old commit).

I am getting a lot of the following error messages like shown in CI:

```
2020-02-21 03:57:57 torrent.go:1688: "olo@SIS001@OBA-237": piece 4fe050208d675e5cd967d41348a31ab11b316806/2 (bbb6deef2a5b8d2916d8f4ae5af7c20dc489e408) hash failure copy error: unexpected EOF
2020-02-21 03:57:57 torrent.go:1688: "olo@SIS001@OBA-237": piece 4fe050208d675e5cd967d41348a31ab11b316806/3 (e3df4315124c80a7fdd0e97dcf88dadbb373503b) hash failure copy error: unexpected EOF
2020-02-21 03:57:57 torrent.go:1688: "olo@SIS001@OBA-237": piece 4fe050208d675e5cd967d41348a31ab11b316806/4 (f00a069a57bb25f87d049f5cacd793775d383bee) hash failure copy error: unexpected EOF
```

it seems to happen for every single pieces of the torrent. Regardless, the torrent are downloading fine.

At this stage, this is only using standard torrent. We have not plugged any custom logic in just yet.

**Comment by anacrolix** [comment]
> @anacrolix I gave it a try off [ddc6184](https://github.com/anacrolix/torrent/commit/ddc61845acb725707781d1acd756a3a60c60c8d0) and it seems to work. The main issue I encountered was needing to set ListenPort to 0 given that it is initialized in
> 
> https://github.com/anacrolix/torrent/blob/c855c7a3665fcd1c5b73cfc22778796e9cf8267e/config.go#L166
> 
> , not sure if this is a change in behaviour or not as we did not need to set it before (but we were running off a very old commit).

Yes, that is a more recent change to the defaults. If you don't want to use the standard networks for BitTorrent, you could disable TCP and uTP so that only your TLS stuff is used.
> I am getting a lot of the following error messages like shown in CI:
> 
> ```
> 2020-02-21 03:57:57 torrent.go:1688: "olo@SIS001@OBA-237": piece 4fe050208d675e5cd967d41348a31ab11b316806/2 (bbb6deef2a5b8d2916d8f4ae5af7c20dc489e408) hash failure copy error: unexpected EOF
> 2020-02-21 03:57:57 torrent.go:1688: "olo@SIS001@OBA-237": piece 4fe050208d675e5cd967d41348a31ab11b316806/3 (e3df4315124c80a7fdd0e97dcf88dadbb373503b) hash failure copy error: unexpected EOF
> 2020-02-21 03:57:57 torrent.go:1688: "olo@SIS001@OBA-237": piece 4fe050208d675e5cd967d41348a31ab11b316806/4 (f00a069a57bb25f87d049f5cacd793775d383bee) hash failure copy error: unexpected EOF
> ```
> 
> it seems to happen for every single pieces of the torrent. Regardless, the torrent are downloading fine.

That's tracked in https://github.com/anacrolix/torrent/issues/381. It's only a change to logging.
> 
> At this stage, this is only using standard torrent. We have not plugged any custom logic in just yet.

Thanks for the feedback so far.

**Comment by chantra** [comment]
I think this issue can be closed. What do you think @yarikk ?

From where I stand, there is now API to add custom listener/dialer. As we start using it, we may find missing bits and pieces, but this would be a different story and we could take it from there at that time.

**Comment by anacrolix** [comment]
Cheers.
