### ISSUE TITLE
http tracker does not work with socks5 proxy

### ISSUE THREAD

**Issue by sickyoon** [anacrolix/torrent#358]
http tracker does not work with socks5 proxy

eg) http://ipmagnet.services.cbcdn.com/

**Comment by anacrolix** [comment]
@sickyoon Could you provide more information? I don't use socks5 proxies in my usage, if you could provide a sample proxy and `cmd/torrent` invocation or something like that it would be very useful.

**Comment by anacrolix** [comment]
@sickyoon did you observe with a proxy configured that your true IP would still appear on that website? Is that the observation?

**Comment by sickyoon** [comment]
I just verified that http tracker is working through socks5 proxy with latest master. I am not sure what changed since this issue was created.
