### ISSUE TITLE
connection allowed even if proxy is misconfigured

### ISSUE THREAD

**Issue by sickyoon** [anacrolix/torrent#359]
It appears that torrent can be retrieved through non-proxied connection if proxy_url is misconfigured.

### Steps to reproduce
To reproduce, run `cmd/torrent/main.go` with `ClientConfig.ProxyURL` set to invalid arbitrary socks5 url.

### Expected
Torrent should not download

### Actual
Torrent downloads successfully

**Comment by sickyoon** [comment]
Should disable accepting connections if proxy is configured

**Comment by anacrolix** [comment]
Was this fixed by https://github.com/anacrolix/torrent/pull/360?

**Comment by sickyoon** [comment]
verified fixed.
