### ISSUE TITLE
download speed in local gigabit LAN tops out at ≈ 1 MB/s

### ISSUE THREAD

**Issue by stapelberg** [anacrolix/torrent#361]
I am using the torrent program to seed an disk image on one computer (≈700 MiB) and to download it onto another computer. Both machines are connected with a gigabit port, and using `scp` the transfer finishes in a few seconds, as expected:

```
% scp chuchi:distri-disk.img.zst /tmp/diskscp
distri-disk.img.zst 100%  681MB 110.9MB/s   00:06    
```

However, the `torrent` program takes over 11 minutes to transfer the same file!
```
% torrent 'magnet:?xt=urn:btih:0aa9282c0644608c1ff50a278f4d3fb19950e654&dn=distri-disk.img.zst&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=http%3A%2F%2Fopen.acgnxtracker.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce'
                                                                                                                                                                
distri-disk.img.zst [===================================================================>] 100% downloading (714 MB/715 MB)
2019/12/25 23:18:55 main.go:182: downloaded ALL the torrents
torrent   47,42s user 13,10s system 8% cpu 11:17,45 total
```

Could the speed be improved for fast connections please? Happy to help look into possible reasons if you want to, or to validate any changes you can come up with :)

Thanks!

**Comment by anacrolix** [comment]
I've had tests on the public network exceed 60MB/s. One quick thing to check would be disabling uTP, and the OS, filesystem type, and device type that filesystem is on. I also note that torrent doesn't have a whole lot of swarm participants, it took a while to find one on a home network that I tested it on.

**Comment by stapelberg** [comment]
Thanks for following up! Answers inline:

> I've had tests on the public network exceed 60MB/s. One quick thing to check would be disabling uTP, 

How do I do that?

> and the OS, filesystem type, and device type that filesystem is on. 

Both are Linux with ext4 on a fast SSD.

> I also note that torrent doesn't have a whole lot of swarm participants, it took a while to find one on a home network that I tested it on.

In this case, there was only one participant, but the transfer was running, so it doesn’t intuitively seem like a discovery issue to me

**Comment by anacrolix** [comment]
That all looks fine. There's no option exposed in `cmd/torrent` yet for disabling UTP. Is the seeder also running via `cmd/torrent`?

**Comment by stapelberg** [comment]
Yes

**Comment by anacrolix** [comment]
@stapelberg I've made some improvements in `cmd/torrent` and related behaviours. Could you try again with `master`.

**Comment by stapelberg** [comment]
Tested with commit baefdfd9eae5867a1cb416979fe7e24e29316ade, and `cmd/torrent` now saturates my gigabit line!

Thank you so much for the changes!

**Comment by anacrolix** [comment]
@stapelberg the end of https://github.com/anacrolix/torrent/issues/364 may be relevant to you.
