### ISSUE TITLE
Consuming way more bandwidth than necessary?

### ISSUE THREAD

**Issue by wegel** [anacrolix/torrent#366]
I'm using torrent.File.Reader to read a torrent's file as if it was a sequential byte stream. Works great.

However, while monitoring the network, I've noticed that I'm downloading way more than the file mandates by itself; for example, an mkv video file with an average bitrate of ~2.44MB/s (112 minutes, 16GB file) will consume about 10-25MB/s from the torrent network while playing it back. Is that normal?

I also tested this with torrentfs; exact same behaviour. Thanks!

**Comment by anacrolix** [comment]
The library will aggressively buffer ahead of the Reader position, causing some overlap in receiving chunks from peers. Optimizing this has been an ongoing effort. You could experiment with the [Torrent.requestStrategy](https://github.com/anacrolix/torrent/blob/master/torrent.go#L50-L56). There are several in place, and hopefully at some point I'll extract the concept out to an interface so you can plug one in. You might also try setting the `duplicateRequestTimeout` to something much higher, maybe 10 seconds or more.

**Comment by wegel** [comment]
Cool; `Torrent.requestStrategy=3` with a 5 seconds `duplicateRequestTimeout` seems to work good in my use-case (with very limited testing, and this is with private tracker with looots of fast seeds), I'm wasting almost no bandwidth now.

**Comment by anacrolix** [comment]
@wegel that's really helpful feedback, cheers.

**Comment by anacrolix** [comment]
@wegel request strategies have been abstracted out now, you should be able to specify them in the `ClientConfig`.

**Comment by anacrolix** [comment]
I'll close this as it's the default strategy as of https://github.com/anacrolix/torrent/commit/2559af0f9ccc00a7c7cac4ea360beee6d94de5e2.

**Comment by anacrolix** [comment]
This is released in `v1.12.0`.
