### ISSUE TITLE
go-flags prevents blockfile use with cmd/torrent

### ISSUE THREAD

**Issue by errnoh** [anacrolix/torrent#37]
https://github.com/anacrolix/torrent/blob/master/cmd/torrent/main.go#L80 seems to fill `rootGroup.Client.IPBlocklist` with `&{[]}`. 

This causes `if cfg.IPBlocklist != nil` to always resolve true, which then prevents the call to `cl.setEnvBlocklist()`

**Comment by anacrolix** [comment]
Great catch, thanks.

**Comment by errnoh** [comment]
Since this is mostly a problem in `go-flags` end I submitted ticket over there as well: https://github.com/jessevdk/go-flags/issues/151

**Comment by anacrolix** [comment]
Thanks, I've come up with my own implementation, let me know if you have any issues or thoughts.
