### ISSUE TITLE
Panic occurring on chunk write when using a proxy 

### ISSUE THREAD

**Issue by tab1293** [anacrolix/torrent#371]
If I set a SOCKS proxy with config's `ProxyURL`, I consistently run in to this panic on torrent download. With no proxy the download completes fine.

```
panic: error writing chunk: open filename.txt: too many open files

goroutine 223 [running]:
github.com/anacrolix/torrent.(*connection).receiveChunk(0xc000526c00, 0xc001537b20, 0x5, 0x1)
	/Users/tom/go/src/github.com/tab1293/torrent-test/vendor/github.com/anacrolix/torrent/connection.go:1349 +0x96a
github.com/anacrolix/torrent.(*connection).mainReadLoop(0xc000526c00, 0x0, 0x0)
	/Users/tom/go/src/github.com/tab1293/torrent-test/vendor/github.com/anacrolix/torrent/connection.go:1142 +0x49c
github.com/anacrolix/torrent.(*Client).runHandshookConn(0xc000144000, 0xc000526c00, 0xc00035e000)
	/Users/tom/go/src/github.com/tab1293/torrent-test/vendor/github.com/anacrolix/torrent/client.go:883 +0x569
github.com/anacrolix/torrent.(*Client).outgoingConnection(0xc000144000, 0xc00035e000, 0xc0000b0aec, 0x4, 0x4, 0x4436f9a, 0x46f6ca7, 0x2, 0x0)
	/Users/tom/go/src/github.com/tab1293/torrent-test/vendor/github.com/anacrolix/torrent/client.go:713 +0x392
created by github.com/anacrolix/torrent.(*Torrent).initiateConn
	/Users/tom/go/src/github.com/tab1293/torrent-test/vendor/github.com/anacrolix/torrent/torrent.go:1723 +0x277
```

I also see tons of these errors in the logs:
`client.go:426: error accepting connection: tcp listener disabled due to proxy`
`client.go:426: error accepting connection: utp listener disabled due to proxy`

The torrent still seems to be downloading data but is interrupted by the panic before the download finishes. Are there too many failed connections being opened due to the proxy that are exhausting my system's file descriptors? The proxy works fine when directing HTTP browser traffic through it.

FWIW I see the error messages I am seeing were added here: https://github.com/anacrolix/torrent/pull/360/files
cc @sickyoon

**Comment by sickyoon** [comment]
maybe upstream connection is not closed.
I can take a look when I get some free time.

**Comment by tab1293** [comment]
I was able to get the download working by lowering my `EstablishedConnsPerTorrent` and `HalfOpenConnsPerTorrent` counts. I can confirm that most of the traffic seems to be going through my proxy. Although, in Wireshark, I see a few peer handshakes that are direct connections. Maybe your fix still is not ensuring 100% of traffic is going through the proxy? 

I still see many of the the `error accepting connection` logs as well. Do you have any idea why these are being encountered so often?

**Comment by sickyoon** [comment]
I don't have time right now to look but my guess is that underlying connection wrapped in disabledListener needs to be closed. `error accepting connection` is probably expected since all incoming connections are blocked and thrown into black hole.

**Comment by sickyoon** [comment]
@tab1293 can you come up with a way to reproduce your error so I can test it on my end?

**Comment by tab1293** [comment]
This issue is a bit harder to replicate than I originally thought. It seems to occur more often on certain torrents rather than others. I would recommend trying with a popular torrent that has a lot of peers. 

Here is an example where I was inconsistently able to reproduce the panic: 
https://gist.github.com/tab1293/7c1abeec7dd09b7ccac8ed70d45bdde5

I do notice two other potential issues:

1. Tons of accepting connection errors. I see thousands of these logs even with relatively short download sessions. What is this a byproduct of? Are we not able to open a listening connection with a proxy enabled?   
`client.go:441: error accepting connection: tcp listener disabled due to proxy`
`client.go:441: error accepting connection: utp listener disabled due to proxy`
2. I am still noticing a handful of BitTorrent handshakes that are not going through the proxy. I was able to capture these events in Wireshark.

Any insight in to these issues the above would be appreciated

**Comment by anacrolix** [comment]
https://github.com/anacrolix/torrent/pull/365#issuecomment-572881841 will probably supercede any issues here.

**Comment by anacrolix** [comment]
I think the disabled listener concept doesn't work. An accept routine is created anyway, that probably spins endlessly calling `Accept`. I think the best solution is to expedite #365.

**Comment by anacrolix** [comment]
@tab1293 what git revision of torrent are you using, and are you using Go modules?

**Comment by tab1293** [comment]
@anacrolix I am using Go modules and have tested with both `v1.11.0` and this commit ff8ce944e9e91443d45036f701934e95c9a0158d.

**Comment by tab1293** [comment]
@anacrolix even with the changes referenced in #365, will it still not be possible to seed while using a proxy? I saw a comment made by @elgatito https://github.com/anacrolix/torrent/pull/256#issue-193523016 that says even with the initial proxy support implementation, the client would **probably** not be able to seed. Is this true and if so, why?

**Comment by anacrolix** [comment]
I don't believe the comment is quite correct. With a proxy I don't believe you can *accept*, which means you will have no incoming peer connections (unless you have other connections that are listening). You can still seed however, when your client initiates outgoing connections. The Client does initiate outgoing connections, even when it requires no data locally, when seeding is enabled.

**Comment by sickyoon** [comment]
incoming connections are disabled atm and seeding still works for me.

**Comment by anacrolix** [comment]
`ProxyURL` is no longer part of `ClientConfig`. If you wish to use proxied connections, you can handle this explicitly yourself using `Client.AddDialer`, and potentially `Client.AddListener` (assuming you can receive inbound proxies connections somehow, the particulars are not relevant to `torrent`. This will fix the broken situation where having proxies made the listener situation confusing for the `Client`. Subsequently, the panic originally described should no longer be possible through any fault of `torrent`. Feel free to discuss.

**Comment by yoonst** [comment]
> `ProxyURL` is no longer part of `ClientConfig`. If you wish to use proxied connections, you can handle this explicitly yourself using `Client.AddDialer`, and potentially `Client.AddListener` (assuming you can receive inbound proxies connections somehow, the particulars are not relevant to `torrent`. This will fix the broken situation where having proxies made the listener situation confusing for the `Client`. Subsequently, the panic originally described should no longer be possible through any fault of `torrent`. Feel free to discuss.

I am revisiting this issue. Could you show me where this `Client` is?
The current Proxy implementation is only applicable to trackers which is not enough protection from ISP / legal trolls.

**Comment by anacrolix** [comment]
@yoonst I think to proceed with the solution I provided above, you want to disable entirely any default listeners on the Client, and add all your proxy dialers manually. A cursory follow-through from https://github.com/anacrolix/torrent/blob/b8e1c9539907b177a7dac66c95304c0dbe91475f/client.go#L236 would suggest that there's no configuration option to disable listeners without affecting trackers too, which might not be intentional.

Are you intending to do testing with proxied dialers again? Perhaps you could verify that it works via Client.AddDialer, and add a configuration option to ClientConfig, disabling the default socket set-up in NewClient.
