### ISSUE TITLE
How to specify files exist on my disk to be uploaded?

### ISSUE THREAD

**Issue by major1201** [anacrolix/torrent#374]
Hi:

I have no idea how to link my torrent file with the files downloaded(or maybe I'm the first one to seed) to be uploaded.

I haven't found such usage, please help.

**Comment by major1201** [comment]
Just set the `DataDir` of the ClientConfig:

```golang
cc := torrent.NewDefaultClientConfig()
cc.DataDir = "/my/serving/dir"
```

**Comment by anacrolix** [comment]
Thanks for following up your own question.
