### ISSUE TITLE
Finding available pieces for a peer

### ISSUE THREAD

**Issue by vlcty** [anacrolix/torrent#375]
Hi,

not a bug but more like "help wanted". I'm currently using your dht lib to find peers for a given info hash. This was really easy to implement thanks to your example code!

Many torrent clients out there shows you the progress/completion in percent for connected peers. When I understand the protocol right I can query a peer and ask what pieces they have. Based on total amount of pieces divided by pieces a peer has I'm able to calculate the percentage value. But after digging into this code I was not able to spot a function returning the info I want.

Am I missing something? Does this lib provide this functionality and did I just overread it? Can you hint me in the right direction?

Thanks in advance!

**Comment by james-lawrence** [comment]
the information you want is stored [here](https://github.com/anacrolix/torrent/blob/master/connection.go#L97) and [here](https://github.com/anacrolix/torrent/blob/master/connection.go#L100)

it'll be a bit of a mess to pull that up to the level you want.

**Comment by anacrolix** [comment]
@vlcty this isn't currently exposed, and should be. I think I would expose the private type `connection` or something based on it as `PeerConnection`, and expose a `Torrent.PeerConnections` method.

**Comment by anacrolix** [comment]
@vlcty are you still interested in this feature?

**Comment by vlcty** [comment]
Wow ... I somehow forgot about it. Yeah I would still be interested in this. Is there anything that changed in the past time? If not I'd dig into the code again and try my best.

**Comment by anacrolix** [comment]
I think it was implemented, in https://github.com/anacrolix/torrent/commit/ddddc63924570fb9331d8d3e0c6b18b124178db0. See https://pkg.go.dev/github.com/anacrolix/torrent?tab=doc#PeerConn.PeerPieces.

**Comment by vlcty** [comment]
Tahnk you very much!
