### ISSUE TITLE
dependency cycle: DHT depends on the torrent/iplist package and torrent depends on DHT.

### ISSUE THREAD

**Issue by james-lawrence** [anacrolix/torrent#376]
makes it impossible to decouple DHT from the torrent package due to the ranger interface (among others).

```
	"github.com/anacrolix/torrent/iplist"
	"github.com/anacrolix/torrent/metainfo"
	"github.com/anacrolix/torrent/bencode"
	"github.com/anacrolix/torrent/iplist"
	"github.com/anacrolix/torrent/logonce"
	"github.com/anacrolix/torrent/metainfo"
```

are all used by package DHT. should probably just merge dht into the torrent repo as a subpackage.

**Comment by anacrolix** [comment]
On the `dht` subpackage: https://github.com/anacrolix/torrent/commit/b68d7cd08e83ede9af5a43b6b2fd2eda9f58aba2. I think allowing using an alternative `anacrolix/dht` from this would require making a `DHT` interface for the `Client` or `Torrent` to use. I don't think I would entirely decouple that repo in the short term however, as it is the default implementation. See also https://github.com/anacrolix/torrent/issues/266.

**Comment by anacrolix** [comment]
@james-lawrence take a look at https://github.com/anacrolix/torrent/commit/afe4d8795daa14a80d3d1ed1e72d1261f566a1b7 for a start in this direction.

**Comment by anacrolix** [comment]
Maybe it would be possible to create separate interfaces in each of those repositories. However I don't believe `anacrolix/dht` will be removed from `torrent@v1` as a dependency, since it is the default. Note that you can now you use your own DHT implementation if you prefer.

**Comment by james-lawrence** [comment]
@anacrolix sorry never responded, I forked your library awhile ago. I only opened this to let you know about that issue.

**Comment by anacrolix** [comment]
I haven't run into an issue due to this, so I will close it.
