### ISSUE TITLE
No space left on device should't crash an app

### ISSUE THREAD

**Issue by axet** [anacrolix/torrent#377]
Hello!

Connection::receiveChunk() shuold not crash an app if it is an recoverable error. Just stop/pause the torrent.

`E/Go: panic: error writing chunk: write failed: ENOSPC (No space left on device)`

```go
	if err != nil {
		panic(fmt.Sprintf("error writing chunk: %v", err))
		t.pendRequest(req)
		t.updatePieceCompletion(pieceIndex(msg.Index))
		return nil
	}
```

Second crash "short write"

**Comment by anacrolix** [comment]
Hi @axet. I haven't decided how to handle this error condition. It's not easy to filter out particular errors in Go as they're so inconsistent and weakly typed. It used to be that we'd log these errors and continue, but it led to the client downloading constantly and never getting anywhere.

A good compromise might be to pause the `Torrent` as you suggest, and allow callers to access the error message?

**Comment by axet** [comment]
My app has torrent state, when you hit "Play/Download" it shows last error: "files altered" for example. It may be extended to basic IO errors as well, no space left, unable to create file / folder. But it hard to implement when app crashes ;)

**Comment by anacrolix** [comment]
As a workaround, you might disconnect the peer to prevent further data in the meanwhile. There is some placeholder code in place to support pausing, but I haven't looked into it further.

**Comment by anacrolix** [comment]
I've expose a default handler and hook for storage write errors in https://github.com/anacrolix/torrent/compare/issue377.

**Comment by anacrolix** [comment]
This is now in master. Feel free to comment.

**Comment by gitpubber** [comment]
> I've exposed a default handler and hook for storage write errors in https://github.com/anacrolix/torrent/compare/issue377.

@anacrolix can you please point me to the resource?

**Comment by gitpubber** [comment]
@anacrolix ,how to do this? which is the commit that i need to refer?

**Comment by anacrolix** [comment]
@gitpubber I think it's bae791a5a290d08d58acc4892af279d804ebc523.

**Comment by gitpubber** [comment]
@anacrolix , thanks
