### ISSUE TITLE
Outgoing connection local ports

### ISSUE THREAD

**Issue by avengermsoft** [anacrolix/torrent#378]
The BTServer is running on port 22491 (ListenPort). DHT is on.
Where do the connections to ports 39298 and 39668 come from?

![изображение](https://user-images.githubusercontent.com/18549626/74611048-9a175f80-5109-11ea-80e6-21d70f8bc766.png)

**Comment by elgatito** [comment]
@avengermsoft ListenPort is for incoming connections.
Outgoing should be going from a random available port.

@anacrolix right?

**Comment by avengermsoft** [comment]
Is it possible to limit the range of outgoing ports?

**Comment by anacrolix** [comment]
![image](https://user-images.githubusercontent.com/988750/74704952-41a9a480-5266-11ea-9aa9-582f53224253.png)

@elgatito that's right. @avengermsoft yes I believe so. It would be easier to intercept the dial calls to provide custom behaviour like this when the dialer/listener Client interfaces are refactored per #365.

**Comment by anacrolix** [comment]
@avengermsoft @elgatito the latest version should allow you to specify your own `Dialer` that will achieve this behaviour.

**Comment by avengermsoft** [comment]
Do you have any examples?

**Comment by anacrolix** [comment]
@avengermsoft You can add a custom dialer with [`Client.AddDialer`](https://pkg.go.dev/github.com/anacrolix/torrent?tab=doc#Client.AddDialer). You could use a [`NetDialer`](https://pkg.go.dev/github.com/anacrolix/torrent?tab=doc#NetDialer) and set `LocalAddr` in its [`net.Dialer`](https://golang.org/pkg/net/#Dialer), or create your own `Dialer` that uses [`net.DialTCP`](https://golang.org/pkg/net/#DialTCP) internally.

**Comment by anacrolix** [comment]
Since this is now possible, I'll close this. Feel free to keep asking questions or reopen if it doesn't work.
