### ISSUE TITLE
Listen on the interface

### ISSUE THREAD

**Issue by avengermsoft** [anacrolix/torrent#379]
Do you plan to listen on the interface?

Sample: "ListenInterface br-lan". I now have 4 ips addresses on the interface br-lan:
<pre>4: br-lan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether dc:a6:32:0c:53:b4 brd ff:ff:ff:ff:ff:ff
    inet 192.168.97.98/27 brd 192.168.97.127 scope global br-lan
       valid_lft forever preferred_lft forever
    inet6 2a05:3580:xxxx:xxxx:dea6:32ff:fe0c:53b4/64 scope global dynamic noprefixroute
       valid_lft 13644sec preferred_lft 8244sec
    inet6 2a05:3580:xxxx:xxxx::98/128 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::dea6:32ff:fe0c:53b4/64 scope link
       valid_lft forever preferred_lft forever
</pre>

**Comment by anacrolix** [comment]
@avengermsoft how would you generally do this in other languages? I believe you want to use https://golang.org/pkg/net/#InterfaceByName, https://golang.org/pkg/net/#Interface.Addrs, and https://github.com/anacrolix/torrent/pull/365 for this.

**Comment by avengermsoft** [comment]
C++ example
`struct ifreq ifr;

memset(&ifr, 0, sizeof(ifr));
snprintf(ifr.ifr_name, sizeof(ifr.ifr_name), "eth0");
if (setsockopt(s, SOL_SOCKET, SO_BINDTODEVICE, (void *)&ifr, sizeof(ifr)) < 0) {
    ... error handling ...
}`

**Comment by anacrolix** [comment]
@avengermsoft do you already have a method to listen on the interface in the way you desire in Go? If you do, and it isn't exposed by the `ClientConfig`, you'll be interested in https://github.com/anacrolix/torrent/issues/380.

**Comment by avengermsoft** [comment]
I found the code, but I don’t understand how to adapt it.
```
func bindToIf(conn net.Conn, interfaceName string) {
    ptrVal := reflect.ValueOf(conn)
    val := reflect.Indirect(ptrVal)
    //next line will get you the net.netFD
    fdmember := val.FieldByName("fd")
    val1 := reflect.Indirect(fdmember)                                   
    netFdPtr := val1.FieldByName("sysfd")                                           
    fd := int(netFdPtr.Int())
    //fd now has the actual fd for the socket
    err := syscall.SetsockoptString(fd, syscall.SOL_SOCKET,
                syscall.SO_BINDTODEVICE, interfaceName)
    if err != nil {
        log.Fatal(err)
    }
```

**Comment by anacrolix** [comment]
You can create your own [`Listener`](https://pkg.go.dev/github.com/anacrolix/torrent?tab=doc#Listener), and add it with [`Client.AddListener`](https://pkg.go.dev/github.com/anacrolix/torrent?tab=doc#Client.AddListener). The specifics for binding to an interface are outside the scope of this repo. I wasn't able to find a complete example online, I expect that after the bind (`setsockopt`) above, you should be able to fit the `net.Conn` into a `net.Listener`. You should also be able to create a raw, unbound `net.Conn` to pass to the above function.

You could also just listen explicitly on all of the IPs of the interface you listed, and then add them all with `Client.AddListener`.

**Comment by anacrolix** [comment]
I believe this can be closed. Feel free to field more questions.
