### ISSUE TITLE
Issues with internal packages when sending pull request

### ISSUE THREAD

**Issue by 0x4139** [anacrolix/torrent#38]
https://github.com/golang/go/issues/11307
```go
  imports github.com/anacrolix/torrent/internal/pieceordering: use of internal package not allowed
```

**Comment by anacrolix** [comment]
Could you include the command you ran that gave the error?

**Comment by hareesh-blippar** [comment]
imports github.com/bitly/nsq/internal/lookupd: use of internal package not allowed

I ran
$ go build

**Comment by anacrolix** [comment]
What is your go version, and from what directory did you run this?

**Comment by hareesh-blippar** [comment]
I used go 1.5.1 and ran it from the main project directory called "project"

The imports are made from a file in a subfolder called "project/subfolder/myfile.go"

**Comment by anacrolix** [comment]
What's your build tool, are you using godeps or gb or something?

**Comment by anacrolix** [comment]
I'm sorry, I need a lot more information to go on.
