### ISSUE TITLE
Lost download progress when resume a stopped task

### ISSUE THREAD

**Issue by hichenming** [anacrolix/torrent#382]
Hi, if I download a big file, such as 6 Gb, when download 1 Gb, I stopped the program to pause the task, and when I restart the program, it will resume download from 220 Mb, so huge content that already downloaded earlier are lost. 

So why that happens, and is there any methods to improve?

**Comment by anacrolix** [comment]
Yes, the storage implementation won't track completed chunks, only entirely completed pieces. Are you using `cmd/torrent`? I will check if any of the download strategies will aid in this.

**Comment by anacrolix** [comment]
The default timeout request strategy should be optimal for this situation. What git revision, or version of `torrent` are you on?

**Comment by hichenming** [comment]
Yes, I'm using cmd/torrent, and compile from latest master branch, commit id is : ddc61845acb725707781d1acd756a3a60c60c8d0

**Comment by anacrolix** [comment]
Thanks. Since that should be using the request strategy I mentioned, it might be easiest to augment the `cmd/torrent` output to determine how many pieces, vs. the total downloaded data is present when the download is stopped, to determine the degree of loss.

**Comment by anacrolix** [comment]
I've done this (https://github.com/anacrolix/torrent/commit/9fb9112d8fd952b9ad6e1324210917a709064340#diff-5dbb4aaf476a0c0d86f3e94c43fca3f6R57), it would appear that the unbiased piece ordering in use probably changes when the pendingPiece PriorityBitmap is altered, meaning the preferred pieces shift around, unnecessarily increasing the number of partial pieces.

**Comment by anacrolix** [comment]
@hichenming You should find that `cmd/torrent` is now much less wasteful between sessions.

**Comment by hichenming** [comment]
@anacrolix Yes, thanks a lot.
