### ISSUE TITLE
Client get locked very long time when resume a big file task

### ISSUE THREAD

**Issue by kylege** [anacrolix/torrent#389]
When resume a torrent task to download very big files, such as 36 GB, the client will be locked for a long time( over 1 minute ), and other torrent tasks can't do anything during the client lock.

Torrent.SetInfoBytes  call   client.lock  and  client.unlock, then call torrent.setInfoBytes, will run into torrent.onSetInfo, the onSetInfo method can be very slow.

I think maybe it's better that the client won't be locked when check the torrent task completion?

**Comment by anacrolix** [comment]
@hichenming would you have an idea of how many files, pieces, piece size etc. your torrent is? Do you want to send me the torrent info privately if you can't share? What storage backend are you using, and are you calling `Torrent.SetInfoBytes` manually yourself?

**Comment by hichenming** [comment]
Hi, I think i have found out the reason that torrent.onSetInfo run slow, I rewrite a different PieceCompletion, and it is much more slow than boltdb.

I test the torrent file with original PieceCompletion solution, the problem just disappeared.

You can reproduce the problem, by set db.NoSync = false in NewBoltPieceCompletion, then download a big file, such as  https://rarbgprx.org/torrent/bizear2

**Comment by hichenming** [comment]
Maybe it's better to use `t.cl.rlock()` instead of `t.cl.lock` in `func (t *Torrent) SetInfoBytes` ?

**Comment by anacrolix** [comment]
Sorry I haven't had a chance to look at this yet.

**Comment by anacrolix** [comment]
@kylege any update?

**Comment by kylege** [comment]
> 

Not tested yes, but i think `DisableInitialPieceCheck` will do the trick.

**Comment by anacrolix** [comment]
Okay I'll close pre-emptively, feel free to reopen if it doesn't fix the problem.
