### ISSUE TITLE
Ability to prioritize blocks/pieces/chunks/files when downloading

### ISSUE THREAD

**Issue by voxadam** [anacrolix/torrent#39]
It would be very beneficial in many applications if anacrolix/torrent had a method for setting the download priority of individual blocks/pieces/chunks (BitTorrent terminology can be somewhat confusing, if not poorly defined in the first place).

While I understand the objections many people have related to selective or "streaming" as there can be a negative effect to the health of the greater swarm as a whole. The thing is, in many cases BitTorrent is used in controlled environments where it's known in advance that such an tactic is perfectly acceptable as it's already been established that there are enough clients with complete copies of the files being shared to sustain a healthy swarm.

anacrolix/torrent isn't a mainstream file sharing client in the same way that µTorrent or Vuze are; it's a library to be incorporated into larger projects where the developers are (hopefully) fully capable of understanding the ramifications of granular prioritization such as this.

**Comment by anacrolix** [comment]
Hi Adam, this is already supported through https://godoc.org/github.com/anacrolix/torrent#Torrent.SetRegionPriority and https://godoc.org/github.com/anacrolix/torrent#File.PrioritizeRegion. There's also a helper, https://godoc.org/github.com/anacrolix/torrent#Torrent.DownloadAll. These do what you'd expect: no ordering is assumed between regions of the same priority, and even with different priorities pieces may be favoured if they have higher priority but it will still mix it up.

**Comment by anacrolix** [comment]
Let me know if you have some particular need that isn't met.

**Comment by voxadam** [comment]
I'm terribly sorry. I'd say that I have no idea how I missed those functions but I'm fairly sure it's fairly sure it has something to do with the fact that it's 0318 in the morning here and I should have gone to bed a couple hours ago.

Feel free to close this erroneous issue. Again, sorry for the noise.
