### ISSUE TITLE
Custom peers

### ISSUE THREAD

**Issue by vintikzzz** [anacrolix/torrent#398]
Hi!
Is it possible to add some custom peer, for example one that will get pieces from S3-bucket or another one that can get pieces from HTTP-server? Is it possbile to add my custom peer implementaion?

**Comment by anacrolix** [comment]
Web seeding isn't currently supported. You can implement your own protocol if you implement `Dialer` or `Listener` in the `torrent` package, if those expose the BitTorrent peer wire protocol. It's not possible to implement your own peer. I suspect you mean the remote part that belongs in `PeerConn`?

**Comment by vintikzzz** [comment]
Yes it looks like `PeerConn `, it will be great if there will be possible to add my own `PeerConn` to torrent. But as I can see `func (t *Torrent) addConnection(c *PeerConn) (err error) {` is not public and there it no public interface for `PeerConn`. Is it good idea anyway? Or there might be better approach to implement my scenario?

**Comment by anacrolix** [comment]
I don't think the PeerConn analogy is correct for alternative sources, although it could be made to work. It would be a lot of work. You might be best to wait for, or implement yourself, web seeding for this.

**Comment by vintikzzz** [comment]
Ok, thank you for response. Is there any plans to implement web seeding?

**Comment by anacrolix** [comment]
Web seeding is tracked at https://github.com/anacrolix/torrent/issues/116.

**Comment by anacrolix** [comment]
Since webseeding is implemented, this is a lot closer to being possible. @vintikzzz Have you had a look at the webseeding code? Are you still interested in this feature?

**Comment by vintikzzz** [comment]
No! Thanks! I have managed it in a little bit another way.

**Comment by anacrolix** [comment]
@vintikzzz What path did you end up taking?
