### ISSUE TITLE
const initializer "github.com/anacrolix/log".Debug is not a constant

### ISSUE THREAD

**Issue by skinner12** [anacrolix/torrent#400]
I've updated the package and now I can't compile my app.

I get this error:

`#github.com/anacrolix/torrent

github.com/anacrolix/torrent@v1.15.0/client.go:149:7: const initializer "github.com/anacrolix/log".Debug is not a constant`

**Comment by anacrolix** [comment]
What update command did you run? `go get github.com/anacrolix/torrent@latest` or something else?

**Comment by anacrolix** [comment]
Let me know what command you run. I've released `v1.15.1` to fix this and some other minor issues.
