### ISSUE TITLE
Upload stalls when seeding through WebTorrent 

### ISSUE THREAD

**Issue by 2m** [anacrolix/torrent#402]
I used `cmd/torrent -seed` to download and then seed a torrent that was initially not available on the WebTorrent trackers.

I use a magnet URI with `&tr=wss://tracker.openwebtorrent.com` attached.

When download was complete I opened `instant.io` and pasted in the magnet URI. The download started, but after half a megabyte it stalled:

![image](https://user-images.githubusercontent.com/422086/80863374-7c778200-8c84-11ea-8c0a-e2fd050a4b7c.png)

Similar thing happened in `btorrent.xyz`:

![image](https://user-images.githubusercontent.com/422086/80863408-b9437900-8c84-11ea-97ec-3cf4476cf575.png)

I see the following in the output of `cmd/torrent` from time to time which could be related:

```
2020-05-02T14:53:28+0300 INFO  tracker_client.go:98: tracker client for "wss://tracker.openwebtorrent.com": websocket instance ended: read message error: websocket: close 1006 (abnormal closure): unexpected EOF
```

**Comment by anacrolix** [comment]
What version of `anacrolix/torrent` are you using? That error seems to occur because the websocket bittorrent trackers expect an announce once a minute, which this client doesn't do, and we get dropped (and promptly reconnect). It shouldn't be related.

**Comment by 2m** [comment]
I used `go get` yesterday to install the command. So it was latest version.

**Comment by anacrolix** [comment]
Thanks. I believe I've found the problem, I'll have a fix soon.

The latest `go get` through Go modules, shouldn't give you a version that has webtorrent support, that's only in the `master` and `webtorrent` branches at present.

**Comment by 2m** [comment]
I used `go get github.com/anacrolix/torrent/cmd/torrent`. Not sure how to check the version of the binary I have installed.

**Comment by anacrolix** [comment]
Thanks for the report. Very obscure bug!

**Comment by 2m** [comment]
Thanks for fixing it so quick!

Is there a way to try out the latest version with `go get`? Or do I need to clone the repo and build it from there?

**Comment by anacrolix** [comment]
Possibly `go get github.com/anacrolix/torrent/cmd/torrent@master`.

**Comment by anacrolix** [comment]
There's also some popular helpers like `gobin`, but I don't use those myself.
