### ISSUE TITLE
request: magnet -> torrent

### ISSUE THREAD

**Issue by joshuarli** [anacrolix/torrent#403]
Hi @anacrolix, this is pretty great software. I try and avoid GUI software as much as possible, and was using aria2 for the longest time. It also works great, just that it's C++ and the build is pretty complicated compared to go programs (well, there's still C++ involved in torrentfs, but it's a lot better, and seems to be yours). So thanks for writing this!

`torrent` is good, and I especially like `torrentfs` because last I checked, it wasn't possible (or at least not easy at all) to selectively download files.

The remaining piece of the puzzle is magnet -> torrent. Currently I'm using `aria2c --bt-metadata-only=true --bt-save-metadata=true MAGNET_LINK` to download the metadata file, which then works great with `torrentfs`.

This is just a feature request for visibility & your consideration. Thanks again!

**Comment by anacrolix** [comment]
@joshuarli You can use `cmd/magnet-metainfo` in this repo. The utilities provided are a bit old and crufty, I'm hoping at some point to create a utility `torrent` or `torrent-cli` that performs a lot of helpful operations.

**Comment by joshuarli** [comment]
Oh, wasn't aware of that (was just going off the readme) - it works great. Thanks again!
