### ISSUE TITLE
possible to use without dht?

### ISSUE THREAD

**Issue by sjpotter** [anacrolix/torrent#406]
From reading the code, it doesn't seem like its friendly to be used without a dht.  Is this correct?  i.e. while one can load a torrent manifest, one can't specify the storage implementation to be used, that can only be done if one only provided the infohash (and hence dependent on the dht to download the rest of the manifest).

which makes m wonder, would it even respect torrent flags that specify that it should be private? i.e. while the documentation says that it supports BEP27 and metainfo has a Private flag, this flag isn't actually used anywhere (i.e. which makes me wonder how one can claim it supports BEP27)

**Comment by anacrolix** [comment]
> From reading the code, it doesn't seem like its friendly to be used without a dht. Is this correct? 

No, you can disable the builtin default DHT with [`ClientConfig.NoDHT`](https://pkg.go.dev/github.com/anacrolix/torrent?tab=doc#ClientConfig). You can also use your own DHT implementations if you wish.

> i.e. while one can load a torrent manifest, one can't specify the storage implementation to be used, that can only be done if one only provided the infohash (and hence dependent on the dht to download the rest of the manifest).

No that doesn't seem correct. The client methods for adding torrents aren't very nice, as discussed in other issues, but you should definitely be able to specify your own storage while adding a Torrent, and its metainfo/info bytes at your leisure.

> which makes m wonder, would it even respect torrent flags that specify that it should be private? i.e. while the documentation says that it supports BEP27

Where does it say this?

> and metainfo has a Private flag, this flag isn't actually used anywhere (i.e. which makes me wonder how one can claim it supports BEP27)

I don't believe BEP27 is supported. The field is exposed but unused.

**Comment by sjpotter** [comment]
> i.e. while one can load a torrent manifest, one can't specify the storage implementation to be used, that can only be done if one only provided the infohash (and hence dependent on the dht to download the rest of the manifest).

i see 5 AddTorrent Functions.

1. AddTorrent(MetaInfo)
2. AddTorrentInfoHashWithStorage(hash, storageImpl)
3. AddTorrentInfoHash(hash)
4. AddTorrentFromFile(filename)
5. AddTorrentSpec

and now I see.  was confused.  I have to use AddTorrentSpec.  that wsa unclear

> >   which makes m wonder, would it even respect torrent flags that specify that it should be private? i.e. while the documentation says that it supports BEP27
>
> Where does it say this?

right here https://github.com/anacrolix/torrent/blob/master/doc.go#L28

**Comment by anacrolix** [comment]
Thanks. The field is exposed in the metainfo, but it's not used in the client. That's probably not sufficient to claim support.

**Comment by sjpotter** [comment]
in looking at the code, it seems the private flag would be pretty easy to support

1) in AddTorrentInfoHashWithStorage() just don't start the dht thread

2) in sendInitialMessages() treat it if the client disables PEX

3) something similar might be needed for local service discovery (but can't see if that's implemented in the code as it is)

thoughts?

**Comment by anacrolix** [comment]
I think you've covered most of it. Tracker handling in anacrolix/torrent doesn't follow the spec, but most clients don't to my knowledge: All trackers are used at all tiers. The BEP would require that wasn't the case. As a simplification, if PEX is disabled entirely for private torrents, this doesn't have to change. LSD isn't currently implemented. There is a `Trusted` field for adding peers that will allow us to circumvent the private flag as implemented per the BEP for testing and other environment-specific circumstances.

**Comment by anacrolix** [comment]
I think any further discussion on BEP 27 should move to its own issue.

**Comment by anacrolix** [comment]
Did you have any further issue here? I think we can close this in favour of an issue regarding implementing BEP 27 if that's what you want?
