### ISSUE TITLE
How to correlate files and pieces?

### ISSUE THREAD

**Issue by RaeesBhatti** [anacrolix/torrent#407]
I'm trying to implement an S3 storage backend. The idea is to temporarily download pieces and then as soon as each piece is complete, upload them to the cloud storage and delete them from local disk.
I'm editing file storage and building the required functionality on top of that. I can start the multipart upload for all of the files on `CreateNativeZeroLengthFiles`:
https://github.com/anacrolix/torrent/blob/6ea0344efd807ab9a3829945ea9760c65223ba72/storage/file.go#L104-L108
S3 needs to know the part number, so that, each part can be uploaded individually. I don't know BitTorrent extensively, so, I was wondering what would be the proper way to find out how many torrent pieces a file spans. Also, how do I correlate a piece to its file? Then I can add some code to the `Competition` method to upload the data in that piece to the corresponding files.
https://github.com/anacrolix/torrent/blob/7dd532d46fa84144c63e5ad6aa4d976a08d0b25b/storage/file_piece.go#L24-L30

**Comment by RaeesBhatti** [comment]
Figured it out

**Comment by botallen** [comment]
@RaeesBhatti  I am trying to achieve similar for google drive. Can you tell more about how you did that ?
