### ISSUE TITLE
How to use a username and password for proxy?

### ISSUE THREAD

**Issue by ChadTaljaardt** [anacrolix/torrent#409]
I want to use this with a sock5 proxy which required a username and password authentication. Does this work with this package.

**Comment by anacrolix** [comment]
Do you mean for the BitTorrent connections, or to trackers/webseeds, or all of the above?

For BitTorrent connections, I recently removed the builtin proxy config and added the ability to add your own [dialers](https://pkg.go.dev/github.com/anacrolix/torrent?tab=doc#Client.AddDialer) and [listeners](https://pkg.go.dev/github.com/anacrolix/torrent?tab=doc#Client.AddListener), which internally you can perform whatever kind of proxying etc. you want.

**Comment by ChadTaljaardt** [comment]
I think all of the above, so everything should go through the proxy, and if the proxy gets disconnected the torrents should not connect through your normal internet. 

something similar to this:

https://support.nordvpn.com/Connectivity/Proxy/1087802472/Proxy-setup-on-qBittorrent.htm

**Comment by anacrolix** [comment]
It can be done, you'll need to configure the `ClientConfig` carefully, and manage the `Dialers` and `Listeners`.

**Comment by ChadTaljaardt** [comment]
Okay will look into it, do you have any examples of this?

I will close this issue in the mean time as i got the answer i was looking for 👍 

Awesome project btw, i really appreciate it!

**Comment by anacrolix** [comment]
I'm sorry I don't currently have any examples.
