### ISSUE TITLE
Not seeing peer connections occasionally on download start

### ISSUE THREAD

**Issue by tab1293** [anacrolix/torrent#413]
I often run in to this issue where downloads will not start on random occasions for a torrent that is definitely being seeded by many peers. 

Below is the client code I am using to initiate downloads:

```go
mi, err := metainfo.Load(torrentFile)
if err != nil {
	return err
}

info, err := mi.UnmarshalInfo()
if err != nil {
	return err
}

cfg := torrent.NewDefaultClientConfig()
cfg.DataDir = "/data"
cfg.DefaultRequestStrategy = torrent.RequestStrategyFastest()

if info.Private != nil && *info.Private {
	cfg.DisablePEX = true
	cfg.NoDHT = true
}

cfg.Debug = true

c, err := torrent.NewClient(cfg)
if err != nil {
	return err
}
defer c.Close()


t, err := c.AddTorrent(mi)
if err != nil {
	return err
}

<-t.GotInfo()

for _, f := range t.Files() {
	f.Download()
}

```

I have attached debug logs of the client code run on the same torrent file in close succession. You can see a lack of logs from `peerconn.go` in the `no_download` log file.

[download_ok_anacrolix.log](https://github.com/anacrolix/torrent/files/4752694/download_ok_anacrolix.log)
[no_download_anacrolix.log](https://github.com/anacrolix/torrent/files/4752695/no_download_anacrolix.log)

Is there some issue with the way I am initiating the client here?

**Comment by anacrolix** [comment]
It looks okay. If there are issues establishing connections with peers after the first few announces at startup, this could cause a delay while the announce intervals expire and you can try those peers again. Would you be able to share the infohash, or torrent file? You can send it privately if you prefer. What revision/version of anacrolix/torrent are you using?

**Comment by tab1293** [comment]
After capturing some network traffic for each attempt at downloading, it seems that the tracker I am using is not returning a peer list for subsequent announce requests. This occurs when trying to download an additional file from a multi-file torrent shortly after the first file was downloaded. I emailed you about how to get access to the specific tracker I am using. 

WRT to the announce intervals you mentioned, if I am starting a new client instance per download would an announce still be delayed because of the expiration from the prior instance? Maybe some session data in the working directory I can clear?

I am using v1.17.1. 

Thanks for the help!

**Comment by anacrolix** [comment]
@tab1293 I don't believe trackers should return empty lists after the first announce. That seems like an optimization attempt on the side of the tracker server.

anacrolix/torrent does not cache peer addresses between connection attempts etc., which could ultimately be the correct fix here. That is, peer addresses are accumulated in the client, and then purged when outbound connections are attempted. Those addresses are not put back unless they're rediscovered later, such as by a subsequent announce/DHT result/PEX exchange etc. If you only have a limited number of peers for a torrent, and you lose the ability to discover them through the aforementioned means, you will no try to reconnect after connections are dropped.

**Comment by anacrolix** [comment]
Are you creating a new Client between completing one file, and starting another? That would include letting a process complete, and then starting a new instance with different files selected. How long are you waiting between the completion of the first files, and starting the new ones?

**Comment by anacrolix** [comment]
Try with revision c81da2d5ee200de6175fe508d3a2ac46d6146a8d. I believe your private trackers are returning empty peer lists, which I think is mentioned as the behaviour to be used when clients behave badly (such as in this case announcing more often than the returned interval). Unfortunately the interval is not tracked across process restarts, but with the fix I've provided, the client will no longer harass the trackers and eventually get some more peers. 

The behaviour previously would have resulted in peers only on the first announce, and never again without a 30 minute pause in activity.

**Comment by tab1293** [comment]
> Are you creating a new Client between completing one file, and starting another? 

Yes I am.
> How long are you waiting between the completion of the first files, and starting the new ones?

A few minutes or so.

To your point about a potential solution being to cache peer addresses between connection attempts, would this manifest as some "session file" that's stored on disk? So client instantiations could read this file and bootstrap connections to previously seen peer addresses? I'm assuming this could also track the announce interval across clients too. Curious to know if this is a feature you would plan on implementing. 

Thank you for this (https://github.com/anacrolix/torrent/commit/c81da2d5ee200de6175fe508d3a2ac46d6146a8d) remedy! I will give it a try and confirm if peers are being discovered after a short amount of time.

**Comment by anacrolix** [comment]
I have no plans to implement this, but yes that's exactly what would be required. Thanks for seeing this issue through and the tracker invite. I'll close this now, let's reopen if it comes up again. I'll make an issue to track the tracker and peer "session".
