### ISSUE TITLE
Local Peers can not be discover ?

### ISSUE THREAD

**Issue by ctwyw** [anacrolix/torrent#418]
I can already download the magnet. these is another question. I build serval server on the PublicIP4 and then build two client behind the NAT router . but could not see them in the DHT node. UNPN is start already. the clients can not share with each other.but the server work well yet. What can I do in this case ?

```
Listening on 0.0.0.0:63333
Nodes in table: 5 good, 5 total
Ongoing transactions: 0
Server node ID: e0cb86882625a25b8a83002f21cd1f5c46*****

b# node id                                  addr                 anntok last query last response cf
0  2572c85bdb9e52254e629285f7eb329075e***** *.*.*.*:40001  20     never      46s ago       0
0  1a6e0b237b73a79091efd6ca8572c06c9fa***** *.*.*.*:40002  20     never      45s ago       0
1  ae614ab3fc2288a8607fb5264e1cef6d7b4***** *.*.*.*:40002   20     never      45s ago       0
1  9d415d2479966acd83c3b3446cbb97a209f***** *.*.*.*:40002 20     never      45s ago       0
1  9730ca99ccae7eb8d243846063fe951326f***** *.*.*.*:40002    20     never      45s ago       0
```

I saw this in the torrent status
`error announcing: reading from socket: read udp4 192.168.199.229:64718->*:40002: i/o timeout`

**Comment by anacrolix** [comment]
There's a spec for local peer discovery that hasn't been implemented. I'm not sure why your DHT servers are unable to connect to each other. Ensure they have different peer IDs, and have different public port numbers outside the NAT.

**Comment by ctwyw** [comment]
Does that mean I should announced the public port and the public ip  to other peers in the DHT ?

**Comment by anacrolix** [comment]
Maybe I misunderstood. Are you running these DHT nodes entirely on your private network? Did you intend for them not to participate on the global network?

**Comment by ctwyw** [comment]
yes, in the private network. It can upload with not NAT , but can not upload inside the NAT.

**Comment by ctwyw** [comment]
Hello,  @anacrolix . It was because local ISP banned the BT-DHT protocol. I fix it by using a messy protocol :)

This leads to another question.  how to use DHT behind Port Restricted NAT or other NAT :( 

Thank you for helping me, best wish!
