### ISSUE TITLE
Support BEP-52: BitTorrent v2

### ISSUE THREAD

**Issue by jpillora** [anacrolix/torrent#424]
Hey Matt, are there plans to support http://bittorrent.org/beps/bep_0052.html ? See also https://blog.libtorrent.org/2020/09/bittorrent-v2/

**Comment by anacrolix** [comment]
Yes, thanks for highlighting that. Things are looking positive with with the blog release, and some of the advantages are more apparent now. The original issue is at https://github.com/anacrolix/torrent/issues/175.

**Comment by jpillora** [comment]
Ah sorry for the repost - cool looks good 👍
