### ISSUE TITLE
panic in utp ackSyn()

### ISSUE THREAD

**Issue by luodw** [anacrolix/torrent#425]
hello, our p2p is based on anacrolix/torrent. In recent days, our p2p restart accidentally.  see the log，we found panic in https://github.com/anacrolix/utp/blob/master/socket.go#L493
![image](https://user-images.githubusercontent.com/14847074/93457858-1da06580-f912-11ea-83db-81b08b6d7687.png).

I found incoming and outgoing conn will both add to socket.conns(map\[connKey\]*Conn,  when accept a incoming conn, it will add to socket.conns，if socket.conns already has the same conn, it will panic.  is there must be panic？or is there something wrong?

ps： we use both tcp and utp 

![image](https://user-images.githubusercontent.com/14847074/93459930-1464c800-f915-11ea-9a3e-54a1b89b5254.png)

**Comment by anacrolix** [comment]
It's recommend to use https://github.com/anacrolix/go-libutp instead. Could you change to that implementation?

**Comment by luodw** [comment]
> It's recommend to use https://github.com/anacrolix/go-libutp instead. Could you change to that implementation?
 Thanks for your reply, I will have a try

**Comment by anacrolix** [comment]
@luodw do you have an update? Did you switch to go-libutp? You can open a PR against anacrolix/utp if you have found a workaround.

**Comment by luodw** [comment]
> @luodw do you have an update? Did you switch to go-libutp? You can open a PR against anacrolix/utp if you have found a workaround.

@anacrolix I use go-libutp and fix the issue.

**Comment by philrhc** [comment]
i just ran into this while scaling the testing of BEP14 onto more machines:
 ```
panic: :|

goroutine 24 [running]:
github.com/anacrolix/utp.(*Socket).ackSyn(0xc000210000, {0xc108?, 0x51f0?, {0xc002747548?, 0x11fd560?}})
	/go/pkg/mod/github.com/anacrolix/utp@v0.2.0/socket.go:494 +0x365
github.com/anacrolix/utp.(*Socket).Accept(0xc000210000)
	/go/pkg/mod/github.com/anacrolix/utp@v0.2.0/socket.go:513 +0x89
github.com/anacrolix/torrent.(*Client).acceptConnections(0xc00013ea08, {0x7ffa0b45f510, 0xc000099260})
	/go/pkg/mod/github.com/philrhc/torrent@v0.0.0-20250529083202-77ef86370fa0/client.go:548 +0x50
created by github.com/anacrolix/torrent.NewClient in goroutine 1
	/go/pkg/mod/github.com/philrhc/torrent@v0.0.0-20250529083202-77ef86370fa0/client.go:308 +0x1689

```
some things:
- i see that the anacrolix/utp dependency is being pulled in at 0.2.0 even though go.mod and go.sum have 0.1.0, i'm not sure why this happened.
- is go-libutp a drop in replacement? Why is anacrolix/utp still being used? https://github.com/anacrolix/torrent/blob/1e3f1bf041caed8db098ee899d0625b599a98f47/go.mod#L26

**Comment by anacrolix** [comment]
Absolutely don't use anacrolix/utp. I think it's only there if CGO isn't available.
