### ISSUE TITLE
How can i see a bunch of downloads by torrentfs

### ISSUE THREAD

**Issue by caryyu** [anacrolix/torrent#432]
Since the document shows how a single file can be monitored under the terminal environment by using `pv`, how can i use pv for multiple files or a directory to show the downloading status?  If there's an overview about a list of downloading, that would be great.

**Comment by anacrolix** [comment]
There is the client status, which is put to the `/` http path here: https://github.com/anacrolix/torrent/blob/master/cmd/torrentfs/main.go#L98-L101. If you run with GOPPROF=http, there'll be a log message to tell you where the http handler is exposed.

I don't think there's any status exposed by the torrentfs, however it could be done by exposing a special file in the FS, like how it's done in the linux kernel with procfs.

Note that torrentfs downloads on demand, you don't have to "wait" for data before trying to use it, but I expect you're aware of that.

**Comment by caryyu** [comment]
Thanks for your output, I will go through this `GOPPROF` env-var later to see if it(https://github.com/anacrolix/torrent/blob/master/client.go#L119) can meet my requirement

**Comment by caryyu** [comment]
According to my initial lookup, This is exactly what I wanted, there's still some printing formats needing to be customized to suit my personal taste, thanks for your help

**Comment by caryyu** [comment]
@anacrolix Do you know any way to turn downloading on-demand to immediate-do After a torrent file gets moved to the mounted folder
