### ISSUE TITLE
Wrong type of arguments to formatting function

### ISSUE THREAD

**Issue by ucwong** [anacrolix/torrent#434]
![image](https://user-images.githubusercontent.com/22344498/98433812-8da6bd00-2105-11eb-886c-3aac8b2893af.png)
https://github.com/CortexFoundation/CortexTheseus/security/code-scanning/21?query=ref%3Arefs%2Fpull%2F818%2Fhead

**Comment by anacrolix** [comment]
This belongs upstream at https://github.com/bittorrent/libutp.

**Comment by anacrolix** [comment]
@ucwong could you link or describe whatever action you took next so there's some continuity for this issue? Thanks
