### ISSUE TITLE
Logging even after discarding logs

### ISSUE THREAD

**Issue by imadr** [anacrolix/torrent#441]
I make a client with the default config but with logging discarded:
```
package main

import (
	torrentlogger "github.com/anacrolix/log"
	"github.com/anacrolix/torrent"
)

func main() {
	config := torrent.NewDefaultClientConfig()
	config.Logger = torrentlogger.Discard
	c, err := torrent.NewClient(config)
	if err != nil {
		panic(err)
	}
	defer c.Close()
	for {
	}
}
```
But I still get some unwanted logs:
```
2020-12-08T22:38:50+0100 NONE  dht.go:109: error looking up "router.silotis.us:6881": lookup router.silotis.us: no such host
2020-12-08T22:38:50+0100 NONE  dht.go:109: error looking up "router.silotis.us:6881": lookup router.silotis.us: no such host
```

Which is weird because [this line is commented](https://github.com/anacrolix/dht/blob/f7ae0d6486f508837e6bc1c66f94c6364e40b1bd/dht.go#L127) but it's not in my `go\pkg\mod\github.com\anacrolix\dht\...\dht.go` :
```
...
hostAddrs, err := net.LookupHost(host)
if err != nil {
    log.Printf("error looking up %q: %v", s, err)
    continue
}
...
```

**Comment by anacrolix** [comment]
Can you provide the output of `go list -m github.com/anacrolix/dht/v2` for your project/cmd?

**Comment by imadr** [comment]
```
$ go list -m github.com/anacrolix/dht/v2
github.com/anacrolix/dht/v2 v2.6.1-0.20200416071723-3850fa1b802a
```
I'm getting this error only on windows, on linux however i'm getting warnings from utp_internal.h

**Comment by anacrolix** [comment]
Running `go get github.com/anacrolix/dht@latest` should fix the issue. I'll pre-emptively close this issue.
