### ISSUE TITLE
Mainstream changes from gitlab.com/axet/torrent

### ISSUE THREAD

**Issue by gitpubber** [anacrolix/torrent#448]
Hello @anacrolix ,

I came across the fork of your torrent package by @axet (used by them in libtorrent). They have patched some codebase(they have documented nicely too)

I think some of these can be mainstreamed here.

Please see:

https://gitlab.com/axet/torrent/-/commit/e487f39026da66a80e8863e18f61967fe78e1148

**Comment by anacrolix** [comment]
@gitpubber some features from libtorrent have been taken before, but currently the delta between anacrolix/torrent and axet's fork is too large. If smaller changes could be chosen (and agreed to first before effort is wasted), I think the two codebases could be brought closer with some PRs. Are you interested in spearheading this?

**Comment by anacrolix** [comment]
@gitpubber Could you please include a reason with status changes like closing? This is a public issue and people don't know what you're thinking.
