### ISSUE TITLE
Download Torrent to Different Path

### ISSUE THREAD

**Issue by gitpubber** [anacrolix/torrent#449]
@anacrolix 
I have client with default configuration with ClientConfig.DataDir set to a path.

When,i add Torrent,it downloads to ClientConfig.DataDir . But,i must be able to provide path where the torrent must be downloaded.

Please help me.

**Comment by anacrolix** [comment]
This was answered here: https://gitter.im/anacrolix/torrent?at=5fe18f00c746c6431ccc4387.
