### ISSUE TITLE
Different path for .torrent.bolt.db

### ISSUE THREAD

**Issue by gitpubber** [anacrolix/torrent#450]
@anacrolix 
Can i set different path for .torrent.bolt.db ?

**Comment by anacrolix** [comment]
You can change the parent directory, but not the file basename. See https://pkg.go.dev/github.com/anacrolix/torrent/storage#NewBoltPieceCompletion.

**Comment by anacrolix** [comment]
@gitpubber do you have any more feedback on this? What are you trying to achieve?

**Comment by gitpubber** [comment]
@anacrolix No feedback. Actually i wanted to download torrents in one directory while i wanted .torrent.bolt.db in another directory

**Comment by anacrolix** [comment]
I could take a PR for this if you are willing.

**Comment by gitpubber** [comment]
@anacrolix i would work on this but only after month because I have university exams this month.

**Comment by gitpubber** [comment]
well, this was solved,right?

**Comment by anacrolix** [comment]
I'll take your word for it, cheers.
