### ISSUE TITLE
Upgrade to pion/webrtc@v3

### ISSUE THREAD

**Issue by Sean-Der** [anacrolix/torrent#451]
Hey @anacrolix 

We just released [v3](https://github.com/pion/webrtc/wiki/Release-WebRTC%40v3.0.0) and would love to help you upgrade if you are interested.

v3 enables [Trickle ICE](https://github.com/pion/webrtc/wiki/Release-WebRTC%40v3.0.0#trickle-ice-is-now-enabled-by-default) users may see faster connection times now. They can connect to others before STUN resolves. This is a breaking change so I will need to figure out how WebTorrent emits/receives candidates.

**Comment by anacrolix** [comment]
Yes, let's give it a try. I'm keen to see if the write size limit issue that came up when streaming with DataChannels has been fixed too.

**Comment by Sean-Der** [comment]
The write size limit hasn't been fixed unfortunately. I don't even know how hard that would be to fix, let me look into that first. Hopefully I can come back to you with a dot release fixing that and then we can upgrade. 

One annoyance is that it depends on remote support as well. Since the remote WebRTC peer may not support EOR you will still have to handle it.

**Comment by anacrolix** [comment]
This was contributed by @Sean-Der in https://github.com/anacrolix/torrent/pull/470.
