### ISSUE TITLE
The new changes compatibility

### ISSUE THREAD

**Issue by ucwong** [anacrolix/torrent#454]
```
Fatal: Error starting protocol stack: json: cannot unmarshal array into Go struct field FileInfo.Meta of type *metainfo.Hash
```
The new changes may have some compatibility issue
https://github.com/anacrolix/torrent/commit/1e9d382af925714420b361c875c70ed2024d0d1f#diff-3d38a7bd1e33b33c2dcc79eb257ead4b90d5ab2e6675d91b227437cb63c21fb6L14

**Comment by anacrolix** [comment]
Could you provide more context? I think if you're using a JSON decoder somewhere, a more JSON-specific decoder instance can be provided, or a custom type wrapping your use of metainfo.Hash would be appropriate?

**Comment by ucwong** [comment]
Yes, ```json.Unmarshal``` is used for decode object with metainfo.hash

**Comment by anacrolix** [comment]
See the comments on https://golang.org/pkg/encoding/json/#Unmarshal regarding UnmarshalText as a fallback. I believe you probably want to use your own custom type for serializing infohashes if you intend to use JSON, since metainfo.Hash is a moving target specific to anacrolix/torrent.

**Comment by ucwong** [comment]
> https://golang.org/pkg/encoding/json/#Unmarshal

Thank you, I will make a check
