### ISSUE TITLE
DHT-Sec is supposed to limit data-hosts, not clients, on DHT

### ISSUE THREAD

**Issue by cathalgarvey** [anacrolix/torrent#46]
So, while exploring `torrent` for #44, I noted that the security handling was essentially excluding insecure nodeIds entirely from the routing table. Further, that some KRPC handlers were heading towards excluding insecure nodeIds entirely from KRPC responses, too.

The original intent of the DHT-Sec extension was to limit the ability for an attacker to _host_ targeted data by limiting their ability to create valid secure IDs. A given external IP can have at most seven valid secure IDs, and cannot choose the ID prefix, making it infeasible for all but the most IP-rich attackers to deliberately target a specific torrent.

However, it was not intended to limit participation in the DHT, and doing so would make the DHT less useful for many applications. An argument _could_ be made that it could optionally extend to barring insecure NodeIds from _offering_ routing information, but it makes no sense to refuse to allow insecure NodeIds to _request_ or even to _post information to secure nodes_.

The reason being that all the Secure ID guarantees is difficulty to choose a prefix; it has no other effect, and pretending that it offers any other sort of guarantee is pointless. As the prefix is _only_ relevant to hosting data on the DHT, applying the secure ID requirement to anything else doesn't add any security, but does impose annoyance on developers wishing to build DHT-centric applications. It doesn't make identifying bad actors easier, because DHT-Sec does not prevent IDs from being changed rapidly, it only limits alteration of the immediate first bytes. It doesn't limit the number of nodes an actor can deploy either, only where in the DHT those nodes must localise themselves.

I propose that `torrent`'s implementation of DHT-Sec be limited to the specification; that non-local IPs be required to have a Secure ID before `torrent` will store data on them or consider them a valid endpoint to request ids from, but that torrent will not refuse service to insecure IDs that come to it requesting or announcing Nodes.

Additional thoughts and considerations:
- Refusing service and excluding nodes entirely because of DHT-Sec would make impossible many alternative uses of Mainline, such as for secure messaging applications which use NodeId as a key fingerprint. Nodes of this sort that are not "Secure" in the libtorrent sense should not host torrent data, but are still valid DHT participants.
- Refusing service will kill many low-end or 'mini' routers that implement minimal DHT traversal to locate resources. These are useful for innovative prototypes into DHT-DNS's, aforementioned secure messaging apps, IOT/Embedded routing, and simply for exploration or monitoring. Requiring them to implement DHT-Sec, which uses an unusual CRC32 that may not be preimplemented on their platform or language, would be harmful to development.
- `torrent` _could_ be more suspicious of insecure Ids in its routing table retention policy, and could choose to drop insecure nodes first to make room for secure nodes. As routing is generally to locate a place to host a torrent, this would be a valid, if unnecessary, policy to adopt.

I hope you reconsider the exclusionary policy on DHT-Sec and look instead at only implementing the basic spec. I'm happy to do the legwork there, seeing how there's not much DHT-Sec here yet, and it's early enough to change direction easily.

Thanks,
Cathal

Background: [LibTorrent DHT-Sec overview](http://www.libtorrent.org/dht_sec.html).

**Comment by anacrolix** [comment]
Thanks for this write up. I've addressed the local network exemption in a recent commit. I'm still studying the impact of the rest of this information.

**Comment by cathalgarvey** [comment]
Thanks for taking it seriously, looking forward to your thoughts. :)

**Comment by anacrolix** [comment]
Could you comment on the commits I've made for this so far?

**Comment by anacrolix** [comment]
I've had another careful look. The implementation does favour secure over insecure nodes in its table. It doesn't refuse service based on the requesters ID. That seems to cover what's described here. The implementation is now at https://github.com/anacrolix/dht, so if there's anything missing, please open an issue there.
