### ISSUE TITLE
json.Unmarshal on metainfo.Hash error

### ISSUE THREAD

**Issue by YouROK** [anacrolix/torrent#463]
I am storing torrent info in json but after adding function UnmarshalText gives error
json: cannot unmarshal array into Go value of type *metainfo.Hash

Code for test:
```
func main() {
	hash := metainfo.Hash{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19}
	var hashTo metainfo.Hash
	buf, err := json.Marshal(hash)
	err = json.Unmarshal(buf, &hashTo)
	fmt.Println(hashTo, err)
}
```

if remove this function all work ok

Function:
https://github.com/anacrolix/torrent/blob/6aaaaaffbaec52e984b91a5e884c4c4589d7dbcb/metainfo/hash.go#L57

**Comment by YouROK** [comment]
Fix it with add function:

```
func (h Hash) MarshalText() (text []byte, err error) {
	return []byte(h.HexString()), nil
}
```

**Comment by anacrolix** [comment]
I think again, you should be wrapping or using a different type for this. I could add this MarshalText method, but I'm not sure what impact it will have on the use of metainfo.Hash elsewhere in anacrolix/torrent.
