### ISSUE TITLE
Webseed not found causes an infinite loop trying to read one of the files inside the torrent.

### ISSUE THREAD

**Issue by ajnavarro** [anacrolix/torrent#464]
First of all, thank you for this awesome library and all the effort that you dedicate to it.

I think I found an error related to web seeds. When we try to read a file inside a torrent file using the `file.NewReader()` API, if the `ws` parameter is wrong (pointing to an URL that does not exists), it will try to reach it indefinitely. Code example reproducing the error:

```go
package main

import (
	"fmt"
	"io"

	"github.com/anacrolix/torrent"
)

const testMagnet = "magnet:?xt=urn:btih:a88fda5954e89178c372716a6a78b8180ed4dad3&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F"

func main() {
	cfg := torrent.NewDefaultClientConfig()
	client, _ := torrent.NewClient(cfg)

	t, _ := client.AddMagnet(testMagnet)
	<-t.GotInfo()
	fmt.Println("GOT INFO")

	f := t.Files()[0]

	r := f.NewReader()

	r.Seek(5, io.SeekStart)
	buf := make([]byte, 5)
	n, err := r.Read(buf)

	fmt.Println("END", n, buf, err)
}

```
This code will hang on an infinite loop throwing the following error:

```
2021-02-03T19:21:36+0100 NONE  webseed-peer.go:110: "The WIRED CD - Rip. Sample. Mash. Share": webseed peer for "https://webtorrent.io/torrents/": Request {0 {0 16384}} rejected: reading "https://webtorrent.io/torrents/The+WIRED+CD+-+Rip.+Sample.+Mash.+Share/01+-+Beastie+Boys+-+Now+Get+Busy.mp3" at "bytes=0-16383": unhandled response status code (404)
```

If we remove the `ws` parameter, everything will work as expected.

As a workaround to avoid this error, you can disable web seeds from configuration: `cfg.DisableWebseeds = true`.

Thank you again for everything!

**Comment by anacrolix** [comment]
Thanks for the report, I'll take a look when I can.

**Comment by anacrolix** [comment]
Thanks for the detailed report.

**Comment by ajnavarro** [comment]
Thank you to have a look at it and maintain this awesome library.
