### ISSUE TITLE
Integration: DeepSource

### ISSUE THREAD

**Issue by withshubh** [anacrolix/torrent#466]
I ran DeepSource analysis on my fork of this repository and found some code quality issues. Have a look at the issues caught in this repository by DeepSource [here](https://deepsource.io/gh/withshubh/torrent/issues/).

[DeepSource](https://deepsource.io/) is a code review automation tool that detects code quality issues and helps you to automatically fix some of them. You can use DeepSource to track test coverage, Detect problems in Dockerfiles, etc. in addition to detecting issues in code. 

The PR #461 fixed some of the issues caught by DeepSource.

All the features of the DeepSource are mentioned [here](https://deepsource.io/features/).
I'd suggest you integrate DeepSource since it is free for Open Source projects forever.

Integrating DeepSource to continuously analyze your repository:
- Install DeepSource on your repository [here](https://deepsource.io/signup).
- Create `.deepsource.toml` configuration specific to this repo or use the configuration mentioned below which I used to run the analysis on the fork of this repo.
- Activate analysis [here](https://deepsource.io/gh/anacrolix/torrent/).

```
version = 1

test_patterns = ["**/*_test.go"]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/anacrolix/torrent"]
```

**Comment by withshubh** [comment]
Update: PR #461 merged the configuration file in this repository. You just need to signup and install DeepSource to continuously analyze the repo. :sparkling_heart:

**Comment by anacrolix** [comment]
@withshubh I've already activated the repo.

**Comment by withshubh** [comment]
> @withshubh I've already activated the repo.

Thanks! @anacrolix :sparkling_heart: 

Also, You can let me know if you have suggestions or feedback regarding DeepSource. :)

I'll close this issue now. :sparkles:
