### ISSUE TITLE
Pieces delete issue

### ISSUE THREAD

**Issue by YouROK** [anacrolix/torrent#471]
Hi,
how do you properly delete pieces?
I have a download that goes into memory.
There is a certain cache, I open the reader, it reads and send to http.
If there are more pieces than the size of the cache, then the last read piece is released.

https://github.com/YouROK/TorrServer/blob/master/server/torr/storage/torrstor/cache.go
https://github.com/YouROK/TorrServer/blob/master/server/torr/storage/torrstor/piece.go

```
func (p *Piece) Release() {
	p.mu.Lock()
	defer p.mu.Unlock()
	if p.buffer != nil {
		p.buffer = nil
	}
	p.Size = 0
	p.complete = false

	p.cache.torrent.Piece(p.Id).SetPriority(torrent.PiecePriorityNone)
}
```

Everything is fine, until one moment, if I give these chunks a priority, it gives an error and does not upload.

Is there any way to reset the state of the piece as it was when the torrent was opened?

**Comment by Lontron** [comment]
@anacrolix ???

**Comment by anacrolix** [comment]
I'm not sure I quite understand, however if the issue is around having a limited storage cache, there are improvements in master for this now. You can provide an indication to the Client of the available storage for each torrent, or even Client, and it will try to avoid thrashing and excessive readaheads. I suspect this could help. Please try master.

**Comment by VuzzyM** [comment]
> I'm not sure I quite understand, however if the issue is around having a limited storage cache, there are improvements in master for this now. You can provide an indication to the Client of the available storage for each torrent, or even Client, and it will try to avoid thrashing and excessive readaheads. I suspect this could help. Please try master.

@YouROK

**Comment by YouROK** [comment]
I use self storage with self pieces impl. In piece using mem buffer(slice) when all size of buffers is more than set in sets first buffer clean but=nil and os mem clean.

When reader seek start and begin read, client read piece as complete, but buffer is nil and completions impl sets to false. My piece return eof and client not readahead. Client read only in reader piece position

**Comment by VuzzyM** [comment]
> I use self storage with self pieces impl. In piece using mem buffer(slice) when all size of buffers is more than set in sets first buffer clean but=nil and os mem clean.
> 
> When reader seek start and begin read, client read piece as complete, but buffer is nil and completions impl sets to false. My piece return eof and client not readahead. Client read and reload torrent only in reader piece position

@anacrolix

**Comment by anacrolix** [comment]
> Client read and reload torrent only in reader piece position

I think I follow this part. On a read error, the client should try to refresh the completion state for the entire readahead window as an optimisation. I think you're suggesting that it doesn't?

It looks like it should here https://github.com/anacrolix/torrent/blob/9c81516139819b4bb4db7617643bf2705404ae5c/reader.go#L236

**Comment by VuzzyM** [comment]
> > Client read and reload torrent only in reader piece position
> 
> I think I follow this part. On a read error, the client should try to refresh the completion state for the entire readahead window as an optimisation. I think you're suggesting that it doesn't?
> 
> It looks like it should here
> 
> https://github.com/anacrolix/torrent/blob/9c81516139819b4bb4db7617643bf2705404ae5c/reader.go#L236

@YouROK

**Comment by YouROK** [comment]
> > Client read and reload torrent only in reader piece position
> 
> I think I follow this part. On a read error, the client should try to refresh the completion state for the entire readahead window as an optimisation. I think you're suggesting that it doesn't?
> 
> It looks like it should here
> 
> https://github.com/anacrolix/torrent/blob/9c81516139819b4bb4db7617643bf2705404ae5c/reader.go#L236

Thx this help me in new version

**Comment by anacrolix** [comment]
Thank you for following this up.
