### ISSUE TITLE
[Debug] Downloaded file has wrong content

### ISSUE THREAD

**Issue by luodw** [anacrolix/torrent#472]
Hello, we use torrent 1.25.0 to distribute files among many nodes. we occasionally  found that, some file download successfully and  all pieces of the torrent is completed, but it is filled will zero, has no real data.  Does anyone has idea about this?

**Comment by anacrolix** [comment]
What storage backend are you using? Is it mmap?

**Comment by luodw** [comment]
@anacrolix Yes, we use mmap

**Comment by anacrolix** [comment]
@luodw It's likely that the file that the torrent client is referencing on the disk, is not the same one that you're looking at later. At some point there's likely a delete and then the file is recreated. Are you also not on Windows?

**Comment by luodw** [comment]
@anacrolix We use bittorrent in Linux and the file indeed recreated many times.  I see the piece completion status in boltdb never delete, is it releated?

**Comment by anacrolix** [comment]
Yes, that would be related. If the files are recreated, but the piece completion database is not reset, the client will believe the torrent to be complete already. You can force it to rehash, or if you're meddling with the files yourself, ensure you notify the client/adjust the piece completion database between runs.

**Comment by luodw** [comment]
@anacrolix ok，we use file storage instead mmap to test whether it is ok. I think your advice is ok, so torrent should expose the api to adjust the piece completion

**Comment by anacrolix** [comment]
Possibly we could include info from this issue in https://github.com/anacrolix/torrent/issues/238.

**Comment by anacrolix** [comment]
I'm not sure there's much else to be done here. The piece completion database must be managed correctly or the data files can do this. Please let me know if I have this wrong.
