### ISSUE TITLE
Support for File System Abstraction packages

### ISSUE THREAD

**Issue by ghost** [anacrolix/torrent#473]
Hello,
I know that there are some storage backends available that we can use.

But,it would be nicer if this project supported file system abstraction packages officially. I would like to see this project support:

1) https://github.com/C2FO/vfs

2) https://github.com/spf13/afero

3) https://github.com/graymeta/stow

4) https://gocloud.dev/howto/blob/

It would eliminate the case of writing custom backends for storage for few.

**Comment by anacrolix** [comment]
I would welcome PRs and suggestions towards this.

**Comment by gitpubber** [comment]
@anacrolix i think that vfs backend might be better, i will see whether i could work on this

**Comment by anacrolix** [comment]
What's the resolution here? This is a valid issue.

**Comment by gitpubber** [comment]
@anacrolix ,

I think https://github.com/C2FO/vfs will be better.

**Comment by anacrolix** [comment]
I have no interest in working on this for now. A storage implementation that wraps VFS interfaces would be the way to go I think.

**Comment by anacrolix** [comment]
On a revisit, I don't know what value implementing this in anacrolix/torrent would provide. If I've missed something though, let me know.
