### ISSUE TITLE
Download torrent to different directory

### ISSUE THREAD

**Issue by gitpubber** [anacrolix/torrent#475]
i would like to have function/method which accepts two parameters. one is metainfo and other is directory.

this way,i want to give path to engine to download torrents at.

**Comment by anacrolix** [comment]
You could write such a function by wrapping a `Client`, the rest of the configuration can be done via the metainfo package and `TorrentSpec`.

**Comment by anacrolix** [comment]
@gitpubber Did the proposed solution work for you?

**Comment by monkeyWie** [comment]
@anacrolix can you show some sample code? thank~
