### ISSUE TITLE
Change Client's settings during runtime of Client

### ISSUE THREAD

**Issue by gitpubber** [anacrolix/torrent#478]
I have `TorrentClient *torrent.Client` . I have initialized it with `torrent.NewDefaultClientConfig()`. Then, i have added few torrents to download using it.

While the torrents are running, i want to change settings of [Client](https://pkg.go.dev/github.com/anacrolix/torrent#Client)  like peerid, blocklist, upload/download limiter, etc.

It seems that one must Close the Client, create new client with New config, add torrents from previous client to new client. i want to know whether there is way to update client's settings other than this.
Can changing `ClientConfig` passed to `NewClient()` can change the settings?

Please help

**Comment by gitpubber** [comment]
In Simple words, i want to modify [ClientConfig](https://github.com/anacrolix/torrent/blob/v1.26.0/config.go#L23) of running torrent client

**Comment by anacrolix** [comment]
@gitpubber currently you can modify some items of the ClientConfig at runtime. `*rate.Limiter` can be adjusted dynamically, as can `iplist.Ranger`. PeerID can not currently be changed on the fly, but it might be possible to support. It would be easiest if you describe which items you want to change and why, as they'll probably all need specific handling.

**Comment by gitpubber** [comment]
Can you please tell me how can I change *rate.Limiter  and iplist.Ranger dynamically ( code snippet would be appreciated ) . 

Also , thank you for your work , @anacrolix

**Comment by gitpubber** [comment]
@anacrolix  , Regarding your second question , I am developing torrent manager and I would like the user to set options of Torrent Client dynamically when torrents will be active. So, since creating new client with new settings, deleting old client, adding active torrents of old torrent to new one seems bad idea , I asked.

**Comment by anacrolix** [comment]
Any type that implements https://pkg.go.dev/github.com/anacrolix/torrent/iplist#Ranger can be dropped in as the IPBlocklist in the ClientConfig. After that, if you mutate it threadsafely, the Client doesn't care. It would be enough to implement a naive lookup with a RWMutex or something. Feel free to contribute this in a PR. The methods on *rate.Limiter are all threadsafe see https://pkg.go.dev/golang.org/x/time/rate#Limiter. I think this was resolved in https://github.com/anacrolix/torrent/issues/233#issuecomment-481902921.

**Comment by anacrolix** [comment]
Feel free to open an issue if you need to change PeerID on the fly. I don't think it's possible to do that for DHT servers, but those have independently determined node IDs anyway. You can also shut them down and add new ones with different settings any time via https://pkg.go.dev/github.com/anacrolix/torrent#Client.AddDhtServer.
