### ISSUE TITLE
Implement SkipRegion(off, len int64)

### ISSUE THREAD

**Issue by jpillora** [anacrolix/torrent#48]
Hey matt, based off [this](https://github.com/anacrolix/torrent/blob/master/client.go#L2058-L2065), I was about to send a PR to add a:

```
func (t Torrent) SetRegionPriorityTo(off, len int64, priority piecePriority)
```

To allow certain regions to be skipped. Though I noticed you've got a `noprio` branch going. Does `torrent` not support changes of priorities on running torrents?

Along with:

```
func (t Torrent) DownloadRegion(off, len int64)
```

Is it possible to implement:

```
func (t Torrent) SkipRegion(off, len int64)
```

?

**Comment by anacrolix** [comment]
It supports changing priorities, the necessary methods just aren't exposed. This can be added trivially with the current master branch. Your other 2 methods can also be added.

The noprio branch is an experiment that removes the internal priorities that aren't currently exposed, and replaces them with priorities based on the offsets of Torrent Readers, so as to allow more responsive seeking on an incomplete torrent.

**Comment by anacrolix** [comment]
I see your downstream issue will require a Torrent.SkipRegion/File.NoDownload method either way. Both master and noprio can support this.

**Comment by jpillora** [comment]
Okay awesome

**Comment by anacrolix** [comment]
Send PR or I'll address this myself in the next few days.

**Comment by jpillora** [comment]
Cool, I'll leave this with you. I was just having a look through the noprio branch and I couldn't see an easy way to add it.

**Comment by jpillora** [comment]
Question relating to this issue, if I created a reader for a torrent, begin reading a particular file and close the reader midway through. Does that region get de-prioritised?

I can see that the [reader is nil'd](https://github.com/anacrolix/torrent/blob/master/reader.go#L156-L159) though I wasn't sure the regions are re-prioritised somehow.

I'm just wondering if there's another way to lower priorities.

**Comment by anacrolix** [comment]
It does not get de-prioritized. This is one of the reasons for the noprio branch, which will support that. There's no public way to deprioritize currently, it's still a work in progress.

**Comment by anacrolix** [comment]
I'm about to merge what should allow for this. If you'd like to do some testing with the priority changes, I'll proceed with implementing the ability to File.Cancel().

**Comment by jpillora** [comment]
Awesome! Will probably have some time tomorrow to test

**Comment by jpillora** [comment]
So skipping regions is now supported via `torrent.Reader.Close()` ? Or will it be supported when `File.Cancel()` lands?

**Comment by anacrolix** [comment]
Ah, Cancel needs to land.

**Comment by jpillora** [comment]
Cool, will be watching 👀

**Comment by anacrolix** [comment]
I've Added File.Cancel(), and Torrent.CancelPieces().

**Comment by jpillora** [comment]
Awesome, will give it a test this weekend :+1:

**Comment by jpillora** [comment]
No one else has commented here so I'll assume its all good! Will reopen if I find anything

**Comment by anacrolix** [comment]
I added a simple test, seems legit.
