### ISSUE TITLE
panic: unaligned 64-bit atomic operation. Support 32-bit architectures too.

### ISSUE THREAD

**Issue by compliment** [anacrolix/torrent#483]
```
panic: unaligned 64-bit atomic operation

goroutine 489 [running]:
runtime/internal/atomic.panicUnaligned()
        runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Xadd64(0x2e4e7c4, 0x1, 0x0, 0x2d87600, 0x30a8d40)
        runtime/internal/atomic/asm_arm.s:233 +0x14
github.com/anacrolix/dht/v2.(*traversal).wrapQuery(0x2e4e784, 0xca9b00, 0x2ef6fa0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/anacrolix/dht/v2@v2.9.1/traversal.go:115 +0x44
github.com/anacrolix/dht/v2.(*traversal).run.func1.1(0x2f8b130)
        github.com/anacrolix/dht/v2@v2.9.1/traversal.go:156 +0x30
github.com/anacrolix/dht/v2.(*traversal).beginQuery.func1.1(0x0)
        github.com/anacrolix/dht/v2@v2.9.1/traversal.go:179 +0x98
github.com/anacrolix/dht/v2.(*Server).beginQuery.func1.1()
        github.com/anacrolix/dht/v2@v2.9.1/server.go:745 +0x24
created by github.com/anacrolix/dht/v2.(*traversal).run
```

**Comment by anacrolix** [comment]
Could you try the associated commit? Was this issue only present on arm, did you find anything else that didn't work?

I would welcome PRs to include CI for testing arm if you're interested.

**Comment by anacrolix** [comment]
`go get github.com/anacrolix/dht/v2@fd60ad06b4827d42a76235103e88b20e633db27c` should do what you need in your project for testing this.

**Comment by compliment** [comment]
> Was this issue only present on arm? 


According to  [atomic/#pkg-note-BUG](https://golang.org/pkg/sync/atomic/#pkg-note-BUG) it affects all 32-bit architectures. I can confirm the same on ARM and 386.  

https://github.com/anacrolix/dht/commit/fd60ad06b4827d42a76235103e88b20e633db27c didn't fix it, same error with different line number. 

example/torrent built for 386 
```
panic: unaligned 64-bit atomic operation

goroutine 795 [running]:
runtime/internal/atomic.panicUnaligned()
	runtime/internal/atomic/unaligned.go:8 +0x2d
runtime/internal/atomic.Xadd64(0x9e321e4, 0x1, 0x0, 0x0, 0x0)
	runtime/internal/atomic/asm_386.s:107 +0x11
github.com/anacrolix/dht/v2.(*traversal).wrapQuery(0x9e321e4, 0x86c4250, 0x9c753c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/anacrolix/dht/v2@v2.9.2-0.20210509011734-fd60ad06b482/traversal.go:115 +0x52
github.com/anacrolix/dht/v2.(*traversal).run.func1.1(0x9c0e008)
	github.com/anacrolix/dht/v2@v2.9.2-0.20210509011734-fd60ad06b482/traversal.go:156 +0x35
github.com/anacrolix/dht/v2.(*traversal).beginQuery.func1.1(0x0)
	github.com/anacrolix/dht/v2@v2.9.2-0.20210509011734-fd60ad06b482/traversal.go:179 +0x93
github.com/anacrolix/dht/v2.(*Server).beginQuery.func1.1()
	github.com/anacrolix/dht/v2@v2.9.2-0.20210509011734-fd60ad06b482/server.go:745 +0x23
created by github.com/anacrolix/dht/v2.(*traversal).run
	github.com/anacrolix/dht/v2@v2.9.2-0.20210509011734-fd60ad06b482/traversal.go:164 +0x83

```

**Comment by anacrolix** [comment]
Could you provide the new stack trace? It's probably another atomic elsewhere in the package that also needs to be fixed.

**Comment by compliment** [comment]
@anacrolix You can build example/torrent from this repo itself for linux 386 and run it on amd64 or for linux arm and run it on arm64. I included the new stack trace for example/torrent for this repo itself in the previous comment.

**Comment by silentmurdock** [comment]
Hello!

I think I've managed to fix the problem with the help of this page: https://go101.org/article/memory-layout.html
I uploaded the 2 modified files here for the **dht v2.9.1** package because I have no other options now.

I use anacrolix torrent for my torrent player application ( [White Raven](https://github.com/silentmurdock/whiteraven) ) for Samsung Smart TV E, F, H series.  Each of these televisions has armv7 and armv6 32-bit processors. 

For me, this bug fix is necessary.

Tested on armv7 32-bit, windows 32-bit, linux 32-bit

Please someone create a commit!

[v2@v2.9.1_fix_unaligned_64-bit-atomic_panic.zip](https://github.com/anacrolix/torrent/files/6526922/v2%40v2.9.1_fix_unaligned_64-bit-atomic_panic.zip)

Thank You!

**Comment by anacrolix** [comment]
Interesting article. I take it then on a 32 bit system, the struct field alignment even of an int64 might be only 4 bytes.

**Comment by anacrolix** [comment]
See https://github.com/anacrolix/dht/pull/46.
