### ISSUE TITLE
Revert Commit 7455b98a0f597c3b84c7ed60b75b9ddf5fd8d341 and switch back from crawshaw.io/sqlite to mattn-sqlite3

### ISSUE THREAD

**Issue by gitpubber** [anacrolix/torrent#484]
Please revert commit [7455b98a0f597c3b84c7ed60b75b9ddf5fd8d341](https://github.com/anacrolix/torrent/commit/7455b98a0f597c3b84c7ed60b75b9ddf5fd8d341).

I don't see any benefit of switching to it. It makes us to use another build tag.
mattn-sqlite3 is database/sql compliant, so why not use it ? 

Many who use anacrolix/torrent use mattn-sqlite3 . So,for them, crawshaw.io/sqlite will be another unnecessary thing which got compiled

**Comment by anacrolix** [comment]
mattn/go-sqlite3 had many issues in the way it was used in anacrolix/torrent. In particular it's necessary to manage connections directly and use incremental blob IO to get full value out of sqlite.

The issue around using mattn/go-sqlite3 and crawshaw.io/sqlite simultaneously has come up several times, and is solved in another issue.

See https://crawshaw.io/blog/go-and-sqlite, https://crawshaw.io/blog/one-process-programming-notes, and https://github.com/anacrolix/torrent/issues/421#issuecomment-735521392 for more info.

**Comment by gitpubber** [comment]
Thanks @anacrolix , no need of reverting

**Comment by anacrolix** [comment]
Thanks mate. Your interest and contributions are appreciated.
