### ISSUE TITLE
How do I use Custom PieceCompletion ?

### ISSUE THREAD

**Issue by gitpubber** [anacrolix/torrent#485]
Can you please make https://github.com/anacrolix/torrent/blob/305ba51dc2d50f7a38d12fbf1d042c7b12fa29d8/storage/file.go#L54 Public Function so that it is accessible outside the package ?

**Comment by anacrolix** [comment]
You're welcome to make a PR for this. Note again that this API is pretty bad, and might be tidied up in the future.
