### ISSUE TITLE
sqlite3 PieceImplementation Panics

### ISSUE THREAD

**Issue by gitpubber** [anacrolix/torrent#489]
Error Log: 
[err.txt](https://github.com/anacrolix/torrent/files/6458363/err.txt)

You can clearly see that's the error of Set() function 

@anacrolix  Please help

**Comment by gitpubber** [comment]
Hey, I added mutex to check whether it works. so,now it doesn't panic but my other crawshank.io database connection doesn't get updated itself

**Comment by anacrolix** [comment]
Is there a unit test that can trigger this?

**Comment by gitpubber** [comment]
> Is there a unit test that can trigger this?

I think not. In my application, i used https://github.com/anacrolix/torrent/blob/v1.27.0/storage/file.go#L55  to use 
https://github.com/anacrolix/torrent/blob/v1.27.0/storage/sqlite-piece-completion.go#L20

@anacrolix somehow resolve this. i tried for almost 3 hours to debug this. sync.Mutex works but it causes other bug(like if i had another crawshaw.io sqlite3 connection,it will not work at all)

**Comment by gitpubber** [comment]
@anacrolix  , Issue is solved . Please release new version . 

Thank you very much. You really are Great Software Developer.

**Comment by anacrolix** [comment]
Done, v1.28.0.
