### ISSUE TITLE
More complex examples for quickstart in README

### ISSUE THREAD

**Issue by zhulik** [anacrolix/torrent#49]
Hi, i noted, that there is no normal examples in docs or in readme. 

I spent some time to understend, how to work with library and i can write more complex, than in docs, example which can save someone's time and reduce barrier to entry.

Will you accept that changes in readme?

**Comment by anacrolix** [comment]
Yes, please proceed

**Comment by 0x4139** [comment]
How are we on that? for example how exactly do you use piece backend?

**Comment by voxadam** [comment]
👍

**Comment by anacrolix** [comment]
Any update on your changes?

**Comment by anacrolix** [comment]
I'm expiring this.
