### ISSUE TITLE
Use gobwas/ws instead of gorilla/websocket

### ISSUE THREAD

**Issue by gitpubber** [anacrolix/torrent#500]
This package uses gorilla/websocket for webtorrent which many criticise as being slow and large.few other packages of websocket like gobwas/ws which are more lightweight and fast are also present.

Why not use them? why use gorilla/websocket?

https://www.freecodecamp.org/news/million-websockets-and-go-cc58418460bb/

https://github.com/gobwas/ws

it could be better to use these packages, no?

**Comment by gitpubber** [comment]
@anacrolix , i saw the codebase which uses gorilla/websocket . i think it's not large(being single file).

can you evaluate https://github.com/gobwas/ws to replace gorilla/websocket ?

**Comment by gitpubber** [comment]
https://github.com/anacrolix/torrent/blob/master/webtorrent/tracker_client.go

**Comment by gitpubber** [comment]
I could have tried to rewrite this, but i don't have much knowledge :(

please help @anacrolix . i would like to use gobwas/ws in my app and i would not like to have 2 websocket dependencies

**Comment by anacrolix** [comment]
Thanks for the suggestion. It just comes down to gorilla/websocket being the most popular after moving on from an golang/x websocket implementation that didn't cope with certain types of usage in some of my projects. I have no attachment to gorilla/websocket, but also no time to work on this unless it affects me currently.

**Comment by gitpubber** [comment]
@anacrolix Done.

see https://github.com/anacrolix/torrent/pull/503
