### ISSUE TITLE
Some downloading status information

### ISSUE THREAD

**Issue by zhulik** [anacrolix/torrent#51]
Is there way to know progress, download speed and time left info? In your cli downloader i see only progress state and it's calculated by separate goroutine wich takes currently downloaded bytes, total bytes and converts it to percentage, [here](https://github.com/anacrolix/torrent/blob/master/cmd/torrent/main.go#L59). 

I can calculate speed and time left by myself, but, maybe, calculating this values in `Client` or in `Torrent` is better, than multiple realizations in all based on your package tools?

**Comment by anacrolix** [comment]
This is a good point. I could expose a download/upload pubsub and let users generate their own statistics with it. Maybe a default consumer for the simplest use case? Regarding the percentage, a helper function that returns torrent statistics, if I haven't already.

**Comment by Sioro-Neoku** [comment]
I would love that!
I'm mostly curious about the upload speed, as the download I can calculate easily as @zhulik mentioned.

**Comment by anacrolix** [comment]
It may just be easiest if I have counters for these, and users can sample them at their own pace, doing diffs over previously observed values.

**Comment by Sioro-Neoku** [comment]
I'm happy with that approach.

**Comment by anacrolix** [comment]
I consider this fixed since https://github.com/anacrolix/torrent/commit/192bb829fb09713ff19c19f0b3af0d82927b0311. Submit new issues if there are other stats you need exposed.
