### ISSUE TITLE
bencode: syntax error (offset: 0): unexpected 'e'

### ISSUE THREAD

**Issue by xackery** [anacrolix/torrent#522]
This error started popping up on torrents for me that worked fine before. I'm.. not fully sure why.

This is part of: 
 https://github.com/anacrolix/torrent/blob/615ac41ae3e0e88515cf2ff73d6f3ce6e9777420/bencode/decode.go#L50

This torrent works fine: https://webtorrent.io/torrents/big-buck-bunny.torrent

Any torrent from this erai-raws does not work and gives above error:
https://ddl.erai-raws.info/Torrent/2021/Spring/Cestvs%20-%20The%20Roman%20Fighter/[Erai-raws]%20Cestvs%20-%20The%20Roman%20Fighter%20-%2010%20[480p][Multiple%20Subtitle].mkv.torrent

they worked previously, seems something changed in their meta file data and broke this library's support.

**Comment by anacrolix** [comment]
Hm, I'm not able to reproduce. What revision of anacrolix/torrent are you using?

**Comment by xackery** [comment]
I'm going to close. I found out that erai-raws added a 401 unauthorized if you requested the url above without a user-agent and so the payload itself was malformed, and so bencode was parsing the data and getting a malformed 'e', aka your repo is not at all at fault, was more user error.

Thanks for taking the time to check
