### ISSUE TITLE
What does NoDefaultPortForwarding do?

### ISSUE THREAD

**Issue by gitpubber** [anacrolix/torrent#528]
https://github.com/anacrolix/torrent/blob/e1cac00bd5dacda2bbada211a6bd2f160f06ce3d/config.go#L31

So, I have noticed that setting this option to true will halve the total no of goroutines ( if total no of goroutines is X, setting this option will almost halve the total no of goroutines to X/2).

So, What does this config do?( I saw at portfwd.go but i need better explanation) . Is it safe to set this config to true ? Any side effects ?

**Comment by anacrolix** [comment]
It's likely that setting it to true is preventing you from receiving incoming connections. That's probably not what you want, although I have noticed that long-running clients can often be spammed by connections requests.

**Comment by gitpubber** [comment]
Ok. Thanks @anacrolix
