### ISSUE TITLE
Mocking Torrent internals

### ISSUE THREAD

**Issue by zhulik** [anacrolix/torrent#53]
Hi. I writing tests for my downloader and i don't want to download anything there. So, i ran into troubles with mocking Torrent.

You define Torrent struct as
```go
type Torrent struct {
	cl *Client
	*torrent
}
```
I undestand, that you want to encapsulate it's logic from the outside code. But it creates some barrier for changing it's internals from the client tests. Your tests is defined in the same package as library, so you can do anything in tests. It is impossible to do it from my tests.

The good practice for testing libraries is defining it's tests in separate package `torrent_test` for example.

Is there any way(interfaces magic or something else) to totally mock downloading and write tests without network access?

**Comment by anacrolix** [comment]
I don't have much experience with mocking, so I'm open to suggestions. If you can provide mocks to be included with the torrent repo I would be appreciative. Open any PR you need to make this happen.

**Comment by zhulik** [comment]
Sorry for my PR, i add some abstraction layer in my and it allows me to mock torrent package without changing it.

**Comment by anacrolix** [comment]
Great to see you solved it. If any of the mocked tests can be submitted that would be useful.

**Comment by zhulik** [comment]
Now i have some expirience with torrent package, so, i will add some readme and examples in a few days.

**Comment by anacrolix** [comment]
Cheers
