### ISSUE TITLE
allow to start new file reader with a customized readahead

### ISSUE THREAD

**Issue by Trim21** [anacrolix/torrent#530]
I'm like to read certain part from a file (a single file in an archive with known size) 

I find that torrent will try to make new connections right after new reader is added. So it would reduce the overhead to re-announce or make extra connect with peers.

```go
func (f *File) NewReaderWithReadAHead(readahead int64) Reader {
	tr := reader{
		mu:        f.t.cl.locker(),
		t:         f.t,
		readahead: readahead,
		offset:    f.Offset(),
		length:    f.Length(),
	}
	f.t.addReader(&tr)
	return &tr
}
```

**Comment by anacrolix** [comment]
Additionally, what if readahead zero did not result in pre-emptive fetching in the client, so that you could set it to 0 and seek in to position, then set it back? Is that also helpful?

**Comment by Trim21** [comment]
I find the solution (maybe).

I set the pieces needed first, then create this new reader from the file.

Feel free to close this issue if you think this new method is not good.

**Comment by anacrolix** [comment]
I'm inspired to actually handle readahead automatically, but also defer any prioritization until read requests are made.

**Comment by anacrolix** [comment]
Well this was implemented. The new default readahead algorithm grows the window linearly. I don't believe there's any readahead until the first read, so you can create a Reader and adjust before use.

**Comment by vintikzzz** [comment]
@anacrolix really interesting feature, but it's not impossible right now to setup own `readaheadFunc`

**Comment by anacrolix** [comment]
Ah, it's not, but you can still configure the readahead in the old fashion. Let's open another issue if custom readahead functions are wanted. Let me know if I've gotten that wrong.

**Comment by vintikzzz** [comment]
@anacrolix I made a ticket for it #687 
is it ok?
