### ISSUE TITLE
error getting piece completion: sqlite.Exec: Conn.Prepare: SQLITE_MISUSE

### ISSUE THREAD

**Issue by bsergean** [anacrolix/torrent#546]
```
2021/08/13 17:42:50 error getting piece completion: sqlite.Exec: Conn.Prepare: SQLITE_MISUSE: bad parameter or other API misuse (select complete from piece_completion where infohash=? and "index"=?)
```

This isn't easily reproducable, but I generated a panic with some buggy code of mine, and it seems to have triggered this sqlite error.

Feel free to close if this isn't actionable, but reporting regardless.

**Comment by anacrolix** [comment]
I think more context is needed. Try deleting the .torrent.db piece completion file in any local directories.

**Comment by anacrolix** [comment]
@bsergean try now with 8a65ef627d849e36ea8ecbf3631fbd767c43b485. Let me know if you get a panic.

**Comment by bsergean** [comment]
This is sad but I can't remember for sure what I was doing. I think I was calling Close twice on a client, inside a unittest, so your fix might help here.

**Comment by bsergean** [comment]
I'm gonna use the latest v1.30.3 tag and tell you if I hit this again, but so far with 1.30.2 I've never seen it, and now the code is running on a bunch of machines.

**Comment by bsergean** [comment]
I took the signal handler code from the cmd/torrent/main.go, and I can cancel a download just fine with the latest version. Will close this.

```
^CINFO[0004] close signal received: interrupt
```

**Comment by bsergean** [comment]
I've tried to add logging by overriding the client logger, but the storage code does not use it. There isn't much log calls in there so I don't know if it's worth it.

I'm trying to see if a particular file trigger this (we have big files that randomly fail to download, for reason likely unrelated to torrent lib (they get periodically deleted).

```
storage$ ag log
file-piece.go
5:	"log"
27:		log.Printf("error getting piece completion: %s", err)

sqlite/sqlite-storage.go
13:	"log"
559:		//log.Printf("batched %v write queries", len(buf))
580:		//log.Printf("func name: %q", funcName)
650:	//log.Printf("readdir %q gave %q", i.location, names)
756:					log.Print("sqlite busy")

sqlite/sqlite-storage-cli/main.go
8:	"log"
24:		log.Printf("error in main: %v", err)

safe-path_test.go
4:	"log"
10:	log.SetFlags(log.Flags() | log.Lshortfile)

piece-completion.go
4:	"github.com/anacrolix/log"
23:		log.Printf("couldn't open piece completion db in %q: %s", dir, err)

file.go
198:	//log.Printf("write at %v: %v bytes", off, len(p))
209:		//log.Printf("%v %v wrote %v: %v", i, e, n1, err)
```

**Comment by anacrolix** [comment]
I'm not sure, but there have been several fixes here recently. I have seen a race in the storage tests that occasionally comes up that hasn't been fixed yet, even on master. I haven't had time to dig in to it yet.

**Comment by bsergean** [comment]
This error is now quite rare, I will try to deploy something with the latest version of anacrolyx/torrent and see if it makes it even ‘rarer’.
