### ISSUE TITLE
Allow configuring the number of concurrent connections

### ISSUE THREAD

**Issue by Sioro-Neoku** [anacrolix/torrent#55]
Hey

[As per our discussion](https://github.com/Sioro-Neoku/go-peerflix/issues/11#issuecomment-169321343), some users would like to configure the number of open connections for performance reasons.

The connection limit is currently a [constant](https://github.com/anacrolix/torrent/blob/153c13db4374722e7665311e0355fdb4c3820363/client.go#L91) . Would be nice if we could configure it from the [config struct](https://github.com/anacrolix/torrent/blob/153c13db4374722e7665311e0355fdb4c3820363/config.go).

Thanks! =)

**Comment by anacrolix** [comment]
I will expose a global limit to connections in a future commit. Thanks.

**Comment by anacrolix** [comment]
I'll be adding this shortly.

**Comment by anacrolix** [comment]
Fixed for torrents as of https://github.com/anacrolix/torrent/commit/838c35f3eacd562279c2e2abb6543708b2d3bd3f. I am still considering a whole-Client connection limit before I consider the bug completely fixed.

**Comment by anacrolix** [comment]
This was fixed by @themihai in https://github.com/anacrolix/torrent/commit/6ab65a49a8a72dea1a28968b2ab42a85fd4566ec.
