### ISSUE TITLE
Question: Download without touching the disk

### ISSUE THREAD

**Issue by jpillora** [anacrolix/torrent#57]
I'd like to stream torrents using a configurable amount of RAM. Assuming I'm not uploading, my plan is create a custom `TorrentDataOpener` which keeps chunks around just long enough to ship them off again. Is this safe to delete a chunk after it has been verified?

**Comment by anacrolix** [comment]
Yes, it should be. Most of the piece-level backends that are currently implemented use caching, and they're able to handle pieces going missing suddenly. It should work, you probably want to cache at a piece level.

**Comment by jpillora** [comment]
Okay cool, yep that was the plan. Thanks!
