### ISSUE TITLE
Question regarding trackerScraper.Run()

### ISSUE THREAD

**Issue by YenForYang** [anacrolix/torrent#590]
https://github.com/anacrolix/torrent/blob/175b826e738c76d1a96e435bc5396e054ca5796a/tracker_scraper.go#L202-L208

I'm confused on why locking the client is necessary for assigning `lastAnnounce`. It doesn't look like `lastAnnounce` is read anywhere besides in `trackerScraper.statusLine()` and only written in `Run()`.

**Comment by anacrolix** [comment]
statusLine occurs while holding the client lock. This could probably be done with an atomic, but it occurs so infrequently.

**Comment by YenForYang** [comment]
Ok gotcha. I think delving into atomics could benefit this library as a whole. Do you mind a change to atomic.Value here? The disadvantage would be the need to document that it contains `trackerAnnounceResult`. But either way, we should document that it needs to be read with a client lock. I think when generics come around `atomic.Value` could be switched for something even better.

**Comment by anacrolix** [comment]
It would be much better with generics here. I don't think it's performance critical enough to worry about. If we move toward using generics for this, a small PR using a longer name as you suggested could be fine in the interim. It will help prove the concept. I wonder if there are some performance cortical areas this could be done though.
