### ISSUE TITLE
Unify size of `PieceIndex` with `pp.Integer`

### ISSUE THREAD

**Issue by YenForYang** [anacrolix/torrent#596]
I've found some cases where `pp.Integer` is used to denote the index of pieces. This is not an issue at all, but it turns out `PieceIndex` is `int` (effectively `int64`) and `pp.Integer` is a `uint32`. I think it would be more maintainable and efficient in the long run to change `pieceIndex` to a 32 bit size (i.e. `uint32`, or `int32` if signed compatibility is important.) As far as I'm aware, there are no torrents out there with remotely close to 2 or 4 billion pieces. 

I guess I could also argue that it would be less memory usage, but I'd just be grasping for straws at that point lol.

**Comment by anacrolix** [comment]
I think you might be right. I have opinions about prematurely using unsigned integers. Piece index should be made to match whatever is addressable from bencode. That probably is uint32.

**Comment by anacrolix** [comment]
There's some difficulties in avoiding cyclic dependencies here with `metainfo`, `peer_protocol`, `types` and more.
