### ISSUE TITLE
Download progress

### ISSUE THREAD

**Issue by jzelinskie** [anacrolix/torrent#6]
Is there a way to get at the download progress of a torrent?
Looks like you could add a method on `torrent` that locks `t.stateMu` and divides the number of completed pieces by the total number of pieces.

**Comment by anacrolix** [comment]
I would like to show a progress bar, and mute most of the log messages by default for ./cmd/torrent. What are your thoughts on that?

Currently status is reported for any binaries importing envpprof, such as torrent on a HTTP handler at /. For ./cmd/torrent, you can run with envvar GOPPROF=http, it'll tell you what address it's serving, full status is available there. See https://github.com/anacrolix/envpprof for more details.

**Comment by jzelinskie** [comment]
sgtm
[mitchellh/ioprogress](https://github.com/mitchellh/ioprogress) is what I've used for the progress bar in rocket.
