### ISSUE TITLE
Change `(*Torrent).files` from type `*[]*File` to `*[]File` 

### ISSUE THREAD

**Issue by YenForYang** [anacrolix/torrent#629]
I think this would be better long term, considering that each `File` instance is owned by a `Torrent`. Ultimately the more pointers we have the more the GC has to work. `*[]*File` is literally a pointer to a pointer to an array containing pointers to `File`s.

The only disadvantage here would be the need to slightly modify the API -- `Files()` would have to return `[]File` instead of `[]*File`.

**Comment by anacrolix** [comment]
This seems particularly easy to do if file priorities are moved on to Torrent, then a value-based File works fine (it's all read-only). Otherwise you need to adjust a lot of callsites to pull a pointer to the particular File in use `&files[index]`.

**Comment by anacrolix** [comment]
I mucked around with the idea, see https://github.com/anacrolix/torrent/tree/flatten-files.

**Comment by anacrolix** [comment]
I don't think it's worthwhile, happy to follow up if someone else is interested in it.
