### ISSUE TITLE
Change `(*Torrent).length` from `*int64` to `int64`

### ISSUE THREAD

**Issue by YenForYang** [anacrolix/torrent#630]
I might have missed something here -- but I don't see why `.length` needs to be a pointer instead of just an `int64`. I mean, we aren't checking `nil` anywhere as far as I can tell. Changing this would actually improve overall safety since we dereference `length` without checking anyway.

**Comment by anacrolix** [comment]
It's a pointer to make use of the uninitialized value a logical error. Not ideal, I'd rather an unwrap() equivalent.
