### ISSUE TITLE
Torrent file parsing error

### ISSUE THREAD

**Issue by jngbng** [anacrolix/torrent#65]
This package sometimes fails to parse a torrent file.
The problem turns out to be a type mismatch error:
"Nodes" field of "MetaInfo" struct is defined as [][]string type,
expecting both host and port are of type string.
However, torrent spec defines port value as of integer type.

http://bittorrent.org/beps/bep_0005.html

**Comment by anacrolix** [comment]
Can you provide a sample torrent file?

**Comment by jngbng** [comment]
Here are torrent files that have "nodes" field.

2016-02-22 10:20 GMT+09:00 Matt Joiner <notifications@github.com>:

**Comment by anacrolix** [comment]
@jngbng There's no attachment. I don't think you can do that on github. Can you provide a link?

**Comment by jngbng** [comment]
Sorry, I hope you may access the file via this link:
http://211.41.234.53:18888/not_working_torrent.zip

2016-02-22 23:41 GMT+09:00 Matt Joiner <notifications@github.com>:

**Comment by anacrolix** [comment]
Thanks. I'll ensure it's parsed correctly, and that the nodes are incorporated into the DHT with commits in the next few days.

**Comment by jngbng** [comment]
Thanks a lot!
2016. 2. 22. 오후 11:54에 "Matt Joiner" <notifications@github.com>님이 작성:
