### ISSUE TITLE
Notify On Completion

### ISSUE THREAD

**Issue by varbhat** [anacrolix/torrent#666]
@anacrolix ,

It would be nice to have `chan metainfo.Hash` which notifies us Torrent Completion.

Moving Torrents upon Completion is requested feature : https://github.com/varbhat/exatorrent/issues/2 . It would be nicer not to poll regularly for completion.

**Comment by anacrolix** [comment]
Could you take a look at https://github.com/anacrolix/torrent/issues/352? You might also look at https://pkg.go.dev/github.com/anacrolix/torrent#Torrent.SubscribePieceStateChanges, which could provide an event-driven way to detect completion. I suspect with suitable feedback on #352, I might have enough information to add something to the API. There is an internal data structure that tracks piece completion very efficiently.

**Comment by anacrolix** [comment]
What was your solution @varbhat ?

**Comment by varbhat** [comment]
@anacrolix , Didn't look much into it. But, these are my current thoughts.

1) Check Periodically whether Torrents are completed and take action based on it. exatorrent already has thu ability to stop torrent when it reaches certain seedratio ( https://github.com/varbhat/exatorrent/blob/a3c79279ab802289c5ee03ccc8af5679f39eeb20/internal/core/routine.go#L26 ) and i may add code for checking whether torrents are complete too. But,this is not optimal solution out there.

2) Torrent.SubscribePieceStateChanges isn't optimal solution,i think.  Because, it requires seperate goroutine per torrent to check for pieces.

3) Completion is most common phenomenon and many would want some event to occur on completion (like moving the torrent). Ergonomically,it would be better to have CompletionChannel (of type `chan metainfo.Hash` )  which sends infohash of completed torrents which can be listened on application-side .

4) I won't want high CPU usage .

**Comment by anacrolix** [comment]
This is fixed in c9c137d8f225ef0c4f29fd2c7a0d66ec22c66331. I can't get a link to pkg.go.dev for this for some reason.

**Comment by anacrolix** [comment]
I think it's okay to spin up goroutines for each Torrent you want to watch and coordinate pushing those in to a channel of completion if you want. I wouldn't want to implement it otherwise unless there were serious performance implications with the way it's done now.
