### ISSUE TITLE
ClientConfig Logger should be used for utp

### ISSUE THREAD

**Issue by anacrolix** [anacrolix/torrent#676]
Per https://github.com/anacrolix/torrent/issues/332#issuecomment-927179066, the ClientConfig Logger should be passed through to go-libutp (and possibly anacrolix/utp when that's in use?). Currently it's necessary to modify the global Logger instance manually, and that belongs to the package, not to any utp instances owned by a torrent Client.

**Comment by FIGBERT** [comment]
I'm looking to write a PR to implement the ClientConfig passthrough, but not sure exactly where to start.

Would changing `utp.Logger` before the initial call to `utp` be sufficient? How can I access `ClientConfig.Logger` from `utp_libutp.go`?

**Comment by anacrolix** [comment]
I think it shoudl be passed through in construction of the utp.Socket. Probably an option in NewSocket, or a method to set it immediately. It will need to be extracted from the owning Socket for any logging that occurs in utp. I.e. the global utp Logger should be given to a new socket that doesn't override the default, and should not be referenced anywhere else.

**Comment by FIGBERT** [comment]
Once anacrolix/go-libutp releases a new version (see: anacrolix/go-libutp#19), I'll start work on a PR here.

**Comment by anacrolix** [comment]
I pushed v1.2.0 for this purpose. Thanks @FIGBERT .
