### ISSUE TITLE
pkg.go.dev not working with anacrolix/torrent 

### ISSUE THREAD

**Issue by varbhat** [anacrolix/torrent#682]
Starting from v1.33 , pkg.go.dev doesn't work properly with anacrolix/torrent . 

See :

https://pkg.go.dev/github.com/anacrolix/torrent@v1.34.0#Torrent.DownloadAll

vs

https://pkg.go.dev/github.com/anacrolix/torrent@v1.32.0#Torrent.DownloadAll

**Comment by anacrolix** [comment]
This is fixed in v1.35.0. Thank you @varbhat .

**Comment by varbhat** [comment]
@anacrolix ,

What was the issue?

**Comment by anacrolix** [comment]
https://github.com/golang/go/issues/49197
