### ISSUE TITLE
Implement BEP 55 Holepunch extension

### ISSUE THREAD

**Issue by anacrolix** [anacrolix/torrent#685]
https://www.bittorrent.org/beps/bep_0055.html

**Comment by anacrolix** [comment]
Looks like the extension is well supported:
![image](https://user-images.githubusercontent.com/988750/233314695-cfa03db2-d2d1-4c72-9dc7-1478dab0b1b8.png)

**Comment by anacrolix** [comment]
This is *not* easy.

**Comment by anacrolix** [comment]
Implemented in v1.51.0.

**Comment by rezad1393** [comment]
> Looks like the extension is well supported in the wild: ![image](https://user-images.githubusercontent.com/988750/233314695-cfa03db2-d2d1-4c72-9dc7-1478dab0b1b8.png)

how did you make that?
what is the software that connected to peers?
I am too noob to know but I like that data.

**Comment by anacrolix** [comment]
I had a very long running, well used instance of anacrolix/confluence running. The data was pulled from its debug vars.

**Comment by anacrolix** [comment]
> > I had a very long running, well used instance of anacrolix/confluence running. The data was pulled from its debug vars.
> 
> I am not a pro so I ask to for clarification. that instance was a bittorrent to http bridge thing?
> 
Yes
> are those parameters inside a '.torrent' file? (which I think they are not) so if I open a torrent file I can see those parameters?
No they're client specific.
> 
> or are they a network capability thing, as in they need to be supported by the dht software running (for example a torrent client)
Yep.
> 
> so you are actually tracking how many dht software(instances) supports which extensions?
Only the ones that contact my long-running instance. These extensions aren't exposed in the DHT protocol, although some of them may be related.

**Comment by rezad1393** [comment]
> Only the ones that contact my long-running instance. These extensions aren't exposed in the DHT protocol, although some of them may be related.

I am not pro so I ask again a bit more specific.
you say that it is not a part of dht protocol. but I thought bittoorent was based on dht protocol for trackerless way of doing things.
are you saying that a BT client a connect to you via dht first then when that is done, BT client  via bottorrent protocol(?) send additional stuff over that expose what extensionss they support?
