### ISSUE TITLE
Allow to set custom readahead function for Reader

### ISSUE THREAD

**Issue by vintikzzz** [anacrolix/torrent#687]
It will be great to be possible to setup custom readahead function for Reader. Current linear implementation is great, but I want to have the ability to customize it (add multiplication in some cases and set upper limit).

**Comment by anacrolix** [comment]
@vintikzzz could you try https://github.com/anacrolix/torrent/tree/readahead-func? Let me know if it works for you.

**Comment by vintikzzz** [comment]
@anacrolix not so much, currently I don't have access to `Reader.pos` and `Reader.contiguousReadStartPos` fields to implement required behaviour. Is it possible to add public getters for them?

**Comment by anacrolix** [comment]
It is possible to compute those by wrapping the Reader to track them yourself. But it seems reasonable to provide some context to the readahead func. Check the updated branch.

**Comment by vintikzzz** [comment]
@anacrolix context is a great option, it really works for me! Thanks! Could you merge it to master branch?
