### ISSUE TITLE
torrentfs doesn't work with macfuse 4 or macos 12

### ISSUE THREAD

**Issue by anacrolix** [anacrolix/torrent#688]
`./cmd/torrentfs` and the `./fs` package use `bazil.org/fuse`, which discontinues support for osxfuse and macfuse. So far we've pinned against an old version that supports osxfuse 3. However with MacOS 12, MacFUSE 4 is required.

Based on the discussion at https://github.com/restic/restic/issues/3096, switching to https://github.com/billziss-gh/cgofuse looks like the best solution for MacOS. `torrentfs` continues to work with Linux, `cgofuse` would add support for Windows.

**Comment by yarikk** [comment]
CGO… I can't help but ask to keep everything CGO optional.

**Comment by anacrolix** [comment]
This was fixed in 8a7ddab78557cf4243400980a1c4f65f43e989cc. No cgo is required.
