### ISSUE TITLE
Prioritization issue in torrent

### ISSUE THREAD

**Issue by tsynik** [anacrolix/torrent#698]
@anacrolix, we used torrent in our web server to stream high bitrate videos from memory. There was possibility to prioritize further blocks with setPriority and they were downloaded in such order: (A|N)-Actual/Next, (R)-Readahead, (H)-High Priority and (N)-Normal. With latest builds for example H and R blocks loaded faster then N and even A - and there is video streaming issue because A block must be completed before play cursor. Last version TorrServer loaded blocks as expected was probably 1.34.0 (not sure). Is there a way to implement piece load order in current torrent code?
https://github.com/YouROK/TorrServer/blob/d4744e2e4751449ba1551bf2c219a62125233d33/server/torr/storage/torrstor/cache.go#L255-L278
https://github.com/YouROK/TorrServer/blob/d4744e2e4751449ba1551bf2c219a62125233d33/server/torr/storage/torrstor/cache.go#L353-L365
![L1](https://user-images.githubusercontent.com/1551446/146687909-4a9c248c-d7b2-47f9-ad4c-206c9cd4acfa.png)
![L2](https://user-images.githubusercontent.com/1551446/146687917-2fa407be-72a7-4d52-83b6-f83ae39395fa.png)

**Comment by anacrolix** [comment]
Thanks for the issue, I'm looking in to this.

**Comment by anacrolix** [comment]
The newest request algorithm spreads requests out so that no chunk is requested more than once, and the highest priority blocks are allocated first. However it will not reassign blocks unless it has no choice. If you prioritize a lot of pieces/all of a torrent, it's very difficult to reach that condition where chunk are reassigned. One work around that I'm considering is to only assign progressively larger numbers of chunks as a connection demonstrates its performance, and capping it to an amount that has served in a previous time window (say 3 to 10s). You might consider only reading ahead a smaller amount, and not prioritizing the entire torrent above None.

**Comment by tsynik** [comment]
> The newest request algorithm spreads requests out so that no chunk is requested more than once, and the highest priority blocks are allocated first.

But it's not clear for me, why even on load 1st 8/16MB of torren data (1s screen) there is also such behaviour as last readahead block loaded faster than 1st one. We don't set any priorities on preload, only readahead window in TorrServer.

**Comment by anacrolix** [comment]
It could happen like that if a bad/slow peer starves out the faster peers. Even if a slower peer is assigned pieces that are initially at the end of the readahead window, if the reader progresses up to that point and the slow peer is still working, it will now be the one allocated the highest priority blocks and won't relinquish those (unless other peers have no alternative but to steal its chunks). So try the workarounds suggested above in the meanwhile. Also note your TorrServer piece prioritization isn't necessary unless you really want to micromanage it. The builtin Reader does this too, and also provides an overridable readahead window.

**Comment by anacrolix** [comment]
I'll post a link to a branch that I'm experimenting with a fix for this soon.

**Comment by anacrolix** [comment]
Could you try https://github.com/anacrolix/torrent/tree/go1.18?

**Comment by tsynik** [comment]
> Could you try https://github.com/anacrolix/torrent/tree/go1.18?
Thanks, i'll try, is go 1.18 required to build? I have this error with 1.17.5 - package constraints is not in GOROOT

**Comment by anacrolix** [comment]
Yes it requires go 1.18

**Comment by tsynik** [comment]
> I'll post a link to a branch that I'm experimenting with a fix for this soon.

Build is OK with go 1.18 and I removed priorities management in TorrServer (so now only readahead matters), according to TorrServer web go 1.18 branch have better connections disribution, but i still have video freeze on slow connection and not fully loaded block near cursor, look at those torrent data cache screens (both done when video stuck):
![LOAD1](https://user-images.githubusercontent.com/1551446/147194482-4492e911-d75c-4941-b426-c8b4c2bf5f7d.png)
![LOAD2](https://user-images.githubusercontent.com/1551446/147194494-87d940cb-3dd5-4cf0-9e64-55da5793129d.png)

**Comment by tsynik** [comment]
> It could happen like that if a bad/slow peer starves out the faster peers. Even if a slower peer is assigned pieces that are initially at the end of the readahead window, if the reader progresses up to that point and the slow peer is still working, it will now be the one allocated the highest priority blocks and won't relinquish those (unless other peers have no alternative but to steal its chunks). So try the workarounds suggested above in the meanwhile. Also note your TorrServer piece prioritization isn't necessary unless you really want to micromanage it. The builtin Reader does this too, and also provides an overridable readahead window.

The idea of readehead cache was to eliminate torrent load slowdown on not stable connections for smooth video streaming. User can set any amount of available memory or disk storage and fill this ahead while streaming if current speed and peers amount allow. Without setPriorities it loads only few readahead blocks after play cursor. With it full configurable cache amount loaded if possible while playing in current TorrServer cache implementation. This works fine with older torrent codebase.

**Comment by tsynik** [comment]
> This might be one solution to #698.
Looks like with last commit blocks loaded fine according to priorities set. Thanks!

**Comment by anacrolix** [comment]
Thank you! A lot of effort has gone into performance recently.

**Comment by anacrolix** [comment]
There are 2 specific changes that could address this issue, one is 112e9b27551b007d18c8628892907fa0ff3e9812, which should reduce the impact that stalling peers can have. The other is 9cf5f66d62739b8ef00dc6526f6fed7baf058f14, which will allow fast connections to steal more requests, especially at higher priorities. I have both on the go1.18 branch. I guess I can keep using both, I'm mindful of wasted downloads, a huge effort has been to reduce the amount of duplicate chunks received. I didn't notice any significant degradation with the latter.

How did you go with go1.18? Clearly it's problematic for people still on 1.17 or less.

**Comment by anacrolix** [comment]
I've pushed these changes in to master, without the dependence on go1.18.

**Comment by tsynik** [comment]
> I've pushed these changes in to master, without the dependence on go1.18.

It works fine with master on go 1.17 now too, few issues:

can you change those messages from reader.go:251-254 to DEBUG level, they spam log alot
https://github.com/anacrolix/torrent/runs/4622254598?check_suite_focus=true

in TorrServer, when user rewind to blocks which was loaded before and have been cleared from cache, peers served it will be banned. Can you add config option to disable IP ban for client?
https://github.com/anacrolix/torrent/blob/fc857d455766421ce1af7fc39360cbea65e7e9ef/torrent.go#L2010

**Comment by anacrolix** [comment]
I will tentatively close this. I'm monitoring to see if the changes affect performance or download duplication.
