### ISSUE TITLE
HTTP unknown tracker scheme

### ISSUE THREAD

**Issue by jzelinskie** [anacrolix/torrent#7]
steps to reproduce: 
```
$ wget http://releases.ubuntu.com/14.04.2/ubuntu-14.04.2-desktop-amd64.iso.torrent
$ torrent ubuntu-14.0.4-2-desktop-amd64.iso.torrent
2015/03/24 20:35:16 client.go:1964: error creating tracker client for "http://torrent.ubuntu.com:6969/announce": unknown scheme
2015/03/24 20:35:16 client.go:1964: error creating tracker client for "http://ipv6.torrent.ubuntu.com:6969/announce": unknown scheme
```

**Comment by anacrolix** [comment]
I never implemented HTTP trackers, because UDP seems present for most torrents. I welcome a patch for this! The interface to be implemented is at http://godoc.org/github.com/anacrolix/torrent/tracker, and UDP can be used as a reference.

Thank you for the issue report.

**Comment by anacrolix** [comment]
I've half completed this.

**Comment by anacrolix** [comment]
HTTP trackers now work. Interestingly I've found that my use of the older 14.04.1 iso in the example gives an error from Ubuntu's tracker, because the ISO is out of date.

**Comment by jzelinskie** [comment]
Yep, that's why my example is using 14.04.2 :P
