### ISSUE TITLE
Is there anyway to config a peer to continue seeding for a certain time after downloaded the whole file?

### ISSUE THREAD

**Issue by half-dead** [anacrolix/torrent#70]
The point of this is to avoid high traffic load on the original seeder when there are a lot of peers need to download the same file.

**Comment by anacrolix** [comment]
I think you want `torrent.Config.Seed = true`? https://godoc.org/github.com/anacrolix/torrent#Config

By default, a Client will upload slightly more than it downloads from any given connection, to cooperate with the network. With Seed set to true, Clients will upload without limit. There's no current way to limit seeding to a period after completion, other than to remove the torrent from the client some time after the the torrent is completely downloaded.

**Comment by half-dead** [comment]
Any chance supporting this? I can think of something like add a new cmd argument '--seed-for=30s'

**Comment by anacrolix** [comment]
Can you manage with dropping the torrent after seeding for a period? Are you exclusively using cmd/torrent, or the programmatic interface as well?

**Comment by half-dead** [comment]
I'm using the programmatic interface, looks like simple set seed to true and sleep for 30 seconds after client.WaitAll() will do the trick.

**Comment by anacrolix** [comment]
Your proposed flag to cmd/torrent that does this would be welcome.
