### ISSUE TITLE
Logging in TorrServer

### ISSUE THREAD

**Issue by anacrolix** [anacrolix/torrent#702]
> I've pushed these changes in to master, without the dependence on go1.18.

It works fine with master on go 1.17 now too, few issues:

can you change those messages from reader.go:251-254 to DEBUG level, they spam log alot
https://github.com/anacrolix/torrent/runs/4622254598?check_suite_focus=true
https://github.com/anacrolix/torrent/blob/fc857d455766421ce1af7fc39360cbea65e7e9ef/reader.go#L251-L255

in TorrServer, when user rewind to blocks which was loaded before and have been cleared from cache, peers served it will be banned. Can you add config option to disable IP ban for client?
https://github.com/anacrolix/torrent/blob/fc857d455766421ce1af7fc39360cbea65e7e9ef/torrent.go#L2010

_Originally posted by @tsynik in https://github.com/anacrolix/torrent/issues/698#issuecomment-1000604159_

**Comment by anacrolix** [comment]
@tsynik 

I also get the first message, I have a storage implementation that makes use of storage.TorrentImpl.Capacity. Do you know if your implementation is also doing this? It would make obvious sense to detect that a storage implementation would expect to drop pieces and lower or ignore the log in this case.

The second message I don't see. I suspect if your storage communications completeness correctly, you shouldn't see it. Are you getting that message?

The banning should only occur if a piece failed to hash and there was no error copying the data from storage. Does your storage implementation return errors for pieces that have been dropped? Could you reference me to the storage implementation you are using?

**Comment by tsynik** [comment]
> The second message I don't see. I suspect if your storage communications completeness correctly, you shouldn't see it. Are you getting that message?
> 
> The banning should only occur if a piece failed to hash and there was no error copying the data from storage. Does your storage implementation return errors for pieces that have been dropped? Could you reference me to the storage implementation you are using?

Here is TorServer peace.Release
https://github.com/YouROK/TorrServer/blob/e7c397116d79b12367efd043ea1ba90fb9516a73/server/torr/storage/torrstor/piece.go#L71-L81
memPeace.Release
https://github.com/YouROK/TorrServer/blob/e7c397116d79b12367efd043ea1ba90fb9516a73/server/torr/storage/torrstor/mempiece.go#L62-L70
and this is our Cache implementation:
https://github.com/YouROK/TorrServer/blob/master/server/torr/storage/torrstor/cache.go

cache cleaning done with clearPriority() there with setPrioriy.peacePriorityNone and in cleanPeaces()

**Comment by anacrolix** [comment]
Could there be a race between a reader trying to read something that your cache has decided to evict? Your piece ReadAt implementation looks right from a quick look. Is it possible pieces are evicted before they are downloaded entirely? That could lead to the state where the piece check fails because the piece was cleared, but the Client still retains the list of "dirtiers". It's possible the workaround for all this would be to implement smart ban, which shouldn't have false positives for banning peers.

**Comment by anacrolix** [comment]
The last item, in the image. Could the Torrent be already closed when Piece.UpdateCompletion is called?

**Comment by tsynik** [comment]
> The last item, in the image. Could the Torrent be already closed when Piece.UpdateCompletion is called?

there is check for c.isClosed in removePiece but maybe i's not always help ;-)
https://github.com/YouROK/TorrServer/blob/e7c397116d79b12367efd043ea1ba90fb9516a73/server/torr/storage/torrstor/cache.go#L117-L121

**Comment by tsynik** [comment]
> Is it possible pieces are evicted before they are downloaded entirely? That could lead to the state where the piece check fails because the piece was cleared, but the Client still retains the list of "dirtiers". It's possible the workaround for all this would be to implement smart ban, which shouldn't have false positives for banning peers.

@anacrolix yes, that's possible as TorrSerer operates with 64MB cache window, and when user forward / rewind  in video player, even blocks which not completed yet outside new cache window marked with PrioriyNone and cleared from cache.

**Comment by anacrolix** [comment]
The IP banning config and smart ban are spun out into new issues. The noisy logging left in this issue has a fix in f7494791d03dceb8968188bb0e8d152e0e23018c. Let me know if this works for you, it might require that you implement storage.TorrentImpl.Capacity so the client can make smarter decisions about the use of your cache, including logging levels per the commit.

**Comment by tsynik** [comment]
> The noisy logging left in this issue has a fix in [f749479](https://github.com/anacrolix/torrent/commit/f7494791d03dceb8968188bb0e8d152e0e23018c). Let me know if this works for you, it might require that you implement storage.TorrentImpl.Capacity so the client can make smarter decisions about the use of your cache, including logging levels per the commit.

Yup, this commit reduce log, but I still have lines about  error reading torrent %s piece %d offset %d, %d bytes: %v" and piece %d completion unchanged, maybe because we use reader with pieceComplete check commented at lines 105-107: https://github.com/anacrolix/torrent/blob/31243ad4fd1b12e26261e81706f65ecc09751e56/reader.go#L105-L107

Here is the debug logging patch for it
[0001-log-update.patch.txt](https://github.com/anacrolix/torrent/files/7850792/0001-log-update.patch.txt)

**Comment by anacrolix** [comment]
@tsynik do you want to contribute those as a PR?

**Comment by tsynik** [comment]
> @tsynik do you want to contribute those as a PR?

@anacrolix I made this as a patch because I already have torrent fork in my repo used for builds with old codebase and dunno how to make another one ;-) there is only few lines changed.

**Comment by anacrolix** [comment]
@tsynik The mute reader patch was done independently in [5a61d8f6ac937636f8253b254bf1be0c4cca0621](https://github.com/anacrolix/torrent/commit/a324fbfee3f3a9f134a75e15e13bbeb0c3dcefd8). I applied your other patch in 9434fe58a2bc3b6deb360713b015110dfa31794c.
