### ISSUE TITLE
Download Rate Limits accounted twice

### ISSUE THREAD

**Issue by AskAlexSharov** [anacrolix/torrent#707]
version 1.40.0

```
const downloadRate = 2Mb
const PieceSize = 1Mb
torrentConfig.DownloadRateLimiter = rate.NewLimiter(rate.Limit(downloadRate), 2* PieceSize) // default: unlimited
```
And see 4Mb/s on network monitor. 

So, RateLimiter works, but looks like accounting done twice. 
(I didn't test upload limiter yet)

**Comment by anacrolix** [comment]
I don't see this behaviour. I am operating a VPN, which seems to see about double the traffic that is received on the interface the client is operating, but that seems to check out correctly and download the amoun it claims.

I'm running with `godo -race ~/go/src/github.com/anacrolix/torrent/cmd/torrent download ~/go/src/github.com/anacrolix/torrent/testdata/sintel.torrent --download-rate 250K` to simulate your constraints.

**Comment by AskAlexSharov** [comment]
Can it be related to 2Mb "burst"? 
I will try to test it again with different values today

**Comment by anacrolix** [comment]
Yes, I believe the default burst is now about 64K, try with something like that.

**Comment by AskAlexSharov** [comment]
Let's close it for now. I will have time to re-check - bit later.
