### ISSUE TITLE
Counter for chunks uploaded

### ISSUE THREAD

**Issue by terrorbyte** [anacrolix/torrent#71]
I've been using this for a while now with some tweaks, one thing I've found most useful was to have a counter for the chunks uploaded, but my implementation leaves a lot to be desired and is incredibly error prone. An official implementation would be excellent and think might help solve some issues people have with seeding to a certain ratio.

**Comment by terrorbyte** [comment]
My implementation adds a integer to the client type and whenever a sendChunk successfully completes it increases the counter and then I expose a ChunksSent to t.go to retrieve that value. If you are interested I will submit a pull request, but I feel like this is a bit of a deviation from your design.

**Comment by anacrolix** [comment]
I have plans to expose {Client.Torrent,Connection}Status blocks with information similar to what's available in WriteStatus in the future. If you're implementing chunks sent on the torrent in the near term, you may find connection.chunksSent a useful place to start. Additionally with regard to the upload ratio, I think you want piece data bytes sent, not necessarily chunks.

**Comment by glutamatt** [comment]
Hi @anacrolix : 😊 thanks for your torrent go implementation
I plan to use it with a private tracker but i'm a bit concerned about the ratio reporting.
The values `Downloaded` and `Uploaded` seems to be from `AnnounceRequest` struct but never set.
If zero is sent as uploaded value, i will be banned so fast 🚔 !
🤔 Am i missing something ?

**Comment by anacrolix** [comment]
I'll look into it soon.
