### ISSUE TITLE
IPv6 doesn't work well with peers

### ISSUE THREAD

**Issue by avengermsoft** [anacrolix/torrent#713]
Hi!

I add distribution with hash "c368b46f53ffe9ee71d8609119b10c956bd6eef1". Anacrolix selects ipv6 peers poorly, very rarely there is an exchange over ipv6 with a peer. On other torrent-clients (utorrent,tixary or other), the exchange is actively going on ipv6.

<details>
<summary>anacrolix / torrent peer information</summary>
Listen port: 993
Peer ID: "-qB4390-KL67YBZBQJSU"
Extension bits: 0000000000100005
Announce key: 514a5355
Banned IPs: 0
udp DHT server at 0.0.0.0:993:
 ID: a8b5b961ec48d4970c779cb63f49c8e96f343168
(dht.ServerStats) {
 GoodNodes: (int) 23,
 Nodes: (int) 211,
 OutstandingTransactions: (int) 0,
 SuccessfulOutboundAnnouncePeerQueries: (int64) 32,
 BadNodes: (uint) 0,
 OutboundQueriesAttempted: (int64) 371
}
udp DHT server at [::]:993:
 ID: ac512c3a75c29af38a03d0c966798cbf06a18183
(dht.ServerStats) {
 GoodNodes: (int) 7,
 Nodes: (int) 163,
 OutstandingTransactions: (int) 0,
 SuccessfulOutboundAnnouncePeerQueries: (int64) 30,
 BadNodes: (uint) 0,
 OutboundQueriesAttempted: (int64) 382
}
(*torrent.ConnStats)(0x4000583c00)({
 BytesWritten: (torrent.Count) 1316806,
 BytesWrittenData: (torrent.Count) 0,
 BytesRead: (torrent.Count) 702758548,
 BytesReadData: (torrent.Count) 701909343,
 BytesReadUsefulData: (torrent.Count) 624363871,
 BytesReadUsefulIntendedData: (torrent.Count) 623380831,
 ChunksWritten: (torrent.Count) 0,
 ChunksRead: (torrent.Count) 42842,
 ChunksReadUseful: (torrent.Count) 38109,
 ChunksReadWasted: (torrent.Count) 4733,
 MetadataChunksRead: (torrent.Count) 4,
 PiecesDirtiedGood: (torrent.Count) 149,
 PiecesDirtiedBad: (torrent.Count) 0
})
# Torrents: 1

Eternals.2021.MVO.IMAX.WEB-DLRip.DD.5.1.x264.MegaPeer.mkv
6.183463% of 3585542495 bytes (3.6 GB)
Infohash: c368b46f53ffe9ee71d8609119b10c956bd6eef1
Metadata length: 17226
Piece length: 4194304 (256 chunks)
Num Pieces: 855 (53 completed)
Piece States: 2C 96 50C 706 1C
Piece availability frequency: 25: 855
Reader Pieces: 101:106
Enabled trackers:
    URL                                                  Extra
    "udp4://109.72.83.209:80/announce"                   next ann: 11m38s, last ann: 2 peers
    "udp6://109.72.83.209:80/announce"                   next ann: 38s, last ann: error getting ip: no acceptable ips
    "udp4://148.251.53.72:6969/announce"                 next ann: 14m29s, last ann: 22 peers
    "udp6://148.251.53.72:6969/announce"                 next ann: 38s, last ann: error getting ip: no acceptable ips
    "udp4://151.80.120.113:2810/announce"                next ann: 11m45s, last ann: 25 peers
    "udp6://151.80.120.113:2810/announce"                next ann: 38s, last ann: error getting ip: no acceptable ips
    "udp4://151.80.120.115:2810/announce"                next ann: 11m48s, last ann: 25 peers
    "udp6://151.80.120.115:2810/announce"                next ann: 38s, last ann: error getting ip: no acceptable ips
    "udp4://152.231.114.171:1337/announce"               next ann: 14m24s, last ann: 23 peers
    "udp6://152.231.114.171:1337/announce"               next ann: 38s, last ann: error getting ip: no acceptable ips
    "udp4://156.234.201.18:80/announce"                  next ann: 9m6s, last ann: 22 peers
    "udp6://156.234.201.18:80/announce"                  next ann: 38s, last ann: error getting ip: no acceptable ips
    "udp4://163.172.170.127:6969/announce"               next ann: 11m48s, last ann: 20 peers
    "udp6://163.172.170.127:6969/announce"               next ann: 38s, last ann: error getting ip: no acceptable ips
    "udp4://184.105.151.166:6969/announce"               next ann: 16m39s, last ann: 9 peers
    "udp6://184.105.151.166:6969/announce"               next ann: 38s, last ann: error getting ip: no acceptable ips
    "udp4://186.10.181.71:1337/announce"                 next ann: 23s, last ann: announcing: context deadline exceeded
    "udp6://186.10.181.71:1337/announce"                 next ann: 38s, last ann: error getting ip: no acceptable ips
    "udp4://198.100.149.66:6969/announce"                next ann: 8m59s, last ann: 23 peers
    "udp6://198.100.149.66:6969/announce"                next ann: 38s, last ann: error getting ip: no acceptable ips
    "http://198.251.84.144:80/announce"                  next ann: 23s, last ann: announcing: Get "http://198.251.84.144:80/announce?compact=1&downloaded=611780959&info_hash=%C3h%B4oS%FF%E9%EEq%D8%60%91%19%B1%0C%95k%D6%EE%F1&key=1363825493&left=3363831808&peer_id=-qB4390-KL67YBZBQJSU&port=993&supportcrypto=1&uploaded=0": context deadline exceeded
    "udp4://207.241.226.111:6969/announce"               next ann: 9m37s, last ann: 9 peers
    "udp6://207.241.226.111:6969/announce"               next ann: 38s, last ann: error getting ip: no acceptable ips
    "udp4://207.241.231.226:6969/announce"               next ann: 13m4s, last ann: 9 peers
    "udp6://207.241.231.226:6969/announce"               next ann: 38s, last ann: error getting ip: no acceptable ips
    "udp4://208.83.20.20:6969/announce"                  next ann: 12m32s, last ann: 200 peers
    "udp6://208.83.20.20:6969/announce"                  next ann: 38s, last ann: error getting ip: no acceptable ips
    "udp4://45.14.225.8:1337/announce"                   next ann: 11m38s, last ann: 100 peers
    "udp6://45.14.225.8:1337/announce"                   next ann: 38s, last ann: error getting ip: no acceptable ips
    "udp4://45.154.253.10:6969/announce"                 next ann: 12m12s, last ann: 64 peers
    "udp6://45.154.253.10:6969/announce"                 next ann: 38s, last ann: error getting ip: no acceptable ips
    "http://45.154.253.10:80/announce"                   next ann: 12m17s, last ann: 50 peers
    "udp4://45.154.253.6:6969/announce"                  next ann: 9m18s, last ann: 52 peers
    "udp6://45.154.253.6:6969/announce"                  next ann: 38s, last ann: error getting ip: no acceptable ips
    "udp4://46.4.101.245:80/announce"                    next ann: 9m55s, last ann: 200 peers
    "udp6://46.4.101.245:80/announce"                    next ann: 38s, last ann: error getting ip: no acceptable ips
    "http://51.38.230.101:80/announce"                   next ann: 11m39s, last ann: 1 peers
    "udp4://62.210.217.207:1337/announce"                next ann: 12m32s, last ann: 21 peers
    "udp6://62.210.217.207:1337/announce"                next ann: 38s, last ann: error getting ip: no acceptable ips
    "udp4://65.108.63.133:80/announce"                   next ann: 11m36s, last ann: 25 peers
    "udp6://65.108.63.133:80/announce"                   next ann: 38s, last ann: error getting ip: no acceptable ips
    "udp4://89.234.156.205:451/announce"                 next ann: 11m45s, last ann: 27 peers
    "udp6://89.234.156.205:451/announce"                 next ann: 38s, last ann: error getting ip: no acceptable ips
    "udp4://91.216.110.52:451/announce"                  next ann: 12m48s, last ann: 0 peers
    "udp6://91.216.110.52:451/announce"                  next ann: 38s, last ann: error getting ip: no acceptable ips
    "udp4://93.158.213.92:1337/announce"                 next ann: 10m48s, last ann: 56 peers
    "udp6://93.158.213.92:1337/announce"                 next ann: 38s, last ann: error getting ip: no acceptable ips
    "http://bt.svao-ix.ru/announce"                      next ann: 24s, last ann: announcing: Get "http://bt.svao-ix.ru/announce?compact=1&downloaded=611780959&info_hash=%C3h%B4oS%FF%E9%EEq%D8%60%91%19%B1%0C%95k%D6%EE%F1&key=1363825493&left=3363831808&peer_id=-qB4390-KL67YBZBQJSU&port=993&supportcrypto=1&uploaded=0": dial tcp 89.222.192.204:80: i/o timeout
    "http://bt4.t-ru.org/ann?magnet"                     next ann: 40s, last ann: announcing: tracker gave failure reason: "Torrent not registered"
    "udp4://explodie.org:6969/announce"                  next ann: 16m39s, last ann: 9 peers
    "udp6://explodie.org:6969/announce"                  next ann: 45s, last ann: announcing: unexpected response action 4
    "udp4://opentor.org:2710"                            next ann: 14m20s, last ann: 0 peers
    "udp6://opentor.org:2710"                            next ann: 9m48s, last ann: 2 peers
    "udp4://public.popcorn-tracker.org:6969/announce"    next ann: 23s, last ann: announcing: context deadline exceeded
    "udp6://public.popcorn-tracker.org:6969/announce"    next ann: 23s, last ann: announcing: context deadline exceeded
    "http://retracker.local"                             next ann: 39s, last ann: error getting ip: lookup retracker.local on 192.168.97.97:53: no such host
    "http://retracker.local/announce"                    next ann: 39s, last ann: error getting ip: lookup retracker.local on 192.168.97.97:53: no such host
    "http://retracker.mgts.by:80/announce"               next ann: 24s, last ann: announcing: Get "http://82.209.230.66:80/announce?compact=1&downloaded=611780959&info_hash=%C3h%B4oS%FF%E9%EEq%D8%60%91%19%B1%0C%95k%D6%EE%F1&key=1363825493&left=3363831808&peer_id=-qB4390-KL67YBZBQJSU&port=993&supportcrypto=1&uploaded=0": context deadline exceeded
    "http://tracker.city9x.com:2710/announce"            next ann: 41s, last ann: announcing: Get "http://[2607:fad0:3801:4::1]:2710/announce?compact=1&downloaded=620169567&info_hash=%C3h%B4oS%FF%E9%EEq%D8%60%91%19%B1%0C%95k%D6%EE%F1&key=1363825493&left=3363831808&peer_id=-qB4390-KL67YBZBQJSU&port=993&supportcrypto=1&uploaded=0": dial tcp [2607:fad0:3801:4::1]:2710: connect: connection refused
    "http://tracker.electro-torrent.pl:80/announce"      next ann: 24s, last ann: announcing: Get "http://62.210.202.61:80/announce?compact=1&downloaded=611780959&info_hash=%C3h%B4oS%FF%E9%EEq%D8%60%91%19%B1%0C%95k%D6%EE%F1&key=1363825493&left=3363831808&peer_id=-qB4390-KL67YBZBQJSU&port=993&supportcrypto=1&uploaded=0": context deadline exceeded
    "http://tracker.internetwarriors.net:1337/announce"  next ann: 22m32s, last ann: 21 peers
    "udp4://tracker.opentrackr.org:1337/announce"        next ann: 13m55s, last ann: 0 peers
    "udp6://tracker.opentrackr.org:1337/announce"        next ann: 39s, last ann: error getting ip: no acceptable ips
    "http://tracker2.itzmx.com:6961/announce"            next ann: 24s, last ann: announcing: Get "http://163.196.200.1:6961/announce?compact=1&downloaded=611780959&info_hash=%C3h%B4oS%FF%E9%EEq%D8%60%91%19%B1%0C%95k%D6%EE%F1&key=1363825493&left=3363831808&peer_id=-qB4390-KL67YBZBQJSU&port=993&supportcrypto=1&uploaded=0": context deadline exceeded
DHT Announces: 8
(torrent.TorrentStats) {
 ConnStats: (torrent.ConnStats) {
  BytesWritten: (torrent.Count) 1316806,
  BytesWrittenData: (torrent.Count) 0,
  BytesRead: (torrent.Count) 702758548,
  BytesReadData: (torrent.Count) 701909343,
  BytesReadUsefulData: (torrent.Count) 624363871,
  BytesReadUsefulIntendedData: (torrent.Count) 623380831,
  ChunksWritten: (torrent.Count) 0,
  ChunksRead: (torrent.Count) 42842,
  ChunksReadUseful: (torrent.Count) 38109,
  ChunksReadWasted: (torrent.Count) 4733,
  MetadataChunksRead: (torrent.Count) 4,
  PiecesDirtiedGood: (torrent.Count) 149,
  PiecesDirtiedBad: (torrent.Count) 0
 },
 TotalPeers: (int) 426,
 PendingPeers: (int) 401,
 ActivePeers: (int) 25,
 ConnectedSeeders: (int) 25,
 HalfOpenPeers: (int) 0,
 PiecesComplete: (int) 53
}
 1. "MG-3.01.4113NgB((lEC"                                  0000000000180005 192.168.97.98:40152-95.53.13.18:31126
    bep40-prio: c6a10942
    last msg: 35.87s ago, connected: 36.15s ago, last helpful: never, itime: 36.087175004s, etime: 0s
    855/855 completed, 0 pieces touched, good chunks: 0/0:0 reqq: 0+0/(1/500):0/32, flags: ic-eHg-c, dr: 0.0 KiB/s
    requested pieces:
 2. "-UT354S-X\xae\x87\x1d+}\u007f\r\xf7\x97-%"             0000000000100005 192.168.97.98:39690-178.94.156.65:26058
    bep40-prio: c3d6c6e1
    last msg: 1.24s ago, connected: 34.06s ago, last helpful: never, itime: 17.293893438s, etime: 537.922693ms
    855/855 completed, 0 pieces touched, good chunks: 0/1:0 reqq: 0+0/(1/255):0/32, flags: c-eHg-c, dr: 0.0 KiB/s
    requested pieces:
 3. "-TR2130-nnuc4hge11ta"                                  0000000000100005 192.168.97.98:993-85.175.186.100:43424
    bep40-prio: f76b6ac2
    last msg: 3.54s ago, connected: 879.16s ago, last helpful: 3.54s ago, itime: 14m31.628499301s, etime: 39.921294794s
    855/855 completed, 0 pieces touched, good chunks: 73/85:0 reqq: 0+0/(1/512):0/32, flags: ic-EI-, dr: 29.3 KiB/s
    requested pieces:
 4. "-UT355W-\x10\xb4\t\x1c\x88\x04\xad\xa3H\xbbY$"         0000000000100005 192.168.97.98:50964-94.45.98.39:23430
    bep40-prio: d4870c69
    last msg: 3.21s ago, connected: 89.59s ago, last helpful: 3.78s ago, itime: 1m26.183170694s, etime: 474.594779ms
    855/855 completed, 0 pieces touched, good chunks: 2/3:0 reqq: 0+0/(1/255):0/32, flags: c-eHg-c, dr: 67.4 KiB/s
    requested pieces:
 5. "-UT355W-\x10\xb4\xcb0\x97\x05\xa7\xecP\x03_\xfb"       0000000000100005 192.168.97.98:42884-83.29.40.10:60798
    bep40-prio: dfa4a042
    last msg: 3.41s ago, connected: 115.84s ago, last helpful: 19.81s ago, itime: 52.355470218s, etime: 1.806276935s
    855/855 completed, 0 pieces touched, good chunks: 12/18:0 reqq: 0+0/(1/255):0/32, flags: ic-eHg-, dr: 106.3 KiB/s
    requested pieces:
 6. "-UT355W-\x10\xb4\xa1\x80\xb0\xb7\xb8\x01\xbc\xfbZ\xe6" 0000000000100005 192.168.97.98:993-109.108.250.88:6297
    bep40-prio: b1d10d0f
    last msg: 51.52s ago, connected: 230.30s ago, last helpful: 53.32s ago, itime: 2m1.26922229s, etime: 3.739358219s
    855/855 completed, 0 pieces touched, good chunks: 26/37:0 reqq: 0+0/(1/255):0/32, flags: ic-eI-c, dr: 111.2 KiB/s
    requested pieces:
 7. "-UT355W-\x10\xb4\x88\xe3\xa7\xdfQ9\u0560\xb1\xec"      0000000000100005 192.168.97.98:43812-5.255.41.237:42542
    bep40-prio: dc6293be
    last msg: 3.08s ago, connected: 107.95s ago, last helpful: 35.85s ago, itime: 1m1.368787215s, etime: 1.589445779s
    855/855 completed, 0 pieces touched, good chunks: 16/18:0 reqq: 0+0/(1/255):0/32, flags: ic-eHg-c, dr: 161.1 KiB/s
    requested pieces:
 8. "-UT355W-\x10\xb4\xabL\xf9CMg'O\x80\x93"                0000000000100005 192.168.97.98:993-178.67.156.195:64641
    bep40-prio: b0bab3ca
    last msg: 1.85s ago, connected: 107.76s ago, last helpful: 3.56s ago, itime: 55.759046422s, etime: 1.961566494s
    855/855 completed, 0 pieces touched, good chunks: 21/31:0 reqq: 0+0/(1/255):0/32, flags: c-eI-c, dr: 171.3 KiB/s
    requested pieces:
 9. "-UT355W-\x10\xb4 \xb6\tp\xdc7-\xac\xae\x15"            0000000000100005 192.168.97.98:52834-46.98.121.170:44946
    bep40-prio: d33251a7
    last msg: 2.07s ago, connected: 77.95s ago, last helpful: 3.71s ago, itime: 46.235772799s, etime: 1.470929006s
    855/855 completed, 0 pieces touched, good chunks: 17/30:0 reqq: 0+0/(1/255):0/32, flags: c-eHg-c, dr: 184.9 KiB/s
    requested pieces:
10. "-UT355W-\x10\xb4\xb9|\xe4J\xc1\x8b\f{8\x8c"            0000000000100005 192.168.97.98:42170-46.166.200.4:51038
    bep40-prio: ea53fcce
    last msg: 2.13s ago, connected: 135.65s ago, last helpful: 3.66s ago, itime: 1m9.874335747s, etime: 3.334294751s
    855/855 completed, 0 pieces touched, good chunks: 43/58:0 reqq: 0+0/(1/255):0/32, flags: c-eHg-c, dr: 206.3 KiB/s
    requested pieces:
11. "-UW127L-YGFobF)iZH~l"                                  0000000000180005 192.168.97.98:993-195.26.18.109:62252
    bep40-prio: 5bdf4408
    last msg: 2.33s ago, connected: 395.93s ago, last helpful: 3.89s ago, itime: 38.878860546s, etime: 12.945336892s
    855/855 completed, 0 pieces touched, good chunks: 171/227:0 reqq: 0+0/(1/500):0/32, flags: c-eI-c, dr: 211.4 KiB/s
    requested pieces:
12. "-LT10B0-kF2VR5wTmWs3"                                  0000000000100005 192.168.97.98:993-46.242.10.59:16733
    bep40-prio: 19f2b0f0
    last msg: 3.45s ago, connected: 156.31s ago, last helpful: 3.63s ago, itime: 44.458855798s, etime: 5.115083807s
    855/855 completed, 0 pieces touched, good chunks: 87/123:0 reqq: 0+0/(1/500):0/32, flags: c-eI-c, dr: 272.1 KiB/s
    requested pieces:
13. "-UT351S-,\xad8|\x11`}\xfay^\xeb,"                      0000000000100005 192.168.97.98:46530-89.169.19.1:19451
    bep40-prio: cc945f17
    last msg: 20.87s ago, connected: 66.41s ago, last helpful: 53.31s ago, itime: 50.254082941s, etime: 367.029965ms
    855/855 completed, 0 pieces touched, good chunks: 7/8:0 reqq: 0+0/(1/255):0/32, flags: ic-eHg-c, dr: 305.2 KiB/s
    requested pieces:
14. "-UT355W-\x10\xb4\x99\x93i\x8cX\xcd\x01\xff/\xf6"       0000000000100005 192.168.97.98:993-37.147.207.5:55460
    bep40-prio: 7b0fdc43
    last msg: 1.83s ago, connected: 197.77s ago, last helpful: 3.57s ago, itime: 1m31.198845823s, etime: 3.09785321s
    855/855 completed, 0 pieces touched, good chunks: 77/89:0 reqq: 0+0/(1/255):0/32, flags: c-eI-c, dr: 397.7 KiB/s
    requested pieces:
15. "-qB4390-WK778XlDEIQ)"                                  0000000000180005 192.168.97.98:993-109.75.61.11:64748
    bep40-prio: 2514f40d
    last msg: 3.35s ago, connected: 458.40s ago, last helpful: 3.59s ago, itime: 3m13.782939498s, etime: 13.591991842s
    855/855 completed, 0 pieces touched, good chunks: 348/557:0 reqq: 0+0/(1/500):0/32, flags: c-EI-c, dr: 409.7 KiB/s
    requested pieces:
16. "-UT3490-\u0767\x9bl\xf0\xba\xefQ]\x86'K"               0000000000100005 192.168.97.98:993-178.205.57.230:49788
    bep40-prio: baa4e1ec
    last msg: 1.87s ago, connected: 480.81s ago, last helpful: 3.58s ago, itime: 4m50.838975813s, etime: 7.285107801s
    855/855 completed, 0 pieces touched, good chunks: 225/249:0 reqq: 0+0/(1/255):0/32, flags: c-eI-c, dr: 494.2 KiB/s
    requested pieces:
17. "MG-3.01.4119p_(gW8_o"                                  0000000000180005 192.168.97.98:993-195.88.143.142:60071
    bep40-prio: 02280049
    last msg: 3.51s ago, connected: 251.36s ago, last helpful: 3.68s ago, itime: 1m34.470758892s, etime: 8.522392878s
    855/855 completed, 0 pieces touched, good chunks: 267/375:0 reqq: 0+0/(1/500):0/32, flags: ic-eI-, dr: 501.3 KiB/s
    requested pieces:
18. "-UT355S-\x89\xb1\xf9Y\x0e\xabJX1/\xa2\xd4"             0000000000100005 192.168.97.98:38546-46.158.211.178:23687
    bep40-prio: b8477d13
    last msg: 3.42s ago, connected: 230.36s ago, last helpful: 19.83s ago, itime: 2m18.546576355s, etime: 4.223149834s
    855/855 completed, 0 pieces touched, good chunks: 150/161:0 reqq: 0+0/(1/255):0/32, flags: ic-eHg-, dr: 568.3 KiB/s
    requested pieces:
19. "-qB4400-bDckxiP4Md5I"                                  0000000000100005 192.168.97.98:993-5.44.168.173:62639
    bep40-prio: 58755c16
    last msg: 3.41s ago, connected: 624.70s ago, last helpful: 3.64s ago, itime: 5m34.732206343s, etime: 18.93629683s
    855/855 completed, 0 pieces touched, good chunks: 812/1118:0 reqq: 0+0/(1/2000):0/32, flags: c-EI-c, dr: 686.1 KiB/s
    requested pieces:
20. "-UT2210-\xbec\xff\xd8z\xed\x103#\xa6\xc7\xc0"          0000000000100005 192.168.97.98:993-109.252.93.78:26676
    bep40-prio: c0b8ae1d
    last msg: 3.36s ago, connected: 423.31s ago, last helpful: 19.78s ago, itime: 3m40.074415656s, etime: 9.092848096s
    855/855 completed, 0 pieces touched, good chunks: 623/685:0 reqq: 0+0/(1/255):0/32, flags: ic-EI-, dr: 1096.2 KiB/s
    requested pieces:
21. "MG-3.01.4118BSUMT9Vw"                                  0000000000180005 192.168.97.98:993-94.140.141.66:2516
    bep40-prio: cd10244f
    last msg: 3.36s ago, connected: 934.65s ago, last helpful: 3.50s ago, itime: 6m6.092895338s, etime: 37.076326965s
    855/855 completed, 0 pieces touched, good chunks: 3060/3773:0 reqq: 0+0/(1/500):0/32, flags: c-eI-c, dr: 1320.5 KiB/s
    requested pieces:
22. "MG-3.01.4118C(*-lkzw"                                  0000000000180005 192.168.97.98:993-85.174.192.70:11158
    bep40-prio: 92f8cf39
    last msg: 3.50s ago, connected: 829.61s ago, last helpful: 3.62s ago, itime: 6m58.388827957s, etime: 20.547305784s
    855/855 completed, 0 pieces touched, good chunks: 2271/2719:0 reqq: 0+0/(1/500):0/32, flags: ic-eI-, dr: 1768.4 KiB/s
    requested pieces:
23. "-KN31\x120-FQ7qAuOoRcnt"                               0000000000100005 192.168.97.98:53076-85.116.125.89:25729
    bep40-prio: 9e64f2b8
    last msg: 3.44s ago, connected: 836.83s ago, last helpful: 3.61s ago, itime: 9m39.535317628s, etime: 14.984979753s
    855/855 completed, 0 pieces touched, good chunks: 2228/2547:0 reqq: 0+0/(1/500):0/32, flags: c-eHg-c, dr: 2378.9 KiB/s
    requested pieces:
24. "-qB4400-7UgJSj)z~s7Z"                                  0000000000100005 192.168.97.98:993-93.157.236.208:61858
    bep40-prio: 863adb9e
    last msg: 3.45s ago, connected: 341.27s ago, last helpful: 3.49s ago, itime: 4m14.976730237s, etime: 3.806847312s
    855/855 completed, 0 pieces touched, good chunks: 715/785:0 reqq: 0+0/(1/2000):0/32, flags: c-EI-c, dr: 3005.1 KiB/s
    requested pieces:
25. "MG-3.01.4118EiQn3G_J"                                  0000000000180005 192.168.97.98:993-109.252.99.237:2048
    bep40-prio: 439cbd43
    last msg: 3.45s ago, connected: 907.21s ago, last helpful: 3.50s ago, itime: 3m54.370931664s, etime: 34.224964501s
    855/855 completed, 0 pieces touched, good chunks: 7755/8172:0 reqq: 0+0/(1/500):0/32, flags: c-eI-c, dr: 3625.4 KiB/s
    requested pieces:
</details>

<details>
<summary>Tixati v2.81 peer information</summary>

![изображение](https://user-images.githubusercontent.com/18549626/149834251-e08c29e1-dd60-4641-ab2e-1ff146aa2278.png)
</details>

**Comment by anacrolix** [comment]
Could you include the version of anacrolix/torrent and anacrolix/dht/v2 you are using?

Have you set [`ClientConfig.PublicIp6`](https://github.com/anacrolix/torrent/blob/c6ee03f449fa82d0fd6ba06d6bdb7c5062b38d28/config.go#L130)?

My first instinct was that the separate DHT servers weren't configured to request IPv6 nodes, but that doesn't appear to be the default behaviour. If `PublicIp6` is not set, the IPv6 server will not be considered "secure" and may be ignored by peers. You might also try setting DefaultWant to [n6,n4], peers might preferentially return IPv6  addresses if it's reversed. Another thing to try is disabling IPv4.

anacrolix/torrent doesn't currently reverse torrent slots separately for incoming and outgoing connections, it might be that the overwhelming present on IPv4 is starving out any outbound attempts for IPv6. The client should favour IPv6 over IPv4 when a peer has both kinds of addresses though.

**Comment by anacrolix** [comment]
@avengermsoft any update?

**Comment by avengermsoft** [comment]
anacrolix@torrent-v1.41.0: Added ipv6 addresses, Enabled uTp. It has become better, but the percentage of ipv6 addresses is still small (1/25=4%).

**Comment by anacrolix** [comment]
Have you tried disabling IPv4? I think IPv6 use in BitTorrent is still just generally very low, probably at the level you gave.

**Comment by anacrolix** [comment]
Please reopen if you have more information.
