### ISSUE TITLE
"banning ip <nil>" error messages

### ISSUE THREAD

**Issue by AskAlexSharov** [anacrolix/torrent#715]
See ~20 messages/min like this:
```
banning ip <nil>
```
It's from:  client.go
cl.logger.Printf("banning ip %v", ip)

FYI: seeder and download app are on same machine (for test purpose). Downloading happening normally.

**Comment by anacrolix** [comment]
@AskAlexSharov thanks! Are you using WebRTC/webtorrent heavily? What version/commit are you using? Can you try with 24e6f3dd7b02c81006e9b478cc8ba0fcd7c7e04a or more recent if you aren't already, and let me know what revision you chose and how it went?

**Comment by AskAlexSharov** [comment]
«WebRTC/webtorrent heavily» - i creating cli command (service) which need download/seed by any way (no conditions). I using default config (but on my experiments disabling webseed reducing speed of peers discovery). Also using https://github.com/ngosang/trackerslist (including WS trackers).

I will try your commit - tomorrow.

**Comment by AskAlexSharov** [comment]
24e6f3d - has next logs (on warning log level):
```
2022/01/26 16:31:39 dispatching packet received on 0.0.0.0:36263: unknown transaction id 554869826
2022/01/26 16:31:39 dispatching packet received on 0.0.0.0:36263: unknown transaction id 16777216
2022/01/26 16:31:41 dispatching packet received on 0.0.0.0:36263: unknown transaction id 554869826
[INFO] [01-26|16:31:41.476] banning ip <nil>
[INFO] [01-26|16:31:41.863] banning ip 123.21.12.130
[INFO] [01-26|16:31:44.284] banning ip <nil>
[INFO] [01-26|16:31:45.334] banning ip <nil>
```

**Comment by anacrolix** [comment]
Sorry it wasn't clear if the `@smartban` branch per our emails was giving you the desired behaviour.

**Comment by anacrolix** [comment]
Okay thanks.

**Comment by anacrolix** [comment]
I believe this is fixed in 1.40.1.

**Comment by anacrolix** [comment]
https://github.com/anacrolix/torrent/issues/723 is related.

**Comment by anacrolix** [comment]
I had this issue with a webseed that changed the data away from what was expected by the torrent. https://github.com/anacrolix/torrent/commit/ec2b1b2073df1eaa39e14aa81a775665dea5b47d fixes it on master.
