### ISSUE TITLE
How to find out if a client is currently uploading data of a specific torrent?

### ISSUE THREAD

**Issue by half-dead** [anacrolix/torrent#73]
The need of this is to know when we can drop a torrent from a client safely.

**Comment by anacrolix** [comment]
Do you mean that it has a connection to which it's uploading pieces at that very moment?

**Comment by half-dead** [comment]
Yes, but I think a connection without any actual traffic doesn't count.

**Comment by anacrolix** [comment]
You can always drop a connection safely, and thus by extension, the connections attached to a Torrent or Client. The BitTorrent protocol expects and allows for this, and no harm is done to either end of the connection.

**Comment by anacrolix** [comment]
I've improved the doc to make this clear.
