### ISSUE TITLE
panic inside client.Close()

### ISSUE THREAD

**Issue by AskAlexSharov** [anacrolix/torrent#744]
```
panic: piece 0 has relative availability 1

goroutine 11864509 [running]:
github.com/anacrolix/torrent.(Torrent).close(0x1400099a000, 0x10406a49c010)
        github.com/anacrolix/torrent@v1.42.0/torrent.go:880 +0x200
github.com/anacrolix/torrent.(Client).Close(0x14000581680)
        github.com/anacrolix/torrent@v1.42.0/client.go:433 +0xd4
```

**Comment by anacrolix** [comment]
How easily can you reproduce this? Is there a particular torrent or configuration that causes it? The invariants around tracking piece availability are quite complex, it would be great if I can make a unit test to cover this.

**Comment by AskAlexSharov** [comment]
only 1 person did report it. not reproducible at the moment.

**Comment by anacrolix** [comment]
Thanks. The piece relative availability is an optimization around picking pieces on rarity. There are several factors involved, so a refactor and unit tests might shake these out if we can't pin them down easily.

**Comment by anacrolix** [comment]
Please reopen if you see this again.
