### ISSUE TITLE
Ban of peer after app restart

### ISSUE THREAD

**Issue by AskAlexSharov** [anacrolix/torrent#746]
See message `banning ... for being sole dirtier of piece 0 after failed piece check` after `kill -9` of App. 
I see that it's happening during hashing pieces (it does re-check all files hashes). 
Probably peer sent us messages before restart, we received it after, and anacrolix/torrent was in process of pieces re-hashing. It caused ban of peer. 

BTW: is it possible to avoid 100% re-hashing after `kill -9`? We have list of completed pieces in DB.

**Comment by anacrolix** [comment]
I think for that to occur, this line would be executed: https://github.com/anacrolix/torrent/blob/f1e56b4017cc6108b44cf2a7fdc15c9f4b271061/peerconn.go#L1433. Could you confirm you have a non-zero value when you get that error message? It's possible we should drop these chunks instead of process them.

**Comment by anacrolix** [comment]
Thanks, I'll wait a while until you can confirm.

**Comment by AskAlexSharov** [comment]
reproduced another banning issue. when fresh node just started, see several:  
`would have banned <ip> for touching piece 46 after failed piece check`
here are `/debug/vars`
```
 "chunks received": {
    "redundant": 15656,
    "total": 335584
  },
```

**Comment by anacrolix** [comment]
Hm per above, I don't think that's a problem. I can't remember all the context for this issue.

**Comment by anacrolix** [comment]
Are you still seeing this issue @AskAlexSharov ? Also on the rehashing, the torrent client will automatically track pieces that it expects to already be complete, and skip rehashing those.

**Comment by AskAlexSharov** [comment]
> Are you still seeing this issue @AskAlexSharov ? Also on the rehashing, the torrent client will automatically track pieces that it expects to already be complete, and skip rehashing those.

Yes, but i found reason: public seedbox anti-virus did corrupt our files and seedbox did seed bad data. It was detected and banned by lib. So, seems great. 

A bit unclear how banning works with “connections limit”, can all peers be banned and eat connections limit and stuck?
