### ISSUE TITLE
HTTP client override, hook improvements.

### ISSUE THREAD

**Issue by denisdubovitskiy** [anacrolix/torrent#749]
Hi, Anacrolix! Thanks for such a rich-featured library! 

At ozon.ru we're creating a service which helps other ones downloading large files over the network from our CDNs. We've chosen this library because it seems to fit our requirements and works well, but in our case some parts of code need to have some changes to provide more flexibility.

Observability is such a crucial thing for our environments and we need to have answers to questions like this:

* Is a service alive?
* Does a service do any useful work right now?
* Do peers get announced over DHT?
* What kind of peers are getting requested (webseeds or direct ones)?
* How many of them? In which proportions? - This case seems to be one of the most important for us.
* Which events are happening with a torrent right now? ("torrent" expvar)
* How many chunks are being requested?
* How many of them received?
* etc... (probably there will be another pull-request with logs improvements)

And there are some webseed metrics which we want to be available as well, but due to the privacy of httpClient we can't intergate our logic. We also want to provide a custom metrics, request modification in the custom client. In the pull request below a client turned to the interface in order to be easily extended by the client code (note that there is a mark "need advice here". In my opinion a webseed client can have different requirements than a client which requests a torrent file). 

* Which webseed host gets requested?
* Which is current time to first byte right now? - This can be traced by the httptrace.
* What HTTP codes are we getting from them?
* Which latency between a webseed and a service?

Could you please review a pull-request https://github.com/anacrolix/torrent/pull/748/files which improves a possibility to capture those metrics and achieve more flexibility? In the code I've tried to make as little changes as I could in order not to break current customer API design.

**Comment by anacrolix** [comment]
Thanks for the deep PR. It will be great to get more insight into these areas.

**Comment by anacrolix** [comment]
@denisdubovitskiy do you have an update on this? Please reopen if you have interest in this still.
