### ISSUE TITLE
can not compiled in linux

### ISSUE THREAD

**Issue by liangmingyuanneo** [anacrolix/torrent#75]
When I build the torrent in linux, it shows this error "/missinggo/mapslice.go:10: undefined: reflect.StructOf". So I searched refection packages of golang and found there is no this function.

**Comment by anacrolix** [comment]
Thanks, what version of Go are you using?

**Comment by liangmingyuanneo** [comment]
go.1.5.1

**Comment by anacrolix** [comment]
Thanks, I'll try to resolve this for older versions of Go shortly. http://tip.golang.org/pkg/reflect/#StructOf

**Comment by anacrolix** [comment]
Fixed in 2a6ebc308589efb4482485ad396a9fd1f0f658d2

**Comment by liangmingyuanneo** [comment]
year.Thank you!
