### ISSUE TITLE
Selecting certain files and deselecting others to be downloaded within a torrent?

### ISSUE THREAD

**Issue by mohamedSulaimanAlmarzooqi** [anacrolix/torrent#756]
Hi.
So if I'm opening a torrent file or magnet by a client, For example
```
package main

import (
	"log"

	"github.com/anacrolix/torrent"
	_ "github.com/anacrolix/torrent/metainfo"
)

func Example() {
	c, _ := torrent.NewClient(nil)
	defer c.Close()
	tor, err := metainfo.LoadFromFile("test.torrent")
	if err != nil {
		panic(err)
	}
	t, _ := c.AddTorrent(tor)
	<-t.GotInfo()
	t.DownloadAll()
	c.WaitAll()
	log.Print("ermahgerd, torrent downloaded")
}
```
And this torrent file contains more than 1 file that it downloads, Is there a way to list them all and selects/deselects them for download?

**Comment by anacrolix** [comment]
You can list the available files after the info is obtained, with Torrent.Files. You can select specific ones by calling https://pkg.go.dev/github.com/anacrolix/torrent#File.Download on those.

**Comment by mohamedSulaimanAlmarzooqi** [comment]
Thanks, Was just hard to find it in this huge list of files.
