### ISSUE TITLE
panic upload rate limiter

### ISSUE THREAD

**Issue by AskAlexSharov** [anacrolix/torrent#770]
Hi. Again saw this error on `v1.46.1-0.20220713100403-caa9400c52fe`

```
panic: upload rate limiter burst size < 16384
goroutine 3142 [running]:
github.com/anacrolix/torrent.(*PeerConn).upload(0xc0307a3b00, 0xc01e81bb40)
	github.com/anacrolix/torrent@v1.46.1-0.20220713100403-caa9400c52fe/peerconn.go:1610 +0x3b9
github.com/anacrolix/torrent.(*PeerConn).fillWriteBuffer(0xc0307a3b00)
	github.com/anacrolix/torrent@v1.46.1-0.20220713100403-caa9400c52fe/peerconn.go:708 +0x8f
github.com/anacrolix/torrent.(*PeerConn).initMessageWriter.func1()
	github.com/anacrolix/torrent@v1.46.1-0.20220713100403-caa9400c52fe/peer-conn-msg-writer.go:24 +0xa6
github.com/anacrolix/torrent.(*peerConnMsgWriter).run(0xc0307a3f40, 0xdf8475800)
	github.com/anacrolix/torrent@v1.46.1-0.20220713100403-caa9400c52fe/peer-conn-msg-writer.go:75 +0xe2
github.com/anacrolix/torrent.(*PeerConn).messageWriterRunner(0xc0005eb238?)
	github.com/anacrolix/torrent@v1.46.1-0.20220713100403-caa9400c52fe/peer-conn-msg-writer.go:47 +0xd8
created by github.com/anacrolix/torrent.(*PeerConn).startMessageWriter
	github.com/anacrolix/torrent@v1.46.1-0.20220713100403-caa9400c52fe/peer-conn-msg-writer.go:40 +0x5b
```

Previous issue: https://github.com/anacrolix/torrent/issues/759

**Comment by anacrolix** [comment]
Could you link to that commit (caa9400c52fe)? I cannot find it.

**Comment by anacrolix** [comment]
Do you know for certain that the burst size is indeed sufficiently high? I think the problem was the same in #759.

**Comment by AskAlexSharov** [comment]
Ah, i remember now. Will try to reduce NetworkChunkSize. 

But it’s potential security problem: some bad client can crash the app by requesting big NetworkChunks.

**Comment by AskAlexSharov** [comment]
Also, I'm still don't really understand the problem:
- I have 2Mb burst size
- But error says it's < 16384
How it can happen?

**Comment by anacrolix** [comment]
@AskAlexSharov I'm not sure, I think we covered it thoroughly in the other issue. Either there's an issue propagating the correct value somewhere in anacrolix/torrent, or the wrong version or incorrect value is being used in hte other projects that are panicking. I did pore over the code pretty extensively already.

**Comment by AskAlexSharov** [comment]
Thank you. When I set 4mb burst, it panics. When i set 2mb burst, it doesn’t panic. Seems I jumped over some limit. Can’t find it, but it’s fine. 
let’s close the issue, because I fixed panic on my side.

**Comment by AskAlexSharov** [comment]
@anacrolix hi. 
I did add some debug logs about this panic:
```
fmt.Printf("before ReserveN: %d, %d\n", c.t.cl.config.UploadRateLimiter.Burst(), int(r.Length))
res := c.t.cl.config.UploadRateLimiter.ReserveN(time.Now(), int(r.Length))
fmt.Printf("after ReserveN: %t\n", res.OK())
if !res.OK() {
	panic(fmt.Sprintf("upload rate limiter burst size < %d", r.Length))
}
```
Out:
```
before ReserveN: 2097152, 1048576
after ReserveN: true
before ReserveN: 1048576, 1048576
after ReserveN: true
before ReserveN: 0, 1048576
after ReserveN: false
panic: upload rate limiter burst size < 1048576
```


And I see that panic happening not because somebody requested more than "burst size". I see several small requests (each one is smaller than burst size) and burst is just over - and it feels for me as an "normal scenario" (need block until limiter is available instead of panic).

**Comment by anacrolix** [comment]
The rate Limiter Burst should not be changing! Do you have some code modifying that?

**Comment by anacrolix** [comment]
A quick check of the implementation of rate.Limiter shows that it can go down if the rate is 0. Is it possible the rate is set to 0 somehow?

**Comment by AskAlexSharov** [comment]
Yes, it set to 0
