### ISSUE TITLE
Customize torrent download path

### ISSUE THREAD

**Issue by monkeyWie** [anacrolix/torrent#774]
Hi, is there any way to specify the download path of a torrent?

**Comment by anacrolix** [comment]
For file-based storage, you can choose any of the `NewFile*` constructors at https://pkg.go.dev/github.com/anacrolix/torrent@v1.46.0/storage#ClientImplCloser. Custom storages are set in https://pkg.go.dev/github.com/anacrolix/torrent#ClientConfig or https://pkg.go.dev/github.com/anacrolix/torrent#Client.AddTorrentOpt.

If you are using `cmd/torrent download`, I think the location is the process working directory.

**Comment by monkeyWie** [comment]
The custom storage implementation is not elegant, can you provide a way to set the torrent download path, for example:
```
c, _ := torrent.NewClient(config)
t1 := c.AddMagnet("")
t1.setDownloadPath("~/download/movie")
t2 := c.AddMagnet("")
t2.setDownloadPath("~/download/music")
```

**Comment by anacrolix** [comment]
No, because file storage isn't the only supported type. All storage-related configuration is confined to the storage implementation itself.

**Comment by monkeyWie** [comment]
Okay~, I will try to implementation a special file strorage.

**Comment by whr819987540** [comment]
Hey, how do you finnaly customize the download path?

**Comment by monkeyWie** [comment]
@whr819987540 
You can refer: https://github.com/GopeedLab/gopeed/blob/09bdb5584a12a3e0ce23bce0e77de79b1b96c971/internal/protocol/bt/fetcher.go#L43-L67

**Comment by whr819987540** [comment]
Got you. You use a map to know each torrent's download path with it's infohash as the map's key.

**Comment by monkeyWie** [comment]
Yep, but that's not a good way to do it. It would be better if the author could provide a method for changing the download path.

**Comment by anacrolix** [comment]
This is incorrect. Please refer to https://github.com/anacrolix/torrent/issues/774#issuecomment-1216135485. You probably want to look at https://pkg.go.dev/github.com/anacrolix/torrent@v1.46.0/storage#NewFileOpts specifically.

**Comment by monkeyWie** [comment]
@anacrolix 
I want to set the download directory for a torrent after obtaining it, but I cannot get the corresponding torrent when using the NewFileOpts option you mentioned. So I can only use the infoHash to config the download directory.

**Comment by anacrolix** [comment]
Ah, if you're trying to get the common torrent client behaviour of moving the files when they're complete to a different location, you'll need to do that manually. When you are satisfied the download is complete (via whatever Torrent or Client method, like WaitAll perhaps), then you can copy the files over, or remove the Torrent from the Client and move the files directly. anacrolix/torrent doesn't provide any helpers for this.

**Comment by anacrolix** [comment]
You could stream the files directly into their final destination, wait for Torrent.GotInfo, then iterate Torrent.Files, calling NewReader for every file and then using io.Copy to your preferred location. As each copy completes, the file is done. This also frees you from having to use a File storage, you can use whatever you want.

**Comment by monkeyWie** [comment]
Thank you for your reply. This solution looks better, I'll go ahead and give it a try.
