### ISSUE TITLE
Provide more stats for torrent

### ISSUE THREAD

**Issue by marcovidonis** [anacrolix/torrent#779]
I'm looking at making a client provide some broad data about a torrent, which don't seem to be part of what `torrent.Stats()` currently gives. The stats I'm interested in could include, for example:

- Whether the file is currently being transferred
- Current and/or average transfer speed, total or per peer
- How long it's been transferring for
- Perhaps some kind of measure of how "popular" a file is

Is any of these already available somewhere I might have missed? Would this be interesting as a PR if I do get to build it?

**Comment by anacrolix** [comment]
Hi @marcovidonis thanks for checking in on the concepts first:

> I'm looking at making a client provide some broad data about a torrent, which don't seem to be part of what `torrent.Stats()` currently gives. The stats I'm interested in could include, for example:
> 
> * Whether the file is currently being transferred

Via a `Reader`, or with peers?

> * Current and/or average transfer speed, total or per peer

Something like this? https://pkg.go.dev/github.com/anacrolix/torrent#Peer.DownloadRate

> * How long it's been transferring for

If you click through to the source on the above method, you can see some fields tracking total expected transfer time etc.

> * Perhaps some kind of measure of how "popular" a file is

This would be some reflection of the seeder or leecher count. That's somewhat outside the realm of a torrent client itself, and more something you can ask directly of trackers or the DHT. 

https://pkg.go.dev/github.com/anacrolix/torrent@v1.47.0/tracker/udp#Client.Scrape
Any code referencing the scrape bloom filters https://pkg.go.dev/github.com/anacrolix/dht/v2@v2.19.0/krpc#Return
You can also probably just do a `get_peers` operation and count the result (if you're happy to max out at the `num` limit that fits in an UDP response packet, it will basically tell you very popular, or if it's not, some degree within 0-200. https://pkg.go.dev/github.com/anacrolix/dht/v2#Server.GetPeers also lets you scrape, you can pull the scrape fields out of the responses and do the math. Here's an example of it being used: https://github.com/anacrolix/dht/blob/238fbb2b96ba6de7bfbc4a5cd534d9d713f63395/cmd/dht/get-peers.go#L41-L47. That command should be ready to roll if you want to play with it `dht announce ...`.

> 
> Is any of these already available somewhere I might have missed? Would this be interesting as a PR if I do get to build it?

You might want to dig through the use of https://github.com/anacrolix/torrent/blob/e81c6569af11e2cab335bf89cef63463c46df9de/client.go#L136, the calls it makes into Torrent, and then into Peer cover a lot of statistics, and some wrangling should get you what you need (and I'm open to changes and additions).

Certainly, the smaller the PRs the better. Thanks!

**Comment by marcovidonis** [comment]
Sounds great, thanks for your help! I'll dig into each of these links, but it sounds like most of what I need is already covered!
