### ISSUE TITLE
Cmd fomat error & the torrent serve cmd cannot be used as a util

### ISSUE THREAD

**Issue by VertigoSHI** [anacrolix/torrent#780]
![image](https://user-images.githubusercontent.com/52185258/194813171-546b691b-79d0-4452-8239-d1207d94ec8c.png)

&
the cmd depends on the sqlite, no configuration info about the db table

**Comment by anacrolix** [comment]
Sorry, could you explain a bit more? The argument parsing is in a bit of flux.
