### ISSUE TITLE
Building issues

### ISSUE THREAD

**Issue by ucwong** [anacrolix/torrent#781]
Occurs after updating github.com/anacrolix/missinggo/v2 from ```v2.7.0``` to ```v2.7.1```

github.com/anacrolix/dht/v2 from ```v2.19.0``` to ```v2.19.1```

```
/root/go/pkg/mod/github.com/anacrolix/stm@v0.4.0/stmutil/containers.go:72:3: cannot use generic type immutable.Map[K constraints.Ordered, V any] without instantiation
/root/go/pkg/mod/github.com/anacrolix/stm@v0.4.0/stmutil/containers.go:76:9: cannot use Map{…} (value of type Map) as type Mappish in return statement:
	Map does not implement Mappish (missing Get method)
/root/go/pkg/mod/github.com/anacrolix/stm@v0.4.0/stmutil/containers.go:76:30: type interhash of interhash{} does not match immutable.Hasher[K] (cannot infer K and V)
/root/go/pkg/mod/github.com/anacrolix/stm@v0.4.0/stmutil/containers.go:79:17: cannot use Map{} (value of type Map) as type Mappish in variable declaration:
	Map does not implement Mappish (missing Get method)
/root/go/pkg/mod/github.com/anacrolix/stm@v0.4.0/stmutil/containers.go:83:9: cannot use m (variable of type Map) as type Mappish in return statement:
	Map does not implement Mappish (missing Get method)
/root/go/pkg/mod/github.com/anacrolix/stm@v0.4.0/stmutil/containers.go:88:9: cannot use m (variable of type Map) as type Mappish in return statement:
	Map does not implement Mappish (missing Get method)
/root/go/pkg/mod/github.com/anacrolix/stm@v0.4.0/stmutil/containers.go:107:3: cannot use generic type immutable.SortedMap[K constraints.Ordered, V any] without instantiation
/root/go/pkg/mod/github.com/anacrolix/stm@v0.4.0/stmutil/containers.go:112:9: cannot use sm (variable of type SortedMap) as type Mappish in return statement:
	SortedMap does not implement Mappish (missing Get method)
/root/go/pkg/mod/github.com/anacrolix/stm@v0.4.0/stmutil/containers.go:117:9: cannot use sm (variable of type SortedMap) as type Mappish in return statement:
	SortedMap does not implement Mappish (missing Get method)
/root/go/pkg/mod/github.com/anacrolix/stm@v0.4.0/stmutil/containers.go:182:14: cannot use generic type immutable.List[T comparable] without instantiation
/root/go/pkg/mod/github.com/anacrolix/stm@v0.4.0/stmutil/containers.go:117:9: too many errors
```

**Comment by anacrolix** [comment]
@ucwong what version of Go are you using? See https://github.com/anacrolix/stm/issues/5.

**Comment by ucwong** [comment]
> @ucwong what version of Go are you using? See [anacrolix/stm#5](https://github.com/anacrolix/stm/issues/5).

go version go1.19.2 linux/amd64

**Comment by ucwong** [comment]
<img width="455" alt="image" src="https://user-images.githubusercontent.com/22344498/197425908-ebc4dc4a-1d8b-424f-98e8-e03b7c3f6b11.png">
It is OK when I run ```go test ./... ``` in stm directly

**Comment by anacrolix** [comment]
I think this is related to https://github.com/anacrolix/torrent/issues/776. I have had instances where the Go is trying to downgrade versions resulting in similar build errors to what you are describing.

**Comment by ucwong** [comment]
Replace the type parameters in its definition with actual types may be the solution of this issue

https://github.com/anacrolix/stm/blob/4f6e80b7bb8c9a8b3036e54b6d02dcc66a690162/stmutil/containers.go#L72

**Comment by anacrolix** [comment]
Without jumping into the code and digging around, is it possible that old versions of the DHT code are pulling in versions of the STM code that don't build anymore? I don't know how far you got in the linked issue @ucwong but it all ends up at https://github.com/golang/go/issues/55955.

**Comment by ucwong** [comment]
> Without jumping into the code and digging around, is it possible that old versions of the DHT code are pulling in versions of the STM code that don't build anymore? I don't know how far you got in the linked issue @ucwong but it all ends up at [golang/go#55955](https://github.com/golang/go/issues/55955).

Just run go get -u ./... in my project and then the issue occurs when building

**Comment by ucwong** [comment]
https://github.com/anacrolix/stm/pull/6

**Comment by ucwong** [comment]
https://github.com/anacrolix/stm/pull/7

**Comment by anacrolix** [comment]
Let's close this in favour of https://github.com/anacrolix/stm/issues/5, which is the real problem.
