### ISSUE TITLE
Hope there are some example codes to show how to use these function

### ISSUE THREAD

**Issue by Shawn-Huang-Tron** [anacrolix/torrent#782]
May be there could be a example directory that contains a lot of use case about how to use the method or function.Thanks.

**Comment by anacrolix** [comment]
There are some examples floating around in the [transfer unit tests](https://github.com/anacrolix/torrent/blob/master/test/transfer_test.go), pkg doc, the [cmd/ directory](https://github.com/anacrolix/torrent/tree/master/cmd), the [Discussions](https://github.com/anacrolix/torrent/discussions) and any of the [downstream projects](https://github.com/anacrolix/torrent#downstream-projects). Sorry I don't have time to commit to this myself, but I welcome contributions.

Please feel free to provided specific examples you require.
