### ISSUE TITLE
Is there a way to stop downloading and delete a single file?

### ISSUE THREAD

**Issue by Kidsunbo** [anacrolix/torrent#797]
I have a torrent file which contains serveral files can be downloaded. The first time I am downloading A and serveral minutes later, I want to stop downloading A and downloading B. So the A become no-needed and I would like to delete it.

But I notice that there seems no way to do such thing. I can stop downloading one file with setting the priority to `PiecePriorityNone`. But I don't have a way to delete the file with this library. I've already tried to delete it with `os.Remove`. But it seems that the priority change needs time to take effect, so the deleted file will still be created after it's deleted and trash left.

**Comment by anacrolix** [comment]
Depending on the storage implementation you're using, parts of files you don't want will still be visible as they share pieces with other files, usually on the boundaries of the files.

**Comment by Kidsunbo** [comment]
> Depending on the storage implementation you're using, parts of files you don't want will still be visible as they share pieces with other files, usually on the boundaries of the files.

Yeah that makes sense. Is there any tutorial for the storage part?

**Comment by anacrolix** [comment]
Sorry there isn't. There's a lot of tests that mess around with it in https://github.com/anacrolix/torrent/tree/master/test.

**Comment by anacrolix** [comment]
There's also quite a few issues discussing specialized implementations there should be a lot of answers there.

**Comment by anacrolix** [comment]
And https://github.com/anacrolix/torrent/discussions.
