### ISSUE TITLE
to change btree lib

### ISSUE THREAD

**Issue by AskAlexSharov** [anacrolix/torrent#799]
change github.com/ajwerner/btree (seems experimental and unpopular)
for example to https://github.com/tidwall/btree (also has Set implementation, generics and seems more popular)

But, be careful - latest version did dropped support of go1.18, can use:	github.com/tidwall/btree@v1.5.0

**Comment by anacrolix** [comment]
Both were benchmarked, see https://github.com/anacrolix/torrent/blob/master/request-strategy/piece-request-order_test.go. At the time ajwerner won out by a large margin. I don't recall the specifics. I even talked to both authors directly about the implementations.

**Comment by AskAlexSharov** [comment]
great info, i will investigate

**Comment by anacrolix** [comment]
Allocations are much higher with tidwall, especially after updating to a newer version. However it has gotten faster, but is not closer to ajwerner in my tests. Let me know what you find.

**Comment by anacrolix** [comment]
Did you have any update on this @AskAlexSharov ? Reopen if you have new information that indicates I should change lib.
