### ISSUE TITLE
How do I get list of peers on a given swarm?

### ISSUE THREAD

**Issue by debunge** [anacrolix/torrent#8]
I'm trying to create ui for toy torrent client and so far everything is good, except I cannot locate where peers live.

**Comment by anacrolix** [comment]
Unused peers are kept per torrent, [here](https://github.com/anacrolix/torrent/blob/master/torrent.go#L86). The size of the reserve peers is kept high enough that we can open new connections as required, but low enough that not too much memory is consumed. If you want to expose some state from the torrent struct, you should ensure that the client lock is taken, and put a method on the Torrent struct that gives you what you need.

Alternatively you can interact directly with trackers or DHT if you don't want to know about peers in the context of a live torrent on a client.

Feel free to raise issues about state that you require from a torrent. You should also see the WriteStatus method, it provides very comprehensive information on client, torrent and connection state and is what I use to debug a live client.

**Comment by debunge** [comment]
Thank you for reply! 
On a slightly related note, how do I control size of Peers? I don't see any constants here...

**Comment by anacrolix** [comment]
[These](https://github.com/anacrolix/torrent/blob/master/client.go#L96) are
used. Sorry, the project is very large, torrent quickly becomes very
complex.

**Comment by debunge** [comment]
Thank you very much!

**Comment by debunge** [comment]
Oh, and also how do I control upload\download speed and ratio? I greped source code for words which I though would be relevant but found nothing useful.

**Comment by anacrolix** [comment]
I haven't implemented that. My purposes haven't required it.

**Comment by debunge** [comment]
If I to implement ratios and speed limits, where would it be best to start looking? I'm still not completely  understand structure of your code...

**Comment by anacrolix** [comment]
@debunge Let's move this to https://gophers.slack.com/#torrent, or https://groups.google.com/group/go_torrent, take your pick.
