### ISSUE TITLE
How to use metainfo.Magnet

### ISSUE THREAD

**Issue by sebest** [anacrolix/torrent#80]
Hi i'm trying to output a magnet uri modifying `torrent-create` but the hash is always 000...

What am i doing wrong?

thanx

```
package main

import (
	"io"
	"log"
	"os"
	"path/filepath"
	"strings"
	"fmt"

	"github.com/docopt/docopt-go"

	"github.com/anacrolix/torrent/metainfo"
)

func main() {
	opts, err := docopt.Parse("Usage: torrent-create <root>", nil, true, "", true)
	if err != nil {
		panic(err)
	}
	root := opts["<root>"].(string)
	mi := metainfo.MetaInfo{}
	mi.SetDefaults()
	err = mi.Info.BuildFromFilePath(root)
	if err != nil {
		log.Fatal(err)
	}
	err = mi.Info.GeneratePieces(func(fi metainfo.FileInfo) (io.ReadCloser, error) {
		return os.Open(filepath.Join(root, strings.Join(fi.Path, string(filepath.Separator))))
	})
	if err != nil {
		log.Fatalf("error generating pieces: %s", err)
	}
  fmt.Println(mi.Magnet())
}
```

**Comment by anacrolix** [comment]
MetaInfo.Magnet takes the hash from MetaInfo.Info.Hash, which hasn't been set. Currently you can do that by bencoding the MetaInfo.Info, then taking the SHA1 of that.

b, err := MetaInfo.Info.MarshalBencode()
h := sha1.New()
h.Write(b)
copy(mi.Info.Hash[:], h.Sum(nil))
m := MetaInfo.Magnet()

If you have any API suggestions, please offer them. I wasn't happy with the metainfo Builder that was previously available, and the current API doesn't reflect my current preference.

**Comment by sebest** [comment]
Thanx for helping!

Reading the code of `torrent-create` here : https://github.com/anacrolix/torrent/blob/master/cmd/torrent-create/main.go#L37

and metainfo.BuildFromFilePath here : https://github.com/anacrolix/torrent/blob/master/metainfo/metainfo.go#L84

It seems that the code of torrent-create is not up to date anymore as it calls GeneratePieces which has already been called by BuildFromFilePath

Back to the initial topic, is there any reason that the code that you mentioned is not in a function like `ComputeHash`, it seems really similar to the code here: https://github.com/anacrolix/torrent/blob/master/metainfo/metainfo.go#L195

**Comment by anacrolix** [comment]
I was considering metainfo.InfoEx.UpdateHash, but seeing as it's only 3 lines to set InfoEx.Hash, I'm not sure it's worth the confusion it will add to people wondering what's setting/modifying that value.

**Comment by sebest** [comment]
From an API perspective, i think that these 3 lines should be "hidden" from the developer.
