### ISSUE TITLE
Torrent.BytesMissing can be out of sync with storage

### ISSUE THREAD

**Issue by luodw** [anacrolix/torrent#828]
Hi, we have a trouble when use torrent to distribute data with torrent version 1.15.1. We use Torrent.BytesMissing() to judge whether data is completely downloaded and return data to client. 

But some times Torrent.BytesMissing() == 0 and the data returned is incomplete, the data has some content with zero, so client download failed. It is happened occasionally. I guess although Torrent.BytesMissing() == 0, but some chunks may be not written to file. 

Has anyone encountered this issue before? or has any ideas?

**Comment by anacrolix** [comment]
Yeah you can get BytesMissing==0 while data is still being written storage. The value tracks the state internal to the client, when it's 0, it's not expecting to need to download any more to complete a Torrent, but it could if piece hashing fails or there's a storage issue.

It would be possible to change it to track the storage.

**Comment by luodw** [comment]
@anacrolix Thanks for your reply.

**Comment by luodw** [comment]
@anacrolix  Thanks for your reply.
1. "It would be possible to change it to track the storage."     Is there a method/function ready to use?

2. "It would be helpful to know what you're coordinating with BytesMissing."    we use ByteMissing just like follow:
`
pcs := torrent.SubscribePieceStateChanges()
for torrent.BytesMissing() > 0 {
       select {
       case <-pcs.Values:
       case <- time.After(time.Second*60):
             return
}
// data has download completely, return to client
_, err := io.copy(http.ResponseWriter, torrent.file)
`

Or what is the right practice to judge whether data is downloaded and complete?

**Comment by luodw** [comment]
@anacrolix thanks, I will have a try.

**Comment by anacrolix** [comment]
@luodw That's a fantastic question. A quick look suggests setting `HalfOpenConnsPerTorrent` to zero is the best option available to you. Also make sure that you have `Seed` true (I guess you do).
