### ISSUE TITLE
Error loading torrent file

### ISSUE THREAD

**Issue by RfadnjdExt** [anacrolix/torrent#831]
Encountered an error when trying to add a torrent file to the downloader. The error message is:

error running main: adding torrents: adding torrent for "file.torrent": error loading torrent file "file.torrent": bencode: syntax error (offset: 417): strconv.ParseInt: parsing "17536620544e4": invalid syntax

This error occurred when trying to load the torrent file. It seems to be related to a syntax error in the file. Thank you.

**Comment by RfadnjdExt** [comment]
Hi, I realized that I forgot to attach the actual torrent file to the issue, which may have made it difficult for you to reproduce the error.

[file.zip](https://github.com/anacrolix/torrent/files/11373121/file.zip)

I apologize for the oversight. I'm still trying to figure out what might be causing the issue, but I'll keep you all posted on any progress I make.

Thanks for your patience and understanding! Best.

**Comment by anacrolix** [comment]
I don't know how someone has managed to produce an info like this, but if you look in the file, and change `7:lengthi17536620544e4` to `6:lengthi17536620544e4`, it will be fixed. anacrolix/torrent is showing the correct behaviour as far as I can tell.

**Comment by RfadnjdExt** [comment]
You right, `length` is 6 length but they produce it with 7 XD. Thank you for your repsonse.
