### ISSUE TITLE
Supported tracker urls

### ISSUE THREAD

**Issue by MaximKiselev** [anacrolix/torrent#842]
hi, i got error.`github.com/anacrolix/torrent.(*Torrent).startScrapingTracker:1610]: error parsing tracker url`
what is that mean? i added wrong retrackers url or what? i used udp and http trackers with ip/name addreses and different ports. also i used ipv6.
i checked. the trackers parsed via go net/url. Did you test different types of tracker url (like http://[ipv6]:9997) and etc?
thanks

**Comment by anacrolix** [comment]
Thanks for the report. That line of code neglects to log the actual error, I'll post a fix shortly.

**Comment by anacrolix** [comment]
Could you try again with https://github.com/anacrolix/torrent/commit/3901c3144bba7445c77465709e450db0f74f7ad8? It will log more information about why it's failing.

**Comment by anacrolix** [comment]
I believe the revision I referred to will identify the issue. I don't see anything in the attached file that looks incorrect, at a glance.

**Comment by anacrolix** [comment]
@MaximKiselev any update on this?

**Comment by MaximKiselev** [comment]
hi, man. thanks a lot. 
i rebuilded lib locally. the problem was in symbols of url address. some lines have cr symbol and external tool(binary) shows only upper error but not for all trackers(and i thought that problem is not in formatting). i did live test - no any error for all trackers

**Comment by anacrolix** [comment]
Thanks!
