### ISSUE TITLE
parsing value for key "nodes": can't unmarshal a bencode string into a []metainfo.Node

### ISSUE THREAD

**Issue by KyleSanderson** [anacrolix/torrent#843]
I have no doubt the software is from 2007~ era, but it looks like these have never been supported. Please see below.

`d8:announce54:https://tracker.cat.org:2711/123456789abcdefg/announce18:azureus_propertiesd17:dht_backup_enablei0ee7:comment3:Cat13:comment.utf-83:Cat10:created by19:Client id is hidden13:creation datei1198664250e8:encoding5:UTF-84:infod6:lengthi443e4:name41:Cat Remote Administrator License 20pc.rar10:name.utf-841:Cat Remote Administrator License 20pc.rar12:piece lengthi32768e6:pieces20:a��?�:��:�����c��7:privatei1e6:source11:Cat Trackere5:nodes0:e`

Parses out (in another application):
```
{
 "announce" : "https://tracker.cat.org:2711/123456789abcdefg/announce",
 "azureus_properties" : {
  "dht_backup_enable" : 0
 },
 "comment" : "Cat",
 "comment.utf-8" : "Cat",
 "created by" : "Client id is hidden",
 "creation date" : 1198664250,
 "encoding" : "UTF-8",
 "info" : {
  "length" : 443,
  "name" : "Cat Remote Administrator License 20pc.rar",
  "name.utf-8" : "Cat Remote Administrator License 20pc.rar",
  "piece length" : 32768,
  "pieces" : "%01a%be%87?%ca:%f8%b2:%a2%a0%a4%02%f8%b6c%e0%e8%83",
  "private" : 1,
  "source" : "Cat Tracker"
 },
 "nodes" : ""
}
```

Anacrolix Error: `parsing value for key "nodes": can't unmarshal a bencode string into a []metainfo.Node`

**Comment by anacrolix** [comment]
Thank you for reporting this! Should be fixed in 050e5cbab8e26a9b28e57a7bc2a964b6d2ceb899, `v1.52.3`.
