### ISSUE TITLE
bug when using for loop

### ISSUE THREAD

**Issue by lovedboy** [anacrolix/torrent#85]
here is my sample code:

```
...
client, err := torrent.NewClient(&clientConfig)
checkErr(err)
files := getNotDownloadTorrentFile() // [file1, file2, file3...]

for _, file := range files{
    metaInfo, err := metainfo.LoadFromFile(file)
    checkErr(err)
    t, err := client.AddTorrent(metaInfo)
    checkErr(err)
    go func() {
            <-t.GotInfo()
            t.DownloadAll()
        }()
    client.WaitAll()
    t.Drop()
}
...
```
I use `for loop` to download all torrent file, the first file named `file1` can be downloaded complete, but downloaded `file2`  fail. Then i restart the process, downloaded `file2` completed but `file3` fail.

I tried many times and the results were the same.. It seem that `torrent` client has a unexpected bug when using `for loop`, only the first element of  variable `files` can be downloaded complete.

*PS*

I use `dd if=/dev/zero of=file ...` cmd to create `file1`,`file2`,`file3`.

**Comment by lovedboy** [comment]
update

The bug will happen if  `file1`、`file2`，`file3` have the same size(I use `dd` to create). Work fine if there are different size.

**Comment by anacrolix** [comment]
What does `getNotDownloadTorrentFile` do? I don't think you're using the API correctly.

**Comment by lovedboy** [comment]
`getNotDownloadTorrentFile ` is a function which return torrent file path list.

@anacrolix I have found the reason. Because `file1`,`file2`,`file3` are the same and have the same piece hash so won't to repeat download.

see my commit  in my fork repo [91ccc2c4f9b101d1797f885e0bd16a68dcb2f083](https://github.com/lovedboy/torrent/commit/91ccc2c4f9b101d1797f885e0bd16a68dcb2f083) : clear `fileStorage complete`   in order to download the file that have the same content but different file names.

after  `client.WaitAll()`, I will call `client.DropAllTorrent()`.
