### ISSUE TITLE
The operator wants to ban BitTorrent, so they want to wrap the data in a layer during transmission

### ISSUE THREAD

**Issue by misslipan** [anacrolix/torrent#850]
I want to use ase encryption to transmit end-to-end block data. Currently, I use hook to connect all connections, but this method will result in slow download and incomplete download data on the download resource end. Do you have a better solution

**Comment by anacrolix** [comment]
I believe you could do this with your own torrent.Dialer and torrent.Listener. You will lose compatibility with regular BitTorrent clients unless they also use the same encryption you do.

The default for this situation in BitTorrent is to use the message stream encryption. If you believe someone is intentionally banning BitTorrent traffic, set the configuration to allow and *require* encryption to minimize the chance that your use of BitTorrent is detected.

**Comment by misslipan** [comment]
![image](https://github.com/anacrolix/torrent/assets/18390442/1ac8a75f-4905-4882-bc52-df90bcd5a1b8)
I don't need to be compatible with regular ones, I just need to be able to use it myself. Is PEX this configuration? At present, I have created a hookconn myself. Before sending, I encrypted, received, and decrypted a downloaded file that was damaged

The following are two places where I added hookconn, both in the client.go file

![image](https://github.com/anacrolix/torrent/assets/18390442/eaa3e1ce-9ee8-46fe-b6c9-8beae8b86d43)
![image](https://github.com/anacrolix/torrent/assets/18390442/4af9bc7a-151a-491f-9aa7-b63889db0d31)

**Comment by anacrolix** [comment]
If you hook connections to your own wrapping encryption, PEX will work within swarms of peers that are compatible with your own encryption, so there's no need to disable it. Your hooks look like they're in the correct places! If you think this is worth adding as a field in ClientConfig, or Torrent, feel free to open a PR.

**Comment by anacrolix** [comment]
Okay I think there's nothing else to do here.
