### ISSUE TITLE
file.BytesCompleted() always return 0

### ISSUE THREAD

**Issue by monkeyWie** [anacrolix/torrent#851]
Firstly thanks for your great project. There have a problem that when I call `file.BytesCompleted()`  to stat a special file speed it always return 0, bur call `torrent.BytesCompleted()` is fine, and it only seems to happen in torrent that piece length is longer.

This is my code:
```
fmt.Printf("file[%d] %d %d\n", i, torrent.Files()[i].BytesCompleted(), torrent.BytesCompleted())
// output
file[0]: 0 16384
file[0]: 0 65536
file[0]: 0 114688
file[0]: 0 245760
```

**Comment by anacrolix** [comment]
Sorry, it took a while for me to understand the problem. File.BytesCompleted is not including dirty chunks in the computation, but it does for Torrent.BytesCompleted.

**Comment by anacrolix** [comment]
One reason not to include dirty bytes in the computation is that they can fail piece checks, and so your download rate would appear to go backwards between successive calls. Is that okay?
