### ISSUE TITLE
Cannot `go get` this library

### ISSUE THREAD

**Issue by cocool97** [anacrolix/torrent#861]
I cannot add this library to my new project using `go get github.com/anacrolix/torrent`, I receive the following error: 
```bash
go: github.com/anacrolix/torrent@v1.47.1-0.20221102120345-c63f7e1bd720: invalid version: unknown revision c63f7e1bd720
```

My project is basically empty, my go mod is the following:

```
module example/test/torrent

go 1.20
```

Is there something I'm doing wrong ?

**Comment by anacrolix** [comment]
See https://github.com/anacrolix/torrent/issues/776. This is a bug with Go. Try with Go 1.21, it should be fixed there.

**Comment by anacrolix** [comment]
Thank you. There's nothing I plan here to do, so I'll close.
