### ISSUE TITLE
error bootstrapping during bucket refresh: getting starting nodes: nothing resolved [dht 0.0.0.0:42069 github.com/anacrolix/dht/v2 server.go:1395]

### ISSUE THREAD

**Issue by MiaoMint** [anacrolix/torrent#865]
I get this error on Android but not on windows, what is the problem and how can I fix it? Code https://github.com/miru-project/bt-server
```text
[2023-08-30 12:23:01 +0000  ERR] error bootstrapping during bucket refresh: getting starting nodes: nothing resolved [dht 0.0.0.0:40157 github.com/anacrolix/dht/v2 server.go:1395]
[2023-08-30 12:23:01 +0000  ERR] error bootstrapping during bucket refresh: getting starting nodes: nothing resolved [dht [::]:40157 github.com/anacrolix/dht/v2 server.go:1395]
```

**Comment by anacrolix** [comment]
It seems like UDP packets or DNS are blocked. It's most likely the former.

**Comment by anacrolix** [comment]
Regarding Miru, have you looked at anacrolix/confluence?

**Comment by MiaoMint** [comment]
> Regarding Miru, have you looked at anacrolix/confluence?

Not yet

**Comment by MiaoMint** [comment]
@anacrolix I don't think I understand. Do I need IPBlacklist?

**Comment by anacrolix** [comment]
I don't know much about Android, but I would do some checks to determine is UDP is functional on the device. I know Android can be tricky around permissioning. You might test this from the perspective of your Android app by pinging a UDP server or something.

**Comment by tsynik** [comment]
@MiaoMint it looks like your network issue accessing dnt servers. Try VPN or another netowork.

**Comment by MiaoMint** [comment]
> @MiaoMint it looks like your network issue accessing dht servers. Try VPN or another netowork. Also, you can check if DNS works and change resolver if it doesn't. That's how we check it in TorrServer - https://github.com/YouROK/TorrServer/blob/34634649024b06921e7f2bb068da4a4ad35fabe4/server/cmd/main.go#L101-L120

Thank you ヾ(≧▽≦*)o
