### ISSUE TITLE
Count the number of bytes uploaded or downloaded.

### ISSUE THREAD

**Issue by whr819987540** [anacrolix/torrent#872]
I would like to build a mechanism that rewards or punishes users based on how many bytes they receive from or send to other peers so that more users would be willing to keep seeding for a while after downloading.
As for bytes received, it could be found through torrent.ConnStats.BytesRead.
But how about bytes sent? When I am downloading, I could send to other peers as well. When I finish downloading and start seeding, I could also send to other peers.

**Comment by anacrolix** [comment]
Are you looking for something like a seeding ratio?

**Comment by whr819987540** [comment]
Seeding ratio could help because if I know this, the number of bytes that a peer send to others will also be known.
But it would be better if torrent could directly supply the number.

**Comment by anacrolix** [comment]
Bytes sent and uploaded by the local client are recorded. I'm not sure about bytes sent by each peer, but that data is only easy to track while the peer remains connected to our local client. Which is it that you're after?

**Comment by whr819987540** [comment]
As you said, I think 'Bytes sent and uploaded by the local client' is enough, which reflects how much the local client gets from others and does for others. For this purpose, which variable do you think is the most suitable? BytesRead and BytesWritten?

**Comment by anacrolix** [comment]
`ConnStats.BytesWrittenData` is data uploaded to peers, I think that's the one you want. Similarly any of the `BytesRead` fields for data received, depending on how specific you want to be.

**Comment by anacrolix** [comment]
I think this can be closed, the question was answered.

**Comment by igorcafe** [comment]
@anacrolix `ConnStats.BytesWrittenData` includes any message sent, right?
not only pieces sent

I would like to show a status of amount downloaded and uploaded, similar to transmission, qbittorrent

I believe they count only total pieces right?

![Image](https://github.com/user-attachments/assets/be26df47-d65e-41f6-b971-f923811f917c)

**Comment by igorcafe** [comment]
oh sorry, I misread, it only count messages that have type = `Piece`, so it's exactly what I need :)

**Comment by anacrolix** [comment]
Yes, your reading is correct. Thank you for sharing your confirmation, this helps others too.
