### ISSUE TITLE
undefined: sync.OnceFunc

### ISSUE THREAD

**Issue by ucwong** [anacrolix/torrent#875]
```
vendor/github.com/anacrolix/sync/aliases.go:14:21: undefined: sync.OnceFunc
```

**Comment by anacrolix** [comment]
I think that's a vendoring problem. You probably need to rerun `go mod vendor`.

**Comment by ucwong** [comment]
> I think that's a vendoring problem. You probably need to rerun `go mod vendor`.

I think I did it

**Comment by anacrolix** [comment]
Ah okay.

**Comment by ucwong** [comment]
I think it is just a linter, when using ```go vet```

**Comment by ucwong** [comment]
Oh, I used the lower go version, I am closing it. thank you

**Comment by anacrolix** [comment]
Thanks for reporting this. I've fixed CI on Windows and dropped support for go 1.20 on v1.53.1.

**Comment by anacrolix** [comment]
There was also a bug in github.com/anacrolix/sync which was fixed.
