### ISSUE TITLE
does it implementation bep 0009?

### ISSUE THREAD

**Issue by lubia** [anacrolix/torrent#88]
http://www.bittorrent.org/beps/bep_0009.html

when we got info hash , we get torrent info from tracker ?

**Comment by anacrolix** [comment]
Yes this is completely supported. You don't have to provide the metainfo or info bytes when you add a Torrent, and the Client will endeavour to obtain these on its own.

**Comment by lubia** [comment]
you mean completely supported bep9 server side ? my situation maybe different,  I need  a client side tool,  I run a spider and receive `announce_peer` request，so I have a active infohash ，how can i use your code to get metadata direct fom peer who send me `announce_peer` request?

**Comment by anacrolix** [comment]
announce_peer is a DHT request that tells a peer about a Client interested in the announced infohash. 
The provided torrent.Client already extracts peers from the DHT to obtain the metainfo.

I think you want to adapt this cmd to your use: https://github.com/anacrolix/torrent/tree/master/cmd/magnet-metainfo. It takes a magnet link (which can be generated from an infohash trivially), and outputs the metainfo.

**Comment by lubia** [comment]
ok  thanks, this is a solution, but a little slow when we ger metainfo from DHT

**Comment by anacrolix** [comment]
You can accelerate the fetching of the metainfo if you add known generous peers, or trackers. DHT inherently takes longer to traverse the address space to nodes with data.
