### ISSUE TITLE
listen tcp6 :42069: socket: address family not supported by protocol

### ISSUE THREAD

**Issue by voidastro4** [anacrolix/torrent#900]
On linux when ipv6 is disabled in the kernel, the torrent binary (cmd) fails:
`error running main: creating client: subsequent listen: listen tcp6 :42069: socket: address family not supported by protocol`

It would be nice if the cmd or library could detect lack of ipv6 and fall  back to ipv4?

**Comment by anacrolix** [comment]
The workaround for now is to disable IPv6 using a flag.

**Comment by anacrolix** [comment]
I have a probable fix for this on master, can you please try it?

**Comment by anacrolix** [comment]
I think this was closed downstream.
