### ISSUE TITLE
ICE Servers config doesn't support authentication for TURN servers

### ISSUE THREAD

**Issue by marcovidonis** [anacrolix/torrent#903]
In #824 I added the option to configure the client with a list of ICE servers. The list is of type `[]string` and is used to provide the URLs of the servers to the WebRTC peer connections, [here](https://github.com/anacrolix/torrent/blob/master/webtorrent/transport.go#L56).

This will work fine when relying on STUN servers, which is the most common solution and doesn't usually require authentication.

However, on some occasions TURN servers are needed for NAT traversal. TURN servers normally require authentication, and the current implementation doesn't allow for that in the client config.

@anacrolix if interested, I'd be happy to open a PR to support passing ICE servers of type `[]webrtc.ICEServer` as used in Pion. I'm just unsure whether there's a clean way of doing it without introducing a breaking change?

**Comment by anacrolix** [comment]
If you're worried about a breaking change, just add a new field and check for that != nil first, falling back to the other field.
