### ISSUE TITLE
Cannot download file from a not completed peer

### ISSUE THREAD

**Issue by thank243** [anacrolix/torrent#906]
code snippet
```go
package main

import (
	"log"

	"github.com/anacrolix/torrent"
)

func main() {
	cfg := torrent.NewDefaultClientConfig()
	cfg.Debug = true
	cfg.DisablePEX = true
	cfg.DisableTrackers = true
	cfg.NoDHT= true

	c, _ := torrent.NewClient(cfg)
	defer c.Close()
	t, _ := c.AddTorrentFromFile("fake.file.torrent")
	t.AddPeers([]torrent.PeerInfo{{Addr: addr("10.0.0.199:31557")}})
	<-t.GotInfo()
	t.DownloadAll()
	c.WaitAll()
	log.Print("ermahgerd, torrent downloaded")
}

type addr string

func(a addr) String() string{
	return string(a)
}
```

When I use those code download file pieces from utorrent client. The code cannot work as expected. The ut have  the not completed file. When I use another ut client download the pieces of this file. It can work proply.

**Comment by anacrolix** [comment]
I didn't test with µtorrent, I don't believe that client is recommended anymore. However testing with qBittorrent worked.

**Comment by F-TD5X** [comment]
I knew this was not a good place, but I still wondering...
@thank243 what was `github.com/thank243/trafficConsume` this for? and why?
![图片](https://github.com/anacrolix/torrent/assets/19651619/ba4f430f-11b9-4395-b20c-9fa81326fa91)

**Comment by thank243** [comment]
> I knew this was not a good place, but I still wondering... @thank243 what was `github.com/thank243/trafficConsume` this for? and why? ![图片](https://private-user-images.githubusercontent.com/19651619/307514679-ba4f430f-11b9-4395-b20c-9fa81326fa91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3ODkxNDUsIm5iZiI6MTcwODc4ODg0NSwicGF0aCI6Ii8xOTY1MTYxOS8zMDc1MTQ2NzktYmE0ZjQzMGYtMTFiOS00Mzk1LWIyMGMtOWZhODEzMjZmYTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDE1MzQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViZGE5OTc4Y2ZlODQxNjQ0MDk4ZDA3NWYzZWM3MzM2YWMzMTRkMDkwNTAzMjcyZmZlZDRlNDEyMWI1YzNhMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xvyD6nooFEL46ApT4K55DUbpC8La68ZUSfVod6V43VY)

Where you got this conn? I just use a private torrent for testing network model.

**Comment by F-TD5X** [comment]
@thank243 I'm not sure where I got this peer. And this torrent is `Archlinux-2024.02.01`. Maybe you can checkout [this](https://github.com/anacrolix/torrent/discussions/891) and try to fix the problem?

**Comment by Moredistant** [comment]
杂种，NMSL
