### ISSUE TITLE
undefined missinggo.Sort error

### ISSUE THREAD

**Issue by ccampbell** [anacrolix/torrent#91]
I haven't updated your library in a while, and I just tried to update to the latest master and ran into this

```
vendor/github.com/anacrolix/torrent/torrent.go:445: undefined: missinggo.Sort
```

I think it's just bad luck that the first time I try to update the library in 8 months you *just* renamed this function which broke it ha

https://github.com/anacrolix/missinggo/commit/5dfcb8994d8894b14cf5300755821b334f95c92c

**Comment by anacrolix** [comment]
I wondered why the CI failed and didn't get around to it until now 😛 

Fixed in https://github.com/anacrolix/torrent/commit/a6cecc6b5f6a89f13ab0cef11a85762679615478
