### ISSUE TITLE
Torrent metainfo not cached

### ISSUE THREAD

**Issue by ccampbell** [anacrolix/torrent#92]
This is more of a question than a bug, but I recently updated to the latest master, and one of the issues I ran into is that the `ConfigDir` option has been removed. This was originally used to cache torrent information to disk. 

It seems like some sort of in memory caching is being used now cause subsequent lookups of the same magnet URL are very fast, but as soon as I kill and restart my program it takes a long time to do the lookups again where previously it was very fast. 

Am I missing something here? Do I have to implement disk based caching myself?

Thanks

**Comment by anacrolix** [comment]
Yes I've moved the caching out of the core package. It's not necessary for a torrent Client, and opinionated to provide a mechanism to do it. Perhaps we can come up with a generic way to do it, I'm currently rolling my own in my own projects.

```
func cachedMetaInfo(infoHash metainfo.Hash) (ret *metainfo.MetaInfo) {
	ret, err := metainfo.LoadFromFile(fmt.Sprintf("torrents/%s.torrent", infoHash.HexString()))
	if err != nil {
		ret = nil
		return
	}
	if ret.Info.Hash() != infoHash {
		ret = nil
		return
	}
	return
}

func saveTorrentFile(t *torrent.Torrent) (err error) {
	f, err := os.OpenFile(fmt.Sprintf("torrents/%s.torrent", t.InfoHash().HexString()), os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0660)
	if err != nil {
		return
	}
	defer f.Close()
	return t.Metainfo().Write(f)
}
```

**Comment by anacrolix** [comment]
I have no intention to do this in the short-term. This might be part of a utility package at some point.
