### ISSUE TITLE
Missing projects using this library

### ISSUE THREAD

**Issue by aicynide** [anacrolix/torrent#929]
1. https://github.com/miru-project/bt-server
2. https://github.com/rebelonion/Dantotsu/tree/torrent
3. https://github.com/LuftVerbot/kuukiyomi
4. https://github.com/RepoDevil/Mr.Matagi
5. https://github.com/kodjodevf/mangayomi

**Comment by anacrolix** [comment]
Could you please link directly to the anacrolix/torrent use in each repo.

**Comment by anacrolix** [comment]
bt-server looks like a duplicate of https://github.com/anacrolix/confluence and doesn't look popular enough yet.

I can't see anacrolix/torrent in Dantotsu.

Kuukiyomi is building on an extremely out of date fork.

The links don't resolve with Mr.Matagi

I'll add Mangayomi.

Thanks

**Comment by anacrolix** [comment]
miru also doesn't resolve now :/

**Comment by sweetbbak** [comment]
can I chime in and add my project?
[https://github.com/sweetbbak/toru](https://github.com/sweetbbak/toru)

**Comment by anacrolix** [comment]
@sweetbbak https://github.com/anacrolix/torrent/commit/89a9cc1628d4eb33e9bc33c34dbd9dd67b3a35fb
