### ISSUE TITLE
Public IP address isn't announced to HTTP tracker

### ISSUE THREAD

**Issue by viciious** [anacrolix/torrent#951]
Hi,

I'm trying to get web tracking to work, but from what I can tell, the IPAddress field never gets set in the HTTP announcement request.

```
	cfg := torrent.NewDefaultClientConfig()
	cfg.Seed = true
	cfg.Debug = true
	cfg.PublicIp4 = net.ParseIP("127.0.0.1")
	cfg.ListenPort = 4567
```

Here's the debug log for the request:

```
[0.205s DBG github.com/anacrolix/torrent tracker_scraper.go:167]
  seeder: announcing to "http://127.0.0.1:1337/test/announce": udp.AnnounceRequest{InfoHash:[20]uint8{0x9, 0x67, 0x7d, 0xac, 0x55, 0xbd, 0x94, 0xc1, 0x56, 0x94, 0xd1, 0xaf, 0xbf, 0x44, 0x68, 0xd4, 0xc7, 0x3c, 0xfd, 0xb2}, PeerId:[20]uint8{0x2d, 0x47, 0x54, 0x30, 0x30, 0x30, 0x33, 0x2d, 0x10, 0x41, 0x6a, 0x9b, 0x1d, 0x89, 0x8, 0x7d, 0x7a, 0x42, 0x2f, 0x2a}, Downloaded:0, Left:5, Uploaded:0, Event:2, IPAddress:0x0, Key:2051157802, NumWant:0, Port:0x11d7}
```
As you can probably tell, the port value of 4567 is propagated to the request, but IPAddress is set to 0.

**Comment by viciious** [comment]
Actually, never mind. I think it's just the debug log that doesn't have it - the tracker does receive the address in the request. Sorry for the false alarm!

**Comment by anacrolix** [comment]
Hmm, it seems like a bug if that's not being logged correctly.

**Comment by viciious** [comment]
This is probably the consequence of IPAddress field not being set at the time of logging due to:

> 	// Note that IPAddress is not set. It's set for UDP inside the tracker code, since it's
	// dependent on the network in use.

https://github.com/anacrolix/torrent/blob/3bbe1c34f0dcd92fb5ba8fa673fd85ffa942952b/torrent.go#L2010

**Comment by anacrolix** [comment]
Thanks for finding that.
