### ISSUE TITLE
Torrent Priority

### ISSUE THREAD

**Issue by valainisgt** [anacrolix/torrent#954]
Does this project support setting a leech priority at a torrent level? Browsing the source code, I can see that you are able to set a priority on a given piece of a torrent, but what about a torrent as a whole? Let's say I am leeching three torrents, `foo`, `bar`, and `qux`. I'd like to be able to mark one of the torrents (`foo`) as a high priority in an attempt to get it completed as fast as possible. The other two torrents (`bar` and `qux`) could download pieces if they could, but everything should be done to get the `foo` torrent downloaded. I thought I had seen a similar question asked, but can no longer find it. Based on my research it doesn't seem like this is possible and might need to be done at an application level.

What I have been able to do is to mark all the pieces of the `bar` and `qux` torrents to be priority none. This effectively pauses those torrents and allows the high priority torrent to go. Instead of marking all of the pieces of `bar` and `qux` to none, I mark all the pieces of `foo` to be high priority, do you think this will have the effect I am looking for? My gut tells me that it won't because these are individual pieces of completely different torrents.

@marcovidonis

**Comment by anacrolix** [comment]
Great question. Torrents will not compete with one another for priority except as far as I know:

- Torrent data in a shared storage will prefer the highest priority data.
- They may share some tracker state, but don't get preferential treatment.

That's it. Torrents do not affect each others dialing, connection limits or anything else. So I think the best thing you could do is set High priority to all the pieces or files of the Torrent you most want. If there's some specific resource you want them to compete for using priorities, let me know.

**Comment by valainisgt** [comment]
Thank you for the insight. I don't have anything in mind for specific resources for torrents to compete for.
