### ISSUE TITLE
Server seems to stop working after failed tracker DNS lookup

### ISSUE THREAD

**Issue by ccampbell** [anacrolix/torrent#96]
I **think** that is what is happening here. I haven't spent a long time debugging, but I have noticed that when I request certain torrents I get this message in my logs:

```
2016/07/08 12:19:51 error preparing announce to "udp://tracker.publicbt.com:80/announce": lookup tracker.publicbt.com on 10.8.0.1:53: no such host
```

After getting that error nothing else seems to work until I restart my webserver I am using this in. 

I know it's not very helpful, but previously I was using this library at revision c7cb1009a5cc1b503d68d5469b9dabfe77b2f959, and I do not see the same problem there.

It could also be something different with my server set up, but I don't think so. Any insight would be greatly appreciated.

**Comment by anacrolix** [comment]
I get this error (warning?) regularly on my servers, it doesn't stop things from working. Perhaps there's some other error? Possibly check your goroutine stacks, often if something panics in a bad spot, it can mess up the use of mutexes and get stuck: The goroutine never finishes panicking so you never know, and leaves the Client locked.

**Comment by ccampbell** [comment]
Okay. I can dig into it a bit more later. When running the older version of this library I get the same error in the logs, but it doesn't cause things to get stuck. That's why I find it a bit suspicious.

**Comment by anacrolix** [comment]
What program are you running that gets this error? If it's private, perhaps you can describe some of the client and torrent options you're using?

**Comment by anacrolix** [comment]
I wonder if this will go away with the fix due to #95. Let me know.

**Comment by ccampbell** [comment]
Will do

**Comment by ccampbell** [comment]
Okay I updated the code to the latest version and I am still experiencing this issue. I just emailed you some code that I am able to use to trigger the behavior. It's hard for me to tell if it is related to the DNS lookup failure or not.

**Comment by anacrolix** [comment]
I've managed to get the code to trigger the issue. It requires that the data be cleared, but the .torrent.db file not be removed (the new piece completion caching for file-based storages introduced for #50. The Client goes into an infinitely loop trying to read data it believes should be there, and the DB insists is. As a workaround, delete the .torrent.db file whenever you remove data from wherever your Client is downloading it to. I'm rejigging the tests so I can test this correctly for the future.
