### ISSUE TITLE
Latest release (1.57.1) has an incompatibility with the dht package

### ISSUE THREAD

**Issue by decentralgabe** [anacrolix/torrent#984]
after running

```govulncheck ./...```

in my project I see:

```
error: package "github.com/anacrolix/torrent/metainfo" without types was imported from "github.com/anacrolix/dht/v2/krpc"
```

Using versions:
* https://github.com/anacrolix/torrent/releases/tag/v1.57.1
* https://github.com/anacrolix/dht/releases/tag/v2.22.0

**Comment by decentralgabe** [comment]
The fix is to update https://github.com/anacrolix/dht/blob/master/go.mod#L21 to use v1.57.1 or
this https://github.com/anacrolix/torrent/blob/master/go.mod#L11 to use v2.22.0

or perhaps to remove dependencies in both directions between the projects

**Comment by anacrolix** [comment]
Thanks, I'll take a look soon.

**Comment by anacrolix** [comment]
That's strange, I can't reproduce the problem. What version of Go are you using?

**Comment by decentralgabe** [comment]
1.23.2 surprisingly I can no longer reproduce. sorry for the noise.

**Comment by anacrolix** [comment]
All good, cheers!
